### ISSUE TITLE
[socket.io] Cannot use 'in' operator to search for 'document' in undefined 

### ISSUE THREAD

**Issue by emroot** [gaearon/react-hot-loader#100]
**What is it?** 
Uncaught TypeError: Cannot use 'in' operator to search for 'document' in undefined 
**Context**
Using react-hot-loader in combination with webpack by running a webpackdevserver.
**Where**
in socket.io.js [version 0.9.10]
![screenshot](http://cl.ly/image/2N280f1c1n1F/download/Image%202015-03-11%20at%204.52.49%20PM.png)
I can provide more info if necessary.

**Comment by emroot** [comment]
FYI this doesn't happen when I use 1.1.4, but breaks with latest version.

**Comment by gaearon** [comment]
This might be the same as #99. If you don't have `exclude: /node_modules/` in loader configuration, you need to add it; it worked only by luck before. Can you verify?

**Comment by MattAitchison** [comment]
@gaearon I had the same issue and `exclude: /node_modules/` fixed it.

**Comment by gaearon** [comment]
Added to Troubleshooting: https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#socketio-cannot-use-in-operator-to-search-for-document-in-undefined

Thanks!

**Comment by Dakuan** [comment]
we are running into this but excluding `node_modules` isnt helping

**Comment by gaearon** [comment]
@Dakuan This happens if you try to process Webpack's own `webpack/client` with something like `babel-loader`. Are you sure you don't have Babel processing `node_modules` or wherever you have installed Webpack Dev Server?

**Comment by Dakuan** [comment]
it does feel like thats whats happening, not sure how as `node_modules` is excluded!

**Comment by gaearon** [comment]
@Dakuan Can you show your config and paste Webpack output?

**Comment by Dakuan** [comment]
Nevermind.

```
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
I will not raise github issues on Friday afternoons
````

**Comment by sagiavinash** [comment]
@gaearon my webpack.config.js is
as u can see i have mentioned exclude: /node_modules/ in the babel loader.
still facing this issue.

const autoprefixer = require("autoprefixer");
const path = require("path");
const webpack = require("webpack");
const sassLoaders = [
  "style-loader",
  "css-loader",
  "postcss-loader",
  "sass-loader?sourceMap?indentedSyntax=sass&includePaths[]=" + path.join(__dirname, "flash/ver_static/css")
];

module.exports = {
  entry: {
    bundle: [
      "webpack-dev-server/client?http://avinash.dev.blng.io", // WebpackDevServer host and port
      "webpack/hot/only-dev-server",
      "/home/avinash/code/flash/flash/ver_static/js/react/app.js"
    ],
    vendor: ["react", "underscore", "moment", "react-router"]
  },
  output: {
    filename: "[name].js", //this is the default name, so you can skip it
    path: path.join(__dirname, "flash/flash/ver_static/js"),
    publicPath: "http://avinash.dev.blng.io/assets/"
  },
  devtool:'source-map',
  module: {
    loaders: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      loader: 'babel',
      query: {
        plugins: ['transform-runtime'],
        presets: ['es2015', 'stage-0', 'react'],
      }
    }, {
      test: /\.scss$/,
      loader: sassLoaders.join("!")
    }]
  },
  postcss: [autoprefixer({ browsers: ["last 2 versions"] })],
  externals: {
    //don"t bundle the jquery npm package with our bundle.js
    //but get it from a global jQuery variable
    "jquery": "jQuery"
  },
  resolve: {
    extensions: ["", ".js", ".jsx"]
  }
};

but still i am getting this error

**Comment by gaearon** [comment]
@sagiavinash The absolute path in the `entry` configuration looks weird. Not saying it causes the issue but I’d try using a relative path there. Otherwise, it’s hard to say, and in any case, this is not related to React Hot Loader.

**Comment by sagiavinash** [comment]
@gaearon found the issue, the problem is that i have a libs directory in the scope of webpack. excluding that folder everything works fine.
thanks for your time.
