### ISSUE TITLE
React 0.13?

### ISSUE THREAD

**Issue by sebastienbarre** [gaearon/react-hot-loader#101]
Was just curious if there was a roadmap for supporting React 0.13.
Or if you needed some help testing.
Thanks, a very helpful tool.

**Comment by gaearon** [comment]
0.13 is supported. Anything in particular that doesn't work?

**Comment by sebastienbarre** [comment]
Oh good news. I was performing an ```npm update``` and it would fail, unfortunately, so I figured it wasn't quite ready yet:
```
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-hot-loader@1.2.3 wants react@>=0.11.0
```
With package.json like this:
```
  "dependencies": {
    "react": "^0.13.1",
...
  "devDependencies": {
    "react-hot-loader": "^1.2.3",
...
```

**Comment by gaearon** [comment]
I don't think this is due to RHL.
You probably have some other peer dependency that wants 0.12 (e.g. React Router).

`>=0.11.0` includes `0.13`.

**Comment by sebastienbarre** [comment]
Apologies, you are correct.

**Comment by gaearon** [comment]
Totally get it, NPM warning is confusing.
