### ISSUE TITLE
_this is not defined

### ISSUE THREAD

**Issue by mnemanja** [gaearon/react-hot-loader#1020]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

An error occurs when I change a component and the hot reloading refreshes the code. The reference to the `this` gets lost.
When I refresh the page, the method works. 
I then go and change a component, and try the same method, it loses the `this` reference and it breaks. 

### Expected behavior

The error should not occur.

### Actual behavior

![screen shot 2018-06-14 at 13 17 55](https://user-images.githubusercontent.com/1423218/41409165-8f2fb64c-6fd5-11e8-9bed-f8eb7e36d118.png)
![screen shot 2018-06-14 at 13 26 09](https://user-images.githubusercontent.com/1423218/41409449-8b6fc5fa-6fd6-11e8-9b89-0f3f8047cc73.png)

### Environment

React Hot Loader version: 4.2.0 and also 4.3.1

Run these commands in the project folder and fill in their results:

1.  `node -v`: 8.10.0
2.  `npm -v`: 6.0.1

Then, specify:

1.  Operating system: Mac
2.  Browser and version: Latest chrome

I've noticed this being a standard issue, but in other, resolved issues the problem was with the versions of the `this`, like `_this1...10` etc.

**Comment by theKashey** [comment]
This is function actually a function of your component, or it should not be reloaded at all?
Ie #1001

**Comment by mnemanja** [comment]
`this` is a reference to the react component in which the method resides and it tries to access it.

I do not think I'm doing anything wrong react-wise. How can this be fixed?

**Comment by theKashey** [comment]
should be fixed in v4.3.3

**Comment by mnemanja** [comment]
I can confirm that it's been fixed with v4.3.3.

**Comment by PavaniGedala23** [comment]
I got the same issue. have updated the react-hot-loader to 4.12.12. Working for me.
