### ISSUE TITLE
Ignoring modules when adding flow

### ISSUE THREAD

**Issue by JavoByte** [gaearon/react-hot-loader#1022]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

I just added `flow` to my project, so I added `@babel/preset-flow` plugin to my `.babelrc`

### Expected behavior

Hot module replacement should work as expected

### Actual behavior

I get this error:

Ignored an update to unaccepted module ./src/browser/pages/Home/Home.jsx
[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves

### Environment

React Hot Loader version: ^4.2
Babel version beta: 7.0.0-beta.44
React version: ^16.2.0

Run these commands in the project folder and fill in their results:

1.  `node -v`: 8.11.1
2.  `npm -v`: 5.6.0

Then, specify:

1.  Operating system: OSX
2.  Browser and version: Chrome 67.0.3396.79

### Reproducible Demo

https://github.com/JavoByte/react-koa-boilerplate

This issue was introduced in this [commit](https://github.com/JavoByte/react-koa-boilerplate/commit/8b0ecb92944f294b78be1691239d228805db510c) Before that commit everything was working ok

**Comment by theKashey** [comment]
The root issue is here - https://github.com/JavoByte/react-koa-boilerplate/blob/master/src/shared/Routes/Routes.jsx#L7

React-loadable is not React-Hot-Loader compatible. As long you _async_ load `pages/Home` you have to `accept` it manually.

The easiest way to fix the issue - wrap with `hot` exports of /pages, so they will be able to hot-reload themselves.
