### ISSUE TITLE
`WeakMap` won't be compiled in `development` mode

### ISSUE THREAD

**Issue by SidKwok** [gaearon/react-hot-loader#1023]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

`WeakMap` won't be compiled in `development` mode, but sometimes we need to hot-reload in some browsers such like ie10 (or any other browsers that do not support `WeakMap`.

### Expected behavior

What you think should happen:
`WeakMap` is compiled by babel

### Actual behavior

What actually happens:
`WeakMap` is in source code in development mode

### Environment

React Hot Loader version: 4.3.3

Run these commands in the project folder and fill in their results:

1.  `node -v`: 8.10.0
2.  `npm -v`: 5.0.0

Then, specify:

1.  Operating system: macos 10.13.5
2.  Browser and version: ie10 (or any other browsers that do not support `WeakMap`)

### Reproducible Demo

You can use `create-react-app` to create a demo project and replace `react-hot-loader` and see the `WeakMap` in development mode.

**Comment by theKashey** [comment]
Yes, you are right.
A lot of companies are thinking about dropping IE11, as long it is old and almost not used. And no one is considering IE10 as a browser nowadays.

**Comment by theKashey** [comment]
But it is not hard to make RHL "syntax correct" for IE10

**Comment by SidKwok** [comment]
`import 'babel-polyfill'` in entry file?

**Comment by SidKwok** [comment]
Not only IE10, but lots of android(4.4, it's still a common used version in China) browsers don't support these syntax.

**Comment by theKashey** [comment]
React-Hot-Loader v3 actually includes polyfill for WeakMaps, it's just a 10 lines of code.
But, if you are ok with importing `babel-polyfill` - go for it!

**Comment by SidKwok** [comment]
ok, I’ll try it. But where is v3 branch?

**Comment by theKashey** [comment]
It's... deprecated

**Comment by newerik** [comment]
I tried to import `core-js/es6/weak-map` in the file where I import `react-hot-loader`, but it still causes error in **IE 9 and IE 10**.
In a hope that I gave a hint, was someone able to make it work in the mentioned legacy browsers?

**Comment by theKashey** [comment]
You wont be able to "fix" it, as long react-hot-loader import itself ontop of everything.

The only thing I could do (and it's partially done) - disable RHL, and not "require" it, if weakmaps are not supported - https://github.com/gaearon/react-hot-loader/blob/master/index.js#L11

**Comment by newerik** [comment]
Found the problem!
I had `react-hot-loader/patch` included in the _Webpack config_.
https://github.com/gaearon/react-hot-loader#no-patch-required
Using **Webpack v4.20.2** and **react-hot-loader v4.3.12** by the way.

Once I removed it, **the application started to work without error in IE 9 and IE 10.** No need to import `core-js/es6/weak-map` polyfill!
`react-hot-loader` is imported only in the entry `index.js` file and added in `.babelrc` like in the documentation:
https://github.com/gaearon/react-hot-loader#getting-started
