### ISSUE TITLE
not working well with webpack 4 and happypack

### ISSUE THREAD

**Issue by sibelius** [gaearon/react-hot-loader#1026]
```
"webpack": "^4.12.0",
    "webpack-cli": "3.0.8",
    "webpack-serve": "1.0.4",
    "webpack-serve-waitpage": "1.0.0"
    "react-hot-loader": "^4.3.3",
```

webpack.config.js
```jsx
const path = require('path');

const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const dotEnv = require('dotenv-webpack');
const FaviconsWebpackPlugin = require('favicons-webpack-plugin');
const HappyPack = require('happypack');
const history = require('connect-history-api-fallback');
const convert = require('koa-connect');
const webpackServeWaitpage = require('webpack-serve-waitpage');

const HOST = process.env.HOST;
const PORT = process.env.PORT;

module.exports = {
  mode: 'development',
  context: path.resolve(__dirname, './'),
  entry: './src/index.js',
  devtool: 'eval-source-map',
  output: {
    path: path.join(__dirname, 'build'),
    filename: 'bundle.js',
    publicPath: '/',
  },
  resolve: {
    modules: [path.join(__dirname, 'src'), 'node_modules'],
    extensions: ['.js'],
  },
  module: {
    rules: [
      {
        test: /\.js?$/,
        exclude: [/node_modules/],
        use: 'happypack/loader?id=js',
        include: path.join(__dirname, 'src'),
      },
      {
        test: /\.(jpe?g|png|gif|svg|pdf|csv)$/i,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[name].[ext]',
              outputPath: 'img/',
            },
          },
        ],
      },
      {
        test: /\.css$/,
        use: 'happypack/loader?id=styles',
      },
    ],
  },
  serve: {
    content: [__dirname],
    port: PORT,
    host: HOST,
    logLevel: 'debug', // default is info
    add: (app, middleware, options) => {
      app.use(
        webpackServeWaitpage(options, {
          title: 'Entria Tech Team',
          theme: 'material',
        }),
      );

      // see: https://github.com/bripkens/connect-history-api-fallback#options
      app.use(
        convert(
          history({
            disableDotRule: true,
            htmlAcceptHeaders: ['text/html', 'application/xhtml+xml'],
          }),
        ),
      );
    },
    dev: {
      logLevel: 'debug',
      stats: {
        assets: true,
        colors: true,
        version: false,
        hash: false,
        timings: true,
        chunks: false,
        chunkModules: false,
      },
    },
  },
  plugins: [
    new dotEnv({
      path: './.env',
    }),
    new HappyPack({
      id: 'js',
      threads: 4,
      // https://github.com/babel/babel-loader#options
      loaders: ['babel-loader?cacheDirectory'],
    }),
    new HappyPack({
      id: 'styles',
      threads: 2,
      loaders: ['style-loader', 'css-loader'],
    }),
    new FaviconsWebpackPlugin('./src/static/favicon.png'),
    new HtmlWebpackPlugin({
      template: './src/index.html',
      chunksSortMode: 'none',
    }), 
  ],
};
```

When I change a single file, it keeps on [hot]: webpack Compiling forever, like the image below

![image](https://user-images.githubusercontent.com/2005841/42112683-04322480-7bbf-11e8-8b2a-c249b6dd7a43.png)

how can I debug this?

My root components have this

```jsx
export default hot(module)(MyComponent)
```

**Comment by theKashey** [comment]
Does it work without React-Hot-Loader?

**Comment by sibelius** [comment]
do I need `new webpack.HotModuleReplacementPlugin(),` on my plugins?

how can I check which files are beeing hot reloaded?

**Comment by theKashey** [comment]
@sibelius - it depends. If you are using webpack-dev-server or serve - you need only `--hot` option.
Use `HotModuleReplacementPlugin` only if you are doing "your own" service, or you will break HMR.

And there is no public API to find out what was reloaded, as far I know. Nor in RHL, nor in webpack, parcel or Electron.

**Comment by sibelius** [comment]
there are some debug flags on hot reload module 

![image](https://user-images.githubusercontent.com/2005841/42239907-cd277e8e-7edb-11e8-9eb7-2a878a5f82b0.png)

it is hot reloading all my files, when I change a single file

here https://github.com/webpack-contrib/webpack-hot-client/blob/master/lib/client/hot.js#L75 just show 1 file that I've changed

here https://github.com/webpack-contrib/webpack-hot-client/blob/master/lib/client/hot.js#L89 shows a list of all files that will the hot reload (15k files)

not sure if this is a bug on my code or webpack or webpack-hot-client or react-hot-loader.

we notice that we have some cyclic dependencies, not sure if this could cause some trouble

webpack-dev-server provides a faster hot reload than webpack-serve

**Comment by theKashey** [comment]
So you actually changed a __single__ file, but nobody __accept__ that change. Then - its __parent got changed__, but nobody accept that change, until `hot` will accept the change for `Application.js`.

After it - __everything below that point__ should be updated.

In reality, it should update only files related to the _change-event propagation_, so something is wrong with that propagation, might be cycles.

You can try to debug webpack internals in terms of finding how it generates and fills the "update modules list". You can found corresponding code at https://github.com/webpack/webpack/blob/master/lib/HotModuleReplacement.runtime.js#L375 (and to the end of a file)

**Comment by sibelius** [comment]
not solved yet

gonna wait for react fast refresh on react web

**Comment by theKashey** [comment]
So is this issue bound to RHL or bundler?

**Comment by sibelius** [comment]
I think wp
