### ISSUE TITLE
Where is the website code located?

### ISSUE THREAD

**Issue by jsakas** [gaearon/react-hot-loader#1045]
Hey, I recently set up HMR with Express and SSR. Turned out it wasn't all that difficult. I would like to update the website with instructions on how to do this: http://gaearon.github.io/react-hot-loader/getstarted/

There is a section "Option 3: Express with webpack-dev-middleware (client & server)" that simply has "XXX TODO". I cannot find that text in this repo.

Where can I PR this?

Thanks!

**Comment by theKashey** [comment]
https://github.com/gaearon/react-hot-loader/blob/gh-pages/getstarted.md
Special branch for github pages.
