### ISSUE TITLE
Documentation for webpack-serve

### ISSUE THREAD

**Issue by anthonator** [gaearon/react-hot-loader#1051]
From the `webpack-dev-server` README.

> Please note that webpack-dev-server is presently in a maintenance-only mode and will not be accepting any additional features in the near term. Most new feature requests can be accomplished with Express middleware; please look into using the before and after hooks in the documentation.

> Use webpack-serve for a fast alternative. Use webpack-dev-server if you need to test on old browsers.

Since `webpack-dev-server` is deprecated and `webpack-serve` is the future it probably makes sense to document usage around `webpack-serve`.

**Comment by frankwallis** [comment]
webpack-serve is [dead](https://github.com/webpack-contrib/webpack-serve#webpack-serve) now. Long live webpack-dev-server :-)

**Comment by anthonator** [comment]
(╯°Д°）╯︵┻━┻

**Comment by theKashey** [comment]
(╯°□°）╯︵ ┻━┻)
