### ISSUE TITLE
Mobx store changes are not applied

### ISSUE THREAD

**Issue by ItamarShDev** [gaearon/react-hot-loader#1055]
### Description
What you are reporting:
When adding  logic or console.log to a Mobx class store, refresh is needed

### Expected behavior
What you think should happen:
the code should probably be updated without refresh

### Actual behavior
What actually happens:
refresh is needed to update the changes

### Environment
React Hot Loader version:
^4.3.4

Run these commands in the project folder and fill in their results:

1.  `node -v`: 8.11.3
2. yarn: 1.7.0

Then, specify:

1.  Operating system: Ubuntu 18.04
2.  Browser and version: Chrome Beta latest

**Comment by theKashey** [comment]
Sorry mate, my Cerebro device is broken and I could not read you mind clearly.

**Comment by theKashey** [comment]
It sounds like `reactive` problem. When you are changing something in mobx store your React components dont get updated. Nobody tells them that they should update.
This is not something RHL could or should do - this is more about more generic Hot Module Replacement - you should `module.hot.accept` changes of your store, and do _something_ to propagate information about the change to the React-MobX connector.

Better check mobx documentation around HMR.

**Comment by theKashey** [comment]
Something like https://github.com/mobxjs/mobx-state-tree/issues/372
By fact it is still not quite well documented.

**Comment by theKashey** [comment]
Or this - https://github.com/mobxjs/mobx/issues/254

**Comment by ItamarShDev** [comment]
Thank you!
