### ISSUE TITLE
reactHotLoader.register is too greedy ?

### ISSUE THREAD

**Issue by htulipe** [gaearon/react-hot-loader#1056]
### Description

I'd like to ask a question (might be a bug or misconfiguration from my side). I've started using RHL and saw an increased bundle size. I looked at a diff of my bundles with and without RHL and saw stuff like this for each modules:

```
(function () {
  var reactHotLoader = __webpack_require__(0).default;

  var leaveModule = __webpack_require__(0).leaveModule;

  if (!reactHotLoader) {
    return;
  }

  reactHotLoader.register(dropdownColl, "dropdownColl", "/full/path/to/js/app/website/module/ui/dropdown-custom.js");
  reactHotLoader.register(toggleList, "toggleList", "/full/path/to/js/app/website/module/ui/dropdown-custom.js");
  reactHotLoader.register(hideList, "hideList", "/full/path/to/js/app/website/module/ui/dropdown-custom.js");
  reactHotLoader.register(init, "init", "/full/path/to/js/app/website/module/ui/dropdown-custom.js");
  reactHotLoader.register(_default, "default", "/full/path/to/js/app/website/module/ui/dropdown-custom.js");
  leaveModule(module);
})();
```

The `dropdown-custom.js` module is not a React component, it's just a bunch of function with only one exported, `init` (default export).

### Expected behavior

Since it's a prod build, I'd expect RHL to not register my modules functions (or at least register only the exported ones). Is this normal behavior ?

### Actual behavior

See sample code above. Also, I'm pretty sure to be on "prod configuration" since I can see in my bundle:

```
if (true) {
  module.exports = __webpack_require__(346);
} else {
  module.exports = require('./dist/react-hot-loader.development.js');
}
```

### Environment

React Hot Loader version: 4.3.5

Run these commands in the project folder and fill in their results:

1.  `node -v`: v8.11.3
2.  `npm -v`: 5.6.0

Then, specify:

1.  Operating system: MacOS HighSierra
2.  Browser and version: -

Many thanks for your help

**Comment by theKashey** [comment]
According to the code - babel `prop` plugin does nothing. Literally nothing. And the problem is not inside `index.js` file, you used as example, but - `babel.js`.
Condition is the same - 
```js
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./dist/babel.production.min.js');
} else {
  module.exports = require('./dist/babel.development.js');
}
```
Here `NODE_ENV` should be a real env variable, not a webpack constant.

**Comment by htulipe** [comment]
I'm not sure to understand what you mean. What's the babel prop plugin and how does it relate to my `reactHotLoader.register` problem ?

**Comment by htulipe** [comment]
Okay so I found my issue, `NODE_ENV` was actually no set at the Node process level but only injected via Webpack. Properly setting NODE_ENV fixes the issue, my bad...  🤭
