### ISSUE TITLE
Can't use `document.body` as app root?

### ISSUE THREAD

**Issue by iansinnott** [gaearon/react-hot-loader#106]
Using `document.body` as the app root works fine with React, but it doesn't seem to work with the hot reloader. I get the following error in the console:

```
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

My react render entrypoint looks like this:

```js
React.render(<Handler/>, document.body);
```

However, when I create a `<div>` with the class "root" and use that in the render call HMR works fine:

```js
React.render(<Handler/>, document.getElementById('root'));
```

Is there something I'm missing here or does HMR simply not work with `document.body`?

**Comment by gaearon** [comment]
It works fine for me with `document.body`. Can you isolate this issue in a repo? (e.g. you can take [react-hot-boilerplate](https://github.com/gaearon/react-hot-boilerplate) and work from there.)

There are other reasons why you shouldn't render to `body` though. See explanation [here](https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375) (second half of the article).

**Comment by gaearon** [comment]
Please reopen if you find a way to repro!

**Comment by iansinnott** [comment]
Will do. Thanks @gaearon. Haven't had time lately but I will let you know I run into this issue again

**Comment by skaapgif** [comment]
@iansinnott I just ran into this same problem while playing around with react-hot-loader and react-router. What caused the problem for me was that I had kept react-hot-loaders default of rendering `<App>` into `document.getElementById('root')` and also rendered `<Router>` into `document.body`, you should only have one of these. Hope that helps.

**Comment by iansinnott** [comment]
Thanks @skaapgif for the info. I haven't had the issue again since but hopefully this thread helps anyone else who runs into it.
