### ISSUE TITLE
improve react-hot-loader typedefs

### ISSUE THREAD

**Issue by sibelius** [gaearon/react-hot-loader#1068]
should react-hot-loader defines a global `module` variable?

for instance, check this simple code:

```jsx
import { hot } from 'react-hot-loader';
import * as React from 'react';

import ClientRouter from './router/ClientRouter'

type Props = {
  children: React.ReactNode,
};

class Main extends React.Component<Props> {
  render() {
    return (
       <span>ok</span>
    );
  }
}

export default hot(module)(Main);
```

it throws the following errors

```
src/Main.tsx:22:20 - error TS2304: Cannot find name 'module'.

22 export default hot(module)(Main);
                      ~~~~~~
```

as `hot(module)` is the new pattern to enable hot reloading, should `module` just be defined on react-hot-loader types?

**Comment by theKashey** [comment]
Em, no - this is __standard__ global variable for webpack or nodejs enviroment. I am not sure why _webpack environment_ is not a thing, but you can use nodejs.
This is how _angular_ solved this issue

Add the necessary types to  `src/tsconfig.app.json`
 ```json
{
  ...
  "compilerOptions": {
    ...
    "types": ["node"]   <----
  },
}
```

That's all.
Or you can define global by yourself, or add `// @ts-ignore` before this construction to swallow error.

But there is nothing RHL could do itself.
