### ISSUE TITLE
Warning for Async HOC component

### ISSUE THREAD

**Issue by Zdend** [gaearon/react-hot-loader#1069]
Whenever I'm importing async modules with react-loadable that I later wrap with a HOC
 I get a following warning:

```
[HMR] Checking for updates on the server...
11:50:00.895 console.js:35 [HMR] Updated modules:
11:50:00.895 console.js:35 [HMR]  - ./src/scripts/apps/enb/modules/api-connector/index.js
11:50:00.896 console.js:35 [HMR]  - undefined
11:50:00.896 console.js:35 [HMR]  - undefined
11:50:00.897 console.js:35 [HMR]  - undefined
11:50:00.897 console.js:35 [HMR] App is up to date.
11:50:00.945 console.js:35 React-hot-loader: a defaultProps(RegisterModuleWrapper) was found where a Component was expected.
          function DefaultProps(ownerProps) {
      return factory(ownerProps);
    }
console.(anonymous function) @ console.js:35
warn @ react-hot-loader.development.js:181
(anonymous) @ react-hot-loader.development.js:1443
hotReplacementRender @ react-hot-loader.development.js:1352
hotReplacementRender$1 @ react-hot-loader.development.js:1477
reconcileHotReplacement @ react-hot-loader.development.js:1486
renderReconciler @ react-hot-loader.development.js:1500
asyncReconciledRender @ react-hot-loader.development.js:1508
proxiedRender @ react-hot-loader.development.js:629
finishClassComponent @ react-dom.development.js:13393
updateClassComponent @ react-dom.development.js:13356
...
```
The reason is most likely the fact that I'm wrapping my async component with a HOC defaultProps on component load. If I don't do it (which I can't do it because I can only set defaultProps HOC during runtime), warning disappears. Warning also disappears if I wrap the whole module with hot(module)(MyAsyncComponent). The problem with the latter is that I have many components that would need to be wrapped like that and the whole HMR is working fine even without it, it just generates this warning that I would love to fix, ideally without suppressing warning logs. 

```
// ... Async Component Module
export default {
    Component: connect(mapStateToProps)(MyComponent),
    Reducers
};
// ... Async component loader that register reducers on load and returns component
export const loadComponent: LoadComponentType = (ComponentLoader, props) =>
    Loadable({
        loader: () => ComponentLoader().then(Module => ReduxRegister.registerModule(Module.default, props)),
        loading: LoadingComponent
    });
// ... ReduxRegister
registerModule = (Module: Module, props: ?Object = {}): ?React.ComponentType<*> => {
    const { Component, Reducers } = Module;

    this.registerReducers(Reducers);
    return defaultProps(props)(Component);
};
```
I'm running the latest version of everything (webpack 4, babel 7, react 16.5, RHL 4.3.8)

Thanks!

**Comment by theKashey** [comment]
Quite interesting approach. It would be great if you will provide any example to play with.
Optionally - could you show the code for `defaultProps`?

I am almost absolutely sure about two things:
1. There is at least one error inside RHL react tree traversal
2. It's 99.9% error proof.

Probably here problem is with components `displayName` - it could be different for rendered and not-yet rendered components - you may set a break point in [the place](https://github.com/gaearon/react-hot-loader/blob/master/src/reconciler/hotReplacementRender.js#L423) where we are comparing old and new `type` and double check "how" they are different in real.

**Comment by Zdend** [comment]
It might take me some time to assemble a reproducible repo. However I set a breakpoint where the warning is and these are the values - not sure whether it will be useful at all.

![screen shot 2018-09-17 at 6 04 17 pm](https://user-images.githubusercontent.com/8145571/45611840-45029480-baa4-11e8-8638-4733c5886ca5.png)

**Comment by theKashey** [comment]
Ok, look like the problem is about seeing "LoadingComponent" in React tree, while a "target" component has been rendered by fact. Somehow similar to #1050

This happens cos RHL is _"always enabled"_ and trying to did it's job even without actual "HMR" event.

Right now there is no way you can solve this issue (this is not a real issue) - probably just suppress warning. Everything should work - it just reporting about situation it could not handle, and shall not handle.

**Comment by Zdend** [comment]
Thanks for taking the time! I'll most likely try to wrap every async component in hot(module) as it clears out undefined in the Updated modules list and solves the warning, it's just a little bit cumbersome to do it for every async component.
```
11:50:00.895 console.js:35 [HMR] Updated modules:
11:50:00.895 console.js:35 [HMR]  - ./src/scripts/apps/enb/modules/api-connector/index.js
11:50:00.896 console.js:35 [HMR]  - undefined
11:50:00.896 console.js:35 [HMR]  - undefined
11:50:00.897 console.js:35 [HMR]  - undefined
```

**Comment by theKashey** [comment]
1. Please dont wrap anything with `hot` without special need
2. disable logging (actually look like you __enabled__ it)
```js
 import {setConfig} from 'react-hot-loader';
setConfig({logLevel: 'error'}); // and this is default value!
```

**Comment by Zdend** [comment]
The reason why I enabled logging in the first place was to find out why Updated modules are undefined as I was getting a pretty long list of undefined. I'm not sure whether it's related to the first issue with the warning but if I wrapped it with hot it actually solved the undefined logging so I thought that I must be doing something right :-)

**Comment by theKashey** [comment]
Try to find the origin of `[HMR]  - undefined` and find why it is `undefined`. There is no way to create a module without `id` - something could be very broken

**Comment by Zdend** [comment]
Thanks man, it seems to be related to webpack-hot-middleware - I'll continue my investigation over there. https://github.com/webpack-contrib/webpack-hot-middleware/issues/306
