### ISSUE TITLE
Update application for all devices

### ISSUE THREAD

**Issue by xgrommx** [gaearon/react-hot-loader#107]
Hello @gaearon I have one question about updating my application on all devices. How can I use proxy for connection like this:
I have localhost:3000 and my ip is 192.168.1.2, but I cannot connect for this. I think need use some proxy but I don't know how.

**Comment by gaearon** [comment]
What kind of devices? iOS?

**Comment by xgrommx** [comment]
Yes I mean IOS, Android, Windows phone

**Comment by tcoopman** [comment]
@xgrommx do you mean you want your applications to be able to surf to your own ip? You have listen to 0.0.0.0 with WebpackDevServer instead of to localhost.

**Comment by gaearon** [comment]
cc @appsforartists who has experience with this

**Comment by xgrommx** [comment]
@tcoopman Okay and where I should connect? To 0.0.0.0:3000 on my phone.

**Comment by gaearon** [comment]
@xgrommx Normally you run server at `0.0.0.0` and connect at whatever IP your computer has in the local network (usually `192.168.something.something`). But I think hot reloading wasn't working like this for me, at least on iOS. I'm not sure why: either socket support isn't there, or I had some other issue.

**Comment by tcoopman** [comment]
@xgromnx I haven't checked it with hot loader, but dev server should work like @gaeron explained

**Comment by appsforartists** [comment]
### Before You Begin ###

1) Add an entry for your app to `/private/etc/hosts`:

```
127.0.0.1       my-app-name.private
```

2) Make sure your `webpackDevServer.listen` call doesn't specify a host:

```javascript
require('prfun');
WebpackDevServer.prototype.listen = Promise.promisify(WebpackDevServer.prototype.listen)

// ...

// Notice, there's no host here; only a port:
webpackDevServer.listen(8080).then(
  // ...
)
```

### iOS ###
1) Download and install [Charles](http://www.charlesproxy.com/) on your computer.
2) Use its [DNS Spoofing feature (-Shift-D)](http://www.charlesproxy.com/documentation/tools/dns-spoofing/) to point [all requests to the *.private TLD to 127.0.0.1](https://docs.google.com/presentation/d/1X2k7U1iinUSSBJQvKLef4qDRuLhok6gtEl6PFf6op0o/edit#slide=id.g58aa60fa7_5181).
3) In your iPad's WiFi settings, set your [computer's IP as a proxy](https://docs.google.com/presentation/d/1X2k7U1iinUSSBJQvKLef4qDRuLhok6gtEl6PFf6op0o/edit#slide=id.g58aa60fa7_5162).
4) Go to http://my-app-name.private:8080 in Safari.
5) In Charles, authorize your iPad's proxy connection.

### Android ###

1) Root your device. (You can find instructions for your particular hardware with a Google search.)
2) Install [Hosts Editor](https://play.google.com/store/apps/details?id=com.nilhcem.hostseditor&hl=en).
3) Use Hosts Editor to point `my-app-name.private` to your computer's IP address.
4) Go to http://my-app-name.private:8080 in Chrome.

**Comment by appsforartists** [comment]
I just wrote that up from memory.  Let me know if it needs editing.

**Comment by gaearon** [comment]
Thanks!

**Comment by gpbl** [comment]
What about using the host name? I set it in the OS X sharing preferences. 
So if my hostname is `gpbl.local`, i set the web server to that address and I can reach `gpbl.local:3000` from the other devices.

Then, my webpack config is something like this:

```js
import os from 'os';
const host = os.hostname() || process.env.HOST || 'localhost';
const PORT = 3001;
const config = {
  entry: [
    `webpack-dev-server/client?http://${host}:${PORT}`,
    'webpack/hot/only-dev-server',
    './app/client.js'
  ],
  output: {
    publicPath: `http://${host}:${PORT}/assets/`
  }
}
```

**Comment by xgrommx** [comment]
I use this

This is my config

```js
var webpack = require('webpack');

module.exports = function(ip, port) {
  return {
    devtool: 'eval',
    entry: [
      'webpack-dev-server/client?' + ip + ':' + port,
      'webpack/hot/only-dev-server',
      './js/app'
    ],
    output: {
      path: __dirname + '/js/',
      filename: 'bundle.js',
      pathInfo: true,
      publicPath: '/js/'
    },
    resolve: {
      extensions: ['', '.js', '.jsx', '.styl']
    },
    module: {
      loaders: [
        {test: /\.js?$/, loaders: ['react-hot', 'babel'], exclude: /node_modules/},
        {test: /\.styl?$/, loader: 'style!css!stylus?paths=node_modules/'}
      ]
    },
    plugins: [
      new webpack.HotModuleReplacementPlugin(),
      new webpack.NoErrorsPlugin()
    ]
  };
};
```

And this is my server

```js
var ip = require('ip');
var port = 3000;
ip = ip.address();

var webpack = require('webpack');
var WebpackDevServer = require('webpack-dev-server');
var config = require('./webpack.config')(ip, port);

new WebpackDevServer(webpack(config), {
  publicPath: config.output.publicPath,
  hot: true,
  historyApiFallback: true,
  headers: {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "Origin, X-Requested-With, Content-Type, Accept"
  }
})
.listen(port, ip, function(err, result) {
  if(err) {
    console.log(err);
  }

  console.log('Listening at ' + [ip, port].join(':'));
});
```

Now it work on all my devices.

**Comment by appsforartists** [comment]
@gpbl that works as long as you only ever want to test one domain.   I have unique hosts set for all my projects.  This is especially important if you are developing an API and an app concurrently.

(The nice thing about your technique is that it uses mDNS, so you don't have to worry about [Apple's utterly broken resolution of .local URLs](https://support.apple.com/en-us/TS3389).)

**Comment by appsforartists** [comment]
@xgrommx Glad you got it working.  I'd still remove the `ip` arg from the `listen` call, so you don't end up confusing yourself later if you try to move to domains and your app stops responding.

**Comment by appsforartists** [comment]
@gaearon I think we can close this now.

**Comment by gaearon** [comment]
I'd like this to be somewhere in docs but I'm not sure where to put it.
If somebody can turn it into an article that'd be great, I'd just link to it.

**Comment by appsforartists** [comment]
I should start doing some technical writing.  I've also got one I want to write about an experiment I'm going with functionally-reactive flux.

**Comment by gaearon** [comment]
@appsforartists You should! I'd love to read your stuff.

**Comment by appsforartists** [comment]
:smiley:

**Comment by savovs** [comment]
Still struggling with this guys, I'm not really sure how to set up my config file :( http://stackoverflow.com/questions/37602797/accessing-webpack-dev-server-from-local-network-react-hot-reloading-on-mobile
