### ISSUE TITLE
IE 10 bug: Object.setPrototypeOf(ProxyComponent, InitialParent);

### ISSUE THREAD

**Issue by tarasbilozir** [gaearon/react-hot-loader#1071]
### Description

What you are reporting:
Bug

### Actual behavior

What actually happens:
IE 10 fails at Object.setPrototypeOf. This function is not supported in IE 10.

### Environment

React Hot Loader version:
4.3.4

Run these commands in the project folder and fill in their results:

1.  `node -v`: 8.11.3
2.  `npm -v`: 5.6.0

Then, specify:

1.  Operating system: Ubuntu 18.04
2.  Browser and version: IE 10

`var ES5ProxyComponentFactory = function ES5ProxyComponentFactory(InitialParent,` `postConstructionAction) {`
  `function ProxyComponent(props, context) {`
    `InitialParent.call(this, props, context);`
    `postConstructionAction.call(this);`
  `}`
  `ProxyComponent.prototype = Object.create(InitialParent.prototype);`
  `Object.setPrototypeOf(ProxyComponent, InitialParent); // IE 10 fails here`
  `return ProxyComponent;`
`};`

**Comment by theKashey** [comment]
`setPrototypeOf` is supported by IE11 and ReactHotLoader could not work without it. You can use `babel-polyfills` or `core-js` to have this method on unsupported browsers.

**Comment by theKashey** [comment]
Also - we are looking forward to disable RHL for systems it could not handle by any reason(#917)

**Comment by tarasbilozir** [comment]
Oh, sorry. This issue is about IE 10. Updated the issue.

**Comment by theKashey** [comment]
Anyway - the only thing I could do - disable RHL at all for the not supported systems.

**Comment by tarasbilozir** [comment]
I think this solution is good enough.

**Comment by theKashey** [comment]
Ok. It's actually a 3 lines in https://github.com/gaearon/react-hot-loader/blob/master/index.js - test that setPrototypeOf exists and eval is supported - by my _today_ is over. See you tomorrow :)

**Comment by tarasbilozir** [comment]
Thank you, bye :)

**Comment by theKashey** [comment]
PR has been drafted. Next version of RHL will include production, not development build if env does not met required conditions - for example due to browser version or CSP
