### ISSUE TITLE
How to trigger page-reload?

### ISSUE THREAD

**Issue by ferlio** [gaearon/react-hot-loader#1075]
Our project is using both React classes and regular .js classes (utils mostly).

Considering we can't hot reload when updating a .js file - is there a solution to trigger a page reload when changing a .js file?
(so I don't have to do it manually after building)

**Comment by theKashey** [comment]
Just enable `hot` in webpack-dev-server and dont do anything else.
As long noone will `module.hot.accept` your changes - page will be reloaded.
