### ISSUE TITLE
Can't fix "React-hot-loader: fatal error caused by" on multiple HOCs

### ISSUE THREAD

**Issue by paumonnu** [gaearon/react-hot-loader#1076]
### Description

Can't fix the error "React-hot-loader: fatal error caused by", tried things for 3 days and no luck. Problem happens on component update and usually the error is thrown by "React-hot-loader: fatal error caused by WithStyles" (Material UI) or "React-hot-loader: fatal error caused by ReduxForm" (Redux Form), so my guess is that's a RHL config and not the packages.

Followed all official instructions and tried other fixes already exposed in this repo, but got no luck.

![rhlerror](https://user-images.githubusercontent.com/35768990/46540318-3ea05500-c8b9-11e8-90e8-8881c5bd242a.png)

### Expected behavior

There should be no error and the component should be hot loaded

### Actual behavior

Error is shown and no update happens until full page reload

### Environment

React Hot Loader version: 4.3.11
Node version: v8.9.0
Npm version: 5.7.1
OS: Windows 10
Browser: Chrome 69.0.3497.100 

### Reproducible Demo

I've created a minimal example repository of the error, you'll find it here:

[https://github.com/Paumonsu/react-hot-loader-test](https://github.com/Paumonsu/react-hot-loader-test) 

Try changing the button label to see the error in console

**Comment by theKashey** [comment]
You are using a few tricky babel plugins, which "should be enabled only in production". 
To be more concrete - https://babeljs.io/docs/en/next/babel-plugin-transform-react-inline-elements - inlines React.createElement, as result RHL could not override it.

**Comment by paumonnu** [comment]
> You are using a few tricky babel plugins, which "should be enabled only in production".
> To be more concrete - https://babeljs.io/docs/en/next/babel-plugin-transform-react-inline-elements - inlines React.createElement, as result RHL could not override it.

Thank you! that was it. Didn't know you can't use that plugin on development. Been using it for months to skip typing "key" tag on iterators. Will have to add key tags on all code from now on.

**Comment by theKashey** [comment]
Try react-uid for key generation.
