### ISSUE TITLE
Seeing bunch of "Cannot find module'*'. errors when saving a sass file.

### ISSUE THREAD

**Issue by justinmwarner** [gaearon/react-hot-loader#1077]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

What you are reporting: Successfully added react-hot-loader to our project, but when we save a .scss file, we get a bunch of errors (> 400) relating to "Cannot find module '*' where * is moment, query-string, redux-batched-actions, etc.

We also see a random TS error that we don't normally get. I think this will help find the solution, which is why I mention it. Without hot reload, this error never came up

Also, strangely, we get errors from our test file which is excluded during this bundling/transpiling.

### Expected behavior

What you think should happen: No errors.

### Actual behavior

What actually happens:Many errors like:
```
ERROR in C:/Users/juwar/source/repos/.../tests/Unit/Utils/Utils.spec.tsx(22,25):
TS2307: Cannot find module 'moment'.
```

### Environment

React Hot Loader version: 4.3.11

Run these commands in the project folder and fill in their results:

1.  `node -v`:10.10.0
2.  `npm -v`:6.4.1

Typescript version 3.0.1

Then, specify:

1.  Operating system:Windows 10
2.  Browser and version: Doesn't apply.

### Reproducible Demo

I cannot do this. I understand this limits the ability to help, but I'm more than happy to do any debugging on my end, but I'm unsure of where to start on this one.

**Comment by theKashey** [comment]
Sorry, but you have got issue with webpack Hot Module Replacement, not with React-Hot-Loader, for which you have enabled this feature.
We cannot help you.
PS: and demo would be required, as long usually this stuff just works.

**Comment by justinmwarner** [comment]
I will take a look at this and close this issue.  I haven't found anything obvious yet, so not sure what the cause is. Will update here if anything is found.  Thanks!
