### ISSUE TITLE
Replace module.makeHot with a decorator

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#108]
Currently RHL only knows about the exported classes.  
If you export a function, you need to use `module.makeHot` API provided by the hot loader:

```js
export default function makeComponent(whatever) {
  class Something {
    ...
  }
  
  if (module.makeHot) { // false in production
    Something = module.makeHot(Something);
  }

  return Something;
}
```

This API is overly verbose and I don't like it.
Instead, we can do some magic to make this work:

```js
import { hotReload } from 'react-hot-loader';

export default function makeComponent(whatever) {
  class Something {
    ...
  }
  return hotReload(Something);
}
```

This would be an identity function in production, and RHL patcher in development. RHL would emit additional code to keep track of current `module` so `withHotReload` knows which module to attach to.

Finally, with ES7 decorators (next version of Babel will support them), we can write this as

```js
import { hotReload } from 'react-hot-loader';

export default function makeComponent(whatever) {
  return @hotReload class Something {
    ...
  };
}
```

Now that we talk about Babel, there's another, much more fun option. If Babel had a transform that wraps each class declaration into a specified function, we would not need this trickery at all. What do you think @sebmck?

**Comment by sebmck** [comment]
> Finally, with ES7 annotations

Just to be pedantic they're decorators and are very different from annotations.

> If Babel had a transform that wraps each class declaration into a specified function, we would not need this trickery at all.

This would be absolutely doable with the plugin API coming in the next major:

```javascript
import { types as t } from "babel";

export function ClassExpression(node) {

}
```

**Comment by sebmck** [comment]
> Finally, with ES7 annotations

Just to be pedantic they're decorators and are very different from annotations.

> If Babel had a transform that wraps each class declaration into a specified function, we would not need this trickery at all.

This would be absolutely doable with the plugin API coming in the next major.

**Comment by gaearon** [comment]
>Just to be pedantic they're decorators and are very different from annotations. 

Yeah. Some recent “decorators or annotations” argument caused a brainfart in my head.

**Comment by gaearon** [comment]
Just wrote some thoughts about what I want 2.0 to become: https://medium.com/@dan_abramov/the-death-of-react-hot-loader-765fa791d7c4

cc @sebmck @milankinen @caspervonb

**Comment by gaearon** [comment]
Continued by:

* https://github.com/gaearon/react-hot-boilerplate/pull/33
* https://github.com/gaearon/react-hot-loader/pull/182
