### ISSUE TITLE
Using `module` for `hot` cancels some webpack optimizations in prod

### ISSUE THREAD

**Issue by smelukov** [gaearon/react-hot-loader#1080]
```js
import React from 'react'
import { hot } from 'react-hot-loader'

const App = () => <div>Hello World!</div>

export default hot(module)(App)
```

This code uses `module` variable. This cancels at least [concatenateModules](https://webpack.js.org/configuration/optimization/#optimization-concatenatemodules) optimization (enabled in prod mode)
https://github.com/webpack/webpack/blob/af90df9998c2aec0a9f8fbb6c488a0c423b1a331/lib/optimize/ModuleConcatenationPlugin.js#L104

Seems like bundles that using RHL has the worst size and eval-performance because some webpack-optimizations just not applying

I've created a simple babel-plugin, that replaces `export default hot(module)(App)` by `export default App` and it dropped **200kb** from total bundle size by dropping useless code and by ModuleConcatenationPlugin stuff.
Notу that we have only 8 places where we using `hot` in our code. 200kb for only 8 places... not bad...

But it seems like a hack... I think, that the problem should be solved on RHL side.

I can create a PR to `babel.prod.js` with replacing `hot(module)(App)` by `App`

**Comment by theKashey** [comment]
Probably we could ship your babel plugin as our `prod` version of babel plugin, which, right now, is doing nothing.

**Comment by smelukov** [comment]
Interesting fact:
I've built only modules, that uses `hot` and got 7056kb (without dropping `module`) vs 4192kb  (with dropping `module`)

**Comment by theKashey** [comment]
That's sounds a bit crazy. How many `hot` calls you have got?

**Comment by smelukov** [comment]
8

**Comment by smelukov** [comment]
> It's nearly 40-50% size reducing for some bundles in prod-mode

It's because
- webpack applies some optimizations only for pure ESModules
- uglifyjs removes entirely `import { hot } from 'react-hot-loader'` because hot is dropped

**Comment by theKashey** [comment]
react-hot-loader in prod is just a few bytes. And a dozen kb in dev mode.
Could you generate webpack stats (ie bundle-analizer) to double check the "real" difference. Or, disable module concatenation, and double check it is a real driver of bundle size change.
The difference is too huge.

**Comment by smelukov** [comment]
Hhhmmm... seems like I was measuring `prod` vs `dev` 🤦
The real difference `prod` vs `prod` is 4-5kb on 8 `hot`-calls
4-5 kb is because we have a really huge amount of chunks

**Comment by theKashey** [comment]
Anyway - removing side-effect is still a good thing.

**Comment by smelukov** [comment]
Sure )

**Comment by theKashey** [comment]
Unfortunately, it does not tree-share React-Hot-Loader itself - ideally the import statement shall also be removed.
