### ISSUE TITLE
The main difference between hot and AppContainer

### ISSUE THREAD

**Issue by smelukov** [gaearon/react-hot-loader#1082]
The docs "tells" that we have two variants of using RHL.
With `AppContainer` and `module.hot.accept`:
```jsx
import React from 'react'
import ReactDOM from 'react-dom'
import { AppContainer } from 'react-hot-loader'
import App from './containers/App'

const render = Component => {
  ReactDOM.render(
    <AppContainer>
      <Component />
    </AppContainer>,
    document.getElementById('root'),
  )
}

render(App)

if (module.hot) {
  module.hot.accept('./containers/App', () => {
    render(App)
  })
}
```
and with `hot`-call:
```jsx
import React from 'react'
import { hot } from 'react-hot-loader'

const App = () => <div>Hello World!</div>

export default hot(module)(App)
```

Did I understand correctly that:
- in the **first** variant we will have **entirely remount** of App-component with whole subtree
- in the **second** variant we will have only force update the state and **partial rerender** on **mounted** App

If it right, then should we make the docs more clearable about this difference?

**Comment by theKashey** [comment]
The best way is just to deprecate AppContainer. But both code examples do the same - updates __everything from the current module and "below"__.

**Comment by smelukov** [comment]
> But both code examples are doing the same - updates everything from the current module and "below"
Hmmmm... but AppContainer is not the same that `hot`. There are different behavior

**Comment by theKashey** [comment]
`hot` is AppContainer + HMR + some stuff around.

**Comment by zhangwilling** [comment]
what's the difference between hot(module)(Main)  and hot(App) in the docs? 
i use 

```
import { hot } from 'react-hot-loader/root'
const App = () => <div>Hello World!</div>
export default hot(App)
```
this got  error:  `Cannot read property 'i' of undefined`

error happen here :  `exports.hot = hot(Object.assign({ id: parent.i }, parent))`

but 

```
import { hot } from 'react-hot-loader'
const App = () => <div>Hello World!</div>
export default hot(module)(App)
```

it's ok

**Comment by theKashey** [comment]
@zhangwilling - then something is wrong with our module system, it's working in an unpredicted way. React-Hot-Loader is trying to get `parent` of `react-hot-loader/root`, ie your module, you are importing `root` from, but something is not working.
Could you shed some light on your build tools?

**Comment by zhangwilling** [comment]
thx for your response, i am a little busy, i will try some experiments at this weekend, then i would give you the demo.

**Comment by theKashey** [comment]
There is no need of real demo. Let's look into [root.js](https://github.com/gaearon/react-hot-loader/blob/master/root.js)
```js
  var hot = require('./index').hot
  var cache = require.cache
  // ^ this would be something like __webpack_require__.cache

  var parent = cache[module.parents[0]]
  // parents should be an array, with a single element, and that element should be "your" module
  // THIS `parent` is undefined. The question is why - wrong data in `parents` or `cache`?

  delete cache[module.id]

  exports.hot = hot(Object.assign({ id: parent.i }, parent))
  // ^^  it dies here
```

**Comment by stephtr** [comment]
> this got error: `Cannot read property 'i' of undefined`

Is it possible that you are using both, `HotModuleReplacementPlugin` and `webpack-dev-server` **`--hot`**?

**Comment by aalpgiray** [comment]
Why is this closed? What is the resolution to the problem? 
I have published a sample code wıth problem in it.

https://github.com/aalpgiray/webapp

**Comment by theKashey** [comment]
Adding 
` Error: React-Hot-Loader: `react-hot-loader/root` is not supported on your system. Please use `import {hot} from "react-hot-loader"` instead`

Yes - use old `{hot}` API instead, `parcel` does not provide information about the parent module `/root` is relying on.

**Comment by aalpgiray** [comment]
Thank you for the quick fix. But, I wonder did I lose something when I use it this way?

**Comment by theKashey** [comment]
@aalpgiray - yes :( and no. `/root` hot just "separated" `hot`. 
`hot(module)` spinups HMR (accepts module update), while `*(App)` - sets the component to work with.
```
import {hot} from 'react-hot-loader';
const finishHOT = hot(module);
// the rest of imports
// ......
finishHOT(App)
```

But :( you cannot inject something before _imports_. You might try to use `require` for `App.js`.

The meaning of all this - setup `accept listened` before any runtime exception in a new code could stop the current script execution.
