### ISSUE TITLE
Component hot load, not work render

### ISSUE THREAD

**Issue by Hal-pan** [gaearon/react-hot-loader#1083]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description
What you are reporting:
I modified the title field in the columns object.
App is up to date, but the style is unchanged
### Expected behavior

What you think should happen:
App is up to date, style is changed
### Actual behavior

What actually happens:
App is up to date, but the style is unchanged
### Environment

React Hot Loader version:
4.3.11
Run these commands in the project folder and fill in their results:

1.  `node -v`: v10.10.0
2.  `npm -v`:3.10.10

Then, specify:

1.  Operating system: os Mojave v10.14
2.  Browser and version:chrome v70.0.3538.67

### Reproducible Demo

Please take the time to create a new project that reproduces the issue.

You can copy your project that experiences the problem and start removing things until you’re left with the minimal reproducible demo. This helps contributors, and you might get to the root of your problem during that process.

Push to GitHub and paste the link here.

**Comment by theKashey** [comment]
Sorry, I am going to close this issue and not properly filled. There is no valuable information, about what does mean "style" for you, and how they works for you.

Styled components usually works (this is our job), webpack style-loader also works (but this is already webpack HMR in work). But there are too many combination to reason about all of them.
