### ISSUE TITLE
Consider using 'sideEffects: false' to allow webpack to tree-shake RHL

### ISSUE THREAD

**Issue by edmorley** [gaearon/react-hot-loader#1095]
### Description

In #1081 (included in RHL 4.3.12) and #1093 (on `master`), the RHL Babel plugin now removes much of RHL when `NODE_ENV=production`, allowing webpack to concatenate modules. However parts of RHL still remain in the bundle, which could be prevented by adding `"sideEffects": false` to `package.json`:
https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

### Expected behavior

A production (`mode: 'production'` and `NODE_ENV=production`) webpack build should include as few parts of RHL as possible.

### Actual behavior

Whilst #1093 definitely helped, there is still RHL code in the bundle output:
https://github.com/edmorley/testcase-react-hot-loader-sideEffects/commit/92d39025ad45cc6350f968b10cb2b54b8d706fb8#diff-6ca863eb505df8653ce3c20b340ba580R4636

### Environment

* React Hot Loader version: `master` (83a4961b)
* `node -v`: 11.0.0
* `npm -v`: N/A (yarn 1.12.0)
* Operating system: Windows 10
* Browser and version: N/A (inspecting bundle)

### Reproducible Demo

See the repository here:
https://github.com/edmorley/testcase-react-hot-loader-sideEffects

The first commit (https://github.com/edmorley/testcase-react-hot-loader-sideEffects/commit/eb5562cce62411294cc6030b62ec29e4e58d0094) shows the output using the latest published RHL (run `yarn && yarn build > build.log` in that repo).

The second commit (https://github.com/edmorley/testcase-react-hot-loader-sideEffects/commit/92d39025ad45cc6350f968b10cb2b54b8d706fb8) was generated by `yarn link`ing in `react-hot-loader` master, then running `yarn build > build.log` again -- and shows the benefit from #1093.

The third commit (https://github.com/edmorley/testcase-react-hot-loader-sideEffects/commit/d59d4f67385f484d9c63197b342336772dd06985) shows the effect of adding `"sideEffects": false` to the `package.json` of that yarn linked `react-hot-loader` master build before running the `yarn build > build.log`.

NB: For the yarn linked builds (2nd and 3rd commit) it's very important to delete the `node_modules` in the `react-hot-loader` git clone before running `yarn build` in the testcase repo, otherwise webpack will include two copies of React (since it will treat `testcase-react-hot-loader-sideEffects/node_modules/react/` and `<RHL-git-clone>/node_modules/react/` as separate modules) - which will give the false impression the bundle size would have increased in normal usage.

**Comment by theKashey** [comment]
There is no way to code split something you did not import. And with latest babel plugin updates you will not import RHL in _normal_ use case.
> the latest-latest version it not yet published.

**Comment by edmorley** [comment]
Hi! Thank you for your reply.

> the latest-latest version it not yet published.

Yeah I realise it isn't, which is why I used a build from `master` (see the issue description).

> There is no way to code split something you did not import. And with latest babel plugin updates you will not import RHL in _normal_ use case.

This is not the case - see the repo linked in the issue description. Specifically this part:

> Whilst #1093 definitely helped, there is still RHL code in the bundle output:
> [edmorley/testcase-react-hot-loader-sideEffects@92d3902#diff-6ca863eb505df8653ce3c20b340ba580R4636](https://github.com/edmorley/testcase-react-hot-loader-sideEffects/commit/92d39025ad45cc6350f968b10cb2b54b8d706fb8#diff-6ca863eb505df8653ce3c20b340ba580R4636)

If it's not expected for there still to have been imported code, then perhaps there is another bug remaining after #1093? And if that bug is fixed, then we won't need #1096 to work around it?

**Comment by edmorley** [comment]
@smelukov hi! The changes in #1093 definitely helped, but I still see some RHL code left in the production bundle using a custom RHL build from `master`:
https://github.com/edmorley/testcase-react-hot-loader-sideEffects/commit/92d39025ad45cc6350f968b10cb2b54b8d706fb8#diff-6ca863eb505df8653ce3c20b340ba580R4636

Is this expected? Could it be resolved via the prod babel plugin (`src/babel.prod.js`) rather than needing to use `"sideEffects": false`? :-)

**Comment by theKashey** [comment]
Probably ‘sideEffects:false’ could help in production, and don’t break anything in dev, as long as Babel plugin injects ‘require’, which ignores sideEffect prop.

**Comment by smelukov** [comment]
`sideEffects` will work only for prod-mode, therefore if `sideEffects: false` does clean remained RHL code then I think that you may add `sideEffects: false` to the RHL package.json :)
