### ISSUE TITLE
Change the react state, but the page does not update.

### ISSUE THREAD

**Issue by chenhebing** [gaearon/react-hot-loader#1103]
### Description

Such as the title.

### Expected behavior

the page can update when the state change.

### Actual behavior

the page dose not update.

### Environment

React Hot Loader version: 4.4.0

1.  node:  8.12.0
2.  npm:  6.4.1
3.  babel: 7.1.2
4. webpack: 4.25.1
5.  koa-webpack: ^5.1.0

Then, specify:

1.  Operating system: macOs
2.  Browser and version: chrome 70

### Reproducible Demo

clone https://github.com/chenhebing/monking-react-render.git, and 'npm run dev'.

webpack.dev.config
```js
......
      rules: [{
            test: /\.jsx?$/,
            loader: 'babel-loader',
            exclude: /node_modules/,
            options: {
                presets: [['@babel/preset-env', {
                    modules: false
                }]],
                plugins: ['react-hot-loader/babel']
            }
        }, {
            test: /\.jsx$/,
            loader: require.resolve('react-hot-loader-loader')
        }]
```

.babelrc
```js
{
    "presets": ["@babel/preset-react"],
    "plugins": [
        "@babel/plugin-transform-modules-commonjs",
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-proposal-object-rest-spread"
    ]
}
```
index.jsx

```js
import React, { PureComponent } from 'react';
import { className } from './index.css';

export default class Home extends PureComponent {
    constructor (props) {
        super(props);
        this.state = {
            count: 1
        };
    }
    handleClick () {
        this.setState({
            count: this.state.count + 2
        });
    }

    render () {
        return (
            <div className={className}>
                <button type="button" onClick={this.handleClick.bind(this)}>+</button>
                <span>{this.state.count}</span>
            </div>
        );
    }
}
```

I modify 'this.state = {count: 1}' to 'this.state = {count: 2}', the count in the page is still 1.

![image](https://user-images.githubusercontent.com/12512045/48544955-c25d5080-e8ff-11e8-9501-299d9354081f.png)

![image](https://user-images.githubusercontent.com/12512045/48545121-208a3380-e900-11e8-8e30-57732cbd2a18.png)

**Comment by theKashey** [comment]
That's one of the rules of React-Hot-Loader - it __preserves__ state. And don't change the _past_. Initial state value, you may set in the constructor, is the _past_.
That's the goal.

**Comment by chenhebing** [comment]
> That's one of the rules of React-Hot-Loader - it **preserves** state. And don't change the _past_. Initial state value, you may set in the constructor, is the _past_.
> That's the goal.

ok, thx!

**Comment by chenhebing** [comment]
> That's one of the rules of React-Hot-Loader - it **preserves** state. And don't change the _past_. Initial state value, you may set in the constructor, is the _past_.
> That's the goal.

I update code to:
```js
import React, { Component } from 'react';
import { className } from './index.css';

export default class Home extends Component {
    constructor (props) {
        super(props);
        this.initCount = 1;
        this.state = {
            count: 0
        };
    }
    handleClick () {
        this.setState({
            count: this.state.count + 2
        });
    }

    render () {
        return (
            <div className={className}>
                <button type="button" onClick={this.handleClick.bind(this)}>+</button>
                <span>{this.state.count + this.initCount}</span>
            </div>
        );
    }
}
```
It is worked. But if code is liked this:
```js
import React, { Component } from 'react';
import { className } from './index.css';

export default class Home extends Component {
    constructor (props) {
        super(props);
        this.constData = {
            initCount: 1
        };
        this.state = {
            count: 0
        };
    }
    handleClick () {
        this.setState({
            count: this.state.count + 2
        });
    }

    render () {
        return (
            <div className={className}>
                <button type="button" onClick={this.handleClick.bind(this)}>+</button>
                <span>{this.state.count + this.constData.initCount}</span>
            </div>
        );
    }
}
```
it not worked. 

This is for improving performance.

**Comment by theKashey** [comment]
It will update "simple" values(which are "equal" between instances) and methods, but would ignore any complex objects, as long they are always unique.
