### ISSUE TITLE
Document that react-hot-loader/babel should now be used in production too

### ISSUE THREAD

**Issue by edmorley** [gaearon/react-hot-loader#1104]
In #1081 the RHL Babel plugin for when `process.env.NODE_ENV` is `production` was changed from a no-op to a plugin that removes the `hot()` wrapper.

This means it's now recommended to not only use the plugin in development, but in any production configs too.

As such, it would be good to update the docs to say that `react-hot-loader/babel` should be used in all environments. eg here:
https://github.com/gaearon/react-hot-loader#getting-started
https://github.com/gaearon/react-hot-loader#migrating-from-create-react-app

CC @smelukov

**Comment by smelukov** [comment]
@edmorley Good idea. Are you willing to do this by your self?

**Comment by edmorley** [comment]
I might have a chance to open a PR in a week or two, but quite a few other things pending at the moment :-)

**Comment by theKashey** [comment]
`hot` in production does nothing, but(!) - as long as you have passed a magic `module` variable inside - it will disable webpack module concatenation. That's why it's good to remove it completely.

**Comment by DinerIsmail** [comment]
@theKashey can you please detail that a bit more? How do you know that it disables webpack module concatenation? Also, do you mean that happens when we use the plugin in production config?

**Comment by theKashey** [comment]
@DinerIsmail - see https://github.com/gaearon/react-hot-loader/issues/1080
