### ISSUE TITLE
Cannot add property _ctor, object is not extensible

### ISSUE THREAD

**Issue by mdtanrikulu** [gaearon/react-hot-loader#1107]
### Description
I was planning to use v4.4.0 for the forwardRef support but unfortunately had this issue; 
Hot-loader tries to add `_ctor` property into objects, it inhibits use of `Object.freeze` method.

### Expected behavior

Usage of Object.freeze method should be fine. 

### Actual behavior

Having this error: 
```js
react-hot-loader.development.js?c2cb:984 Uncaught TypeError: Cannot add property _ctor, object is not extensible
```

### Environment

React Hot Loader version: 4.4.0

1.  `node -v`: 10.6.0
2.  `npm -v`: 6.4.1

1.  Operating system: macOS Mojave 10.14.1
2.  Browser and version: Chromium 61.0.3163.100

### Reproducible Demo

[Here it is.](https://codesandbox.io/s/kkkwmjozx3?module=%2Fsrc%2FApp.js)

**Comment by theKashey** [comment]
That's a known problem. Please switch to the `next` branch (v 4.5.1)

**Comment by theKashey** [comment]
Lets keep this open until fix would land to a real release.

**Comment by theKashey** [comment]
Since 4.6.0
