### ISSUE TITLE
Babel plugin causes react to be added to all Webpack outputs even if not used

### ISSUE THREAD

**Issue by driskell** [gaearon/react-hot-loader#1109]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

Granted this can be edge case as most of the time all outputs from a webpack will contain react. In a couple of my projects, however, we use a single webpack and build many bundles for many different areas of the application, both frontend and backend, and also to generate render blocking bundles separate to deferred bundles - and react is always in a deferred bundle.

With multiple entry points in webpack, some using React and some not, as described above, all outputs contain react, react.production.min and the react hot loader code, in some cases tripling or quadrupling the size of what should be small outputs.

### Expected behavior

Outputs that do not require react, do not have react hot loader in them or any of its dependencies.

### Actual behavior

The bottom of the output always contains the following, even if the output never had react within it, and therefore pulls in additional chunks of code. This is added by the babel plugin.

```
(function () {
    var reactHotLoader = __webpack_require__(0).default;

    var leaveModule = __webpack_require__(0).leaveModule;

    if (!reactHotLoader) {
        return;
    }

    reactHotLoader.register(_extends, "_extends", "non-react-import.js");
    reactHotLoader.register(_typeof, "_typeof", "non-react-import.js");
    leaveModule(module);
})();
```

The following are therefore added to the bundle unnecessarily (as can be seen in the source map):

```
"webpack:///./node_modules/react-hot-loader/index.js",
"webpack:///(webpack)/buildin/harmony-module.js",
"webpack:///./node_modules/react/index.js",
"webpack:///./node_modules/fbjs/lib/emptyFunction.js",
"webpack:///./node_modules/react-hot-loader/dist/react-hot-loader.production.min.js",
"webpack:///./node_modules/object-assign/index.js",
"webpack:///./node_modules/fbjs/lib/emptyObject.js",
"webpack:///(webpack)/buildin/module.js",
"webpack:///./node_modules/react/cjs/react.production.min.js",
```

As an example, it increases a 156K bundle to 170K, an increase of 14K. For small bundles that are 10K it's a doubling in size. Granted, this is not a significant, but it was unexpected and took time to investigate what the impact was as we hadn't anticipated this code to be in the bundle at all.

### Environment

React Hot Loader version: 4.3.12

Run these commands in the project folder and fill in their results:

1.  `node -v`: 8.12.0
2.  `npm -v`: 6.4.1

Then, specify:

1.  Operating system: OSX Mojave
2.  Browser and version: Safari 12

### Reproducible Demo

Can look at generating one if needed.

**Comment by driskell** [comment]
Further investigation it might be related to process.env.NODE_ENV not being picked up in the babel part, as the development one is what adds in the extra code.

**Comment by theKashey** [comment]
PS: Ok, it wouldn't be "nothing", as long as it has to import React for `AppContainer`. 
Babel plugin should not amend files in production mode, only remove calls to `hot`. Please sure that you are not just providing some settings for webpack, but have NODE_ENV set as a real env variable during the build.

**Comment by driskell** [comment]
@theKashey the DefinePlugin (I’m using webpack 3) only performs a replace in generated code and doesn’t actually set NODE_ENV of the webpack process itself.

This means that without running webpack with NODE_ENV=production the Babel code for React hot loader does not use the production version and so it appends the above code snippet and brings in React.

I’ve been trying to work out what I should be doing. I thought perhaps it is because I do not use webpack “-p” and give my own Uglify webpack plugin version but even that does not set NODE_ENV within the webpack environment - only in the generated code.

At the moment my workaround is to manually set it inside my webpack.prod.js config file at the top. Or to prefix my webpack run on the command line with NODE_ENV=.

At the moment I’m wondering if it’s missing documentation that when using React hot loader you need to run webpack in this way or if I’ve completely messed up my investigation but I haven’t yet had time to do a full end to end check and comparison.

**Comment by driskell** [comment]
> Please sure that you are not just providing some settings for webpack, but have NODE_ENV set as a real env variable during the build.

Yes this is what I am missing for sure.

**Comment by theKashey** [comment]
If something is not easy discoverable - it should be documented.
If you have struggled with our readme - be the change you seek and raise a PR.

**Comment by driskell** [comment]
@theKashey Yes I was going to. But my concern is this is documented somewhere and it just needs linking up. Specifically you were able to suggest the solution pretty accurately so I wondered if you’d seen it documented somewhere? If not I will raise a PR with full details that when using React-hot-loader/Babel then webpack production build must be run with NODE_ENV set.

Though in all honesty... I do wonder if there’s a way to rewrite the Babel loader such that the same code is written for both development and production builds and references NODE_ENV in such a way that optimisation will strip the code out and have the same effect as if hot() was never there or removed. That seems a nice challenge to me and means you don’t need to change how you run webpack and the bundle reduces in size in the exact same way it does with React - and it’s already well documented to use DefinePlugin to reduce bundle size in production.
