### ISSUE TITLE
Example Error Boundary

### ISSUE THREAD

**Issue by BetterCallSky** [gaearon/react-hot-loader#1111]
### Description

> React supports error handling out of the box since v16 using componentDidCatch. You can create your own Error Boundary and install it after hot has been applied:

Is it possible to provide an example Error Boundary?

I tried to create my own component using the official example with 'redbox-react', but the error is not gone after doing more changes. I keep the error in the state, and the error is never cleared.

Example component
```tsx
import React from 'react';
import RedBox from 'redbox-react';

export class ErrorBoundary extends React.Component<any, any> {
  constructor(props: any) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error: Error) {
    // Update state so the next render will show the fallback UI.
    return { hasError: error };
  }

  componentDidCatch(error: Error, info: any) {
    console.error(error, info);
  }

  render() {
    if (this.state.hasError) {
      return <RedBox error={this.state.hasError} />;
    }

    return this.props.children;
  }
}

```

How to clear the state if there are any changes?

### Expected behavior

Flow should look like this:
 edit code -> runtime error -> error boundary (red box) -> edit code again and fix error -> error boundary is hidden.

### Actual behavior

edit code -> runtime error -> error boundary (red box) -> edit code again and fix error -> error boundary is still visible.

### Environment

React Hot Loader version: 4.5.1

**Comment by theKashey** [comment]
:nods: It's not easy to catch "update" event and remove error overlay. 
@neoziro - I think we have to make ErrorOverlay a part of AppContaner

**Comment by theKashey** [comment]
Never mind. AppContainer has a prop named `errorReporter`, you just __can`t__ provide a settings for it :)

**Comment by BetterCallSky** [comment]
@theKashey 

Should I also use`<AppContaner />`? In readme, it's mentioned to use only `hot(..)`.  Here https://github.com/gaearon/react-hot-loader#migrating-from-v3

**Comment by theKashey** [comment]
In short:
 - the feature you are asking for is supported
 - you can't use it :)

We have to:
 - create a way to specify settings to the AppContainer created __inside__ hot
 - probably add one more field to `setConfig`, as long as your settings should be applied application wide.

**Comment by theKashey** [comment]
4.6.0 gives you everything.
Check `errorReporter` and `ErrorOverlay` options of `setConfig`

**Comment by BetterCallSky** [comment]
@theKashey thanks! 

One small thing. I can see below error when there is any runtime error. Is it expected or it should be displayed only during hot updates? 

![image](https://user-images.githubusercontent.com/4478684/49946091-86adaa80-feee-11e8-9f0d-651b93b38faa.png)

**Comment by theKashey** [comment]
As long as it displays an error - yes.
That is the error it tries to show?

**Comment by theKashey** [comment]
Should work "right" with the last version.
