### ISSUE TITLE
document.body may not be created yet when initializing RHL

### ISSUE THREAD

**Issue by renchap** [gaearon/react-hot-loader#1127]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

With RHL 4.6, when I can not load my entrypoint with a script tag in my page's `<head>`.

### Expected behavior

Everything should work

### Actual behavior

JS error: `Uncaught TypeError: Cannot read property 'appendChild' of null` on this line: https://github.com/gaearon/react-hot-loader/blob/f15b108cfac2aa6b8f98496b1e3103a4ad1c9e9c/src/errorReporter.js#L112

### Environment

React Hot Loader version: 4.6.0
Chrome 71

### Analysis

The `<script>` tag is synchronous, so it blocks the page loading to download the JS file and executes it. But as this is done while processing the document's `<head>`, the `<body>` tag is not yet processed, thus there is no `<body>` node in the page DOM yet.

### Possible fix

Fix wrap this function in `document.addEventListener("DOMContentLoaded", …)` so it is executed once the whole document has been parsed and the `<body>` tag exists.

### Workaround

Until this is fixed, you can move your `<script>` tag inside `<body>` (at the start or at the end) and everything will work fine

**Comment by renchap** [comment]
PR with my proposed fix here: #1128

**Comment by theKashey** [comment]
Try 4.6.1

**Comment by nfm** [comment]
@theKashey I can confirm this issue is still happening on 4.6.1. `document` is defined, but `document.body` isn't necessarily present at the time the script runs. @renchap's PR looks appropriate but will need to incorporate your change from 40e3ff2e5279468e2a6b39bc31299c47184e6935.

**Comment by theKashey** [comment]
Ok, I didn't get initial issue right - document is defined, but body is still not.
My bad.

**Comment by nfm** [comment]
Thanks @theKashey, I can confirm 4.6.2 resolves this issue :heart:
