### ISSUE TITLE
`const not initalized` in IE11

### ISSUE THREAD

**Issue by wasong** [gaearon/react-hot-loader#1130]
### Description
Development mode RHL with `webpack-hot-middleware` causes a `const not initalized` error in IE11 but works fine in Chrome. Production build works well in all environments with RHL disabled.

### Expected behavior

App should load properly in IE11 with RHL enabled.

### Actual behavior

These are the errors from my IE11 console.
![image](https://user-images.githubusercontent.com/10610126/50066764-8f161780-0172-11e9-8237-1d957eb42260.png)

This is the source code in dev mode where the error occurs
`; /* eslint-disable global-require, import/no-unresolved */ (function register() { /* react-hot-loader/webpack */ const reactHotLoader = __webpack_require__(/*! react-hot-loader */ "../node_modules/react-hot-loader/index.js").default; if (!reactHotLoader) { return } /* eslint-disable camelcase, no-undef */ const webpackExports = typeof __webpack_exports__ !== 'undefined' ? __webpack_exports__ : exports; /* eslint-enable camelcase, no-undef */ if (typeof webpackExports === 'function') { reactHotLoader.register(webpackExports, 'module.exports', "/projectPath/node_modules/@babel/polyfill/lib/index.js"); return } /* eslint-disable no-restricted-syntax */ for (const key in webpackExports) { /* eslint-enable no-restricted-syntax */ if (!Object.prototype.hasOwnProperty.call(webpackExports, key)) { continue } let namedExport; try { namedExport = webpackExports[key]; } catch (err) { continue } reactHotLoader.register(namedExport, key, "/projectPath/node_modules/@babel/polyfill/lib/index.js"); } })(); 
/* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! ./../../../webpack/buildin/global.js */ "../node_modules/webpack/buildin/global.js")))`

I suspect its the `for (const key in webpackExports)` part thats breaking in IE but I'm not sure how I would go about fixing it.

### Environment

React Hot Loader version: ^4.6.0
1.  `node -v`: v8.10.0
2.  `npm -v`: 6.0.1
1.  Operating system: MacOS Mojave 10.14.1
2.  Browser and version: IE11

**Comment by theKashey** [comment]
Try 4.6.1

**Comment by wasong** [comment]
Works with 4.6.1! Thanks!
