### ISSUE TITLE
Version 4.6.0 cause some error.

### ISSUE THREAD

**Issue by fwh1990** [gaearon/react-hot-loader#1131]
### Description

```js
// Error message
TypeError: Cannot read property 'call' of undefined
```

```js
// Source code
module.updateTimeout = setTimeout(function () {
      try {
        requireIndirect(sourceModule.id);
      } catch (e) {
        console.error(e);   // Yep, emit error from here.
      }
      module.instances.forEach(function (inst) {
        return inst.forceUpdate();
      });
});
```

### Expected behavior

Version 4.5.2 is ok.

### Actual behavior

Version 4.6.0 break.

### Environment

React Hot Loader version:

Run these commands in the project folder and fill in their results:

1.  `node -v `: 8.11.4
2.  `yarn -v`:  1.12.3

Then, specify:

1.  Operating system: macOs
2.  Browser and version: chrome latest

### Reproducible Demo

No, sorry.

**Comment by theKashey** [comment]
As far as I know - it does not `emit` error - it `report` error.

**Comment by theKashey** [comment]
Try 4.6.1. It does not change anything, except messaging around real error.

**Comment by fwh1990** [comment]
And then I got more message
```js
React-Hot-Loader: error detected while loading ./src/components/app/App.tsx
```

**Comment by fwh1990** [comment]
You should know that the error message only appear at first time. And no side effect happened, the RHL can work as usual.

**Comment by theKashey** [comment]
I shall not swallow the error. Something is not right, and it should report what exactly and where.
PS: You may manually remove try/catch block around require, and double check the root issue.

**Comment by fwh1990** [comment]
Error from webpack
```js
modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```

**Comment by fwh1990** [comment]
When I remove `webpack.DllReferencePlugin(...)` from my webpack config. The error gone.

**Comment by theKashey** [comment]
So - look like this error is a real error.

Try https://github.com/mzgoddard/hard-source-webpack-plugin

**Comment by fwh1990** [comment]
I have added `hard-source-webpack-plugin` in webpack config, but nothing changed. Am I need to input some options into this plugin?

**Comment by fwh1990** [comment]
> Remove DLL plugin and use only _Hard_ one - and you shall get the same _good_ speed.

Yeah, I have the same speed now. Thank you very much.
