### ISSUE TITLE
Unhandled JS Exception: Can't find variable: document

### ISSUE THREAD

**Issue by relign** [gaearon/react-hot-loader#1132]
I  have started the `websocket` service for remote debugging. The `webpack-dev-server` socket service is requested from the `Web Worker` to get the updated code.
However, I get the error "Unhandled JS Exception: Can't find variable: document" ,  it because of `web worker` don't have `document`.
I think it isn't right in `react-hot-loader@4.6.0`:
![image](https://user-images.githubusercontent.com/13749042/50074194-1bc5e180-0216-11e9-94e5-b63b0cd121e9.png)
The pr link: https://github.com/gaearon/react-hot-loader/pull/1128

I want know what should I do?

**Comment by relign** [comment]
This PR solve the issue.
https://github.com/gaearon/react-hot-loader/pull/1128

**Comment by theKashey** [comment]
Issue already was issued - #1126
