### ISSUE TITLE
I can't figure out why I get an error

### ISSUE THREAD

**Issue by SovietAlex** [gaearon/react-hot-loader#1137]
### Description
I get this every time

> [WDS] Hot Module Replacement enabled.
> 2client?0836:80 [WDS] App updated. Recompiling...
> client?0836:133 [WDS] 0% - compiling.
> client?0836:133 [WDS] 10% - building modules (0/1 modules).
> client?0836:133 [WDS] 10% - building modules (0/2 modules).
> client?0836:133 [WDS] 10% - building modules (1/2 modules).
> client?0836:133 [WDS] 10% - building modules (2/2 modules).
> client?0836:133 [WDS] 10% - building modules (2/3 modules).
> client?0836:133 [WDS] 10% - building modules (3/3 modules).
> client?0836:133 [WDS] 10% - building modules (3/4 modules).
> client?0836:133 [WDS] 10% - building modules (4/4 modules).
> client?0836:133 [WDS] 10% - building modules (4/5 modules).
> client?0836:133 [WDS] 10% - building modules (4/6 modules).
> client?0836:133 [WDS] 10% - building modules (5/6 modules).
> client?0836:133 [WDS] 10% - building modules (6/6 modules).
> client?0836:133 [WDS] 10% - building modules (6/7 modules).
> client?0836:133 [WDS] 10% - building modules (6/8 modules).
> client?0836:133 [WDS] 10% - building modules (6/9 modules).
> client?0836:133 [WDS] 10% - building modules (6/10 modules).
> client?0836:133 [WDS] 10% - building modules (7/10 modules).
> client?0836:133 [WDS] 10% - building modules (7/11 modules).
> client?0836:133 [WDS] 10% - building modules (8/11 modules).
> client?0836:133 [WDS] 10% - building modules (8/12 modules).
> client?0836:133 [WDS] 10% - building modules (9/12 modules).
> client?0836:133 [WDS] 10% - building modules (10/12 modules).
> client?0836:133 [WDS] 10% - building modules (11/12 modules).
> client?0836:133 [WDS] 10% - building modules (12/12 modules).
> client?0836:133 [WDS] 10% - building modules (12/13 modules).
> client?0836:133 [WDS] 10% - building modules (12/14 modules).
> client?0836:133 [WDS] 10% - building modules (12/15 modules).
> client?0836:133 [WDS] 10% - building modules (12/16 modules).
> client?0836:133 [WDS] 10% - building modules (12/17 modules).
> client?0836:133 [WDS] 10% - building modules (12/18 modules).
> client?0836:133 [WDS] 10% - building modules (12/19 modules).
> client?0836:133 [WDS] 10% - building modules (13/19 modules).
> client?0836:133 [WDS] 10% - building modules (14/19 modules).
> client?0836:133 [WDS] 10% - building modules (15/19 modules).
> client?0836:133 [WDS] 10% - building modules (16/19 modules).
> client?0836:133 [WDS] 10% - building modules (17/19 modules).
> client?0836:133 [WDS] 10% - building modules (18/19 modules).
> client?0836:133 [WDS] 10% - building modules (18/20 modules).
> client?0836:133 [WDS] 10% - building modules (18/21 modules).
> client?0836:133 [WDS] 10% - building modules (18/22 modules).
> client?0836:133 [WDS] 10% - building modules (18/23 modules).
> client?0836:133 [WDS] 10% - building modules (18/24 modules).
> client?0836:133 [WDS] 10% - building modules (18/25 modules).
> client?0836:133 [WDS] 10% - building modules (18/26 modules).
> client?0836:133 [WDS] 10% - building modules (18/27 modules).
> client?0836:133 [WDS] 10% - building modules (18/28 modules).
> client?0836:133 [WDS] 10% - building modules (18/29 modules).
> client?0836:133 [WDS] 10% - building modules (18/30 modules).
> client?0836:133 [WDS] 10% - building modules (18/31 modules).
> client?0836:133 [WDS] 10% - building modules (19/31 modules).
> client?0836:133 [WDS] 10% - building modules (20/31 modules).
> client?0836:133 [WDS] 10% - building modules (21/31 modules).
> client?0836:133 [WDS] 11% - building modules (22/31 modules).
> client?0836:133 [WDS] 11% - building modules (23/31 modules).
> client?0836:133 [WDS] 11% - building modules (24/31 modules).
> client?0836:133 [WDS] 11% - building modules (25/31 modules).
> client?0836:133 [WDS] 11% - building modules (26/31 modules).
> client?0836:133 [WDS] 11% - building modules (27/31 modules).
> client?0836:133 [WDS] 11% - building modules (28/31 modules).
> client?0836:133 [WDS] 11% - building modules (29/31 modules).
> client?0836:133 [WDS] 11% - building modules (30/31 modules).
> client?0836:133 [WDS] 11% - building modules (30/32 modules).
> client?0836:133 [WDS] 11% - building modules (31/32 modules).
> client?0836:133 [WDS] 11% - building modules (32/32 modules).
> client?0836:133 [WDS] 71% - sealing.
> client?0836:133 [WDS] 72% - optimizing.
> client?0836:133 [WDS] 73% - basic module optimization.
> client?0836:133 [WDS] 74% - module optimization.
> client?0836:133 [WDS] 75% - advanced module optimization.
> client?0836:133 [WDS] 76% - basic chunk optimization.
> client?0836:133 [WDS] 77% - chunk optimization.
> client?0836:133 [WDS] 78% - advanced chunk optimization.
> client?0836:133 [WDS] 79% - module and chunk tree optimization.
> client?0836:133 [WDS] 80% - chunk modules optimization.
> client?0836:133 [WDS] 81% - advanced chunk modules optimization.
> client?0836:133 [WDS] 82% - module reviving.
> client?0836:133 [WDS] 83% - module order optimization.
> client?0836:133 [WDS] 84% - module id optimization.
> client?0836:133 [WDS] 85% - chunk reviving.
> client?0836:133 [WDS] 86% - chunk order optimization.
> client?0836:133 [WDS] 87% - chunk id optimization.
> client?0836:133 [WDS] 88% - hashing.
> client?0836:133 [WDS] 89% - module assets processing.
> client?0836:133 [WDS] 90% - chunk assets processing.
> client?0836:133 [WDS] 91% - additional chunk assets processing.
> client?0836:133 [WDS] 92% - recording.
> client?0836:133 [WDS] 91% - additional asset processing.
> client?0836:133 [WDS] 92% - chunk asset optimization.
> client?0836:133 [WDS] 94% - asset optimization.
> client?0836:133 [WDS] 95% - emitting.
> client?0836:133 [WDS] 100% - Compilation completed.
> client?0836:223 [WDS] App hot update...
> log.js:23 [HMR] Checking for updates on the server...
> index.tsx:32 Uncaught Error: Preventing hot swap.
>     at index.tsx:32
>     at hotSetStatus (bootstrap 2c04382e606a60159e4e:857)
>     at Object.hotCheck [as check] (bootstrap 2c04382e606a60159e4e:879)
>     at check (dev-server.js:13)
>     at EventEmitter.<anonymous> (dev-server.js:47)
>     at EventEmitter.../node_modules/events/events.js.EventEmitter.emit (events.js:81)
>     at reloadApp (client?0836:226)
>     at Object.ok (client?0836:139)
>     at SockJS.onmessage (socket.js:41)
>     at SockJS.EventTarget.dispatchEvent (eventtarget.js:51)

### Webpack Config
`var webpack = require('webpack');
var path = require('path');

const prod = !!process.argv.find(x => x == '-live')
const hot = !!process.argv.find(x => x == '--hot');

const config = {
    entry: [
        "react-hot-loader/patch",
        "./index.tsx",
    ],
    output: {
        path: path.join(__dirname, '../MVC/BlainWeb/Content/js'),
        filename: "front-end.js",
    },

    
    // Enable sourcemaps for debugging webpack's output.
    devtool: "source-map",

    resolve: {
        // Add '.ts' and '.tsx' as resolvable extensions.
        extensions: [".webpack.js", ".web.js", ".ts", ".tsx", ".js", "test"]
    },

    plugins: !hot 
        ? [
            new webpack.optimize.UglifyJsPlugin({ mangle: false, sourcemap: false }),
        ] 
        : [
            new webpack.NamedModulesPlugin(),
            new webpack.HotModuleReplacementPlugin()
        ],

    externals: {
        react: "React",
        "react-dom": "ReactDOM",
        radium : "Radium",
        lodash : "_",
        moment : "moment",
        jquery : "jQuery"
    },
    module: {
        loaders: [
            // All files with a '.ts' or '.tsx' extension will be handled by 'ts-loader'.
            { test: /\.css?$/, loader: "style-loader!css-loader" },
            {
                test: /\.tsx?$/,
                loaders: [
                    "react-hot-loader/webpack",
                    {
						loader: "awesome-typescript-loader",
						options: {
						  ignoreDiagnostics: [2322]
						}
					}
                ],
                exclude: path.resolve(__dirname, 'node_modules'),
                include: path.resolve(__dirname, "src"),
            },
            // All output '.js' files will have any sourcemaps re-processed by 'source-map-loader'.
            {
                enforce: "pre",
                test: /\.js$/,
                loader: "source-map-loader"
            },
        ]
    },
	

    devServer: {
        hot: hot,
        inline: hot,
    }

};

module.exports = config;`

### Package Json
`{
  "name": "blain-web-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack",
    "start": "webpack-dev-server",
    "static": "static -at 0.0.0.0 dist",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git"
  },
  "author": "",
  "license": "",
  "homepage": "https://blnnetv3.blainsupply.com",
  "dependencies": {
    "@types/google-maps": "^3.2.0",
    "@types/googlemaps": "^3.30.5",
    "@types/webpack-env": "^1.13.1",
    "color": "^1.0.3",
    "css-loader": "^0.28.7",
    "daterangepicker": "^2.1.25",
    "detect-browser": "^1.7.1",
    "es6-promise": "^4.1.0",
    "es6-shim": "^0.35.3",
    "fixed-data-table": "^0.6.4",
    "geolib": "^2.0.22",
    "immutability-helper": "^2.6.6",
    "install": "^0.10.4",
    "javascript-natural-sort": "^0.7.1",
    "jquery": "^1.12.4",
    "lodash": "^4.17.4",
    "moment": "^2.17.1",
    "npm": "^5.6.0",
    "promise": "^7.1.1",
    "radium": "^0.22.0",
    "ramda": "^0.25.0",
    "react": "^15.6.2",
    "react-bootstrap": "^0.31.2",
    "react-data-grid": "^2.0.2",
    "react-dom": "^15.6.1",
    "react-drag-sortable": "^1.0.5",
    "react-google-maps": "^7.3.0",
    "react-input-mask": "^1.2.2",
    "react-month-picker": "^1.3.0",
    "react-onclickoutside": "^6.1.1",
    "react-redux": "^5.0.5",
    "react-select": "^1.1.0",
    "redux": "^3.6.0",
    "reselect": "^3.0.1",
    "style-loader": "^0.19.0",
    "uuid": "^3.1.0",
    "webpack-env": "^0.8.0"
  },
  "devDependencies": {
    "@types/node": "^8.0.9",
    "@types/ramda": "github:types/npm-ramda#dist",
    "@types/react-hot-loader": "^3.0.3",
    "@types/react-select": "^1.2.7",
    "awesome-typescript-loader": "^3.1.3",
    "casual": "^1.5.14",
    "on-build-webpack": "^0.1.0",
    "react-container-query": "^0.8.1",
    "react-hot-loader": "^3.0.0-beta.7",
    "source-map-loader": "^0.2.1",
    "ts-node": "^3.3.0",
    "typescript": "^2.5.2",
    "webpack": "^3.8.1",
    "webpack-dev-server": "^2.11.2",
    "webpack-hot-middleware": "^2.18.2"
  }
}`

### Index.tsx
`import * as React from "react";
import * as ReactDOM from "react-dom";
import { Provider } from 'react-redux';
import { AppContainer } from "react-hot-loader";
import IEBlocker from './pages/utilities/block';
import * as browser from 'detect-browser';

import Store from './store/store';

import activeRoute from './pages/utilities/route-provider';

import { LocalStore } from './shared/storage';

import * as Radium from 'radium';

```
const render = Component => {
    ReactDOM.render(
        <Radium.StyleRoot>
            <Provider store={Store} >
                <Component />
            </Provider>
        </Radium.StyleRoot>, 
        document.getElementById('blain-app')
    );
}
```

// handle the auto reload flag
if (module && (module as any).hot) (module as any).hot.addStatusHandler(status => {
    // if hot swap is off throw an exeption
    if (!LocalStore.retrieve('hotSwapStatus')) {
        window["hotSwapFailed"] = true;
        throw new Error('Preventing hot swap.');
    }
})

const block = (browser || {}).name == 'ie' && ((parseInt(browser.version) < 11 && activeRoute.ie11Plus) || activeRoute.edgeOnly);

render(block ? () => <IEBlocker canBypass={!!activeRoute.canByPassBlock} byPassing={() => render(activeRoute.pageComponent)} edgeOnly={activeRoute.edgeOnly} /> : activeRoute.pageComponent);
`

**Comment by theKashey** [comment]
You are using react-hot-loader `3.0.0-beta.7`. Version 3 was never "released", and died in the same "beta" status a year ago.
Consider moving to version 4.
