### ISSUE TITLE
Followed the docs, but not sure if it is working!

### ISSUE THREAD

**Issue by ReactGirl** [gaearon/react-hot-loader#1141]
I had followed the docs, but I'm not sure if the hot reload is working or not!

I had deployed a create-react-app, ejected it, applied the typescript configuration and tried to apply the react-hot-loader.

My webpack.config ended up as:
https://github.com/ReactGirl/nexter/blob/master/config/webpack.config.dev.js

My wrapped hot component:
https://github.com/ReactGirl/nexter/blob/master/src/components/App.tsx

The rest of the story:

It seems that hot reloading is working (at some degree), but I'm not seeing any feedback on the Developer Javascript console, what sounds a little bit suspicious (and definitely not what I want).

In the Terminal (where the yarn start was executed) I see a "compiling" message after a code change.

I've read the docs and tried to follow all the instructions, but something seems fishy due to the following:

1. A "compiling..." message in the console after a code change.
2. No feedback in the Developer Web Console.
3. A period of time to reload a little bit higher than I was expecting.

But on the other hand, it seems that the browser is not performing a full reload after a change in the code.

So I'm a bit confused.

I'm using: 
```
 React 16.6.3
 Webpack 4.19.1
 Typescript
 React-hot-loader 4.6.3
```

As mentioned, the code repository can be found in my GitHub:
https://github.com/ReactGirl/nexter

**Comment by ReactGirl** [comment]
Any ideas?

**Comment by theKashey** [comment]
Sorry. Didn't find time to investigate yet.

**Comment by ReactGirl** [comment]
Just looking on the code below, do you see something wrong?

`import React, { Component } from "react"
import { hot } from "react-hot-loader"
import { selectArticle } from "../actions"
import Homepage from "./Homepage/Homepage"
import { BrowserRouter, Route, Link } from "react-router-dom"
const PATH = process.env.NODE_ENV === "production" ? "/nexter/" : "/"

interface IState {}
interface IProps {}

class App extends Component<IProps, IState> {
  render() {
    return (
      <BrowserRouter>
        <div className="wrapper">
          <Route path={`${PATH}`} exact component={Homepage} />
        </div>
      </BrowserRouter>
    )
  }
}
export default hot(module)(App)`

The full code is here, and it is very basic, as it is just a environment setup:
https://github.com/ReactGirl/nexter

**Comment by theKashey** [comment]
Everything is working great. Just 4 seconds is needed to generate an update, and to emit 3mb(of what?) file at the same time.

4 seconds is too much, but I am not sure what is the driver of this slowness.

The problem is with your webpack configuration - it's too complex, and probably is doing something wrong.

I've replaced it with an empty webpack config, and update time went to 145ms. Plus bundle lost 1mb somewhere.

Here it is: https://gist.github.com/theKashey/0477957a6f284985e3d6a4d6c1b7d320

Please don't go hard ways (ejecting CRA) if you don't need it.

**Comment by ReactGirl** [comment]
Ok. So the correct answer is: 

Do not use [Create-React-App](https://github.com/facebook/create-react-app) for the same creator of react-hot-loader if you want to use typescript because the webpack configuration after ejected is too complex.

Lets close the issue and pretend nothing happened.
