### ISSUE TITLE
Manual reload of the page when using RHL breaks SourceMaps

### ISSUE THREAD

**Issue by joacim-boive** [gaearon/react-hot-loader#1143]
### Description
Create React App v2.1.2
React Hot Loader v4.6.3

Implemented RHL according to the instructions [here ](https://github.com/gaearon/react-hot-loader) in a default install of Create React App.

Sample repo here: https://github.com/joacim-boive/cra

1. Initial Load - Hot Reloading and SourceMaps works as expected
2. Make a code change.
3. Hot reloading is triggered - SourceMaps is not updated with the new code.
4. Manually reload page - SourceMaps stops working and source-tab i Chrome Dev tools looks weird - you now only see the file(s) that you updated.

Before reload:
![image](https://user-images.githubusercontent.com/270235/50685700-8e0e3280-101a-11e9-9b4c-6d1c6f7fde2d.png)

After code change, hot reload and manual reload:
![image](https://user-images.githubusercontent.com/270235/50685744-b39b3c00-101a-11e9-9d97-9824080c5432.png)

### Expected behavior

I exepect SourceMaps to be updated and continue to work after a manual reload.

### Actual behavior

SourceMaps is broken.

**Comment by joacim-boive** [comment]
Ok, so I did some further investigation and the SourceMaps for Create React App is actually working - sort of.

What threw me of was that the catalog tree was closed on reload and that the appearance of the "new" file: C:/Users/jobo15/IdeaProject/cra/src appeared. The existing file doesn't see the code update, only this new file contains the code update but it ends up incorrectly in the source tree.

Ok, so after mocking about in my real repo I now have sourcemaps working and updating as expected.
Until I reload... >:-( Then I only see the changed file(s) that came with the hot reload. If I look at the .map-file it only contains code for the last code change and not the entire codebase of the bundle.

If I could get the entire code base included in the source maps it would now work as expected. But currently the only way to get it to work again is to restart webpack so it generates a new sourcemap. That works until I make a code change and round and round we go.


I realize that this description is a bit(?) confusing by now but any input would be appreciated. :)

**Comment by theKashey** [comment]
Unfortunately there is nothing we could do here - this is all about Hot Module Replacement, and that's a __webpack__ feature.
And it's quite confusing, but you will have as many "my-file.jsx", as many changes you made - old and obsolete files are __not removed__.

What's how webpack(script tags in browser) works.

**Comment by joacim-boive** [comment]
I got it working by following these steps:
Add, to your webpack config:
`new webpack.SourceMapDevToolPlugin({
                    filename: 'js/bundle.app.[hash].js.map',
                    append: '//# sourceMappingURL=[url]',
                    moduleFilenameTemplate: path.relative(app.buildCatalog, '[resourcePath]'), // Point sourcemap entries to the original file locations on disk
                }),`

[hash] is the key here, otherwise the browser caches the sourcemap.

Setup a Workspace in Chrome Dev Tools and map the source files:
https://developers.google.com/web/tools/chrome-devtools/workspaces/

Now sourcemaps are dynamically updated and works even after a full reload - at least for me. ;)
