### ISSUE TITLE
ReactDOM errors.

### ISSUE THREAD

**Issue by fwh1990** [gaearon/react-hot-loader#1145]
### Description

```error
 ReferenceError: react_dom__WEBPACK_IMPORTED_MODULE_9___default is not defined
```

### Actual behavior

It's ok when I refresh page. Some errors are reported when I change code.

```js
import ReactDOM from 'react-dom';
```

### Environment

React Hot Loader version:

**4.6.3**

Run these commands in the project folder and fill in their results:

1.  `node -v`: v8.11.4
2.  `npm -v`: 5.6.0
3. `yarn -v`: 1.12.3

Then, specify:

1.  Operating system: macos 10.14.1
2.  Browser and version: chrome 71

**Comment by theKashey** [comment]
What is `react-dom` version then?

**Comment by fwh1990** [comment]
> What is `react-dom` version then?

16.7.0

**Comment by fwh1990** [comment]
I solved this problem by adding package **@hot-loader/react-dom@16.7.0**. Is that a right way?

**Comment by theKashey** [comment]
Probably I could not help you. In all my cases it's working well, as designed. There is something specific to your case, but that "something" is invisible to me.

**Comment by theKashey** [comment]
Next time....
