### ISSUE TITLE
[Question] Wrapping Provider's in HMR good or bad?

### ISSUE THREAD

**Issue by rockchalkwushock** [gaearon/react-hot-loader#1146]
Reading the docs [here](https://github.com/gaearon/react-hot-loader#hotcomponent-options) I'm getting the idea that wrapping any `Provider` is a _bad idea_ and instead should only wrap `App` in `hot()`. Am I correct in that assumption? Why would wrapping a `Provider` be a bad idea?

```javascript
// possibly bad?
const Root = () => (
  <ApolloProvider client={client}>
    <IntlProvider
      locale={userLocale}
      messages={flattenMessages(messages[userLocale])}
    >
      <ThemeProvider theme={theme}>
        <App />
      </ThemeProvider>
    </IntlProvider>
  </ApolloProvider>
)

export default hot(Root)
```

```javascript
// good
const App = () => <Title>Hello World</Title>

export default hot(App)
```

**Comment by theKashey** [comment]
It's not bad idea.

The bad idea: using `hot` in the same file you are creating (or importing) `client`(or `store`), as long as it would lead to their _recreation_.

So it's easier to go with v2. Safer :)
