### ISSUE TITLE
How to get help?

### ISSUE THREAD

**Issue by ReactGirl** [gaearon/react-hot-loader#1149]
Wrote an [issue](https://github.com/gaearon/react-hot-loader/issues/1141) and provide the[ code](https://github.com/ReactGirl/nexter) 18 days ago. 

Is this the right place or should I try other platforms as Quora, Reddit or Stackoverflow?

**Comment by rockchalkwushock** [comment]
@ReactGirl 

I will take a look at your issue and answer back this evening if this is still persisting.

**Comment by ReactGirl** [comment]
@rockchalkwushock It still persisting. Thanks.

**Comment by theKashey** [comment]
@ReactGirl - sorry, I am the last standing maintainer, and I am on annual vacations.

**Comment by theKashey** [comment]
Question answered.
