### ISSUE TITLE
Use function component instead of class in prod build?

### ISSUE THREAD

**Issue by lencioni** [gaearon/react-hot-loader#1154]
I noticed that the prod build is currently 1.43 KiB. https://unpkg.com/react-hot-loader@4.6.3/dist/

It looks like most of the weight comes in because the AppContainer component is a class

https://github.com/gaearon/react-hot-loader/blob/015fcf09ff35e0bfec7e8d0702ce4419f5966d0a/src/AppContainer.prod.js#L5-L9

Would it make sense to change this to be a function component instead to reduce production bundle size?

```jsx
function AppContainer(props) {
  return React.Children.only(props.children)
}
```

**Comment by theKashey** [comment]
That's a brilliant idea!
