### ISSUE TITLE
Hot reload works only at layout [Warning: You cannot change <Router history>]

### ISSUE THREAD

**Issue by shapkarin** [gaearon/react-hot-loader#1158]
I get an error when I try to change other file except layout. When I change Layout file everything is OK, nut if I try to change other page `'./Pages/Shows'` I get an error `Warning: You cannot change <Router history>`

Layout:
```js
import { Router, Switch, Route, Redirect } from 'react-router-dom';
import { hot } from 'react-hot-loader';
import Shows from './Pages/Shows';

const Layout = function ({ startPage, phone }) {
    return (
      <Provider store={store}>
        <Router history={createHistory()}>
          <div>
            <Header phone={phone}/>
            <Switch>
                <Route
                  exact
                  path="/shows"
                  component={Shows}
                />
....

const App = hot(module)(Widget);

render(
  <App { ...config } />,
  document.getElementById('root')
);

```

Also I added plugin to webpack.config
```js
{
    test: /\.js$/,
    exclude: /(node_modules|bower_components)/,
    use: [
        'react-hot-loader/webpack',
...
```

**Comment by theKashey** [comment]
You got it wrong. And probably you are updating redux store every time.
Move `<div><Header...</div>` to another file and component, and make it hot.
Only your __application__ should be updated, not the code to setup and render it.

**Comment by shapkarin** [comment]
oh... I see.. so in my way I trying to make hot also routes. I'll try that, thanks

**Comment by theKashey** [comment]
You may make routes also hot, just move them to another file.
During hot update some files should not be updated and you have to keep “root” unchanged to keep the application state.

**Comment by shapkarin** [comment]
@theKashey can't understand what's wrong, I move to other file and now I see logs that all update but at browser I don't see any changes...

**Comment by theKashey** [comment]
It depends. Sometimes some complex HOCs(Redux v6, for example) are not hot-reloadable.
If you have an example - I could try to find the problem.

**Comment by shapkarin** [comment]
I use "react-redux": "^6.0.0" 
But how to figure out ?

**Comment by shapkarin** [comment]
hmm. 5.1.1 works fine. oh... 😞

**Comment by jwm0** [comment]
If you are having this issue this is most likely due to `createBrowserHistory` being in the same file you **accept** in the HMR. Since the entire file specified will be reloaded, there will be a new history created on each HMR refresh and you will get the error. The simple solution is to create history in a separate file and import it.

**Comment by kristian2x** [comment]
@theKashey Would you mind sharing the commit or issue in react-redux?

**Comment by theKashey** [comment]
Not a year later, it's completely different codebase nowadays.

**Comment by kristian2x** [comment]
@theKashey oh dang I'm still in the year 2019 I guess..

**Comment by isumix** [comment]
Thanks to @theKashey for a hint.
I had HMR hot reload with webpack
```jsx
import { hot } from 'react-hot-loader/root';
import React from 'react';
import { Admin } from 'react-admin';
import { createBrowserHistory } from 'history';
const history = createBrowserHistory();
const App = () => (
    <Admin history={history}>
    </Admin>
);
export default hot(App);
```
This gave me `You cannot change <Router history>` every time I save.
To fix this issue I had to move this
```js
import { createBrowserHistory } from 'history';
export const history = createBrowserHistory();
```
to different file.
