### ISSUE TITLE
React-hot-loader: hot could not find the id property in the module

### ISSUE THREAD

**Issue by clicktronix** [gaearon/react-hot-loader#1160]
### Description
Hey. Received this error after updating to RHL 4.6.3
![image](https://user-images.githubusercontent.com/15245608/51560084-c41e3400-1ead-11e9-8bf5-9d4a9dbd29f5.png)
I did not find such errors in Google, I decided to create an issue
### Environment
React Hot Loader version: 4.6.3
NodeJS: 11.6.0
NPM: 6.5.0
React: 16.7.0
React-dom: 16.7.0
Typescript: 3.2.2

Place of the app render function
```
import { hot, setConfig } from 'react-hot-loader';

setConfig({
  ignoreSFC: true,
  pureRender: true,
});

function render(component) {
  ReactDOM.hydrate(
    hot(component),
    document.getElementById('root'),
  );
}
```
HMR part
```
if (module.hot && process.env.NODE_ENV !== 'production') {
  module.hot.accept(['./core/App', './core/configureApp'], () => {
    const nextConfigureApp = require('./core/configureApp').default;
    const NextApp = require('./core/App').App;
    const nextAppData = nextConfigureApp(appData);
    render(<NextApp {...nextAppData} jssDeps={appData.jssDeps} />);
  });
}
```
webpack configuration part
```
test: /\.tsx?$/,
    use: ([
        loader: 'babel-loader',
        options: {
          babelrc: false,
          cacheDirectory: true,
          plugins: [
            'react-hot-loader/babel',
            'syntax-dynamic-import',
          ],
       ])
```
What could have happened? Updated almost all packages to the latest versions.

If you need a lot more information here is the repository branch where it happened: https://github.com/fullstack-development/react-redux-starter-kit/tree/51-hmr-configure-for-i18n-jss

**Comment by theKashey** [comment]
```js
import { hot, setConfig } from 'react-hot-loader';

setConfig({
  ignoreSFC: true,
  pureRender: true,
});

function render(component) {
  ReactDOM.hydrate(
    hot(component), <--- THIS IS HMR PART, AND IT HAS ANOTHER INTERFACE
    document.getElementById('root'),
  );
}
```
- You shall use `hot(module)(component)
- I recommend to `import {hot} from 'react-hot-loader/root'`, and then you may `hot(component)
- __do not__ use it in the same file, you are doing `hydrate`. Move one file _deeper_ to maintain the application state. (that's HMR rule, not RHL - you shall "accept" change somewhere, and everything _below_ (and including _accept location_) would be updated)/

HMR part... in short - you dont need it. `hot` will do everything.

**Comment by clicktronix** [comment]
@theKashey Thank you very much! did not notice in the import part `/root`. My fault, I will be more attentive. It all worked.
