### ISSUE TITLE
hot update fails in webpack bootstrap

### ISSUE THREAD

**Issue by wmertens** [gaearon/react-hot-loader#1161]
I'm using Webpack 4.28, latest RHL, and in the past month or two, hot reload stopped working. I'm getting this error:

```
VM78:37 React-Hot-Loader: error detected while loading ./lib/universal/Root.jsx
window.console.error @ VM78:37
(anonymous) @ react-hot-loader.development.js:2381
setTimeout (async)
updateInstances @ react-hot-loader.development.js:2377
(anonymous) @ react-hot-loader.development.js:2401
hotSetStatus @ bootstrap:246
hotApply @ bootstrap:628
cb @ process-update.js:66
(anonymous) @ process-update.js:82
Promise.then (async)
check @ process-update.js:81
./node_modules/.registry.npmjs.org/webpack-hot-middleware/2.24.3/node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:42
processMessage @ client.js:268
handleMessage @ client.js:136
handleMessage @ client.js:99
17:53:18.486 VM78:37 TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (bootstrap:723)
    at fn (bootstrap:100)
    at react-hot-loader.development.js:2379
```

what's happening is that webpack tries to run the new module from `modules[moduleId]` ([here](https://github.com/webpack/webpack/blob/9fe42e7c4027d0a74addaa3352973f6bb6d20689/lib/MainTemplate.js#L213)) but that doesn't have the module yet. I'm wondering if this is triggered by RHL somehow calling require before webpack is ready?

**Comment by theKashey** [comment]
I heard that error already - #1131, #1082 and so on.
I was never able to reproduce and trace the problem. Do you have an example?

**Comment by wmertens** [comment]
I just figured out it's because I have 2 webpack bootstraps :(

It's very unlikely this is due to RHL so closing this, sorry I can't be of help for the other issues.
