### ISSUE TITLE
eval('evalAllowed = true') breaks our csp

### ISSUE THREAD

**Issue by olemartin** [gaearon/react-hot-loader#1162]
We are using a csp-framework that reports all violations of csp to a central server. This statement (from index.js) gets reported all the time in production. 
```
var evalAllowed = false;
try {
  eval('evalAllowed = true');
} catch (e) {
  // eval not allowed due to CSP
}
```

Could you please do this when requiring `react-hot-loader.development.js`?

**Comment by theKashey** [comment]
Got the point 👍
