### ISSUE TITLE
Parent module not being registered in the cache tree

### ISSUE THREAD

**Issue by reaysawa** [gaearon/react-hot-loader#1166]
### Description

Have a Root component like this

```
import React from "react"
import { Provider } from "react-redux"
import { hot } from "react-hot-loader/root"
import store from "redux/store"

import HelloReact from "components/HelloReact"

const Root = () => (
  <div id="root">
    <Provider store={store}>
      <HelloReact />
    </Provider>
  </div>
)

export default hot(Root)
```

And an entrypoint like this

```
import "core-js/shim"
import "regenerator-runtime/runtime"
import { setConfig } from 'react-hot-loader'
setConfig({
  ignoreSFC: true,
  pureRender: true,
})
import React from "react"
import { render } from "react-dom"

import Root from "containers/Root"

render(
  <Root />,
  document.getElementById("app")
)
```

### Expected behavior

Loads correctly

### Actual behavior

The entrypoint module is **not** registered as the parent in the **hot-exported Root module** object.

![image](https://user-images.githubusercontent.com/17429390/51804553-24f89400-2241-11e9-9021-87e5454fa613.png)

However, the entrypoint module registers the **hot-exported Root module** as his child.

![image](https://user-images.githubusercontent.com/17429390/51804569-73a62e00-2241-11e9-8e2b-7a39d648cc45.png)

### Environment

React Hot Loader version: 4.6.3

1.  Operating system: Ubuntu Linux
2.  Browser: Chrome

### Reproducible Demo

Please take the time to create a new project that reproduces the issue.

You can copy your project that experiences the problem and start removing things until you’re left with the minimal reproducible demo. This helps contributors, and you might get to the root of your problem during that process.

https://github.com/reaysawa/saga-react-kit

**Comment by reaysawa** [comment]
Additionally, changing from

```
import { hot } from "react-hot-loader/root"
export default hot(Root)
```

to

```
import { hot } from "react-hot-loader"
export default hot(module)(Root)
```

Makes the build succeed, but doesn't hot reload.

**Comment by theKashey** [comment]
HMR "bubbles" thought parents, finding the one, which will accept it. If something is wrong with parents - something is wrong with HMR.

**Comment by theKashey** [comment]
Something is broken in webpack, and __only__ in webpack. Try to remove `enforce`, and `runtimeChunk`.

**Comment by reaysawa** [comment]
The final step was to set 

```
import { setConfig } from 'react-hot-loader'

setConfig({
  ignoreSFC: true, // RHL will be __completely__ disabled for SFC
  pureRender: true, // RHL will not change render method
})
```

Although I'm still getting errors in the console

`React-hot-loader: Cold component Root at RHL./src/containers/Root.js has been updated`

Which is mentioned in the README

> 
> If you will update cold component React-Hot-Loader will complain (on error level), and then React will cold-replace Component with a internal state lose.
> 
>     Reach-Hot-Loader: cold element got updated

But I'll just ignore those errors for now. Will post here if I manage to fix them.

**Comment by theKashey** [comment]
@reaysawa - you may use `ignoreSFC` to _cold_ all SFC, and RHL will not complain about it, only in one case - you are using `hot-loader/react-dom` or `webpack-plugin`.
In any other case, it will nullify all RHLs work (cold elements shall not be updated)

As I could see - you are using `webpack-loader` but you are excluding it from accessing `node_modules` (exclude: /node_modules/)

__webpack-loader loaded is going to land a patch on your node_modules/react-dom__, do not restrict it!

**Comment by reaysawa** [comment]
@theKashey thanks for the help, I have some other questions related to that so I'll open another issue
