### ISSUE TITLE
v4.6.4 "TypeError: leaveModule is not a function"

### ISSUE THREAD

**Issue by thecorsair** [gaearon/react-hot-loader#1168]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

run yarn dev
receive an ERROR "TypeError: leaveModule is not a function"
if use v4.6.3 
all normal

### Expected behavior

no issue

### Actual behavior

```
/Users/hanlike/Documents/neuronFE/node_modules/webpack-cli/bin/cli.js:235
                                throw err;
                                ^

TypeError: leaveModule is not a function
    at /Users/hanlike/Documents/neuronFE/configs/webpack.config.base.js:141:3
    at Object.<anonymous> (/Users/hanlike/Documents/neuronFE/configs/webpack.config.base.js:142:3)
    at Module._compile (/Users/hanlike/Documents/neuronFE/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Module._compile (/Users/hanlike/Documents/neuronFE/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
```
### Environment

webpack 4.29
Typescript 3.2
babel 7
repo https://github.com/electron-react-boilerplate/examples/tree/master/examples/typescript

React Hot Loader version: v4.6.4

Run these commands in the project folder and fill in their results:

1.  `node -v`:v10.13.0
2.  `npm -v`:yarn 1.12.3

Then, specify:

1.  Operating system: macos mojove
2.  Browser and version:Chrome 71

### Reproducible Demo

Please take the time to create a new project that reproduces the issue.

You can copy your project that experiences the problem and start removing things until you’re left with the minimal reproducible demo. This helps contributors, and you might get to the root of your problem during that process.

Push to GitHub and paste the link here.

**Comment by concefly** [comment]
I met the same problem

https://github.com/gaearon/react-hot-loader/compare/v4.6.3...v4.6.4#diff-66ea0cdc3989360adbd4955babda95e0R46

![image](https://user-images.githubusercontent.com/6647656/52043146-df5a0500-2579-11e9-8164-095ba655920a.png)

**Comment by luangjokaj** [comment]
Same problem! 

https://github.com/luangjokaj/react-ssr-boilerplate

**Comment by demkovych** [comment]
+1

**Comment by blinkzz** [comment]
Same

**Comment by lyboy2012** [comment]
+1

**Comment by theKashey** [comment]
🔥

**Comment by theKashey** [comment]
Honestly - I have no idea why this code got executed on webpack side. But:
- 4.6.4 deprecated
- 4.6.5 released

**Comment by blinkzz** [comment]
4.6.5 - still same error
How simple version bump should have fixed this?

**Comment by theKashey** [comment]
@blinkzz - 4.6.5 should contain patch - https://github.com/gaearon/react-hot-loader/commit/6f8573fb44f7089d24e7c6f4af0246bf87477fff

**Comment by blinkzz** [comment]
Yeap, that was an issue with npm cache, even after node_modules clean install.
Thanks for clue and quickfix

**Comment by thecorsair** [comment]
v4.6.5 fixed
