### ISSUE TITLE
"react hot loader got: ... in ..."

### ISSUE THREAD

**Issue by natew** [gaearon/react-hot-loader#1169]
I'd like to debug this, but think first step is making this error message a bit more clear. I'm pretty confused what's happening and why. I'd be happy to add some messaging here once I can understand a bit.

### Description

Getting this error:

![image](https://user-images.githubusercontent.com/12100/52091526-8d10e800-2569-11e9-821c-4a64cef316e4.png)

What you are reporting:

### Expected behavior

Should report why it's happening, steps to fix potentially, and show a bit better information.

### Actual behavior

Imprecise message.

### Environment

React Hot Loader version: 4.6.5

**Comment by theKashey** [comment]
`got` XXX `instead of` YYY `and where`. Usually, it would re-render the nested tree with a state loss.

This is from hot-renderer, when something went unpredictable, and after update XXX is not (new)XXX, but YYY. Memo vs SFC in this case.

For the message is clear, but the formatting is not quite. Probably I should pick something more console friendly.

**Comment by natew** [comment]
In this case I’m not changing anything like memo to sfc just editing the
thing directly. Is it potentially a bug then?

**Comment by theKashey** [comment]
Definitely. Could you parse a code around <SomeProvider><AndSomethingInsideProbablyMemoVersionOfChangeThemeByName/></SomeProvider>.

**Comment by theKashey** [comment]
Confirmed. The issue is with React 16.7+, where `fiber.elementType` is Memo, but `fiber.type` is memo-ed component.

**Comment by theKashey** [comment]
There were 2 mistakes:
- `memo` was not properly supported in `hot-render`, that's why you saw this message
- reloading `Providers` was not supported __at all__. In all the tests they were created _above_ reloading point.
