### ISSUE TITLE
Remove "react-🔥-dom patch detected. You may use all the features." console messages

### ISSUE THREAD

**Issue by stnwk** [gaearon/react-hot-loader#1173]
Hello :)

It would be nice if we could get rid of this message in the console too:
> React-Hot-Loader: react-🔥-dom patch detected. You may use all the features.

It's possible to silence all other console logs, but not this one :/

See https://github.com/gaearon/react-hot-loader/blob/f15b108cfac2aa6b8f98496b1e3103a4ad1c9e9c/src/reactHotLoader.js#L118

What do you think?

**Comment by theKashey** [comment]
Probably it's better to display a message like this when hot patch is __not__ detected, as long as we rely on it.

**Comment by a7madgamal** [comment]
how to fix it then?

**Comment by theKashey** [comment]
The current version would display this message only if hot-patch is hot present.
> React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work

Cos, you know, 16.6+ features really __might not work__, especially hooks. React-Hot-Loader is not very _reliable_ thing and might ruin all DX with _eeeeaaaasssyyyy_ 😭

**Comment by mohsinulhaq** [comment]
https://github.com/gaearon/react-hot-loader/commit/38b63cd
This commit said it's supporting 16.8.4, why do we still say it doesn't support 16.6+?
Are there any known issues with 16.6+?

**Comment by theKashey** [comment]
@mohsinulhaq - you just linked a common in `webpack loader`, which __is__ a "react-🔥-dom patch".
There are a few things RHL cannot do from a "user-space" _properly_. For example, hooks are breaking some internal stuff, and we are injecting additional API into `react-dom` to actually make them work _without surprices_.

So - long story short - all the tests are passing __with__ and __without__ hot patch. Everything is about reducing _WTF per minute_. RHL is a hacky tool by nature - we are hacking things.

**Comment by mohsinulhaq** [comment]
Ok understood, so what do you think would be a proper solution? Does something need to change in react-dom officially?

**Comment by theKashey** [comment]
https://github.com/reactjs/rfcs/pull/74 - but it's a bit stale.
