### ISSUE TITLE
hot update failed for module even though it works (RHL + Fable)

### ISSUE THREAD

**Issue by SirUppyPancakes** [gaearon/react-hot-loader#1181]
### Description
I am trying to get RHL working with Fable (an F# to JavaScript compiler), and I am very close, but it seems there is still some issue causing an error message to appear.

Fable uses it's own webpack loader (and relies on Babel), and the original issue can be seen here: https://github.com/fable-compiler/Fable/issues/1733

The original issue was that `fable-loader` did not set `babelOptions.filename` which RHL seems to need. This can be remedied by adding the option in `fable-loader` (this has not been updated in the main line yet, but I have just been patching node_modules for now while trying to get to the bottom of this).

Now that the original issue is gone, RHL seems to be working 100% (I can change code and it hot-reloads successfully, all while maintaining react component state).
However, when a hot-update occurs, RHL still reports an error:
![Image of Yaktocat](https://user-images.githubusercontent.com/12754240/52811139-99a93c00-3051-11e9-969e-de049c273e63.png)

It seems that something is still tripping RHL up, but I can't seem to figure out what. I've looked at the code that is generated into the bundle, that is throwing the error, but I am not familiar enough with the internals of HMR to figure out what could be causing it...
This is the function that throws the error (after a timeout of 100ms)...
```
var chargeFailbackTimer = function chargeFailbackTimer(id) {
  return setTimeout(function () {
    var error = 'hot update failed for module "' + id + '". Last file processed: "' + getLastModuleOpened() + '".';
    logger.error(error);
    logException({
      toString: function toString() {
        return error;
      }
    });
    // 100 ms more "code" tolerant that 0, and would catch error in any case
  }, 100);
};
```
and it is called later...
```
var failbackTimer = chargeFailbackTimer(sourceModule.id);
  var firstHotRegistered = false;

  // TODO: Ensure that all exports from this file are react components.

  return function (WrappedComponent, props) {
    clearFailbackTimer(failbackTimer);
    // register proxy for wrapped component
    // only one hot per file would use this registration
    if (!firstHotRegistered) {
      firstHotRegistered = true;
      reactHotLoader.register(WrappedComponent, getComponentDisplayName(WrappedComponent), 'RHL' + moduleId);
    }
...
```
It looks like it is thrown after 100ms unless the other call to `clearFailbackTimer` cancels it... so maybe something is too slow?

Any ideas what could be tripping up RHL in this case? It's strange that RHL is working, but still ends up throwing this error. Any insight would be appreciated 😁 

### Environment

React Hot Loader version: 4.6.5

Run these commands in the project folder and fill in their results:
1.  `node -v`: 11.4.0
2.  `npm -v`: 6.4.1
3. `yarn -v`: 1.12.3

Then, specify:

1.  Operating system: Windows 10 x64
2.  Browser and version: Chrome (Version 72.0.3626.109 (Official Build) (64-bit))

### Reproducible Demo

Download the demo ([RHL_Fable.zip](https://github.com/gaearon/react-hot-loader/files/2866866/RHL_Fable.zip)), and then run `yarn` (or `npm install`).
Before running `yarn start`, you must edit the file at `node_modules/fable-loader/index.js`.
Look for the `transformBabelAst` function and add the line:
`babelOptions.filename = sourceMapOptions.path.replace(/\\/g, '/');`
between
`babelOptions.sourceMaps = true;`
and
`babelOptions.sourceFileName = path.relative(process.cwd(), sourceMapOptions.path.replace(/\\/g, '/'));`
Save the file and then run `yarn start`.

Open `app/index.html` in the browser and make changes to `src/Counter.fs` to see the issue in action.

**Comment by SirUppyPancakes** [comment]
Ah I just looked at the generated JS code and realized that I wasn't exporting `hot` properly. I think it's working properly now! I'll do some more testing to be sure and post back here later tonight.

**Comment by SirUppyPancakes** [comment]
Alright everything is working fine after fixing my code. Here is how you do the F# equivalent of the JavaScript code in the docs:

In your root component...
```
let private hot: obj -> obj = import "hot" "react-hot-loader/root"

let Component = hot <| fun () -> React.ofType<Main, _, _> { input = obj(); output = obj() } []
```
Here, my root component is a class-component called `Main`. The `React.ofType` generates the `React.createComponent` call. I also import `hot` here. This is a must, and you CANNOT wrap it as a utility function in some other file (which is pretty standard Fable/F# practice), since I'm guessing it implicitly grabs a reference to the enclosing `module`. The reason I use `obj` as the type is because Fable does not have a unifying type to refer to a "react component". A react component is either a function type (returning `ReactElement`) or a `ComponentClass`, so it's easier to just use obj and get on with it. Fable will generate the `export` needed for the `Component` variable, since it is a top-level binding.

In your top-level rendering file (application entry point)...
```
ReactDom.render(React.createElement(Main.Component, obj(), []), Browser.document.getElementById "app_container")
```
Here, we use the standard `render` function and use `React.createElement` on our `hot` exported root component.
It is vital as well that you do not combine these two files. RHL throws a warning/error in the console if you try to use the result of `hot` directly instead of simply exporting it like above.

I will be putting in a PR with Fable to get the loader `babelOptions.filename` added and this setup should work very nicely.

As a side note, it would be very helpful if the RHL docs (in the spot where it mentions the old-style `hot(module)(component)` function), also mentioned that you MUST have `hot` in the same file as where you call it, and not wrap it up in some other utility file, since it implicitly captures `module` during import (though this does only really come into play with transpiled languages TBH).

Cheers! 🎉

**Comment by theKashey** [comment]
🙀that’s was a quite unexpected integration. Happy it worked!
PS: use ‘hot’ from ‘React-hot-loader/root’ - it just a one function call.
