### ISSUE TITLE
React Context breaks app

### ISSUE THREAD

**Issue by PutziSan** [gaearon/react-hot-loader#1184]
### Description

If you assign a provider to a variable, the app breaks with `Invalid value used as weak map key`:

```javascript
import React from "react";

const Ctx = React.createContext();
const Prov = Ctx.Provider;
```

see codesandbox: https://codesandbox.io/s/5yr558ky0x

removing the line `const Prov = Ctx.Provider;` in `src/App.js` or `""react-hot-loader/babel"` in `.babelrc` resolves the issue.

### Environment

React Hot Loader version: 4.7.0

### Reproducible Demo

https://codesandbox.io/s/5yr558ky0x

**Comment by dkadrios** [comment]
Ran into the same issue.  Removing `react-hot-loader/babel` from .babelrc does indeed seem to resolve things, but I wonder what is the consequence of doing so?

**Comment by theKashey** [comment]
My bad. Trying to "register" "Provider.Provider"

**Comment by kog-7** [comment]
I also encountered the same problem, if i remove react-hot-loader/babel,i can't use this hot again,how to solve? 
Error as follows
`updateFunctionProxyById
./node_modules/react-hot-loader/dist/react-hot-loader.development.js:1034
  1031 | 
  1032 | var updateFunctionProxyById = function updateFunctionProxyById(id, type, updater) {
  1033 |   // Remember the ID.
> 1034 |   idsByType.set(type, id);
  1035 |   var proxy = proxiesByID[id];
  1036 |   if (!proxy) {
  1037 |     idsByType.set(type, id);`

**Comment by theKashey** [comment]
I'll push update today. It's a one-line change.

**Comment by kog-7** [comment]
thanks，looking forward to

**Comment by diondirza** [comment]
@theKashey I still got this error on my end with v4.7.1
> react.development.js:188 Warning: Rendering <Context.Consumer.Provider> is not supported and will be removed in a future major release. Did you mean to render <Context.Provider> instead?

because I had context which destruct a consumer like this
`const LocaleConsumer = LocaleContext.Consumer;`.

**Demo** 
https://codesandbox.io/s/6xpmnnl81n

**Comment by theKashey** [comment]
The patch is already here - #1190, just finishing something prior...
