### ISSUE TITLE
Using the react-fire-dom actually makes it not HMR properly, without it it does

### ISSUE THREAD

**Issue by natew** [gaearon/react-hot-loader#1185]
### Description

Just using `react-hot-loader/webpack` in webpack, it still shows the console warning. So then I added the alias to the patched one. But with that, my HMR suddenly degrades and basically re-loads entire app.

When I have only the `react-hot-loader/webpack` it works flawlessly. But it shows the console log.

### Expected behavior

Just curious what's going on and if you'd know why that would be the case. Also why is it logging that it can't find the patch when I'm using the webpack loader?

React 16.8.2 and hot-loader 4.7 or 4.65

**Comment by theKashey** [comment]
You may exclude node_modules from a loaded, that's a common setup. So webpack loader would not be able to land a patch.

Anyway - could you tick `preserve log` in the console, and help me understand why using `hot-loader/read-dom` led to a full refresh. It sounds like a runtime js error.

**Comment by natew** [comment]
Ok, I'm able to get it working now. Not sure what changed as I redid a few things in the process, but if anyone sees this ticket I can post my new config if need be.

**Comment by theKashey** [comment]
👍

**Comment by spand** [comment]
@natew Would love to see the new config :-)
