### ISSUE TITLE
React-Hot-Loader is not supported in this environment.

### ISSUE THREAD

**Issue by wulucxy** [gaearon/react-hot-loader#1188]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

when run `npm start`，cli will console out：

```
React-Hot-Loader is not supported in this environment.
```

### Expected behavior

when run `npm script`，why did this happen?

### Actual behavior

not waring msg

### Environment

React Hot Loader version: 4.7.1

Run these commands in the project folder and fill in their results:

1.  `node -v`: 8.10.0
2.  `npm -v`: 5.6.0

**Comment by borisding** [comment]
Hi!

I'm having same message after applying https://github.com/gaearon/react-hot-loader#webpack-plugin for my SSR project.

**Comment by theKashey** [comment]
```js
  var evalAllowed = false;
  try {
    eval('evalAllowed = true');
  } catch (e) {
    // eval not allowed due to CSP
  }

  // RHL needs setPrototypeOf to operate Component inheritance, and eval to patch methods
  var jsFeaturesPresent = typeof window !== 'undefined' && !!Object.setPrototypeOf;

  if (!jsFeaturesPresent || !evalAllowed) {
    // we are not in prod mode, but RHL could not be activated
    console.warn('React-Hot-Loader is not supported in this environment.');
    ....
  }
```

So, which variable - `jsFeaturesPresent` or `evalAllowed` is falsy?

**Comment by borisding** [comment]
> ```js
>   var evalAllowed = false;
>   try {
>     eval('evalAllowed = true');
>   } catch (e) {
>     // eval not allowed due to CSP
>   }
> 
>   // RHL needs setPrototypeOf to operate Component inheritance, and eval to patch methods
>   var jsFeaturesPresent = typeof window !== 'undefined' && !!Object.setPrototypeOf;
> 
>   if (!jsFeaturesPresent || !evalAllowed) {
>     // we are not in prod mode, but RHL could not be activated
>     console.warn('React-Hot-Loader is not supported in this environment.');
>     ....
>   }
> ```
> 
> So, which variable - `jsFeaturesPresent` or `evalAllowed` is falsy?

It's showing

```
jsFeaturesPresent: false
evalAllowed: true
```

**Comment by taikn** [comment]
Same here `jsFeaturesPresent: false`,` typeof window` is undefined

**Comment by theKashey** [comment]
@borisding - so there is no window in SSR, and there is no RHL on SSR side - it relies on `module` update API, which does not exist on the server side.

I would say - the right way to mitigate the problem - suppress this message on SSR.
