### ISSUE TITLE
Context lost briefly during hot reload

### ISSUE THREAD

**Issue by natew** [gaearon/react-hot-loader#119]
I've noticed this and someone else opened [this ticket](https://github.com/reapp/reapp-ui/issues/50).

In Reapp I've been using the context patch with 0.13 to enable 0.14-like parent context. So perhaps it's just a bit early. But I notice that during the hot reload I get errors where my context objects are undefined. I can find the patch for you, it's in the parent context react thread.

**Comment by gaearon** [comment]
Have you tried with React master? It should use parent context.
We need to know if it's an inherent issue in RHL, or just an issue with that specific patch.

**Comment by gaearon** [comment]
I'm pretty sure it's https://github.com/facebook/react/issues/3404 (fixed in https://github.com/facebook/react/pull/3494).
This should get into 0.13.2: https://github.com/facebook/react/issues/3629.

Please reopen if you see this problem in React master.
