### ISSUE TITLE
4.6 breaks react easy state

### ISSUE THREAD

**Issue by pungggi** [gaearon/react-hot-loader#1192]
Hello 
I am using gatsby with react easy state.
gatsby 2.0.69 introduced a new version of react-hot -loader 4.6

As of this version anything is not hot updated  **if it is wrapped with [view ](https://github.com/solkimicreb/react-easy-state#creating-reactive-views) from react easy state**..

For example:

index.js

```js
import { view } from 'react-easy-state'

export default view(() => {
  return (
     <div className={classColor}>
       <h1>About</h1>
     </div>
  )
})
```
Changing something within the view function does not trigger a reload. This was working with gatsby 2.0.68 that uses react hot loader 4.5.

**Comment by pungggi** [comment]
I setup a repo for reproduction

https://github.com/pungggi/rhl

see Branch hotload4_6 this uses the latest packages with react hot loader ^4.6.0

**Comment by theKashey** [comment]
I will take a look later, meantime try setting 
```js
import { setConfig } from 'react-hot-loader'

setConfig({
  pureRender: false, // was set to true at 4.7
  pureSFC: false, // was set to true at 4.6
})
```

**Comment by pungggi** [comment]
Yes! This works> 
```js
setConfig({
  pureRender: true,
  pureSFC: false,
})
```

**Comment by pungggi** [comment]
sorry no this does not work either, (I was still in the old branch).

**Comment by pungggi** [comment]
https://github.com/gatsbyjs/gatsby/pull/10455 somehow related?

**Comment by theKashey** [comment]
It does not work cos `ignoreSFC` is set to `true` in the gatsby and no "patch" is present.
Adding a patch (`yarn add react-dom@npm:@hot-loader/react-dom`) solves the problem.

PS: But you helped me discover one regression in RHL, which does not matter in this case.

**Comment by theKashey** [comment]
Nope, that was not a regression. It should be so
```
commons.js:37720 React-hot-loader: Cold component Root at /Users/akorzunov/dev/github/react-hot-loader/tests/rhl/.cache/root.js has been updated
__stack_frame_overlay_proxy_console__ @ commons.js:37720
commons.js:37720 React-hot-loader: Cold component default at /Users/akorzunov/dev/github/react-hot-loader/tests/rhl/.cache/root.js has been updated
```
RHL is threating `default` and `Root` from `Gatsby` internals as not-hot-reloadable(cold) componenst, and thus it leads to remount.

But the fact (ignoreSFC) - the are `cold` and error is legit.

__gatsby it not hot-reloadable without a patch__.

**Comment by buzinas** [comment]
@pungggi why was this issue closed? How can I make react-hot-loader work with react-easy-state?

**Comment by buzinas** [comment]
Btw, I'm not using `gatsby`, but `react-static`. Everything hot reloads correctly until I wrap my component with `view`, then it stops reloading.

**Comment by theKashey** [comment]
There is a long going issue about react-hot-loader and react-static - https://github.com/nozzle/react-static/issues/894

**Comment by solkimicreb** [comment]
v6.1.3 of react-easy-state fixes this issue. (I am the author of the lib) Sorry for the super slow fix, it was a tricky one.

**Comment by theKashey** [comment]
Gonna apply literally the same fix from React-Hot-Loader side. It shall be more hooks friendly.

Anyway - __v6.1.3 of react-easy-state fixes this issue__.
