### ISSUE TITLE
Cold errors are too loud. How to disable throwing / Add option to disable throwing

### ISSUE THREAD

**Issue by NawarA** [gaearon/react-hot-loader#1197]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

What you are reporting:

My top-level App.js component is hot. My app has many children components, I did not add Hot to them, since the top is hot, and hot should propagate. Whenever I update the app's children, I get cold errors that take over my console.**

The thing is, the software works as intended: on update, the app state is maintained while the DOM refreshes. Yet I'm flooded with errors in my console, even though the software is working as intended. This model makes no sense: if everything works why is it being noisy and distracting from development?

### Expected behavior

What you think should happen:

The software should work (its working today) but it doesnt throw, or throws a warning or there is a way to disable this cold warning/error. 

### Actual behavior

What actually happens:

How can I prevent this error from being thrown `"React-hot-loader: Cold component {component name} {component location} has been updated`?

Thank you!

### Environment

React Hot Loader version:
`"react-hot-loader": "^4.7.2"`

Run these commands in the project folder and fill in their results:

1.  `node -v`:
2.  `npm -v`:

Then, specify:

1.  Operating system: `Ubuntu 18.04 LTS`
2.  Browser and version: `Firefox 65`

### Reproducible Demo

**Not sure you need a demo to understand this issue. If you need a demo, I'll see what I can do.**

Please take the time to create a new project that reproduces the issue.

You can copy your project that experiences the problem and start removing things until you’re left with the minimal reproducible demo. This helps contributors, and you might get to the root of your problem during that process.

Push to GitHub and paste the link here.

**Comment by NawarA** [comment]
How I do disable this wonderful library from constantly throwing, even though its working correctly?

**Comment by theKashey** [comment]
`Cold` components would exist only in two cases:
- you `cold` them. But you said that you only `hot` your top level component.
- you `ignoreSFC`, thus `cold` all functional components, but didn't use webpack-loader(🔥-patch), and RHL should not work properly.
- you are definitely not using hot-patch, as long it, and only it disabled this warning at all.

So the question you have to answer - why components got cold. Is it a misconfiguration?

**Comment by theKashey** [comment]
A new version, 4.7.2, would suppress this message on the server side.
