### ISSUE TITLE
Cannot find module 'react-hot-loader'

### ISSUE THREAD

**Issue by joetidee** [gaearon/react-hot-loader#1199]
When running a simple Jest integration test I get a "Cannot find module 'react-hot-loader'" error.

Not sure if this is a react-hot-loader issue, but have created a StackOverflow question:
https://stackoverflow.com/questions/55013250/jest-cannot-find-module-react-hot-loader

### Environment

React Hot Loader version: 4.7.1

Run these commands in the project folder and fill in their results:

1.  `node -v`: 8.11.1
2.  `npm -v`: 6.8.0

Then, specify:

1.  Operating system: Mac

**Comment by theKashey** [comment]
That's definitely more your configuration problem, than React-Hot-Loader's. Lets continue on SO.
