### ISSUE TITLE
Spread the word

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#12]
The rough edges are fixed and the react-hot-loader is now pretty stable to use.

However most of React community have either not heard about it, think switching to Webpack is difficult or that react-hot-loader is not mature enough.

I think live-editing is the future of
front-end development and I'm full
of enthusiasm for this approach, but this projects needs more community awareness.

I wrote an [explanatory blog post](https://gaearon.github.io/react-hot-loader) but not many have seen it yet. I'm also thinking about making some other impressive videos showcasing using this with some cool community React projects.

**If you want to make "cmd+s" the new "cmd+r", help spread the word.** I can't do this alone.

**Comment by bravo-kernel** [comment]
Simply love it :+1:
