### ISSUE TITLE
Error scheduler.unstable_shouldYield is not a function

### ISSUE THREAD

**Issue by bulby97** [gaearon/react-hot-loader#1200]
### Description

I'm having this error everytime I try to change a React Component.

![image](https://user-images.githubusercontent.com/3509412/54167038-cde70f80-44cc-11e9-82aa-de2e23410bf6.png)

Then when I move my mouse it keeps displaying again and again.
Not sure this can help, but the project I'm working on is built using webpacker

### Environment
```
"react": "^16.8",
"react-dom": "npm:@hot-loader/react-dom",
"react-hot-loader": "^4.7.2",
```

**Comment by bulby97** [comment]
It was because of react-test-renderer version. Fixed right now.

**Comment by theKashey** [comment]
Have a good day :)
