### ISSUE TITLE
@types don't get found

### ISSUE THREAD

**Issue by daviddelusenet** [gaearon/react-hot-loader#1201]
### Description

The `@types/react-hot-loader` package doesn't get recognised by VSCode.

### Expected behavior

VSCode would find the `@types/react-hot-loader` package.

### Actual behavior

Code in my `App.tsx`:

```
import HelloWorld from './components/HelloWorld';
import { hot } from 'react-hot-loader/root';
import * as React from 'react';

const App = () => (
    <HelloWorld city="Amsterdam" name="David" />
);

export default hot(App);
```

Two lines from my `package.json`:

```
"@types/react-hot-loader": "^4.1.0"
```
```
"react-hot-loader": "^4.8.0"
```

However, VSCode gives me the following error:

![Screenshot 2019-03-13 at 12 53 12](https://user-images.githubusercontent.com/1398418/54277022-fcc5ba00-458e-11e9-8aeb-3ab8233145c3.png)

### Environment

React Hot Loader version: `4.8.0`

Run these commands in the project folder and fill in their results:

1.  `node -v`: v10.13.0
2.  `npm -v`: 6.8.0

Then, specify:

1.  Operating system: macOS Mojave 10.14.3
2.  Browser and version: -

**Comment by theKashey** [comment]
Types are defined inside RHL, just remove ‘@types’ and it shall work.

**Comment by daviddelusenet** [comment]
@theKashey thanks for the quick response! 

I removed my `@types/react-hot-loader` dependency, removed my `node_modules` folder and ran `npm i`.

However, the error is still there.

**Comment by theKashey** [comment]
https://unpkg.com/react-hot-loader@4.8.0/ - both `root.js` and `root.d.ts` are present in a package.

**Comment by daviddelusenet** [comment]
Yes, I think it was a `tsconfig.json` setting. When I added:

```
"moduleResolution": "node"
```

The errors went away!

**Comment by theKashey** [comment]
👍
