### ISSUE TITLE
Unhandled JS Exception: Can't find variable: exports

### ISSUE THREAD

**Issue by mateeqazam** [gaearon/react-hot-loader#1203]
### Description

I am trying to configure `haul` with react-native by following [this guidelines](https://callstack.github.io/haul/docs/getting_started.html).But, after complete configuration, I am getting an exception error, that is, `Can't find variable: exports`

<img width="323" alt="Screenshot 2019-03-15 at 5 18 30 PM" src="https://user-images.githubusercontent.com/5912756/54430965-e9f5e580-4746-11e9-81b8-c0331c9504fc.png">

### Environment
```
node: v11.11.0
npm: 6.7.0

react: "16.8.3",
react-dom: "^16.8.4",
react-hot-loader: "4.6.1",
react-native: "0.59.1"

```

**Comment by theKashey** [comment]
React-native contain it's own (~v2) version of React-Hot-Loader and you cant use the _real_ RHL there.

That's all I know.

**Comment by mateeqazam** [comment]
Actually this issue is related to haul. So closing this issue.

Anyway, thanks for your time @theKashey

**Comment by mateeqazam** [comment]
Actually, this issue is related to haul. I didn't configure haul correctly with react-native. Fixed it now and closing this issue.

Anyway thanks for your time @theKashey

**Comment by theKashey** [comment]
👍 , even if I down know what _haul_ is.

**Comment by hapablap21** [comment]
@mateeqazam, 
What was the solution?  I'm having this exact issue right now in RN with Haul in iOS.  Works on android, interestingly enough.

**Comment by rebirthtobi** [comment]
@mateeqazam do you care the share the solution to your the problem

**Comment by theKashey** [comment]
Please update RN version to replace RHL with React-Fast-Refresh.
