### ISSUE TITLE
React.lazy and react-hot-loader still can't work together

### ISSUE THREAD

**Issue by liiiku** [gaearon/react-hot-loader#1206]
### Description
I saw this issue # 1139, and I tried the solution mentioned in it, but I still haven't solved it yet.
```
yarn add react-dom@npm:@hot-loader/react-dom

resolve: {
    alias: {
      'react-dom': '@hot-loader/react-dom'
    }
}
```

### Environment

React Hot Loader version: ^4.8.0

1.  `node -v`: v9.11.2
2.  `npm -v`: 5.6.0
3.  `react -v`: 16.8.4

**Comment by theKashey** [comment]
Could you be a bit more concrete? 
All my tests - unit, manual, and just daily work experience with RHL - are _green_.

**Comment by liiiku** [comment]
> Could you be a bit more concrete?
> All my tests - unit, manual, and just daily work experience with RHL - are _green_.

It's my code's writing errors that make it ineffective. There's no problem now. Thank you very much！

**Comment by theKashey** [comment]
👍 good luck
