### ISSUE TITLE
Is the README updated for 4.5.0+ still relevant?

### ISSUE THREAD

**Issue by mohsinulhaq** [gaearon/react-hot-loader#1211]
The Readme says:
```es6
setConfig({
  ignoreSFC: true, // RHL will be __completely__ disabled for SFC
  pureRender: true, // RHL will not change render method
});
```
I wanted to know if this is the recommended config for every RHL setup.

**Comment by theKashey** [comment]
... no, it's no longer required - these values are now default.

**Comment by mohsinulhaq** [comment]
https://github.com/gaearon/react-hot-loader/blob/5e6cc4b4b1867a8e563cb92d1e51ee6423ab6bf4/src/configuration.js#L27
Here, I can see that `ignoreSFC` is set to `false`. Am I checking at the wrong place?

**Comment by theKashey** [comment]
once you will add "🔥-patch" - it will set the value. in a readme it also was mentioned
- (required) use webpack plugin to let RHL patch React-DOM for you.
- (alternative) use react-🔥-dom to use already patched React-DOM.

**Comment by mohsinulhaq** [comment]
so do you mean if i dont use the patched react-dom, i will have to set ignoreSFC and pureRender
values myself?

**Comment by theKashey** [comment]
`pureRender` is set by default, and please dont touch `ignoreSFC` - it will just kill RHL.

**Comment by mohsinulhaq** [comment]
Ok, thanks for the info. Closing the issue.
