### ISSUE TITLE
about the output path problem

### ISSUE THREAD

**Issue by qwe1164915372** [gaearon/react-hot-loader#1219]
Hello,I'm using the react-hot-loader.There are two problems confusing me.
first problem:
        I config the webpack output folder to dist.The dist folder and my index.html are in one directory. So I introduce the bundle.js file and set the script src as './dist/bundle.js'. I think the react-hot-loader will work.But only the bundle.js works.To my confusion, after,I alter the src './dist/bundle.js' to 'bundle.js',it works.
second problem:
        After I change into 'bundle.js',though the react-hot-loader is working,browser console gives me a warning as follow:

       Download the React DevTools for a better development experience: https://fb.me/react-devtools
       react-hot-loader.development.js:2433 React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work.

       I revised the instance that https://github.com/gaearon/react-hot-boilerplate gives.But it doesn't work.

![Uploading problem2.png…]()
![folder](https://user-images.githubusercontent.com/31558384/55572353-f8c62b80-5739-11e9-8039-101e8d72376e.png)

I'm looking forward to getting the answers.Thanks.
       here is the information.
       "node" : 10.9.0
       "npm" : 6.9.0
       "Operating system" : "windows10"
       "chrome" : 73.0.3683.86

**Comment by theKashey** [comment]
1. Look like you are having some issue with __webpack HMR__, please refer to webpack documentation, especially about setting proper [publicPath](https://webpack.js.org/guides/public-path/).

2. React-Hot-Loader will notice you about potential improper work, cos it's could be a real thing. RHL needs "hot-patch" to works more or less properly, injected via webpack loader or `hot-loader/react-dom`. See readme for details. There is an open issue to be able to suppress this warning for the users who don't want to use `hot-patch`, but it's not so easy to control this behavior as long as it got executed before any user code could reconfigure it.

**Comment by qwe1164915372** [comment]
Thank very much for your reply. I have corrected my publicPath. The first problem has been solved.
For the seconde question, I configed 'react-hot-loader/patch/' before. I'm so sorry. Maybe it was too late yesterday. I forgot to tell you.Please look at the picture below. But console warns me that react-🔥-dom patch is not detected. I‘m confused.
![aa](https://user-images.githubusercontent.com/31558384/55598621-3cdf1d80-5786-11e9-87e4-8368f7487fc4.png)
![ss](https://user-images.githubusercontent.com/31558384/55598623-410b3b00-5786-11e9-8312-20ded395c496.png)

I'm looking forward to getting your answer.Thanks.

**Comment by theKashey** [comment]
`hot-patch` and `patch.js` are different things.
- check that /patch.js is no longer required - https://github.com/gaearon/react-hot-loader#no-patch-required
- hot patch(react-🔥) - https://github.com/gaearon/react-hot-loader#webpack-plugin

**Comment by qwe1164915372** [comment]
Thanks very much. You are so patient. Love you.
