### ISSUE TITLE
react-hot-loader RHL failed, It refreshes all the page

### ISSUE THREAD

**Issue by xinggangling** [gaearon/react-hot-loader#1224]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description
     I had tried react@16.8.6 and react-hot-loader@4.8.3, but it answer me 'react 16.6+ maybe is not detected'; So i searched the issues for it; do like below:
       1. package: "@hot-loader/react-dom": "^16.8.6",
       2. root component:
            - import { hot } from 'react-hot-loader/root';
            - export default hot(App); 
       3. webpack:
            resolve: {
                 alias: {
                      'react-dom': '@hot-loader/react-dom'
                 }
            },

What you are reporting:

### Expected behavior
        refresh all my pages
What you think should happen:
        i dont know ..
### Actual behavior

What actually happens:

### Environment

React Hot Loader version:

Run these commands in the project folder and fill in their results:

1.  `node -v`: 9.11.0
2.  `npm -v`:  5.6.0

Then, specify:

1.  Operating system:
2.  Browser and version:
     Chrome v73.0.3683.86
### Reproducible Demo

[react-demo.zip](https://github.com/gaearon/react-hot-loader/files/3058891/react-demo.zip)

Please take the time to create a new project that reproduces the issue.

You can copy your project that experiences the problem and start removing things until you’re left with the minimal reproducible demo. This helps contributors, and you might get to the root of your problem during that process.

Push to GitHub and paste the link here.

**Comment by theKashey** [comment]
Still, don't get time to take a look, but usually, the problem is with webpack hot module replacement.
Is it enabled?

**Comment by xinggangling** [comment]
@theKashey i had enabled it.could you help me look it.it refresh all.i had uploaded my demo

**Comment by theKashey** [comment]
I've double tested your example - it works out of the box

**Comment by theKashey** [comment]
Actually, I am not so sure. Your application has problems with a first update - it remounts top level container.
There are two reasons to do it
- `App`/`AppContainer` is not equal to the one used during the first render (have no idea why)
- `RHL` thinks that it should be disabled before "first run", where "first run" is an application start.

Something very, very suspicious.

**Comment by theKashey** [comment]
In short:
- there is a bug in RHL, for the "small" applications without any React 16 stuff used (skippin first update)
- in your application you have a "double start", I am not sure why, but it got executed twice, breaking many things.

**Comment by xinggangling** [comment]
I had got it error,it is my package devServer {publicPath} error. thank you for your answer.😀

**Comment by theKashey** [comment]
So wrong public path for `assets` was breaking webpack HMR, while a bug in RHL was resetting state one the first refresh. Double strike.

Releasing a new version to fix your problem.
