### ISSUE TITLE
IE11 is throwing errors

### ISSUE THREAD

**Issue by karolisgrinkevicius-home24** [gaearon/react-hot-loader#1226]
### Description

IE11 is throwing error regarding usage of `Object.assign` without it being polyfilled.

### Expected behavior

IE11 doesn't throw any error in console.

### Actual behavior

IE11 throws any error in console.

### Environment

React Hot Loader version: 4.8.3

Run these commands in the project folder and fill in their results:

- `npm@6.9.0`
- `node@11.12.0`
- MAC OS X 10.14.4
- IE11 on Windows 8.1

This should be fairly easy to reproduce for everyone. I used VirtualBox.

**Comment by theKashey** [comment]
Fair issue. As long as there were just one valid reason to use Object.assign - easy to fix.

**Comment by karolisgrinkevicius-home24** [comment]
@theKashey thanks a lot for your quick response and commit related to this issue. Do you have a clue when this is going to be released in the registry?

**Comment by theKashey** [comment]
Only tomorrow, sorry

**Comment by karolisgrinkevicius-home24** [comment]
For me https://github.com/gaearon/react-hot-loader/commit/c5af009ae7b31f26b6b1f6b909dbaa6679e3351e didn't fix the issue in IE11. Since we're supposed to include `import { hot } from 'react-hot-loader/root';` there still `Object.assign` is present. https://github.com/gaearon/react-hot-loader/blob/v4.8.4/root.js#L17

@theKashey Could you please take another look into this? Thanks.

**Comment by theKashey** [comment]
Oh, that file dropped from my sight. I was analyzing only `/src` paired example using the old hot API.

**Comment by theKashey** [comment]
Now it's shall be done :)

**Comment by karolisgrinkevicius-home24** [comment]
After upgrading `react-hot-loader` to the latest version (`4.8.5`) I'm getting a syntax error:
![Screenshot 2019-05-16 at 09 48 06](https://user-images.githubusercontent.com/46492012/57832205-c0e1e780-77bf-11e9-93cb-772caf2e58ca.png)
I tried importing without root as an error states as follows:
```jsx
import { hot } from 'react-hot-loader';
```
But in this case I get yet another error complaining about `hot` has not been found in the module itself.

**Comment by theKashey** [comment]
At it was working before?
Could you please debug this code, changes were around
- the first check - it was `module.parents[0]`, which is the same (ie parent existed).
- the `module.hot` check. Without it(`module.hot.accept`) nothing would work, it should exists

**Comment by theKashey** [comment]
@karolisgrinkevicius-home24 - I really need an answer! Did I shipped broken version, or it's not so bad?!

**Comment by karolisgrinkevicius-home24** [comment]
@theKashey actually the error is different than it was before using IE11. On Chrome it's working well just like before. 
> Could you please debug this code, changes were around

I honestly didn't get what you want me to debug. Could you please clarify?

**Comment by theKashey** [comment]
So it’s working for Chrome, but generate this change errors only for IE11?
Is it the same build?

**Comment by karolisgrinkevicius-home24** [comment]
Yes. The error is thrown only on IE11. I was using a new build which is https://www.npmjs.com/package/react-hot-loader/v/4.8.5. The error on IE1 is caught in `react-hot-loader/root.js:6`, seems to be an issue that module doesn't have parents for some reasons on IE11.

**Comment by tzimmermann** [comment]
After some digging, I found that the new IE11 `SyntaxError` is caused by a trailing commas in the Error constructor argument list.

This fails in IE11

```js
throw new Error(
      'React-Hot-Loader: `react-hot-loader/root` is not supported on your system. ' +
        'Please use `import {hot} from "react-hot-loader"` instead',
    );
```

but this works:

```js
throw new Error(
      'React-Hot-Loader: `react-hot-loader/root` is not supported on your system. ' +
        'Please use `import {hot} from "react-hot-loader"` instead'
    );
```

When I fix it locally, though, I get another error that `Promise is undefined` which originates here https://github.com/gaearon/react-hot-loader/blob/master/src/global/generation.js#L47

**Comment by tzimmermann** [comment]
> Yes. The error is thrown only on IE11. I was using a new build which is https://www.npmjs.com/package/react-hot-loader/v/4.8.5. The error on IE11 is caught in `react-hot-loader/root.js:6`, seems to be an issue that module doesn't have parents for some reasons on IE11.

@karolisgrinkevicius-home24 Note that the `SyntaxError` (at least the one I am getting) has nothing to do with runtime problems like a missing `module.parents`.
IE chokes on some syntax that it cannot parse, even before evaluating the JS code block.

**Comment by theKashey** [comment]
Trailing commas are mine bad, sorry.
But you have to add polyfills by your own.

**Comment by karolisgrinkevicius-home24** [comment]
Polyfills are not a problem at all. @tzimmermann thanks for digging into the issue. @theKashey could you please fix that SyntaxError so that IE11 engine is able to parse it properly?

**Comment by theKashey** [comment]
v4.8.6 would fix it

**Comment by maulikdesai21** [comment]
Is this fixed? I am still getting Object.assign in 4.12.11 and 4.8.6 gives me Promise in undefined :(

**Comment by theKashey** [comment]
So it's broken again then. Some polyfills, like Promises or Object.assign, are _commonly_ expected to be present :(

**Comment by theo-mesnil** [comment]
I have the same issue :(

**Comment by theKashey** [comment]
Just tested - the only polyfill RHL is requiring - Promise (`import 'core-js/modules/es6.promise';`), which going to be used in any case.

**Comment by suhanw** [comment]
I'm on 4.13.0, and it appears Promise is still undefined, it's throwing the error here:
https://github.com/gaearon/react-hot-loader/blob/69b9d483ab3b5af3db8466bbdb124591d6670b81/src/global/generation.js#L59

**Comment by StefanoVuerich** [comment]
Having the same issue @suhanw was showing.

Any news on this? Cannot run o IE11.

**Comment by moonjoungyoung** [comment]
Any news on this?
