### ISSUE TITLE
Does not bind methods

### ISSUE THREAD

**Issue by christianalfoni** [gaearon/react-hot-loader#123]
Hi there,

When I add a method to a component and use it in "render" the method is not bound to the component. I have to refresh browser to make that work.

When looking at `bindAutoBindMethods` the `component.__reactAutoBindMap` is always undefined.

**Comment by gaearon** [comment]
It's a regression. That's why we're [going TDD in the upcoming rewrite](https://github.com/gaearon/react-hotify/tree/master/tests)..

I'll take a look what's up, thanks for reporting.

**Comment by gaearon** [comment]
The fix should be out as `react-hot-loader@1.2.6`.

**Comment by christianalfoni** [comment]
:+1:

**Comment by mmahalwy** [comment]
I still have this problem....

**Comment by gaearon** [comment]
@mmahalwy 

Can I ask you to check whether `react-hot-loader@2.0.0-alpha` solves this issue?
Please provide any feedback on it in this PR: https://github.com/gaearon/react-hot-loader/pull/182

**Comment by stevenhauser** [comment]
For what it's worth @gaearon I had this issue and alpha-3 fixed it for me. Thanks for all the work you're doing on all of these projects!
