### ISSUE TITLE
hot reload after fails linking local npm package

### ISSUE THREAD

**Issue by ChuckJonas** [gaearon/react-hot-loader#1237]
### Description

I have react hot-loader setup and work well in a webpack react project.  The project also has a dependency on a npm module that I manage.  

I often need to make change to this package and test them out in my react project.  I used to be able to do this by running:

First, running `npm link` in my npm module, then running `npm link my-npm-package` in the react project.

However, this has recently started failing with an error message:

```
ERROR in ../my-npm-package/build/index.js
Module not found: Error: Can't resolve 'react-hot-loader' in '/Users/jonas/Documents/code/my-npm-package/build'
```

When I open `/my-npm-package/build/index.js` there is no reference to `react-hot-loader` (this package has nothing to do with react).

### Expected behavior

It should allow me to link local package

### Actual behavior

It throws an error on compile: `Can't resolve 'react-hot-loader' `

### Environment

React Hot Loader version:

`"react-hot-loader": "4.8.4",`

Run these commands in the project folder and fill in their results:

1.  `node -v`: v9.3.0
2.  `npm -v`: 6.1.0

Then, specify:

1.  Operating system: osx 10.12.6 
2.  Browser and version: chrome 73.0.3683.103

### Reproducible Demo

I don't have time to create a minimal reproducible example today.  Will try to see if I can reproduce with a blank project and npm module later tonight...

**Comment by ChuckJonas** [comment]
FYI, I've tried including react-hot-loader both via `import` and `webpack` entry point.   Same result

**Comment by ChuckJonas** [comment]
ahh... I see this is documented... Sorry!

https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md

**Comment by ChuckJonas** [comment]
FYI,

My webpack loader was only: `exclude: /node_modules/`, which is why once I linked it (and the path changed to `/Users/jonas/Documents/code/my-npm-package/` it was picked up.  Setting `include` instead fixed it

**Comment by theKashey** [comment]
There are two ways to resolve this issue:
- `exclude` files out of the current folder, or only `include` the ones you need.
- override module resolution using webpack __alias__
```js
{
 resolve: {
   alias: {
     'react-hot-loader': path.resolve(path.resolve(path.join(__dirname, './node_modules/react-hot-loader'),
}
```
Now - any `react-hot-loader`, anywhere, would refer to a single point at your file system.

Wherever path you will chose - you __have to apply the second way for `react` and `react-dom`__, or they would refer to another, unpatched, version of react and react-dom.
