### ISSUE TITLE
HMR fails when NodeExternals() is used

### ISSUE THREAD

**Issue by PerfectionCSGO** [gaearon/react-hot-loader#1239]
### Description

What you are reporting: 
HMR fails silently when using webpack-node-externals in electron rendered process.

### Expected behavior

What you think should happen:
```
[WDS] 100% - Compilation completed.
client:265 [WDS] App hot update...
log.js:24 [HMR] Crash
```

Or if it is actually working.

```
[WDS] App hot update...
log.js:24 [HMR] Checking for updates on the server...
log.js:24 [HMR] Updated modules:
log.js:24 [HMR]  - ./src/app/layout/pages/home/home.tsx
log.js:24 [HMR]  - ./src/app/layout/routes/routes.tsx
log.js:24 [HMR]  - ./src/app/layout/app/app-wrapper.tsx
log.js:24 [HMR]  - ./src/app/layout/app/app.tsx
log.js:24 [HMR] App is up to date.
```

### Actual behavior

What actually happens:
```
[WDS] 100% - Compilation completed.
client:265 [WDS] App hot update...
```

### Environment

React Hot Loader version:

Run these commands in the project folder and fill in their results:

1.  `node -v`:10.15.3
2.  `yarn-v`:1.15.2

Then, specify:

1.  Operating system: Windows 10
2.  Browser and version: Electron 5.0.0

**Comment by theKashey** [comment]
That's actually more about `webpack` or something else __before__ React-Hot-Loader will try to do it's job.

**Comment by PerfectionCSGO** [comment]
My setup looks something like this:

deps
```
    "electron": "^5.0.0",
    "webpack": "^4.30.0",
    "webpack-cli": "^3.3.1",
    "webpack-dev-server": "^3.3.1",
    "webpack-merge": "^4.2.1",
    "webpack-node-externals": "^1.7.2"
```

scripts
```
    "build:renderer:hot": "webpack-dev-server --progress --hot --config webpack.config.renderer.development",
    "build:main:hot": "webpack --progress --hot --config webpack.config.main.development",
    "build:asar": "asar pack ./dist/www ./dist/pack/app.asar",
    "serve": "electron .",
    "start": "yarn build:main:hot && npm-run-all --parallel build:renderer:hot serve",
```

index.ts
```
window.loadURL(`http://localhost:8080`);
```

Notably, in electron 5.0.0 you have to specifically enable node integration in your window like so,
```
    webPreferences: {
      nodeIntegration: true
    }
```

I'm not so sure where I should be reporting this issue or where it exactly is, suggestions would be helpful.

**Comment by theKashey** [comment]
Sorry, I am absolutely lame in `Electron`, but probably you should start there, even if the failure is on webpack part.
