### ISSUE TITLE
Use `semi`

### ISSUE THREAD

**Issue by theKashey** [gaearon/react-hot-loader#1241]
Long story short - by `react-hot-loader` is the only project I am more or less responsible for which uses `no semicolons` rule.

I am pretty sure that about a year ago the TC39 make it clear - automatic semicolon insertion is an evil, and encourages us to use them - https://github.com/tc39/ecma262/pull/1062

@neoziro - look like you are not using `semi` in `smooth-code` projects, so I need your opinion in this.

`semi:false` here is some sort of legacy. __Should RHL start `semi:true`__?

**Comment by neoziro** [comment]
It is OK for me!

**Comment by theKashey** [comment]
:sweet:, I’ll reconfigure prettier then.
