### ISSUE TITLE
Autobind decorator

### ISSUE THREAD

**Issue by slonoed** [gaearon/react-hot-loader#125]
I want to use autobind decorator for components.

This https://github.com/andreypopp/autobind-decorator/blob/master/src/index.js work fine with React (method binding).
But have issue with RHL. Decorator bind method to instance. When new RHL add new prototype to prototype chain nothing happened, because method already in instance and new method in proto not visible when getter called.

I use ugly hack and check in getter `if (this.props)` to determine is *this* – instance.

It is not an issue with RHL or decorator itself. I try to find nice solution.

**Comment by chrisvariety** [comment]
The exact message I get when trying this is `Cannot set property fooBarMethod of #<Component> which has only a getter`

**Comment by gaearon** [comment]
You can try finding a fix by adding a failing test to [react-hotify](https://github.com/gaearon/react-hotify/tree/master/tests). Then, if you find a solution, I can backport it to RHL.

**Comment by slonoed** [comment]
@gaearon should I add test for work with autobind-decorator?

**Comment by gaearon** [comment]
@slonoed Yes, if you also find a fix.

**Comment by gaearon** [comment]
@slonoed It's also worth checking [if this change](https://github.com/andreypopp/autobind-decorator/issues/2#issuecomment-99631250) helps (or makes it worse, I dunno)

**Comment by vasa-chi** [comment]
Dunno if much help, but here is a test for react-hotify for this problem (using core-decorators):

```js
import React, { Component } from 'react';
import createShallowRenderer from './helpers/createShallowRenderer';
import expect from 'expect.js';
import makeHotify from '../src/makeHotify';

import { autobind } from 'core-decorators';

class Bar {

  @autobind
  getProps() {
    return typeof this.props;
  }

  render() {
    return <div>{this.getProps()}</div>;
  }
}

describe('autobind usage', function() {

  let renderer;
  let hotify;

  beforeEach(() => {
    renderer = createShallowRenderer();
    hotify = makeHotify();
  });

  it('should bind methods of hotified components', function() {
    const HotBar = hotify(Bar);
    const barInstance = renderer.render(<HotBar />);
    expect(renderer.getRenderOutput().props.children).to.equal('object');
  });
})
```

**Comment by gaearon** [comment]
Thanks! I'll definitely get back to this after my React Europe talk.

**Comment by cpsubrian** [comment]
Happy to help test possible fixes. Also wondering if this is a general problem interoperating with decorators in general, and it that should be the focus rather than `@autobind` in particular?

**Comment by slonoed** [comment]
For me this issue not actual now. I switch to arrow functions in class definition.

```
class Cmp extends Component {
  myBindedFunc = () => {
     this.callSmth();
  }
}
```

**Comment by cpsubrian** [comment]
I've done the same, but consider it a temporary fix. I prefer the decorator approach (because I bind at the class level, not the method level). I will chime back in here if my other decorators have issues (I haven't gotten that far yet, this is my first hot-reload project).

**Comment by lelandrichardson** [comment]
@slonoed this arrow function approach works? Will it always? I would have thought that in that scenario the arrow function would have made `this` bound to the `this` in the context outside of your class definition. Is this just a convenient bug or is this actually the spec'd behavior of arrow functions inside class definitions?

**Comment by opatut** [comment]
I am having issues with the arrow function, actually. The hot reloading does not apply when using `render () => { ... }` instead of `render () {}`. Hence, no autobinding :( Any ideas on how to fix this?

**Comment by slonoed** [comment]
@lancefisher I think there is no spec for arrow functions in class.
This is babel stuff https://gist.github.com/jeffmo/054df782c05639da2adb
Babel put this functions assignments in constructor. And bound to this in constructor (i.e. instance of class).

@opatut why you want bind render? It is always called by library code, isnt it?

**Comment by opatut** [comment]
It's not only about binding `render`, when I add other methods, such as event callbacks, I cannot change logic inside them with hot reloading, since they are not proxied.

However, I find that binding the methods with `.bind()` or `.call()` upon usage works great, especially after I discovered the new (stage 0) [function bind syntax](http://babeljs.io/blog/2015/05/14/function-bind/).

**Comment by gaearon** [comment]
Properties are very tricky to hot reload because they're really being defined inside the constructor.
We'll see what we can do with a Babel plugin later, but for now, the workaround from @opatut is the best we got.

**Comment by gaearon** [comment]
We're supporting autobind decorator in the next beta release coming soon.
Stay tuned.

**Comment by gaearon** [comment]
Can I ask you to check whether `react-hot-loader@2.0.0-alpha` solves this issue?
Please provide any feedback on it in this PR: https://github.com/gaearon/react-hot-loader/pull/182

**Comment by steadicat** [comment]
`2.0.0-alpha` fixes hot reload of fat arrow methods for me. Thank you!

**Comment by gaearon** [comment]
@steadicat Hmm, I'm pretty sure fat arrow methods still shouldn't get hot reloaded. Can you check again, or share a reproducible case?

**Comment by gaearon** [comment]
(That said `@autobind` decorator should work now. Just not the fat arrows.)

**Comment by steadicat** [comment]
@gaearon You're right, it turns out I have a decorator on my components that somehow works around this issue. Here’s a reduced test case (code below):

![](https://dl.dropboxusercontent.com/u/140702/hotreload.gif)


```js

import React from 'react';

function wrap(Component) {
  return class Wrapper {
    render() {
      return <Component {...this.props} />;
    }
  }
}

@wrap
export default class Test {

  render() {
    return this.renderInner();
  }

  renderInner = () => {
    return <h1>Version 4</h1>;
  }

}
```

**Comment by gaearon** [comment]
Oh. It works because it generates a new class on every invocation. The downside is `Test` state will be reset on every hot reload.

**Comment by yangmillstheory** [comment]
I don't think this is fully working with `react-hot-loader@^3.0.0-beta.1`  yet.

Small test commit [here](https://github.com/yangmillstheory/react-hot-boilerplate/commit/ee888c5129d3dd46a8e7e5a8c7530f95287d8381).

![jun-04-2016 12-03-46](https://cloud.githubusercontent.com/assets/2729079/15801530/cc71ccdc-2a4c-11e6-93d3-af8107e14e98.gif)

In the demo above there's 3 steps:

1. without `@autobind` on `onClick`, click the button. This doesn't have the right context - `this` is `null`.
1. add `@autobind` to `onClick` - this is recognized by RHL and correct logs the right state in the console (`this` is bound to the `Counter` instance).
2. remove `@autobind`, `this` is still bound to the `Counter` instance.

Hope that's helpful, would really love to use decorators in my projects!

**Comment by episodeyang** [comment]
I'm having trouble too, no production ready example yet.

**Comment by gaearon** [comment]
Add/removing `@autobind` is not going to be hot reloaded correctly—it doesn’t seem to be very useful to support this corner case. But tweaking `@autob`ound methods should work. If not, please file a new issue with a reproducing project.

**Comment by episodeyang** [comment]
got it! I moved to the beta and everything worked after I updated to node 6.x, so it is all good!
Thanks for the response.
