### ISSUE TITLE
Dummy question.

### ISSUE THREAD

**Issue by eriknyk** [gaearon/react-hot-loader#126]
please can you tell me, 
what text editor did you used to make the video destration?
it is atom? textmate2? or another?,.. if it is atom or textmate2 wich theme was it,..
just for curiosity,..
thanks and good job, I will try it soon.

Best Regards.

**Comment by gaearon** [comment]
It is Sublime + [Spacegray Light](https://github.com/kkga/spacegray).

**Comment by eriknyk** [comment]
Thanks dude!
