### ISSUE TITLE
Hot loader resets redux state after saving

### ISSUE THREAD

**Issue by kkseven07** [gaearon/react-hot-loader#1266]
Hot loader resets redux state in all routes/components. However, it works fine in App component which is decorated with hot(). Can you help me with this problem? The problem is described on the stackoverflow topic

[Source code on stackoverflow](https://stackoverflow.com/questions/56548975/why-react-hot-loader-only-works-for-hotmoduleapp-and-resets-reducer-state-in)

 "react-hot-loader": "^4.3.0",
"react": "^16.8.5",
"redux": "^3.5.2",
"react-redux": "^7.0.3",
"react-router": "^4.3.1",

**Comment by theKashey** [comment]
First of all, try to repeat this test with a proper, up-to-date, version of react-hot-loader. `React-redux` __v7__ is based on `hooks`, and the minimum RHL'v version with proper support for them is v4.9.0.

**Comment by kkseven07** [comment]
Updated to 4.11.0, nothing changed

**Comment by kkseven07** [comment]
Sometimes the error happens: 
![Screen Shot 2019-06-12 at 10 36 03 AM](https://user-images.githubusercontent.com/25701048/59323785-eea64780-8cfd-11e9-84e1-a90dd2318fcf.png)

**Comment by kkseven07** [comment]
If it helps, this is the structure from react chrome extenstion:
![Screen Shot 2019-06-12 at 10 48 29 AM](https://user-images.githubusercontent.com/25701048/59324249-d46d6900-8cff-11e9-8e33-a51484b18808.png)

**Comment by theKashey** [comment]
1. get rid of `const store = configureStore(/* provide initial state if any */)` in the `Root`, IT IS RECREATED on every update
2. Look at `const store = configureStore();` you have `index.js`
3. Pass ^that^ store to the Root

```js
const render = Component => {
  ReactDOM.render(
    <AppContainer>
      <Component store={store}/>
    </AppContainer>,
    document.getElementById('wrapperContainer'),
  );
};
```

4. __even better__ - remove `hot` from `App` and wrap `Root` with `hot` instead. 

> Wrap a top-level component with `hot`, and double check that all important variables(like store) got initialized "before" it, so would be not affected by hot-update.

Bonus: __install eslint__, which would reveal (and fix) so many mistakes in your code.

**Comment by kkseven07** [comment]
Thank you so much, I'll install eslint to fix everything. Спасибо, что помогаете таким как мы с такими глупыми ошибками

**Comment by theKashey** [comment]
👨‍🔧, все такими были.
