### ISSUE TITLE
HMR isn't working with `react-loadable`

### ISSUE THREAD

**Issue by heath-freenome** [gaearon/react-hot-loader#1270]
I am using HMR with the `react-loadable` component to implement code splitting.  DESPITE what the documentation says, it seems that these two components don't work well together.  I'm using React-Router 4 and have set up my routes with components that are `Loadable` wrapped.  If I make changes to a component that is part of the hierarchy, the change does not get reflected.  IF I make the loadable wrapped component also do the `hot(module)(Component)` per the documentation, then things work (although I still see a warning in the console when I turn on logging).

Here is an example of what I mean by `Loadable` wrapped
```
import { hot } from 'react-hot-loader'; // RHL v4
import React from 'react';
import { Redirect, Switch, Route } from 'react-router';
import { BrowserRouter } from 'react-router-dom';
import Loadable from 'react-loadable';

import LoadableLoading from './components/loadableLoading/loadableLoading';

const Routes = () => {
  return (<div>
    <BrowserRouter>
      <AppRoute>
        <Switch>
...
         <Route exact path="/some/path" component={Loadable({
            loader: () => import(
              './routes/some/someComponent' /* webpackChunkName: "someComponent" */
            ),
            loading: LoadableLoading
          })}/>
...
        </Switch>
      </AppRoute>
    </BrowserRouter>
  </div>);
};

export default hot(module)(Routes);
```

When I enabled logging, I was seeing something that looked like:
`unexpected require(./app/javascript/routes/some/someComponent.jsx) from disposed module ./app/javascript/routes.jsx`

If I implement the work-around mentioned in the README.md and create an `index.jsx` file in `./routes/some` that looks like:
```
import { hot } from 'react-hot-loader'; // RHL v4

import SomeComponent from './someComponent';

export default hot(module)(SomeComponent);
```

and change the import in `routes.jsx` to:
```
import('./routes/some' /* webpackChunkName: "someComponent" */),
```
things start working... although I do see the following in the log, once:
`unexpected require(./app/javascript/routes/some/index.jsx) from disposed module ./app/javascript/routes.jsx`

At this point I'm not really blocked, but it seems like the documentation is not correct in that `react-loadable` doesn't really work without my using the work-around specified.  Either there really IS an issue here or maybe I'm doing something wrong?

**Comment by theKashey** [comment]
Your code is wrong in one line - `Loadable` __is not a Comonent__ (someone shall burn in hell for making it unclear), and you shall precreate component you are going to use.
That would give component a "name"(top level variable), and fix all the things.

JFYI: Right now you are geting a new componet on every Routes re-render.
```js
import { hot } from 'react-hot-loader'; // RHL v4
import React from 'react';
import { Redirect, Switch, Route } from 'react-router';
import { BrowserRouter } from 'react-router-dom';
import Loadable from 'react-loadable';

import LoadableLoading from './components/loadableLoading/loadableLoading';

// extract variable creation here
const PathRoute = Loadable({
            loader: () => import(
              './routes/some/someComponent' /* webpackChunkName: "someComponent" */
            ),
            loading: LoadableLoading
          });

const Routes = () => {
  return (<div>
    <BrowserRouter>
      <AppRoute>
        <Switch>
...
         <Route exact path="/some/path" component={PathRoute}/> // use it
...
        </Switch>
      </AppRoute>
    </BrowserRouter>
  </div>);
};

```

**Comment by heath-freenome** [comment]
Thanks!  I'll try that change and see if it make a difference

**Comment by theKashey** [comment]
We tested `loadable-component` multiple times, and, as long as it hasn't changed since then - it's working 💯, I am 💯% sure.

**Comment by heath-freenome** [comment]
Confirmed!  It works great when I use the recommended pattern, Thanks!
