### ISSUE TITLE
It doesn't work in `create-react-app`

### ISSUE THREAD

**Issue by fengxinming** [gaearon/react-hot-loader#1271]
It doesn't work in `create-react-app`, there are two demos below:

[Demo 1](https://github.com/fengxinming/react-starter/tree/master/react-redux)
[Demo 2](https://github.com/fengxinming/react-starter/tree/master/react-dva)

**Comment by theKashey** [comment]
Honestly - it doesn't worth to fix it. CRA was always quite strict and closed system, especially for things like React-Hot-Loader.

If you need reloading for create-react-app - try something fresh - https://github.com/facebook/create-react-app/issues/7227
