### ISSUE TITLE
hotRenderWithHooks dose not provide context (?)

### ISSUE THREAD

**Issue by Bnaya** [gaearon/react-hot-loader#1274]
getting `TypeError: Cannot read property 'muiFormControl' of undefined`

`stack.type` points to `FormLabel` is part of MUI 1.x, that expects getting context, 
But the function call supplies only props.

![Screen Shot 2019-06-27 at 8 23 07](https://user-images.githubusercontent.com/1304862/60239032-f7c61580-98b4-11e9-86a4-3fee5454191f.png)

```
react-hot-loader@4.11.1

react-dom@npm:@hot-loader/react-dom@16.8.6
```

BTW without patching react-dom, it works.

**Comment by theKashey** [comment]
React 15 legacy :(
_Patching_ react-dom activates configuration option `ignoreSFCWhenInjected`, so RHL stop wrapping FC with anything. And that anything was a Class component for FCs with a legacy context (cos it's not easy to track it).

### Hot to fix
1. `setConfig({ignoreSFCWhenInjected: false})` - it will fix hot comparison render when react-dom is patched
2. `setConfig({disableHotRendererWhenInjected: true});` - to disable buggy hotReplacementRender, and be happy ever after.

**Comment by theKashey** [comment]
v4.12 comes with `disableHotRendererWhenInjected` set to `true` by default.

**Comment by Bnaya** [comment]
Can you elaborate a bit what we "lose" when disableHotRendererWhenInjected: true?

**Comment by theKashey** [comment]
Nothing. Except some bugs like you faced, plus some problems with libraries with use `React.readContext` method directly.
