### ISSUE TITLE
"react-🔥-dom patch is not detected" warning appearning when react and react-dom are used from CDN

### ISSUE THREAD

**Issue by victor-cordova** [gaearon/react-hot-loader#1275]
### Description

Hello, I've been unable to find a clear answer in other issues as to whether or not it's possible to use react-dom from cdn without the warning mentioned in the title. Please note that I'd prefer not to use `@hot-loader/react-dom` (to minimize complexity in my setup) and just use regular react-dom. If React is loaded from node_modules then the warning doesn't appear. Thanks in advance :pray:  

### Expected behavior

For the warning not to appear when everything is configured correctly

### Actual behavior

Warning still shows

### Environment

React Hot Loader version: 4.11.1

Run these commands in the project folder and fill in their results:

1.  `node -v`: 	v8.15.0
2.  `npm -v`: 6.9.0

Then, specify:

1.  Operating system: OSX
2.  Browser and version: Chrome 70

### Reproducible Demo

[Link](https://github.com/victor-cordova/react-hot-reload-warning)

**Comment by theKashey** [comment]
Simply answer - no, that's not possible. `react-dom` expected or be patched already, or could be patched in runtime via webpack-loader.
The only way here would be to suppress the error message - `setConfig({showReactDomPatchNotification: false})`

**Comment by alex-my** [comment]
@theKashey I am sorry, I can not find showReactDomPatchNotification.
