### ISSUE TITLE
Question: Why do we need to require 'react-hot-loader' before 'react' and 'react-dom'?

### ISSUE THREAD

**Issue by rfgamaral** [gaearon/react-hot-loader#1277]
The [Getting started](https://github.com/gaearon/react-hot-loader#getting-started) section clearly states to:

> Make sure `react-hot-loader` is required before `react` and `react-dom`:

Is there an explanation for it and/or what are the possible issues that might arise for not doing so? I'm asking this because I really want to understand the reasoning for this and why the following example still works fine:

**index.tsx:**

```tsx
import React from 'react';
import ReactDOM from 'react-dom';

import Application from './Application';

ReactDOM.render(<Application name="Ricardo" />, document.getElementById('root'));
```

**Application.tsx:**

```tsx
import React from 'react';

import { hot } from 'react-hot-loader'; // I'm using Parcel, so no 'root'!

interface Props {
    name: string
}

class Application extends React.Component<Props> {
    render() {
        return <div>Hello {this.props.name}</div>;
    }
}

export default hot(module)(Application); // Again, using Parcel!
```

**Comment by theKashey** [comment]
The problem arise if you use webpack-loader( or babel-plugin) extended to `node_modules`. Then `react-dom` would require `react-hot-loader`, which would require `react-dom`, which would be an empty object yet, and everything would fail.

In a reverse - `react-hot-loader` -> `react-dom` -> `react-hot-loader` which are empty yet, but it could handle this case gracefully.

**Comment by rfgamaral** [comment]
So, in other words, this is not a problem with Parcel and my implementation is fine?

**Comment by theKashey** [comment]
Yep. If it __is__ not a problem - it's not a problem :)

**Comment by rfgamaral** [comment]
Thank you for the clarification. I guess I just need to keep in mind that this could be a problem if I move/use Webpack instead of Parcel in a different project :)
