### ISSUE TITLE
Hi, is there a way to configure react-hot-loader to work in conjunction w/ an existing webserver? 

### ISSUE THREAD

**Issue by datpham23** [gaearon/react-hot-loader#128]
I have a java webapp running localhost:8080 and the webpack-dev-server on localhost:3000. I'm serving my page from the java webapp and serving up my scripts from the webpack-dev-server but when a module updates the hot-loader is looking to my java webapp for the update. 

http://localhost.com:8080/scripts/1c5c268ad2d6ec92411b.hot-update.json - 404

Is there a way to configure the hotloader to point to the webpack-dev-server?

**Comment by gaearon** [comment]
Yes, you should set `output.publicPath` in your Webpack config to point to the WebpackDevServer port. For example, `publicPath: 'http://localhost:3000/scripts/`.
