### ISSUE TITLE
Why hot update file loads, but not change the content?

### ISSUE THREAD

**Issue by BaumVitaly** [gaearon/react-hot-loader#1281]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

Replacing of hot-loader files 

### Expected behavior

hot-loader file should be replaced after changing content

### Actual behavior

I try to use react-hot-loader and i saw in network log this:

![Screenshot from 2019-07-03 16-56-51](https://user-images.githubusercontent.com/30584905/60583248-adf99580-9db4-11e9-98ec-71e6e1ffef9a.png)

main.js it's a main bundle. And in index.html page i see this:

![Screenshot from 2019-07-03 17-00-03](https://user-images.githubusercontent.com/30584905/60583304-c8337380-9db4-11e9-8af2-ec006488a407.png)

as i know that new hot-loader file should be replaced with old and apply the changes, but files not replaced

### Environment

React Hot Loader version: 4.9.0

1.  `node -v`: 10.16.0
2.  `npm -v`: 6.9.0

1.  Operating system: Ubuntu 18.04
2.  Browser and version: Google Chrome 75.0.3770.100

**Comment by theKashey** [comment]
No files __could__ be replaced
- that's webpacks job, we have no control upon this.
- updates are stacking one on another. It's not bound to the "files", but only to a virtual module system.
- this is fine 🔥
