### ISSUE TITLE
Production is broken after 4.8.5

### ISSUE THREAD

**Issue by chrisbutler** [gaearon/react-hot-loader#1283]
# Description

We have been using RHL with Recompose for a long time, but suddenly our production server cannot start (development is fine).

`export default compose(
  hot(module),
  withSomeHOC,
)(HotReloadedParent)
`

Upgrading past version `4.8.5` produces the following error when trying to run the code in production mode:

`TypeError: b.apply is not a function at node_modules/recompose/dist/Recompose.cjs.js:810:18`

Seemingly the signature of `hot(module)` has changed in production mode after the above stated version?

### Expected behavior

It should continue to work as before. Production should ABSOLUTELY NEVER be affected by RHL

### Actual behavior

Production build/deployment fails because of code error

### Environment

React Hot Loader version: 4.8.5

**Comment by theKashey** [comment]
> It should continue to work as before. Production should ABSOLUTELY NEVER be affected by RHL

So, this is exactly what's happening - it wipes itself from production to ABSOLUTELY NEVER affect your App.

```js
export default compose( hot(module), withSomeHOC, )(HotReloadedParent)
// becomes
export default compose(, withSomeHOC, )(HotReloadedParent)
```

This is definitely a bug, as long as it shall not remove `hot(module)` - only `hot(module)(something)`, and somewhere around `4.8` we added code for babel plugin to delete another form of `hot`, and that's ended as a false positive.

But, anyway, I would ask you to change the code - you __have__ to remove magic `module` variable, or some production optimization would be disabled.

### How to fix
- if you are using webpack:
```js
import {hot} from 'react-hot-loader/root';
....
export default hot(withSomeHOC(HotReloadedParent))
```

- if you are using "not" webpack (and `/root` would complain):
```js
export default hot(module)(withSomeHOC(HotReloadedParent))
```

**Comment by theKashey** [comment]
v4.12.2 is containing the fix for babel plugin. You might use your old code, but I still encourage you to update it.
