### ISSUE TITLE
vnode.nodeName is deprecated in preactX,use vnode.type instead

### ISSUE THREAD

**Issue by wen911119** [gaearon/react-hot-loader#1295]
https://github.com/gaearon/react-hot-loader/blob/0c7947421a6b1dd20c0bb3bfe12327c591013eb2/src/adapters/preact.js#L13

**Comment by wen911119** [comment]
![20190708192417](https://user-images.githubusercontent.com/13494648/60806620-0fa37080-a1b6-11e9-8346-d6e21d031640.jpg)

**Comment by theKashey** [comment]
Without something like https://github.com/preactjs/preact/pull/1120 Preact would not be hot-reloadable friendly anyway :(

**Comment by theKashey** [comment]
So - still the question - does this fix fixes anything with Preact? It should not work in any case.
