### ISSUE TITLE
Weird error about global.WebSocket

### ISSUE THREAD

**Issue by quangbuule** [gaearon/react-hot-loader#130]
```js
var global = (function() { return this; })();

/**
 * WebSocket constructor.
 */

var WebSocket = global.WebSocket || global.MozWebSocket;
```

`global` is `undefined` so, it throw error. But when I test using `ws` with browserify, it was `window`.

I am trying to use react-hot-loader and can't figure this out. Hope someone who experienced this could help. Thanks a lot.

**Comment by gaearon** [comment]
Is it really related to React Hot Loader? I think it's more like a generic Webpack issue, so you should ask in Webpack's repo. Here's [how you shim globals](http://webpack.github.io/docs/shimming-modules.html) with Webpack. Does this help?

**Comment by quangbuule** [comment]
Yeah, but I think that if some guys here have solved the problem.

It would be nice if you put some thoughts in here:
https://github.com/webpack/webpack-dev-server/issues/174#issuecomment-102079669
