### ISSUE TITLE
Basic Typescript project not rendering anything, throwing error "require is not defined"

### ISSUE THREAD

**Issue by ericbiewener** [gaearon/react-hot-loader#1301]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

Can't get it to work in a basic Typescript project. Relevant configuration lines from my [sample project](https://github.com/ericbiewener/bootstrap-react/tree/react-hot-loader):
- [`babel-loader`](https://github.com/ericbiewener/bootstrap-react/blob/react-hot-loader/webpack.config.ts#L29) and [`.babelrc`](https://github.com/ericbiewener/bootstrap-react/blob/react-hot-loader/.babelrc)
- [hot-exported module](https://github.com/ericbiewener/bootstrap-react/blob/react-hot-loader/src/App.tsx#L6)
- [Rendering of the app into the DOM](https://github.com/ericbiewener/bootstrap-react/blob/react-hot-loader/src/main.tsx)

### Expected behavior

It works!

### Actual behavior

Nothing renders, console shows the following error:

```
Uncaught ReferenceError: require is not defined
    at Object.events (external "events":1)
    at __webpack_require__ (bootstrap:685)
    at fn (bootstrap:59)
    at Object../node_modules/webpack/hot/emitter.js (emitter.js:1)
    at __webpack_require__ (bootstrap:685)
    at fn (bootstrap:59)
    at Object../node_modules/webpack/hot/dev-server.js (dev-server.js:50)
    at __webpack_require__ (bootstrap:685)
    at fn (bootstrap:59)
    at Object.0 (app.js:30305)
```

### Environment

React Hot Loader version: 4.12.6

Run these commands in the project folder and fill in their results:

1.  `node -v`: 12.2.0
2.  `npm -v`: 6.9.0

Then, specify:

1.  Operating system: Mac OS X 10.14.5
2.  Browser and version: Chrome 75.0.3770.100

### Reproducible Demo

https://github.com/ericbiewener/bootstrap-react/tree/react-hot-loader
- `yarn start`: start app without HMR, works fine
- `yarn run hot`: start app with HMR, shows console error

**Comment by theKashey** [comment]
remove `target: 'node',` from your webpack config. You are welcome.
