### ISSUE TITLE
hot update was not successful. hot updated failed for module ...  Last file processed:""

### ISSUE THREAD

**Issue by lancerace** [gaearon/react-hot-loader#1302]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description
 react-hot-loader is working. i am attempting to add **"@hot-loader/react-dom": "^16.8.6",**
because of the warning in console stating that it **may not support react 16.6 feature** . 

After adding it i got this error, 
![image](https://user-images.githubusercontent.com/15110899/61293548-8966da00-a806-11e9-87b7-93cbb2f21358.png)

**file processed** was an empty string, i assume there is something wrong with my relative path 
   in my webpack configuration? @hot-loader/react-dom" couldn't detect my file path to **process**?

**error information in console**
![image](https://user-images.githubusercontent.com/15110899/61294507-840a8f00-a808-11e9-8ae2-469a7132e142.png)

![image](https://user-images.githubusercontent.com/15110899/61294410-56254a80-a808-11e9-9d10-839360f66b29.png)

#### below is my settings for react hot loader 
```javascript
//index.js
import ReactDOM from "react-dom";
import React from "react"; //sets the name Component to the default export of the 'react' package

//import { ThemeProvider } from "@material-ui/styles"; //JSS way of providing theme to top level. Passing it down to react components
//import "semantic-ui-css/semantic.min.css";
import "./styles.css";
import App from "./App";

const render = () => {
  ReactDOM.render(<App />, document.getElementById("reactApps"));
};

render();
```
```javascript
//webpack.config.js

module.exports = {
  mode: "development",
  entry: ["./src/index"],
  output: {
    publicPath: "http://localhost:3000/", // relative to HTML page
    path: path.resolve(__dirname, "dist"),
    filename: "[name].bundle.js",
    chunkFilename: "[name].js"
    //pathinfo: true
  },
  resolve: {
    alias: {
      "react-dom": "@hot-loader/react-dom"
    }
  }, ......
  devServer: {
    open: true,
    contentBase: path.join(__dirname, "dist"),
    historyApiFallback: true,
    port: 3000
 }
}
```
```javascript
//app.js
import { hot } from "react-hot-loader/root"; //enable ^16.6 react feature(preserve component internal state) for hmr.
import React, { Component } from "react";
import { Route, Switch, BrowserRouter as Router } from "react-router-dom";
import Login from "./login";
/*
const Main = React.lazy(() =>
  import( webpackChunkName: "MainPage"  "./Main");*/
import Main from "./Main";

class App extends Component { 
... 
}
export default hot(App);
```

**What you are reporting:**
Red Error in console and overlay appearing in my webpage. Something wrong with my configuration ?
### Expected behavior
no error overlay
What you think should happen:
working as expected. no errors screaming at me.

### Environment

React Hot Loader version:
"react-hot-loader": "^4.12.6",
Run these commands in the project folder and fill in their results:

1.  `node -v`: v 8.11.3
2.  `npm -v`: 6.9.2

Then, specify:

1.  Operating system:window
2.  Browser and version: chrome Version 75.0.3770.142 (Official Build) (64-bit)

Not sure how to solve it. would appreciate some help :D

**Comment by theKashey** [comment]
Look for the error between ‘import {hot}’ and call to ‘hot’ - it was not called.

**Comment by lancerace** [comment]
![theimport](https://user-images.githubusercontent.com/15110899/61352801-e020f200-a8a0-11e9-90cd-b8cb08c04a51.png)

step into function call

![importedhot](https://user-images.githubusercontent.com/15110899/61352854-fcbd2a00-a8a0-11e9-9d29-d4849448495e.png)
![hotCurrentChildModule](https://user-images.githubusercontent.com/15110899/61352883-0e9ecd00-a8a1-11e9-9358-8e884e666036.png)

hotcurrentchildmodule undefine?..

so i tried looking into it and not sure what to do now..? got even more lost because of the boilerplate code generated from development make it hard to debug.
sourcemap(eval-source-map) was not working as what i expected to be too.

**Comment by theKashey** [comment]
The problem is somewhere between the __first__ part(`import`) and the __second__ - `export default hot(App)`.
You've just debugged the first one, which was absolutely ok.

**Comment by lancerace** [comment]
**second** - ``` export default hot(App).```
![1](https://user-images.githubusercontent.com/15110899/61479443-6f73f580-a9c6-11e9-8c06-1673e15e9dee.png)
**breakpoint**
![2](https://user-images.githubusercontent.com/15110899/61479482-86b2e300-a9c6-11e9-8675-74bba9f10b0a.png)
**found the source**
![origin](https://user-images.githubusercontent.com/15110899/61479506-9500ff00-a9c6-11e9-8439-79f4fc393f60.png)
![found](https://user-images.githubusercontent.com/15110899/61479543-a2b68480-a9c6-11e9-8251-f1da6dc2c962.png)
box that display error info is too small, cant find an option to maximize so i combine it.
![a](https://user-images.githubusercontent.com/15110899/61479578-af3add00-a9c6-11e9-985b-7dc0795fce9b.png)
```stack: "ReferenceError: lastModuleOpened is not defined↵    at eval (eval at <anonymous> (webpack-internal:///./node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:1:1)↵    at eval (webpack-internal:///./node_modules/react-hot-loader/dist/react-hot-loader.development.js:2706:17)"```

![lastModuleOpened](https://user-images.githubusercontent.com/15110899/61480209-07beaa00-a9c8-11e9-8bf7-aa9c12a4641e.png)

**Comment by theKashey** [comment]
But they are defined, and you were getting "correct" error message before.
Double check - first part if setting up `chargeFailbackTimer`, you just debugged, while the second part is clearing that timeout.
Timeout was not cleared - error would be displayed.

And you haven't answered the main question - what do you see except RHL error box? Is Application dead?

Try:
- setup breakpoint at the "first part"
- configure debugger to stop on exception
<img width="230" alt="Screen Shot 2019-07-16 at 4 38 36 pm" src="https://user-images.githubusercontent.com/582410/61495650-e6c47c00-a9fc-11e9-8e6b-bffe7fc0866b.png">

- run. It should stop on the "real" problem.

**Comment by lancerace** [comment]
> And you haven't answered the main question - what do you see except RHL error box? Is Application dead? 

Pardon me, I'm not really sure what I'm doing mostly..

this is the whole view of what I'm looking at. application is not dead
![image](https://user-images.githubusercontent.com/15110899/61574777-a9dcb000-aaf6-11e9-8540-e5ac1db0fd50.png)


> Try:
 > 1. setup breakpoint at the "first part"
 > 2. configure debugger to stop on exception

![image](https://user-images.githubusercontent.com/15110899/61574828-777f8280-aaf7-11e9-94fa-261490662ac3.png)

**Comment by theKashey** [comment]
It seems to me that you did `.2`, but not `.1`. "ParseSupported" is usually evaluated on script startup, when polyfills are initiated, and that shall take a place __before__ react hot loader initialization.

Let me conclude - you are not able to find the issue by yourself, and I am not able to guest the cause by myself. Please provide an example to reproduce - that's the only way to continue. You may DM me if the project is not public.

**Comment by hi-zhaolei** [comment]
I have met same issue.
The real reason that you got this error because the hot function not execute. 
Close webpack souceMap and check the complied file，you will see module just export App component.
The reason why for this situation is babel thought current NODE_ENV is 'production' in compile process. We can see babel.prod.js in RHL repo that babal will replace the `hot(App)` code.
So.  if you use webpack node api to start dev server. make sure the process.env.NODE_ENV is define correct.

**Comment by anishhegde14** [comment]
I'm getting the same error and I'm quite new to react and js so can you please tell me the steps and location of the files where i have to make the changes

**Comment by lancerace** [comment]
> I'm getting the same error and I'm quite new to react and js so can you please tell me the steps and location of the files where i have to make the changes. And I'm using vscode.

Few mths ago of me encountering that issue was, i am using atom. i was trying to find a solution to this and i decided to switch to vscode and it work. i am not clear on the fix behind it but it worked for me. 


well.. i think my solution doesn't help others as i'm getting 3 thumbdown lol...

**Comment by LKNSI** [comment]
Also having this issue, was original using react-rewired. Started a new project from scratch, ejected, and followed steps exactly to try not make any mistakes on my end. I wish I could give you something reproducible but it would end up just being an exact copy of your instructions which wouldn't be helpful.

**Comment by HEMANT96** [comment]
⚛️🔥😭: hot update was not successful collapseRetry
(1/1)
(AppContainer, in Coursecart (at pages/index.js:25)) TypeError: Cannot read property 'edges' of undefined

Stack trace:
at new Coursecart (http://localhost:8000/commons.js:76880:30)
in Coursecart (at pages/index.js:25)
in Layout (at pages/index.js:16)
in IndexPage (created by HotExportedIndexPage)
in AppContainer (created by HotExportedIndexPage)
in HotExportedIndexPage (created by PageRenderer)
in PageRenderer (at query-result-store.js:86)
in PageQueryStore (at root.js:56)
in RouteHandler (at root.js:78)
in div (created by FocusHandlerImpl)
in FocusHandlerImpl (created by Context.Consumer)
in FocusHandler (created by RouterImpl)
in RouterImpl (created by Context.Consumer)
in Location (created by Context.Consumer)
in Router (at root.js:73)
in ScrollHandler (at root.js:69)
in RouteUpdates (at root.js:68)
in EnsureResources (at root.js:66)
in LocationHandler (at root.js:124)
in LocationProvider (created by Context.Consumer)
in Location (at root.js:123)
in Root (at root.js:132)
in StaticQueryStore (at root.js:138)
in _default (at app.js:94)

**Comment by kambleaa007** [comment]
my <input> tag have children i removed them then worked
