### ISSUE TITLE
TypeError: Object(...)(...) is not a function

### ISSUE THREAD

**Issue by jeetiss** [gaearon/react-hot-loader#1309]
### Description

no semicolon code style in node_modules breaks hmr

### Expected behavior

all work nice

### Actual behavior

What actually happens:

```
TypeError: Object(...)(...) is not a function
```

<img width="469" alt="Снимок экрана 2019-07-25 в 13 37 04" src="https://user-images.githubusercontent.com/6726016/61868099-5cd75000-aee1-11e9-9317-04a7dbf5f0f4.png">

### Reproducible Demo

repo with bug and steps to reproduce
https://github.com/jeetiss/gatsby-hmr-bug

**Comment by theKashey** [comment]
Sooo easy? Why nobody reported it before?

**Comment by theKashey** [comment]
However - that did not help.
- `;` is lost during rollup bundling.
- `;` is added by webpack plugin itself
- the problem does exist only for `node_modules` in the SRC - the code from webpack plugin is just DIFFERENT - without ";", that somehow is bound to the source map generation
- I am just changing IIFE mode (to !function) to prevent the issue.

**Comment by theKashey** [comment]
The best fix - scope webpack loader to `react-dom`

**Comment by jeetiss** [comment]
> the problem does exist only for node_modules in the SRC

@theKashey this not right
I am update [example](https://github.com/jeetiss/gatsby-hmr-bug) with npm package that breaks hmr

https://github.com/jeetiss/module-that-breaks-hmr

**Comment by jeetiss** [comment]
@theKashey thanks for help ❤️

**Comment by theKashey** [comment]
If you will compare the final result for "normal" node modules, and your ones - it's different.
How it works in short:
- you are given a `source`
- I am reading `webpackTagCommonJSExports.js`
- I am concatenating `source` and `patch` with `"\n\n;"` as a _glue_.

Usually: - everything is working as expected
For "your" modules: - there is no glue, plus some comments which should not be present.

And that's not quite explainable.
