### ISSUE TITLE
! THIS IS NOT YOUR COMPONENT !

### ISSUE THREAD

**Issue by theKashey** [gaearon/react-hot-loader#1311]
```
        ! THIS IS NOT YOUR COMPONENT !
        !  THIS IS REACT-HOT-LOADER  !

        And you are probably looking for a function component of yours
        It's hidden, but there is a way to fix this - just reconfigure your application a bit
```

You might see this in your code, especially if you clicked __"Show Component Source"__ in the React Dev Tools.

You were looking for some component, and got `ProxyFacade` - that's how React-Hot-Loader works - it's wrapping everything with Proxies.

### And you can fix it!
To fix this problem you need "react-🔥-patch", and there are tree ways how to apply it:

#### Webpack loader
Use a [webpack-plugin](https://github.com/gaearon/react-hot-loader#webpack-plugin) to land a patch. That's the safest way.
```
// would only land a "hot-patch" to react-dom
{
    test: /\.js$/,
    include: /node_modules\/react-dom/,
    use: ['react-hot-loader/webpack']
},
```

#### hot-loader/react-dom alias
Use a [hot-loader/react-dom](https://github.com/hot-loader/react-dom) with prelanded patch. See hot-loader repo for the instalation details.
```js
// webpack.conf
...
resolve: {
    alias: {
      'react-dom': '@hot-loader/react-dom'
    }
}
...
```

#### hot-loader/react-dom yarn override
Just `yarn add react-dom@npm:@hot-loader/react-dom`, but only for `yarn` package manager.

**Comment by ivancarvalhofilho** [comment]
None of the mentioned fixes worked for me, what worked was changing the default _react-hot-reload_ lib to another one such as _webpack-hot-reload_ lib.
Ex:
```
// webpack.conf
module.exports = {
  ...
  entry: [
    "webpack/hot/dev-server.js", 
    ...
  ],
  output:{
    publicPath: '/' // Webpack hot reload require this param to work properly
  },
 ...
}
```
(I was using React v17 and Router v6)

**Comment by vikivarun** [comment]
> 

I am facing this issue and it is not working for me

**Comment by inspiraller** [comment]
I am also facing the same issue as @Karen-boop.
Why was the message closed? What is the solution

**Comment by inspiraller** [comment]
Ok I've bit the bullet and changed the npm package to - react-refresh - as advised from this README
https://www.npmjs.com/package/react-hot-loader

**Comment by minhnh87** [comment]
It works for me (the first way). Thank you so much
