### ISSUE TITLE
HMR App is up to date bundle rebuilt Nothing hot updated

### ISSUE THREAD

**Issue by JapinderSandhu** [gaearon/react-hot-loader#1317]
### Description

Hello all, I had this error "React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work. #1227"

I took @mrfelton 's advice on an issue posting here https://github.com/gaearon/react-hot-loader/issues/1227 and I got rid of the error in the console, however the hot-module reloading is still not working. As was suggested I modified my webpack.dev-client.config file. 

The hot module re-loading seems to work for my html sometimes however it absolutely does not work for my css. 

When I save my css file it detects there is a change and the console status is 
`
>[HMR] bundle rebuilding
>client.js:242 [HMR] bundle rebuilt in 80ms
>process-update.js:41 [HMR] Checking for updates on the server...
>process-update.js:112 [HMR] Nothing hot updated.
>process-update.js:121 [HMR] App is up to date.
`

My app is a react app and it's using webpack.

### Reproducible Demo
 

Below are the key parts of my setup and if you want to try it your self please do It would be greatly appreciated as I have been stuck on this for some time and it is agonizing;
In Terminal:
1.  git clone https://github.com/JapinderSandhu/noenglish_website/tree/ssr-dynamic-imports
2. npm install
3. npm run dev OR npm run prod 

### Expected behavior

I expect the hot-loading to work all the time for my development environment for all my css and html files.

### Actual behavior

The hot-module rarely works, changes are detected however it does not update the files. Sometimes works for html never works for css

### Environment
OS:MacOS High Sierra Version 10.13.4
"react-hot-loader": "4.8.8"
npm -v : 6.9.0
node -v: 10.16.0

> 
> package.json
> 
> ```json
>   "dependencies": {
>     "@hot-loader/react-dom": "16.8.6",
>     "react": "16.8.6",
>     "react-dom": "16.8.6",
>     "react-hot-loader": "4.8.8",
> }
> ```
> 
> app.js
> 
> ```js
>import React from "react"
>import ReactDOM from "react-dom"
>import AppRoot from "./components/AppRoot"
>import { AppContainer } from "react-hot-loader"
>
>function render(Component) {
>  ReactDOM.hydrate(
>    <AppContainer>
>      <Component />
>    </AppContainer>,
>    document.getElementById("react-root")
>  )
>}
>render(AppRoot)
>
>if (module.hot) {
>  module.hot.accept("./components/AppRoot.js", () => {
>    const NewAppRoot = require("./components/AppRoot.js").default
>    render(NewAppRoot)
>  })
>}
>
> ```
> 

> .babelrc
> 
> ```json
>   {
 > "presets": [
>    [
>      "env",
>      {
>        "targets": {
>          "browsers": ["last 2 versions"]
>        },
>        "debug": false
>      }
>    ],
>    "babel-preset-react"
>  ],
>  "plugins": ["syntax-dynamic-import", "universal-import"],
>  "env": {
>    "development": {
>      "plugins": ["react-hot-loader/babel"]
>    }
>  }
>}
>
> ```
> 
> webpack.dev-client.js
>```js
>const path = require("path")
>const webpack = require("webpack")
>const ExtractCssChunks = require("extract-css-chunks-webpack-plugin")
>
>module.exports = {
> name: "client",
>  mode: "development",
>  entry: {
>    vendor: ["react", "react-dom"],
>    main: [
>      "react-hot-loader/patch",
>      "babel-runtime/regenerator",
>      "webpack-hot-middleware/client?reload=true",
>      "./src/main.js"
>    ]
>  },
>  resolve: {
>    alias: {
>      'react-dom': '@hot-loader/react-dom'
>    }
>  },
>  output: {
>    filename: "[name]-bundle.js",
>    chunkFilename: "[name].js",
>    path: path.resolve(__dirname, "../dist"),
>    publicPath: "/"
>  },
>  devServer: {
>    contentBase: "dist",
>    overlay: true,
>    hot: true,
>    stats: {
>      colors: true
>    }
>  },
>  optimization: {
>    runtimeChunk: {
>      name: "bootstrap"
>    },
>    splitChunks: {
>      chunks: "initial",
>      cacheGroups: {
>        vendors: {
>          test: /[\\/]node_modules[\\/]/,
>          name: "vendor"
>        }
>      }
>    }
>  },
>  devtool: "source-map",
>  module: {
>    rules: [
>      {
>        test: /\.js$/,
>        exclude: /node_modules/,
>        use: [
>          {
>            loader: "babel-loader"
>          }
>        ]
>      },
>      {
>        test: /\.css$/,
>        use: [
>          { loader: ExtractCssChunks.loader },
>          {
>            loader: "css-loader"
>          }
>        ]
>      },
>      {
>        test: /\.(jpg|png|gif)$/,
>        use: [
>          {
>            loader: "file-loader",
>            options: {
>              name: "assets/page1_media/images/[name].[ext]"
>            }
>          }
>        ]
>      },
>      {
>        test: /\.md$/,
>        use: [
>          {
>            loader: "markdown-with-front-matter-loader"
>          }
>        ]
>      }
>    ]
>  },
>  plugins: [
>    new ExtractCssChunks({ hot: true }),
>    new webpack.DefinePlugin({
>      "process.env": {
>        NODE_ENV: JSON.stringify("development"),
>        WEBPACK: true
>      }
>    }),
>    new webpack.HotModuleReplacementPlugin()
>  ]
>}
>```
>

**Comment by theKashey** [comment]
I'm afraid I could not do anything with CSS. The common advice is not to use `ExtractCssChunks` in dev mode.

According to [documentation](https://github.com/faceyspacey/extract-css-chunks-webpack-plugin) `hot` is a loader option, not the plugin.

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
           {
             loader:ExtractCssChunks.loader,
             options: {
               hot: true, // if you want HMR
               reloadAll: true, // when desperation kicks in - this is a brute force HMR flag
             }
           },
           "css-loader"
         ]
      }
    ]
  },
  plugins: [
    new ExtractCssChunks(
        {
          // Options similar to the same options in webpackOptions.output
          // both options are optional
          filename: "[name].css",
          chunkFilename: "[id].css",
          orderWarning: true, // Disable to remove warnings about conflicting order between imports
        }
    ),
  ]
}
```

**Comment by JapinderSandhu** [comment]
I fixed the problem, Im actually following a udemy course Webpack 4: Beyond the Basics with Lawrence Whiteside. He has his github repository here https://github.com/lawwantsin/webpack-course/tree/local-domains which I am following.

His github repository works perfectly fine with HMR and all the outlined webpack configs. 

I was frustrated comparing every single line of code with his, after about 4 days of this I found that it was exactly the same as his except my package.json versions were different.

So combining some advice from this other issue "React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work. #1227" I matched my package.json with his I then reinstalled my node_modules and IT WORKED!!!

VOILA I am still clueless as to why/how it works now and not before, I hope some one can enlighten me? 

I believe the biggest reason is that the version of react-hot-loader changed to the older one which made it work.

package.json BEFORE

```
package.json
{
  "name": "no-english-website",
  "version": "1.0.0",
  "main": "index.js",
  "description": "website for no english film",
  "repository": "",
  "license": "MIT",
  "dependencies": {
    "@hot-loader/react-dom": "16.8.6",
    "ajv": "^6.5.2",
    "babel-cli": "*",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-runtime": "*",
    "babel-plugin-universal-import": "^4.0.0",
    "babel-polyfill": "*",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "*",
    "babel-preset-react": "^6.24.1",
    "bootstrap": "^4.3.1",
    "brotli-webpack-plugin": "^1.0.0",
    "compression-webpack-plugin": "^1.1.11",
    "css-loader": "^0.28.11",
    "cssnano": "^4.0.0",
    "ejs-loader": "^0.3.1",
    "express": "^4.16.3",
    "express-static-gzip": "^0.3.2",
    "extract-css-chunks-webpack-plugin": "^4.5.6",
    "extract-loader": "^1.0.2",
    "file-loader": "^1.1.11",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "markdown-with-front-matter-loader": "^0.1.0",
    "mini-css-extract-plugin": "^0.4.1",
    "optimize-css-assets-webpack-plugin": "^4.0.3",
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "react-hot-loader": "4.8.8",
    "react-iframe": "^1.8.0",
    "react-router": "^5.0.1",
    "react-router-dom": "^5.0.1",
    "react-universal-component": "^4.0.0",
    "style-loader": "^0.20.3",
    "uglifyjs-webpack-plugin": "^1.2.7",
    "url-loader": "0.6.2",
    "webpack": "^4.14.0",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "^3.0.8",
    "webpack-dev-middleware": "^3.1.3",
    "webpack-dev-server": "^3.1.4",
    "webpack-flush-chunks": "^2.0.3",
    "webpack-hot-middleware": "2.22.2",
    "webpack-hot-server-middleware": "^0.5.0",
    "webpack-node-externals": "^1.7.2"
  },
  "scripts": {
    "prod": "NODE_ENV=production node src/server/main.js",
    "dev": "nodemon --watch src/server --watch config --inspect src/server/main.js",
    "heroku-postbuild": "npm run build"
  },
  "devDependencies": {
    "babel-plugin-transform-regenerator": "^6.26.0"
  }
}
```


package.json AFTER


```
package.json
{
  "name": "no-english-website",
  "version": "1.0.0",
  "main": "index.js",
  "description": "website for no english film",
  "repository": "",
  "license": "MIT",
  "dependencies": {
    "@hot-loader/react-dom": "16.8.6",
    "ajv": "^6.5.2",
    "babel-cli": "*",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-runtime": "*",
    "babel-plugin-universal-import": "^4.0.0",
    "babel-polyfill": "*",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "bootstrap": "^4.3.1",
    "brotli-webpack-plugin": "^1.0.0",
    "compression-webpack-plugin": "^1.1.11",
    "css-loader": "^0.28.11",
    "cssnano": "^4.0.0",
    "ejs-loader": "^0.3.1",
    "express": "^4.16.3",
    "express-static-gzip": "^0.3.2",
    "extract-css-chunks-webpack-plugin": "^3.0.6",
    "extract-loader": "^1.0.2",
    "file-loader": "^1.1.10",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "markdown-with-front-matter-loader": "^0.1.0",
    "optimize-css-assets-webpack-plugin": "^4.0.3",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-hot-loader": "^4.3.3",
    "react-iframe": "^1.8.0",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "react-universal-component": "^4.0.0",
    "style-loader": "^0.20.3",
    "uglifyjs-webpack-plugin": "^1.2.7",
    "url-loader": "0.6.2",
    "webpack": "^4.14.0",
    "webpack-cli": "^3.0.8",
    "webpack-dev-middleware": "^3.1.3",
    "webpack-dev-server": "^3.1.4",
    "webpack-flush-chunks": "^1.2.3",
    "webpack-hot-middleware": "2.22.2",
    "webpack-hot-server-middleware": "^0.5.0",
    "webpack-node-externals": "^1.7.2"
  },
  "scripts": {
    "prod": "NODE_ENV=production node src/server/main.js",
    "dev": "nodemon --watch src/server --watch config --inspect src/server/main.js",
    "heroku-postbuild": "npm run build"
  },
  "devDependencies": {
    "babel-plugin-transform-regenerator": "^6.26.0"
  }
}```

**Comment by theKashey** [comment]
It's 4.12 already! Please try the latest

**Comment by JapinderSandhu** [comment]
I updated react-hot-module to 4.12 and it works! I will look further into this and figure out why it didnt work. 

The exact moment It worked was when I copied over the package.json and re-installed the node_modules. So it must be a different plugin that was problematic. 

Let me know if anyone finds out why, thanks.

**Comment by gary-rivera** [comment]
fwiw - each of these dependencies were a mismatch: 
- "babel-preset-es2015" <<< this one didn't exist in your original package.json
- "extract-css-chunks-webpack-plugin"
- "file-loader"
- "mini-css-extract-plugin"
- "react"
- "react-dom"
- "react-hot-loader"
- "react-router"
- "react-router-dom"
- "webpack-bundle-analyzer" <<< this one didn't exist in your original package.json
- "webpack-flush-chunks"

![Screen Shot 2022-07-19 at 4 17 17 PM](https://user-images.githubusercontent.com/65045826/179863924-acb070c9-0b9a-409f-96a5-e4849f5f6dcf.png)
