### ISSUE TITLE
HMR is refreshing the entire component tree on any change.

### ISSUE THREAD

**Issue by hannadrehman** [gaearon/react-hot-loader#1318]
### Description

after updating to `4.12.10` and using `"react-dom": "npm:@hot-loader/react-dom",`  any change in the components no matter how deeply nested. hmr will refresh the entire component tree. it should only update the change which caused it. 

### Expected behavior
HMR should only update the piece of code which was changed. or view which was updated. 

### Actual behavior
HMR refreshes entire component tree on every change made to any component in that tree. even if its a small change in one character in view. it refreshes the whole component tree.

```
main.js:164839 [HMR] Updated modules:
main.js:164839 [HMR]  - ./packages/applications/doctors-dashboard/src/App/Modules/EventsPage/EventsPage.component.jsx
main.js:164839 [HMR]  - ./packages/applications/doctors-dashboard/src/App/Modules/EventsPage/index.js
main.js:164839 [HMR]  - ./packages/applications/doctors-dashboard/src/App/Router/Router.component.jsx
main.js:164839 [HMR]  - ./packages/applications/doctors-dashboard/src/App/Router/index.jsx
main.js:164839 [HMR]  - ./packages/applications/doctors-dashboard/src/App/Layout/Layout.component.jsx
main.js:164839 [HMR]  - ./packages/applications/doctors-dashboard/src/App/Layout/index.jsx
main.js:164839 [HMR]  - ./packages/applications/doctors-dashboard/src/App/index.jsx
main.js:164839 [HMR]  - ./packages/applications/doctors-dashboard/src/App.hot.js
main.js:164839 [HMR] App is up to date.
```

changes like `hello world` to `hello worl` will trigger entire tree refresh.
i am using `code spliting` and `lazy` thats why i am able to see chunk loading aswell (loading gif).

### Environment

React Hot Loader version: 4.12.10

Run these commands in the project folder and fill in their results:

1.  `node -v`: v10.16.2
2.  `npm -v`: 6.9.0

Then, specify:

1.  Operating system: macOS 10.14.6
2.  Browser and version:  chrome latest

**Comment by theKashey** [comment]
That means that RHL is not working at all. What was your previous configuration?

**Comment by hannadrehman** [comment]
i was using this 

```import { hot } from 'react-hot-loader';
const App = () => <div>Hello World!</div>;
export default hot(module)(App);```

**Comment by theKashey** [comment]
Then I could not help you, as long a it's expected to work, and I could not find your problem without seeing your case.

**Comment by hannadrehman** [comment]
alright. i will try to create a test repo and post here

**Comment by LaloHao** [comment]
You have to patch the dom on your entry file, just before importing `React` for the first time
 
```ts
import 'react-hot-loader/patch';
import React from 'react';
import { render } from 'react-dom';
import App from './App';

render(<App />,
  // tslint:disable-next-line
  document.getElementById('app'),
);
```

**Comment by hannadrehman** [comment]
@LaloHao  i am adding it in my webpack config. 
```  if (!isProd) {
    config.entry.unshift('react-hot-loader/patch');
  }```

**Comment by theKashey** [comment]
Try to remove `hot-loader/react-dom`. Without it RHL should failback to the "old mode", and if it will still not work - then the problem is not with RHL.

**Comment by hannadrehman** [comment]
@theKashey tried removing `hot-loader/react-dom` i am seeing the same behaviour

**Comment by theKashey** [comment]
Then something else if broken. And the only way to fix is to provide an example to reproduce.

**Comment by BertelBB** [comment]
I am having the same issue and have a similar use case. I'm lazy loading every *page* (route) among other things. It worked fine when I was using react-hot-loader 3 and before updating to react 16.

I did find a fix though. So instead of just wrapping the root component with the hot module, I also wrap every page with the hot module and then it works.

Lets say you have HomePage.jsx, UserPage.jsx and AboutPage.jsx. Then each of these components needs to be wrapped with the hot module.

**Comment by theKashey** [comment]
So how it was "not working" - full page refresh or just react remount? Which code-splitting library you use?

**Comment by BertelBB** [comment]
@theKashey any change to a react component, be it class or functional, resulted in a full page refresh. I am using the react-universal-component library for code-splitting

**Comment by theKashey** [comment]
As far as I remember `react-universal-component` is not RHL compatible, and any update should just does nothing.
Anyway - full page update is `webpack` related issue - it's updating page due to unaccepted code update - adding `hot` somewhere below just catching that update.

**Comment by BertelBB** [comment]
@theKashey the documentation recommends RUC for code-splitting and states that it is compatible. react-async-component is incompatible

**Comment by theKashey** [comment]
It's _really_ compatible with `React.lazy` - RHL could import it by itself. `React-Loadable` and `React-Imported-Componet` could reload themselves, and `@loadable-components` are fully incompatible unless you wrap export with `hot`.
Meanwhile, `react-async-component` might just throw runtime exception and die.

**Comment by hannadrehman** [comment]
i am using `lazy` and it still happens? . i followed docs and everything step by step.

**Comment by theKashey** [comment]
Could not ques without example, sorry.

**Comment by hannadrehman** [comment]
i want to add more here. maybe this might help some one. 
so my HMR works now as expected. i get the updates to for what ever was changes,
but suddenly after a delay of 1-2 seconds the whole tree refreshes :/

**Comment by theKashey** [comment]
😅what you did to fix it? What's in the logs?

**Comment by hannadrehman** [comment]
well i updated webpack in the first place.  different configs of webpack like `hot:false` `inline:false`
played with them for sometime untill i start getting warnings that react hot loader started giving error that its not configured properly. 
my final config for dev server is 
```
{
    contentBase,
    compress: true,
    port: env.DEVSERVER_PORT,
    historyApiFallback: true,
    hot: true,
    inline: true,
    overlay: true,
    open: true,
    publicPath: '/',
    proxy: {
      changeOrigin: true,
      '/(api|apiv2|accounts)/**': {
        target: env.PROXY_URL,
        secure: false,
        changeOrigin: true,
      },
      '/(apis)/**': {
        target: 'http://localhost:3000',
        secure: false,
        changeOrigin: true,
      },
    },
  };```
after that it works. i get updates instantly but it refreshes the tree after 5-6 seconds.

**Comment by hannadrehman** [comment]
i finally found what the exact issue was in my app and was able to fix it for now. 
i have a hook which fetches current logged in user by calling some other hook in my app root. 
on every RHL update the effect is getting called which forces it to fetch logged in user. thus refreshing my entire tree because the app will not work if user is not logged in.

```
export function useLoggedInUser() {
  const {
    response: user,
    networkMeta: userApiMeta,
    call: fetchUser, // it will never return a new reference of call. its taken care of.
  } = useNetwork(userApi.getUserProfile);

  useEffect(() => {
  // on every change 
  // fetchUser is getting called again and again, 
    fetchUser();
  }, [fetchUser]);

  useEffect(() => {
    if (
      userApiMeta.status === APP.API_NETWORK_STATUS.SUCCESS &&
      user.username
    ) {
      sentry.setUser(user.username);
      if (clevertap.isCleverTapActive()) {
        clevertap.setUser(user.first_name, user.username);
      }
    }
  }, [user, userApiMeta]);
  return [user, userApiMeta];
}

export default useLoggedInUser;

```
i am not sure why the effect is getting called again and again. 

for now i have simply added an if to prevent it

```
  useEffect(() => {
    if (!user) {
      fetchUser();
    }
  }, [fetchUser, user]);
```

**Comment by theKashey** [comment]
Any `useEffect` with non zero dependency list would be re-executed at HMR. That's the only "safe" way to apply any code changes you might have.

**Comment by hannadrehman** [comment]
thanks @theKashey clearing my doubts. also i think this effect update on HMR should be part of the docs/readme. it surely will confuse people.

**Comment by theKashey** [comment]
It is :) https://github.com/gaearon/react-hot-loader#hook-support
