### ISSUE TITLE
React 16.9.0 support webpack plugin 

### ISSUE THREAD

**Issue by Bnaya** [gaearon/react-hot-loader#1319]
Due to changes in react 16.9, the patch in the webpack plugin no longer works
Also, seems like they baked react-refresh code into react-dom, that is very similar to this code,
So maybe with some tweaks this patch won't be needed at all?

The change:
```js
if (child.tag === Fragment ? element.type === REACT_FRAGMENT_TYPE : child.elementType === element.type)
```
```js
        if (child.tag === Fragment ? element.type === REACT_FRAGMENT_TYPE : child.elementType === element.type || (
        // Keep this check inline so it only runs on the false path:
        isCompatibleFamilyForHotReloading(child, element))) 
```

Related: hot-loader/react-dom#14

**Comment by Bnaya** [comment]
NOTE: master has failing tests,
https://travis-ci.org/gaearon/react-hot-loader/jobs/567475841#L750-L751
But the ci.sh exit with exit code 0 and not 1.

**Comment by theKashey** [comment]
> So maybe with some tweaks this patch won't be needed at all?

Out logic is a bit different. It's possible to change our API to match react expectations, but not quite like this.
