### ISSUE TITLE
Use of react-hot-loader without WebpackDevServer

### ISSUE THREAD

**Issue by balanceiskey** [gaearon/react-hot-loader#132]
Is there a way to use react-hot-loader without the WebpackDevServer and instead use the webpack watch task in node? We kick off our webpack compilation in dev environments like this:

```
webpack(config).watch(200, () => { // some other stuff });
```

I guess my question really centers around how WebpackDevServer knows to re-provision javascript chunks on the page and how I can emulate that behavior for pages loaded via say express or hapi.

**Comment by syranide** [comment]
Reimplementing the features provided by WebpackDevServer is probably a waste of time, personally I just proxy the WebpackDevServer into a path on my regular web server (in my case nginx). I get all the benefits of WebpackDevServer without having to use it to serve other content.

**Comment by balanceiskey** [comment]
Hmmm, that might be a good option. So I guess in dev environments we'd kill this `webpack.watch` approach and just spin up the server. Is this the only/best option?

**Comment by gaearon** [comment]
Also check out https://github.com/glenjamin/webpack-hot-middleware

**Comment by balanceiskey** [comment]
Thanks guys! I'll close out the issue for now as this should do the trick.
