### ISSUE TITLE
RHL breaks important information from React

### ISSUE THREAD

**Issue by kud** [gaearon/react-hot-loader#1325]
### Description

What you are reporting: some error information is missing when RHL is enabled.

I recently had a problem. I forgot to `export default` a component I imported into another one.

And the errors from the console were not so explicit due to RHL.

### Expected behavior

What you think should happen: when I disable RHL, I've got this kind of errors which helps me a lot:

```
 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Element`.
    in Element (created by TextPageMainDivision)
```

or also:

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Element`.
```

### Actual behavior

What actually happens: when I enable RHL, I've got those errors:

`TypeError: "undefined has no properties"` in `backend.js`

or again:

`TypeError: undefined has no properties react-hot-loader.development.js:1229`

which is way less clear.

### Environment

React Hot Loader version: 4.12.11

Run these commands in the project folder and fill in their results:

1.  `node -v`: v12.9.0
2.  `npm -v`: 6.11.1

Then, specify:

1.  Operating system: macOS 10.14.6
2.  Browser and version: Firefox 70.0a1 (2019-08-21) (64-bit)

### Reproducible Demo

I'm sorry, I cannot yet.

**Comment by theKashey** [comment]
Duplicate of #1324

**Comment by kud** [comment]
Thanks!
