### ISSUE TITLE
global is undefined? unable to start RHL

### ISSUE THREAD

**Issue by threepointone** [gaearon/react-hot-loader#133]
I have an express server that serves my html from :3111. I also start a webpack dev server (copied from https://github.com/gaearon/react-hot-boilerplate/blob/master/server.js) on :3000. in my html, I load localhost:3000/script.js

```js
// webpack.config.js
var webpack = require('webpack'),
  path = require('path');

module.exports = {
  devtool: 'eval',
  target: 'web',
  entry: [
    'webpack-dev-server/client?http://0.0.0.0:3000', // WebpackDevServer host and port
    'webpack/hot/only-dev-server',
    './editor/index.js'
  ],
  output: {
    path: path.join(__dirname, 'public'),
    filename: 'editor.js',
    publicPath: '/'
  },
  module: {
    loaders: [{
      test: /\.js$/,
      // exclude: /node_modules/,
      loaders: ['react-hot', 'envify-loader', 'babel-loader']
    }]
  },
  resolve: {
    extensions: ['', '.js', '.jsx']
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ]
};

```

```js
// server.js
import webpack from 'webpack';
import WebpackDevServer from 'webpack-dev-server';
var wconfig = require('./webpack.config');

new WebpackDevServer(webpack(wconfig), {
  publicPath: wconfig.output.publicPath,
  hot: true,
  historyApiFallback: true
}).listen(3000, 'localhost', err => console.log(err || 'webpack at localhost:3000'));
```
It seems to compile alright
<img src='https://i.imgur.com/JdYnUlc.png'/>

When I start the app, it bails almost immediately, saying `Uncaught TypeError: Cannot read property 'WebSocket' of undefined` (because `global` is undefined)
<img src='https://i.imgur.com/ndbxuNv.png'/>

Anything I need to do on my express server/html to make this work?

**Comment by gaearon** [comment]
You'll want to uncomment `exclude: /node_modules/,` because some of the scripts used by hot module replacement machinery will not work with Babel out of the box.

**Comment by threepointone** [comment]
Ok, that helped. I also had to republish disto with compiled files(which I should probably do from now on for modules that I publish), and set up a proxy to the dev server (I used express-http-proxy). Thank you!

**Comment by gaearon** [comment]
>which I should probably do from now on for modules that I publish

Yeah, this is always the easiest way for everybody!

**Comment by leozdgao** [comment]
I meet the same problem. Here is my config:

```
import path from 'path'
import webpack from 'webpack'
import { entryPoint, externals, autoprefixerLoader } from './baseConfig'
import config from '../config'

const webpackDevServerAddress = `http://localhost:${config.webpackDevPort}`
const cssLoaderForDev = `style-loader!css-loader!${autoprefixerLoader}`

export default {
  devtool: 'eval',
  entry: [
    `webpack-dev-server/client?${webpackDevServerAddress}`,
    'webpack/hot/only-dev-server',
    entryPoint
  ],
  externals,
  output: {
    path: process.env['PUBLISHPATH'] || './assets',
    filename: 'bundle.js',
    publicPath: `${webpackDevServerAddress}/assets/`
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ],
  resolve: {
    extensions: [ '', '.js', '.jsx' ]
  },
  module: {
    loaders: [
      { test: /\.jsx?$/, loader: `react-hot-loader!babel-loader`, exclude: '/node_modules' },
      { test: /\.css$/, loader: cssLoaderForDev },
      { test: /\.less$/, loader: `${cssLoaderForDev}!less-loader` }
    ]
  }
}
```

And, yes, my `webpack.dev.config.js`:
```
require("babel-core/register")

module.exports = require('./webpack/webpack.dev')
```

I do not fully understand the solution above...I do not comment the `exclude: '/node_modules'`, and I think I have the uncompiled module in node_modules.

**Comment by gaearon** [comment]
`exclude: '/node_modules'` is wrong.
`exclude: /node_modules/` is correct.

**Comment by leozdgao** [comment]
It works, thanks! :smile:

**Comment by smondal** [comment]
Set the valid target thing for webpack.
```
module.exports = {
  // ...

  target: 'node',
};
```
