### ISSUE TITLE
Cause a serious error in ie11 when use RHL with core-js@3.2.1, babel@7.5.5

### ISSUE THREAD

**Issue by DevAngsy** [gaearon/react-hot-loader#1331]
### Description

For this error, I made a [reproducible demo](https://github.com/DevAngsy/react-ie11), you can enter the build floder and run it by **_serve_**.
According to the **Getting started** of **react-hot-loader**, I wrote a react project, and I want this project is compatible with ie11. Therefore, I put **'import core-js/stable'** in the top of index.js.

##### index.js :
```js
import 'core-js/stable';
import 'regenerator-runtime/runtime';
import './rhlConfig';

import './main';
```

##### main.js :
```js
import React from 'react';
import ReactDom from 'react-dom';

import App from './App';

try {
  ReactDom.render(<App />, document.getElementById('root'));
} catch (error) {
  console.log('error --->', error);
}
```

##### babel-loader config, disabled _useBuiltIns_ option :
![Annotation 2019-09-01 202812](https://user-images.githubusercontent.com/27341089/64076409-2cac7980-ccf7-11e9-884e-b492ece251f1.jpg)

I build this project for **_production_**, open it in ie11 by serve, I got this error(**click to enlarge ^^-^^**):

![Annotation 2019-08-29 222713](https://user-images.githubusercontent.com/27341089/63949176-8f5e0500-caac-11e9-9b05-ae6d3d3acd0a.jpg)

that url :
```code
https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%2C%20_owner%7D&args[]=%20for%20the%20full%20message%20or%20use%20the%20non-minified%20dev%20environment%20for%20full%20errors%20and%20additional%20helpful%20warnings
```

I opened that url that error message mentioned above, but I don't know where the error come from. When I stript **react-hot-loader** from project and rebuild, it works normally in ie11 browserslist.
Or don't import **core-js**, it works normally too. Once I use them simultaneously, that error will appear again.

If set the **useBuiltIns** option to 'usage' and delete the import of **core-js** and **regenerator-runtime/runtime**, because js files don't use any ecmascript method, core-js polyfills were not added, so it works normally in ie11. But ie11 need some polyfill, example: promise, Array.from etc. 
##### 'usage' option and index.js :
![Annotation 2019-09-01 210851](https://user-images.githubusercontent.com/27341089/64076853-c75b8700-ccfc-11e9-9028-45b12530575e.jpg)
![Annotation 2019-09-01 210902](https://user-images.githubusercontent.com/27341089/64076855-ca567780-ccfc-11e9-94aa-4c0b642de018.jpg)
If I prepend the webpack entry array with polyfills that ie11 required, like this :
![Annotation 2019-09-01 211529](https://user-images.githubusercontent.com/27341089/64076928-a47da280-ccfd-11e9-815a-9c32ab89a24e.jpg)
It works in ie11, woot, looks strange...

If set the **useBuiltIns** option to 'entry', that error will appear again.
##### 'entry' option and index.js :
![Annotation 2019-09-01 210736](https://user-images.githubusercontent.com/27341089/64076841-97ac7f00-ccfc-11e9-88f7-9343160e4e89.jpg)
![Annotation 2019-09-01 210757](https://user-images.githubusercontent.com/27341089/64076843-9aa76f80-ccfc-11e9-911d-dc7f4fe09c81.jpg)

### Expected behavior

This react project should work normally with ie11 browser.

### Actual behavior

The try-catch block catch an error.

### Environment

React Hot Loader version: 4.12.12
NodeJs version: 12.9.1
NPM version: 6.11.2
Operating system: Windows10 1903 Pro for WorkStations 64bit
Browser and version: IE 11
Babel/Webpack version: 7.5.5/4.39.3

### Reproducible Demo

[Simple Reproducible Demo](https://github.com/DevAngsy/react-ie11)

**Comment by DEV-YANGS** [comment]
>Note: You can safely install react-hot-loader as a regular dependency instead of a dev dependency as it automatically ensures it is not executed in production and the footprint is minimal.

**This is important**

**Comment by DEV-YANGS** [comment]
Hope to look my **Reproducible Demo**

**Comment by theKashey** [comment]
polifills, core-js included, should be installed before anything else.
> RHL is technically polyfill, so it should be installed before React
```js
// index.js - import everything in the right order
import 'core-js/stable';
import 'regenerator-runtime/runtime';
import './rhlConfig';
import './main';

// main.js - have a clean "real application" code
import React from 'react';
import ReactDom from 'react-dom';

import App from './App';

try {
  ReactDom.render(<App />, document.getElementById('root'));
} catch (error) {
  console.log('Error -->', error);
}
```

**Comment by DEV-YANGS** [comment]
Still have this error in **Reproducible Demo**.

**Comment by theKashey** [comment]
@DEV-YANGS - you have closed the issue because....?

**Comment by DEV-YANGS** [comment]
I want to rewrite a more detailed issues about this error and make a simple reproducible demo.

**Comment by DEV-YANGS** [comment]
And I will reopen this issue.

**Comment by DevAngsy** [comment]
I have modified this issue.

**Comment by DevAngsy** [comment]
@theKashey , I found the solution of this error, just put the 'core-js/stable' and 'regenerator-runtime/runtime' before 'react-hot-loader/patch' in the webpack entry array, like this:

![Annotation 2019-09-13 200423](https://user-images.githubusercontent.com/27341089/64861139-cd892600-d661-11e9-935d-7948479fb88b.jpg)

If import 'core-js/stable' and 'regenerator-runtime/runtime' after 'react-hot-loader/patch', that error will occur.

I think you should add a prompt in the doc temporarily to let developers note this problem.

**Comment by theKashey** [comment]
OOOOOF. I remember this problem.
The best solution I could give you - use as "native" compilation target as possible in dev mode. In that case 99.9% polyfills would mean literally nothing, and would be unable to cause a problem.
