### ISSUE TITLE
views cannot be updated when set alias for 'react-dom' in webpack.base.js

### ISSUE THREAD

**Issue by Heshiyu1996** [gaearon/react-hot-loader#1336]
I set the alias for 'react-dom' in`webpack.base.js`, which makes the views can't be updated when running `history.push('xxxx')` in the production environment, but setting it in `webpack.config.dev.js` only is work well.

### Description

set alias for 'react-dom' 
```js
    resolve: {
        alias: {
            'react-dom': '@hot-loader/react-dom'
        }
    },
```

### Expected behavior

The views can be updated when running `history.push('xxx') ` in the production environment by setting in `webpack.base.js`

### Actual behavior

The views can't be updated when running `history.push('xxx') `  in the production environment by setting in `webpack.base.js`

### Environment

React Hot Loader version:

Run these commands in the project folder and fill in their results:

1.  `node -v`: 8.12.0
2.  `npm -v`: 6.9.0
3. `react`: 16.9.0
4. `react-dom`: 16.9.0
5. `react-hot-loader`: 4.12.11,
6. `@hot-loader/react-dom`: 16.8.6,
Then, specify:

1.  Operating system: macOS Mojave 10.14.4
2.  Browser and version: Chrome 76.0

**Comment by theKashey** [comment]
You haven't provided and valuable information for the problem.
There is also no explanation why `react-dom` and `@hot-loader/react-dom` versions are not the same.
And of course - `history.push('xxx')` has nothing to do with everything above - that's something about your personal code.

**Comment by Heshiyu1996** [comment]
> You haven't provided and valuable information for the problem.
> There is also no explanation why `react-dom` and `@hot-loader/react-dom` versions are not the same.
> And of course - `history.push('xxx')` has nothing to do with everything above - that's something about your personal code.

Sorry...My last description is simply and I try to explain detail again after upgrading my `@hot-loader/react-dom` version.

The webpack's config files in my project have 3 type: `webpack.base.js`、`webpack.config.dev.js`、`webpack.config.prod.js`. 

I add `resolve.alias` in the first file, which will be merged into the 'dev' and 'prod' file when running in different environment.

I add these npm package into my project:
```json
    "devDependencies": {
        "webpack": "^4.39.1",
        "webpack-cli": "^3.3.6",
        "webpack-dev-server": "^3.7.2",
        "webpack-merge": "^4.2.1"
    },
    "dependencies": {
        "@hot-loader/react-dom": "^16.9.0",
        "react": "^16.9.0",
        "react-dom": "^16.9.0",
        "react-hot-loader": "^4.12.11"
    }
```

```js
// src/App.js
import { hot } from 'react-hot-loader/root';
...

export default connect(
    mapStateToProps,
    mapDispatchToProps
)(hot(App));
```

```json
// .babelrc
{
  "plugins": [ "react-hot-loader/babel" ]
}
```

```js
// webpack.base.js
module.exports = {
    resolve: {
        alias: {
            '@': paths.appSrc,
            'react-dom': '@hot-loader/react-dom'
        }
    },
```

```js
// webpack.config.dev.js
const merge = require('webpack-merge');
const webpack = require('webpack');
const baseWebpackConfig = require('./webpack.base');

const webpackConfig = merge(baseWebpackConfig, {
    mode: 'development',
    cache: true,
    devtool: 'source-map',
    plugins: [new webpack.HotModuleReplacementPlugin()],
    devServer: {
        overlay: true,
        hot: true
    }
});

module.exports = webpackConfig;
```

According the above config, I find the dom can't update when running `history.push('xxx')`, which just is like no change, but the route is modified into the new one.

**Comment by theKashey** [comment]
> The webpack's config files in my project have 3 type: webpack.base.js、webpack.config.dev.js、webpack.config.prod.js.

Does not matter

> I add resolve.alias in the first file, which will be merged into the 'dev' and 'prod' file when running in different environment.

does not matter

> I add these npm package into my project:

does not matter

```
export default connect(
    mapStateToProps,
    mapDispatchToProps
)(hot(App));

// SHOULD BE 
const RealApp = connect(
    mapStateToProps,
    mapDispatchToProps
)(App);

export default RealApp
```

> // .babelrc

does not matter

> // webpack.base.js

does not matter

> when running history.push('xxx')

Sorry - I would be not as polite, as I should, but WTF is `history.push('xxx')`? As I mentioned above - this is something specific to your own codebase, something you created.
Does it connected to a react-router? Another router? No router? Who listens to a change? What all this have in common with HotModuleReplacement, and long your application is just broken?

What you have to remove to fix it? When it broke? That is the __REAL__ reason.
Try to find it. And I could not help you with this quest, sorry.

**Comment by Heshiyu1996** [comment]
`"react-router-dom": "^5.0.1"`

I am using react-router-dom in my project, and  `history.push('xxx')` is a function for routing. 
I used to configure my webpack to alias `@hot-loader/react-dom` ,  which makes it build into production code.

I solved the problem:
1/ use `yarn add react-dom@npm:@hot-loader/react-dom` rather then set alias in webpack conf.

2/ configure alias in dev mode only.

emm..this is my first time to comment a issue, and thank you for your understand and thought:)

**Comment by Heshiyu1996** [comment]
> > The webpack's config files in my project have 3 type: webpack.base.js、webpack.config.dev.js、webpack.config.prod.js.
> 
> Does not matter
> 
> > I add resolve.alias in the first file, which will be merged into the 'dev' and 'prod' file when running in different environment.
> 
> does not matter
> 
> > I add these npm package into my project:
> 
> does not matter
> 
> ```
> export default connect(
>     mapStateToProps,
>     mapDispatchToProps
> )(hot(App));
> 
> // SHOULD BE 
> const RealApp = connect(
>     mapStateToProps,
>     mapDispatchToProps
> )(App);
> 
> export default RealApp
> ```
> 
> > // .babelrc
> 
> does not matter
> 
> > // webpack.base.js
> 
> does not matter
> 
> > when running history.push('xxx')
> 
> Sorry - I would be not as polite, as I should, but WTF is `history.push('xxx')`? As I mentioned above - this is something specific to your own codebase, something you created.
> Does it connected to a react-router? Another router? No router? Who listens to a change? What all this have in common with HotModuleReplacement, and long your application is just broken?
> 
> What you have to remove to fix it? When it broke? That is the **REAL** reason.
> Try to find it. And I could not help you with this quest, sorry.

"react-router-dom": "^5.0.1"

I am using react-router-dom in my project, and history.push('xxx') is a function for routing.
I used to configure my webpack to alias @hot-loader/react-dom , which makes it build into production code.

I solved the problem:
1/ use yarn add react-dom@npm:@hot-loader/react-dom rather then set alias in webpack conf.

2/ configure alias in dev mode only.

emm..this is my first time to comment a issue, and thank you for your understand and thought:)

**Comment by theKashey** [comment]
Concluding what you've said - `@hot-loader/react-dom` + `webpack-aliases` are not working in production mode. However `yarn add react-dom@npm:@hot-loader/react-dom` and just `react-dom` does work well.

**Comment by Heshiyu1996** [comment]
> Concluding what you've said - `@hot-loader/react-dom` + `webpack-aliases` are not working in production mode. However `yarn add react-dom@npm:@hot-loader/react-dom` and just `react-dom` does work well.

yes, that's right.
After that I read the detai from your other README.md, I know the reason.
[https://github.com/hot-loader/react-dom](https://github.com/hot-loader/react-dom)

**Comment by theKashey** [comment]
Why?

**Comment by Heshiyu1996** [comment]
> Why?
In sub title(<<Rewire>>), you wrote that `You may set configuration to only use react-🔥-dom only in dev mode.`
So I guess the reason is that I set the configuration in production mode after building, because I 
set the `webpack-aliases` in `webpack.config.base.js` which will be merge into `webpack.config.prod.js`.
