### ISSUE TITLE
Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by zhaohuanyuu** [gaearon/react-hot-loader#1341]
### Description

i have installed @hot-loader/react-dom and configured webpack resolve alias , then use react-redux connect component occurred error.but normal when I don't use react-hot-dom

### Expected behavior

work fine

### Actual behavior

The above error occurred in the <ConnectFunction> component:
    in ConnectFunction (created by HotExportedConnect(App))
    in AppContainer (created by HotExportedConnect(App))
    in HotExportedConnect(App)
    in Provider

### Environment

React: 16.8.6 / 16.9.0
React-dom: 16.8.6 / 16.9.0
@hot-loader/react-dom: 16.8.6 / 16.9.0
React Hot Loader version:  4.12.13

### Reproducible Demo
npm install
npm start
https://github.com/zhaohuanyuu/hooks-with-hot-loader

**Comment by theKashey** [comment]
It seems to me that that problem is DLL plugin, and aliasing was not defined for it. 
Please try to use `webpack loader` provided, to apply the patch in a different way, or give a try to [React Fast Refresh](https://github.com/facebook/react/issues/16604#issuecomment-531520900)

**Comment by zhaohuanyuu** [comment]
> It seems to me that that problem is DLL plugin, and aliasing was not defined for it.
> Please try to use `webpack loader` provided, to apply the patch in a different way, or give a try to [React Fast Refresh](https://github.com/facebook/react/issues/16604#issuecomment-531520900)
thank you very much

**Comment by zhangwilling** [comment]
you mean we should also set the alias(`'react-dom': '@hot-loader/react-dom'`) in webpack.dll.config.js ?
你是指我们还需要在dll中指定alias(`'react-dom': '@hot-loader/react-dom',`)？

**Comment by zhangwilling** [comment]
`Please try to use webpack loader provided` means (react-hot-loader-loader)[https://github.com/NoamELB/react-hot-loader-loader]?
