### ISSUE TITLE
render never called after a hot reload - how do I debug this

### ISSUE THREAD

**Issue by RobertGary1** [gaearon/react-hot-loader#1346]
# # Expected behavior
The render method should be called after a component is updated. I can see that the source code as been updated but if I put a break point on render() its never called. The DOM does not update correctly.
What you think should happen:

### Actual behavior

What actually happens:

### Environment

React Hot Loader version:
4.12.13
Run these commands in the project folder and fill in their results:

1.  `node -v`:
v10.16.3
2.  `npm -v`:
6.9.0
Then, specify:

1.  Operating system:
Chrome

**Comment by theKashey** [comment]
Could you please try `4.12.12`? It might be #1342

**Comment by RobertGary1** [comment]
No, I'm still seeing it. Oddly I see the console log that its updating. And if I look at the source code in the browser its correctly updated. Its just not calling the render to update the DOM. This was working before, I must have messed up some configuration.

**Comment by RobertGary1** [comment]
I fixed it In index.js I changed
import {App} from './App';
to 
import App from './App';

My guess is that it was loading the class App directly bypassing the default export of 
export default hot(module)(App);

**Comment by theKashey** [comment]
So you were using _not-warmed_ App... It should work, but as long as there is no `AppContainer` around the `App` - the _deep force update_ was not called, causing your issue.
