### ISSUE TITLE
Cannot get react-hot-loader to work with babel 7

### ISSUE THREAD

**Issue by neberej** [gaearon/react-hot-loader#1351]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

I can't get `react-hot-loader` to work with Babel 7

### Expected behavior

React-hot-loader should work as intended. Changing a component should reflect in realtime.

### Actual behavior

Terminal console shows: 'Compiled Successfully'
Browser console shows:  `Ignored an update to unaccepted module`

### Environment

React Hot Loader version: 8

Run these commands in the project folder and fill in their results:

1.  `node -v`: 10.16.3
2.  `npm -v`: 6.9.0

Then, specify:

1.  Operating system: Both Windows and Mac
2.  Browser and version: Chrome

### Reproducible Demo

https://github.com/neberej/react-seed

---

Some more context:

babel.config.js

```
module.exports = {
  presets: ["@babel/preset-react", ["@babel/preset-env", {"modules": "commonjs"}]],
  plugins: ["react-hot-loader/babel"]
};
```

webpack.config.js

```
entry: ['webpack/hot/dev-server', 'webpack-hot-middleware/client', './src/index'],
...
loaders: ['react-hot-loader/webpack', 'babel-loader']
```

Terminal throws:

```
Compiled successfully
```

Browser console throws:
```
Ignored an update to unaccepted module ./src/js/Home.js -> ./src/index.js
The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See https://webpack.js.org/concepts/hot-module-replacement/ for more details.
```

Refreshing the page (F5) shows the update.

I have been unsuccessfully trying to get this to work for few days now. Some suggestions/help would be highly appreciated.

**Comment by theKashey** [comment]
You have to __accept__ the update. Usually by wrapping an export of some module (like `Home.js`) with `hot`. Without Hot-Module-Replacement properly established RHL will do nothing. 

You have misses one, very important, step.

**Comment by neberej** [comment]
@theKashey Thanks Anton. That helped. 

I also had to add `react-hot-loader/patch` on my webpack entry.

**Comment by theKashey** [comment]
> I also had to add react-hot-loader/patch on my webpack entry.

And that's not a requirement anymore, just good to have.
