### ISSUE TITLE
Confusing instructions for RHL setup

### ISSUE THREAD

**Issue by mohsinulhaq** [gaearon/react-hot-loader#1360]
The current documentation about setting up RHL is a bit confusing:

2.  Mark your root component as _hot-exported_:

```js
// App.js
import { hot } from 'react-hot-loader/root';
const App = () => <div>Hello World!</div>;
export default hot(App);
```

3.  Make sure `react-hot-loader` is required before `react` and `react-dom`:

* or `import 'react-hot-loader'` in your main file (before React)
* or prepend your webpack entry point with `react-hot-loader/patch`, for example:
  ```js
  // webpack.config.js
  module.exports = {
    entry: ['react-hot-loader/patch', './src'],
    // ...
  };
  ```

Now if I follow the second step then obviously I have to import this component in some other file and render it using React DOM. So I can't import RHL before both React and ReactDOM, as mentioned in the third step.
Please clarify the steps for me. They already changed a lot in the past year or so.

**Comment by theKashey** [comment]
```js
// App.js
import { hot } from 'react-hot-loader/root';
const App = () => <div>Hello World!</div>;
export default hot(App);

//  index.js
import "react-hot-loader"; // imported "before react"
import ReactDOM from "react-dom"; // does not matter which "react"
import "./App.js"

ReactDOM.render(<App/>....)
```
The import order is not "per file", it's "per project". Feel free to import RHL as often as you need, but try to keep "the first" import "before React".
