### ISSUE TITLE
Suppress trackTailUpdates if 'true' passed

### ISSUE THREAD

**Issue by brandon-pereira** [gaearon/react-hot-loader#1386]
The docs say `The warning is informational - it is a notice that this tail update logic is triggered, and does not indicate a problem in the configuration or usage of react-hot-loader.`. I have a team of developers working with me, I'm managing the SSR/HMR setup. I don't think every developer should need to know about the inner works of a HMR. Ideally, I can set setConfig({ trackTailUpdates:true }). to suppress the out-of-bounds warning since it's just informational and not an issue with the configuration. I'd like to keep our console logs to a minimal.

Discussion also happening here: #1368

Opening a new issue to track when I create a PR

**Comment by theKashey** [comment]
Fixed in `4.12.16`, to see this message again one should change log level to `warn`
