### ISSUE TITLE
Reload without webpack-dev-server client modules

### ISSUE THREAD

**Issue by cadorn** [gaearon/react-hot-loader#139]
I am a tooling dev. I want to use this project to add hot reloading for jsx for webpack on the server but use my own client code instead of the socket.io based webpack hot reload client code that signals `react-hot-loader`.

Where is the `react-hot-loader` interface that the socket.io based webpack hot reload client code uses exposed? I am hoping to call this myself directly when I get a change notification through my own change notification system.

**Comment by gaearon** [comment]
Hey! React Hot Loader works on top of Webpack's Hot Module Replacement interface (`module.hot`). AFAIK it's [implemented in transport-agnostic way](https://github.com/webpack/webpack/blob/bac9b48bfb0f7dd9732f2faafb43ebb22ee2a2a7/lib/HotModuleReplacement.runtime.js), so the actual transport is only referenced here:

https://github.com/webpack/webpack-dev-server/blob/8e8f540b2f7b35f7b6c3ce616a7fd2215aaa6eea/client/index.js#L64-L67 (listens to Socket.io for hot updates and calls `postMessage`)

This message will be picked up (again, in transport-agnostic way) by this “hot server” that is a thin wrapper over HMR API:

https://github.com/webpack/webpack/blob/bac9b48bfb0f7dd9732f2faafb43ebb22ee2a2a7/hot/only-dev-server.js#L59-L67

Does this help?

**Comment by cadorn** [comment]
I think I am getting closer. When I run:

`window.postMessage("webpackHotUpdatedf943cf06be4efe7882a", "*");`

I get a 404 for http://localhost:8082/webpack/df943cf06be4efe7882a.hot-update.json if the hash is invalid (expected). Or it seems to find it (if I used previous hash before modification) but nothing gets reloaded on client.

The hot file being loaded does have one entry in it `{"h":"49d286bd194695484a4b","c":[0]}`

So it appears the client is not refreshing something?

**Comment by cadorn** [comment]
So it appears I had my paths wrongly configured and thats why I got the 404. It seems to trigger the hot reloader now. Thanks!
