### ISSUE TITLE
4.12.16 React Type Declarations are overriding project configuration

### ISSUE THREAD

**Issue by r0skar** [gaearon/react-hot-loader#1391]
### Description

While starting up my project today, I noticed that my own JSX types dont work anymore (I am not using React). I am using the babel plugin [jsx-dom-expressions](https://github.com/ryansolid/babel-plugin-jsx-dom-expressions), which comes with their own JSX typings. However these are now in conflict with `@types/react` and `tsc` throws hundredths of errors. Unfortunately, TS is [not yet able to exclude a specific dts file](https://github.com/microsoft/TypeScript/issues/18588). This is related to the changes in https://github.com/gaearon/react-hot-loader/issues/1359. Any chance this change could be reverted so that we can again use react-hot-loader in a project where the JSX is not compiled by React?

### Environment

React Hot Loader version: 4.12.16

Run these commands in the project folder and fill in their results:

1.  `node -v`: v12.13.0
2.  `npm -v`: 6.12.1
3.  `yarn -v`: 1.19.1

**Comment by theKashey** [comment]
Look like #1359 was not a great idea

**Comment by theKashey** [comment]
4.12.17 released
