### ISSUE TITLE
How to Hot Reload when .env file changes are occurred?

### ISSUE THREAD

**Issue by skirankumar7** [gaearon/react-hot-loader#1392]
How to Reload when .env file changes are occurred?

currently, Need to stop webpack server and need to start again better if we were able to catch .env file changes and hot reload.

Any ideas, suggestions?
Thanks in Advance.

**Comment by theKashey** [comment]
https://youtu.be/J3GqBkw6ebk - advice #6 - __use nodemon__. This issue is 100% related to webpack, and webpack only.
