### ISSUE TITLE
Would it be possible to customize the "hot update was not successful" error CSS?

### ISSUE THREAD

**Issue by ndbroadbent** [gaearon/react-hot-loader#1396]
### Description

I would like to fix the `⚛️🔥😭: hot update was not successful` errors in my app, because there is some conflicting CSS (buttons, list items), and it's hidden behind my app header (due to `position: fixed`.)

<img width="1280" alt="Screen Shot 2019-11-22 at 6 41 27 PM" src="https://user-images.githubusercontent.com/139536/69423036-bc425100-0d57-11ea-99ce-fc12bc5715b6.png">

*(This is an expected bug in my own code, and not a problem with `react-hot-loader`. I just want to fix the CSS to make the error message look nicer.)*

I found [the source code for this error message](https://github.com/gaearon/react-hot-loader/blob/125b213aa03cfa0baea22420987efc412e0caf07/src/errorReporter.js), but I can't see any way to modify the CSS and make it look better in my app.

### Expected behavior

CSS should be customizable with class names, instead of inline styles.

### Actual behavior

CSS cannot be customized, because react-hot-loader adds inline styles that cannot be overidden.

**Comment by ndbroadbent** [comment]
Fixed with some `!important` CSS rules:

<img width="1280" alt="Screen Shot 2019-11-22 at 6 56 58 PM" src="https://user-images.githubusercontent.com/139536/69423903-e432b400-0d59-11ea-995e-e8629b8cf621.png">

SCSS:

```

.react-hot-loader-error-overlay {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen,
    Ubuntu, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
  font-size: 12px;
  z-index: 10000;

  & > div {
    top: 45px !important;
    padding: 25px !important;
  }

  ul > li {
    list-style-type: none;
    & > span {
      left: 25px !important;
    }
    & > p {
      margin-left: 25px;
    }
  }

  h2 {
    font-size: 21px;
  }

  button {
    padding: 8px 15px;
    margin-left: 15px;
    font-size: 12px;
    vertical-align: middle;
    margin-top: 15px;
  }
}
```

**Comment by theKashey** [comment]
Got anything to contribute into the HotLoader code?
