### ISSUE TITLE
redux store lost

### ISSUE THREAD

**Issue by SingedLL** [gaearon/react-hot-loader#1401]
### Description
```js
import React, { Fragment } from 'react';
import { connect } from 'react-redux';
import { injectIntl } from 'react-intl';
import { Button } from 'antd';

import { getDetail } from '../get-detail-actions';

class Detail extends React.Component {
  constructor(props) {
    super(props);

  }

  componentDidMount() {
    this.props.getDetail()
  }

  render() {
    const {
      intl: { formatMessage },
      detail,
    } = this.props;

    return (
      <div>{detail.name}</div>
    );
  }
}

export default injectIntl(connect(
  ({ detail }) => ({ detail: detail,}), {getDetail},
)(Detail));
```

when I refresh,  this.props.detail become undefined.

React Hot Loader version: 4.12.18

Run these commands in the project folder and fill in their results:

1.  `node -v`: v12.8.1
2.  `npm -v`: 6.10.2

**Comment by theKashey** [comment]
the problem is not here. 
Try to figure out what is happening with the `store` itself, and is it "above" the `hot` method, so is not affected by the code update.

There is an information in the console about which files are replaced during the update, the file you are creating store(or it's parent) should not be in that list.

**Comment by SingedLL** [comment]
I guess it has something to do with higher-order components。

`import React, { Component } from 'react';
import { Route, Switch, Redirect } from 'react-router';
import loadable from '@loadable/component';
import Layout from '../layout';

const BDetail = loadable(() => import('./a-detail.jsx'));
const ADetail = loadable(() => import('./b-detail.jsx'));

class DetailContainer extends Component {

  render() {
    const {
      match: { path },
    } = this.props;

    return (
      <Layout showFooter={false}>
        <Switch>
          <Route
            exact
            path={path}
            component={ADetail}
          />
          <Route
            exact
            path={path}
            component={BDetail}
          />
          <Redirect from="/" to={path} />
        </Switch>
      </Layout>
    );
  }
}

export default DetailContainer;
`

**Comment by theKashey** [comment]
`loadable` is not quite RHL friendly, but that should not be a reason.
