### ISSUE TITLE
Hot Loader + Redux = full app refresh and lost redux state

### ISSUE THREAD

**Issue by yourfavorite** [gaearon/react-hot-loader#1403]
I'm trying to put together a boilerplate for kicking off electron apps I want to make. I've pulled some pieces from others and have it mostly working but I'm running into trouble getting hot reloading working.

### Description

What you are reporting:
Typescript + Redux causes changes to reload entire app and destroy Redux Store.

### Expected behavior

What you think should happen:
Individual component should re-render and Redux Store should stay in tact.

### Actual behavior

What actually happens:
Entire app is re-rendered and Redux Store is reset.

### Environment

React Hot Loader version: 4.12.18

Run these commands in the project folder and fill in their results:

1.  `node -v`: 10.16.0
2.  `npm -v`: 6.10.3

Then, specify:

1.  Operating system: Mac
2.  Browser and version: Electron 7.1.1

### Reproducible Demo

I've pushed the boilerplate here: https://github.com/yourfavorite/yf-boilerplate

Specifically I ran into a snag with the normal use of hot.accept(). If I pass in the expected arguments to that function then I get no hot reloading. However if I call hot.accept() without any arguments, hot reloading works but breaks redux and seems to reload the entire app instead of just the modified component.

```
// Hot reloading
if (module.hot) {
  // For some reason this causes DOM updates to fail
  // module.hot.accept('./App', () => render());

  // But this works?
  module.hot.accept();
}
```

**Comment by theKashey** [comment]
I would propose wrap export of `App` with `hot` provided by RHL.
In your case the file with `store` creation (`configureStore`) is also being updated, and everything you need - move "update boundary" a bit lower.

**Comment by yourfavorite** [comment]
Thanks @theKashey Any chance you could provide a little more detail around the execution of this? I tried wrapping the export of `App` with `hot` as `export default hot(App);` but this then causes type errors inside of `index.tsx`

```TS2605: JSX element type '{ history: History<any>; }' is not a constructor function for JSX elements.
  Type '{ history: History<any>; }' is missing the following properties from type 'Element': type, props, key```

**Comment by yourfavorite** [comment]
Did some more digging. If I run the following example as is and open it in my browser, hot reload works. However if I copy the TSX and Store for that project into my boilerplate, the code functions but does not hot reload.

Changing this:
```
// Hot reloading
if (module.hot) {
  // Reload components
  module.hot.accept('./App', () => {
    render();
  });
}
```

To this:
```
// Hot reloading
if (module.hot) {
  // Reload components
  module.hot.accept();
}
```

Gets hot reloading working, but once again it clears state as it seems to just refresh the entire page. I'm wondering if this is an issue with my setup or a compatibility issue with electron-forge?

**Comment by theKashey** [comment]
Additionally you are not using nor `react-hot-loader/babel`, nor `react-hot-loader/webpack`/`@hot-loader/react-dom`.
And yet again -  do not "accept" the update in the file you have your store created. Move `module.hot.accept()` to the `App.tsx` level.

Right now it's expected not to work, as long as almost all requirements are not met.

**Comment by yourfavorite** [comment]
Thanks @theKashey. I've got some more work to do on it and I appreciate the guidance.

**Comment by ezos86** [comment]
Was there ever a solution for this, I have same issue, my hot reload is in my App.tsx and uses the module.hot.accept() but still loses all state when it happens, I have to manually refresh page, which defeats the hot reload purpose.. haha

**Comment by yourfavorite** [comment]
@ezos86 
TBH, I don't really remember where I ended up on this one since it was quite a while ago. Additionally, a lot has changed in the time that has passed. You should probably take a look at React Fast Refresh solutions instead of react-hot-loader for now.
