### ISSUE TITLE
Babel plugin breaks tree-shaking  in production

### ISSUE THREAD

**Issue by sHooKDT** [gaearon/react-hot-loader#1406]
Enabling `react-hot-loader/babel` plugin in production could break tree shaking.

### Expected behavior

Babel plugin leaves minimal footprint in production as said in README.

### Actual behavior

I haven't dived so deep, but as far as I understood:

1. babel plugin injects some helper method in code that uses class components
2. webpack's ModuleConcatenationPlugin bails out of optimization due to `eval` usage
3. **This breaks tree shaking for the module and for the whole dependency subtree** (?)

The piece of code injected to classes: 
```
  // @ts-ignore
  _proto.__reactstandin__regenerateByEval = function __reactstandin__regenerateByEval(key, code) {
    // @ts-ignore
    this[key] = eval(code);
  };
```

So the fact is: with babel plugin enabled during production build, modules are not being concatenated and many dependencies are not tree-shaked which leads to higher bundle size.

### Environment

RHL - 4.12.12
@babel/core - 7.5.5
webpack - 4.41.2

**Comment by sHooKDT** [comment]
It seems that I've found the root of evil. I was using webpack with `mode: production`, but without explicitly setting NODE_ENV to production, because I believed it's set automatically for everything used under the hood.

With production mode explicitly set this plugin work correctly. Sorry for opening the issue!

**Comment by theKashey** [comment]
However you are right - dev mode would prevent module concatenation (by using `module` variable), as well as "registering" all functions causing "side effects".
