### ISSUE TITLE
Use @babel/runtime-corejs3 and react-hot-loader make bundle bigger

### ISSUE THREAD

**Issue by rainydayDY** [gaearon/react-hot-loader#1407]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

.babelrc
{
  "presets": [
    [
      "@babel/preset-env"
  ],
  ["@babel/preset-react"]
],
  "plugins": [
      [
          "@babel/plugin-transform-runtime", {
            "helpers": true,
            "corejs": 3,
            "regenerator": true
          }
      ],
      ["@babel/plugin-proposal-decorators", { "legacy": true }],
      ["@babel/plugin-proposal-class-properties"],
      ["react-hot-loader/babel"]
  ]
}

### Expected behavior

use webpak and babel7 can make bundle smaller than before

### Actual behavior

the variable‘s name in chunk is so long ,like this：
【_babel_runtime_corejs3_core_js_stable_set_timeout__WEBPACK_IMPORTED_MODULE_0___default】
process.env.NODE_ENV="production"

### Environment
production
React Hot Loader version: 4.12.18

Run these commands in the project folder and fill in their results:

1.  `node -v`: v8.14.1
2.  `npm -v`: 6.4.1

Then, specify:

1.  Operating system:  doesn't effect
2.  Browser and version: doesn't effect

### Reproducible Demo

Please take the time to create a new project that reproduces the issue.

You can copy your project that experiences the problem and start removing things until you’re left with the minimal reproducible demo. This helps contributors, and you might get to the root of your problem during that process.

Push to GitHub and paste the link here.

**Comment by theKashey** [comment]
> use webpack and babel7 can make bundle smaller than before

Well, who said that?

> the variable‘s name in chunk is so long ,like this：

The variable name is created by `webpack`, and then __expected to be minimized__ by `terser`. Probably production mode was not properly enabled.

In the meantime I could ensure you - `react-hot-loader/babel` in production mode does __nothing__, except removing itself from the code. So it's theoretically impossible to cause any issues to your codebase.

Setting `NODE_ENV="production"` is NOT ENOUGHT to enable production mode. You should also change `mode` in webpack config, as well as provide the proper `ENV` using different plugins. Refer to documentation and have a happy new year.
