### ISSUE TITLE
Hot-update.json 404 not found

### ISSUE THREAD

**Issue by simkessy** [gaearon/react-hot-loader#1408]
Trying to get hot reload working but the hot-update.json file is served on post 10005 ( can access directly) while my app is on port 8080. So when it tries to load it it tries on post 8080 and fails. I'm trying to figure out how to get these things working together but i'm not seeing how. The proxy setting hasn't helped at all. 

```
module.exports = Object.assign(baseConfig, {
  mode: 'development',
  devtool: 'cheap-module-eval-source-map',
  devServer: {
    allowedHosts: ['.ec2.pin100.com'],
    // 0.0.0.0 binds to all interfaces. The public port is 8080 which is served
    // by nginx and proxied to the internal webpack port of 10005.
    host: '0.0.0.0',
    port: 10005,
    hot: true,
    hotOnly: true,
    // https: true,
    publicPath: '/',
    contentBase: ['./src', './public'],
    // headers: {
    //   'Access-Control-Allow-Origin': '*'
    // },
    // disableHostCheck: true
    proxy: {
      '/hot-update.{json, js}': {
        target: '0.0.0.0:10005',
        secure: false
      }
    }
  }
});
```

**Comment by theKashey** [comment]
Sorry, but this question should be asked for `webpack`, not `react-hot-loader`. Out job starts a bit later.

**Comment by simkessy** [comment]
Well do you see if I'm doing anything wrong?

**Comment by theKashey** [comment]
Yes, you are doing something wrong - you are using complex setup without proper understanding how it works, why it broke, and how to fix it.
I have no idea what 50% of this variables do, and never tried to use them. So, sorry - there is no way I could help you.
