### ISSUE TITLE
How to remove RHL from Create React App

### ISSUE THREAD

**Issue by ORESoftware** [gaearon/react-hot-loader#1424]
Looking forward to new iterations of these kinds of tools. I see the deprecation notice  - it looks like CRA comes with RHL out of the box. For now I just want to use HMR without RHL. Is there a way to remove RHL from CRA without ejecting?

On a side note - is there a section on how to hook into RHL cycles/state? For example, when a change is detected, when it's recompiling, attempts to re-render, and then finishes re-rendering?

//  CRA = create react app, RHL = react hot loader

**Comment by theKashey** [comment]
`RHL` __never__ was a part of `CRA`. It always was just a pure `HMR` and nothing else.

> On a side note - is there a section on how to hook into RHL cycles/state?

There is no such API export both externally and internally.
