### ISSUE TITLE
Error when try to install this package: "React.createElement: type is invalid"

### ISSUE THREAD

**Issue by macabeus** [gaearon/react-hot-loader#1426]
### Description

I'm trying to add this package on my project, but I'm receiving the following error:
> react.development.js:167 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

But my project works fine before to try to add RHL. And adding a `console.log` one line before the error I can see that my component really exist:

![image](https://user-images.githubusercontent.com/9501115/75360864-501f3e00-58ae-11ea-9e64-e047b662a120.png)

I'm using ES6 modules and the babel's presets `@babel/preset-env` and `@babel/preset-react`.

I tried to follow the entire step on readme, but I'm always receiving this error. So I tried again to follow the setup from begin, so I noticed that I receive this error just adding the package, even that I didn't change anything on the code! Just using that:

```
yarn workspace front add react-hot-loader -E
```

### Expected behavior

It should work.

### Actual behavior

It isn't working. I'm receiving the exception `React.createElement: type is invalid` just adding the package on my project.

### Environment

1. React Hot Loader version: 4.12.19
2. `node -v`: v11.10.1
3.  `npm -v`: 6.7.0
4.  Operating system: macOS
5.  Browser and version: Chrome 79.0.3945.130

**Comment by macabeus** [comment]
It isn't look like an error on RHL. I just removed my `node_modules` and installed again that, and now I can run my application.
I don't know why it happened.

**Comment by theKashey** [comment]
`React.createElement: type is invalid`....(and the second part)`recieved undefined`.
Sometimes installing new packages breaks stuff and you have at least to rerun the build, sometimes clearing a (babel?) cache. The cache is stored in `node_modules/.cache`

RHL itself is not able to break your app in such way.

**Comment by macabeus** [comment]
@theKashey Yeah. I really don't know why, but for some reason, I need to add the packages on `package.json`, install that, remove the cache, and build again. Otherwise I'll receive this error.

**Comment by theKashey** [comment]
🤞
