### ISSUE TITLE
Static variables in TypeScript overwritten on hot reload

### ISSUE THREAD

**Issue by bladeSk** [gaearon/react-hot-loader#1427]
When using static class variables in TypeScript, the variables get overwritten on a hot reload. This breaks code where preserving the contents of static variables is important. In the repro case below, which is just a slightly modified [demo project](https://github.com/gaearon/react-hot-loader/tree/master/examples/typescript), it gets even weirder and the static variable does not change _at all_ once hot-reloaded. 🤔

### Reproducible Demo

https://github.com/bladeSk/rhl-ts-static-bug - the bug occurs in [src/BuggyStaticCounter.tsx](https://github.com/bladeSk/rhl-ts-static-bug/blob/master/src/BuggyStaticCounter.tsx)

I also tried `private static globalCount?: number` instead of `private static globalCount = 0`, but it has the same effect, the only difference being the variable initialized to `undefined` instead of a `0`.

**Comment by theKashey** [comment]
🤷‍♂️ Don't use ClassComponents, it's very hard to support them or don't use react-hot-loader - see the deprecation notice for this project. [React-fast-refresh](https://github.com/facebook/react/issues/16604) solves this problem from a bit different angle, but solves.
