### ISSUE TITLE
Possible to force http protocol?

### ISSUE THREAD

**Issue by jasondonnette** [gaearon/react-hot-loader#1429]
### Description

I am running a webpack-dev-server set up with `react-hot-loader` on http://localhost:8181 and working on an app where the dev environment is set up such that the app is loaded on a URL with the `https` protocol. This gives me a `ERR_SSL_PROTOCOL_ERROR` error:

![image](https://user-images.githubusercontent.com/823765/75938322-54160780-5e3c-11ea-8a89-e22972bd5144.png)

Is it possible to configure react-hot-loader to use a certain protocol? (eg: `http` in my case, but I imagine other scenarios may want need to enforce `https`).

I currently have `react-hot-loader` set up with the normal babel plugin configuration. It works well when loading it standalone at http://localhost:8181.

**Comment by theKashey** [comment]
`React-Hot-Loader` is not using anything except "React" - that's all about `webpack-dev-server` configuration.
Sorry, but I cannot help you.
