### ISSUE TITLE
configuration warning if app never rendered

### ISSUE THREAD

**Issue by glenjamin** [gaearon/react-hot-loader#143]
This one had me confused for a bit!

I got this warning:
> It appears that React Hot Loader isn't configured correctly. If you're using NPM, make sure your dependencies don't drag duplicate React distributions into their node_modules and that require("react") corresponds to the React instance you render your app with. If you're using a precompiled version of React, see https://github.com/gaearon/react-hot-loader/tree/master/docs#usage-with-external-react for integration instructions.

Which sent me off checking for duplicate Reacts, but in fact I had just never triggered an initial render of the application!

Do you think this is detectable? maybe looking for any element with a data-reactid or something?

**Comment by gaearon** [comment]
This is not going to be an issue in next versions. They will be based on [react-hotify](https://github.com/gaearon/react-hotify) that doesn't have a dependency on `ReactMount`. So I don't plan to fix it in 1.0.

**Comment by gaearon** [comment]
We won't have this limitation in the next beta release coming soon.
Stay tuned.

**Comment by gaearon** [comment]
Can I ask you to check whether `react-hot-loader@2.0.0-alpha` solves this issue?
Please provide any feedback on it in this PR: https://github.com/gaearon/react-hot-loader/pull/182

**Comment by glenjamin** [comment]
Seems to be fixed :+1:
