### ISSUE TITLE
Next Hot Loader

### ISSUE THREAD

**Issue by lucasconstantino** [gaearon/react-hot-loader#1437]
Creating this issue to ~promote~ introduce a project intended to facilitate use of `react-hot-loader` on existing Next.js application, for those who desperately need it.

https://github.com/lucasconstantino/next-hot-loader

**Refer:**
https://github.com/zeit/next.js/issues/4494

**Comment by theKashey** [comment]
> It might soon be deprecated in favour of Fast Refresh;

Probably it would be a better idea to :justdoit: 😅

**Comment by theKashey** [comment]
NextJS did it - https://nextjs.org/blog/next-9-4#fast-refresh
