### ISSUE TITLE
Step 1 (of 3): Enabling Hot Module Replacement (HMR), how to config? - I use Babel.transform

### ISSUE THREAD

**Issue by JieChang** [gaearon/react-hot-loader#1441]
how to config? - I use Babel.transform

**Comment by theKashey** [comment]
Hot Module Replacement is a feature of a bundler. Webpack, Parcel and so on.
Refer to their documentation.
- https://webpack.js.org/concepts/hot-module-replacement/
- keep in mind Parcel did  implement FastRefresh and does not require RHL.

**Comment by JieChang** [comment]
![image](https://user-images.githubusercontent.com/8551885/79851738-4e7a7e00-83f8-11ea-9250-c16dea73feb3.png)
Babel.transform(code, {
    presets: ['es2015', 'react'],
    plugins: ['react-hot-loader/babel'],
  })
I use Babel not Webpack - Browser real-time compilation

**Comment by theKashey** [comment]
You definitely not doing that - if you are able to run babel in the browser, then you don't need babel, and you are doing something wrong.

If you are trying to `plugins: ['react-hot-loader/babel'],` then some "module system" has to handle this request, send well as send the requested module to the frontend. You need a bundler for it.

If you are not 100% confident about what you doing, just stop. Or be ready to invest more of your personal time to understand how all this stuff work.

All this but NOT react-hot-loader - it's time is after everything is already working, after the "update".

**Comment by JieChang** [comment]
![image](https://user-images.githubusercontent.com/8551885/79985363-139e4600-84dd-11ea-8b30-64cfdd7604e7.png)
Babel.transform(code, {
    presets: ['es2015', 'react', 'react-hot-loader/babel'],
    plugins: [['proposal-decorators', { legacy: true }], ['proposal-class-properties', { loose: true }]]
  })

**Comment by theKashey** [comment]
Your problem is not here, as well as not in babel.
