### ISSUE TITLE
@types/react peer dependency causes npm/yarn warnings

### ISSUE THREAD

**Issue by okovpashko** [gaearon/react-hot-loader#1446]
# Description

We don't use TypeScript in our project and after updating to the latest react-hot-loader version we started getting the following warning during the dependencies installation:
```
warning " > react-hot-loader@4.12.19" has unmet peer dependency "@types/react@^15.0.0 || ^16.0.0".
```

Please consider removing this package from the peer dependencies because not all the projects use TypeScript

### Environment

React Hot Loader version: 4.12.19

Run these commands in the project folder and fill in their results:

1.  `node -v`: v13.12.0
2.  `npm -v`: 6.14.4

Then, specify:

1.  Operating system: MacOS
2.  Browser and version: Chrome 80

### Reproducible Demo

```
npm init --yes && npm i react react-dom react-hot-loader
```

**Comment by Fernando-Marquardt** [comment]
Maybe the field peerDependenciesMeta can be added to package.json, so the dependency can be made optional.

With this, if the dependency is found on the project, versions will be compared, but no warning will be thrown if not installed.

**Comment by theKashey** [comment]
It was added a while ago

**Comment by theKashey** [comment]
😅but the new package version was not released

**Comment by theKashey** [comment]
v4.12.21 released

**Comment by okovpashko** [comment]
Thank you for the quick response! The warning is gone after updating to v4.12.21.

**Comment by Fernando-Marquardt** [comment]
Nice. Thank you for the update.
