### ISSUE TITLE
Set up RHL & WHL app is working but without any HL

### ISSUE THREAD

**Issue by budarin** [gaearon/react-hot-loader#1473]
### Description
Try to make ssr & HMR
set up RHL according to the manual 
set up webpack hot reloading
app is working but in console there is no any HMR and hot reloading does not work

![image](https://user-images.githubusercontent.com/8055157/86354517-dd660b00-bc71-11ea-9323-a2d280dadf93.png)

### Expected behavior
expect HMR is working

### Actual behavior
HMR is not working

### Environment

React Hot Loader version: 4.12.21

Run these commands in the project folder and fill in their results:

1.  `node -v`: v14.4.0
2.  `npm -v`: 6.14.5
3.  'yarn -v': 1.22.4 - I use it

Then, specify:

1.  Operating system: any (MacOs, Windows)
2.  Browser and version: any

### Reproducible Demo
[demo repository](https://github.com/budarin/ssr-hmr-problem-demo)

**Comment by theKashey** [comment]
HMR is not only a plugin in webpack config, which just adds HMR related code to the bundle, but a different mode of running server code.
I am not sure how you run webpack, but proper settings to `webpackHotMiddleware` or `webpackDevMiddleware` could be missing.

**Comment by budarin** [comment]
@theKashey thanks alot!
