### ISSUE TITLE
Not working inside of virtual machine

### ISSUE THREAD

**Issue by tajo** [gaearon/react-hot-loader#148]
I am using OSX Yosemite for developing. I want to test my website in Internet Explorer 11 (in dev mode), so I've installed Parallels 10 with Windows 8.1 inside (modern.ie edition). I was able to make it working after I replaced the wepack-dev-server host  from `localhost` to `0.0.0.0`. However, react hot reloader doesn't work (in IE11 or Win Chrome). Actually, I think the whole webpack hot reload doesn't work, since there are no related messages in the console. Is there some problem with sockets? Maybe it's not really a RHL issue, but I wonder if you have some working set up (using RHL inside of VM)? Thanks.

**Comment by gaearon** [comment]
AFAIK Windows doesn't understand `0.0.0.0` thing.
But I'm such a network noob so can't really answer your question.

**Comment by fabriciocolombo** [comment]
I am using Windows 7 for developing. I am running the server and browser on same machine, and hot reload works fine with both wepack-dev-server host: `localhost` and `0.0.0.0`. I will try access from virtual machine to test.

**Comment by grssnbchr** [comment]
+1

**Comment by grssnbchr** [comment]
I am developing on a Ubuntu VM (VirtualBox). When setting the IP in Webpack to 0.0.0.0, I can access the server from outside (i.e. my Windows host) the via (using bridged network) - however, hot reloading does not work. Is there a solution for this? I think it has to do with the sockets?

**Comment by gaearon** [comment]
I'm closing because, if it is an issue, it is a Webpack (or Webpack Dev Server) issue, not React Hot Loader's.

**Comment by SimenB** [comment]
`0.0.0.0` is supported in `webpack-dev-server@1.11.0` https://github.com/webpack/webpack-dev-server/commit/eb50101b449d1fb99600d9c710db70679f6f4592
