### ISSUE TITLE
Release 1.2.8 to prevent peerDependency from being enforced in react

### ISSUE THREAD

**Issue by dariocravero** [gaearon/react-hot-loader#154]
Hey @gaearon could you do a new minor release to have the _peerDependency_ on `react` removed on npm? This would allow us to use `0.14.0-beta1`. Thanks :)

**Comment by gaearon** [comment]
This is out. Can you please verify that it works?

**Comment by syranide** [comment]
Isn't this a bad idea?

Each react-hot-loader is not compatible with every react version and peerDependency makes it easy to install/update without having to manually track version numbers. If you're testing beta versions and all packages are not yet updated for the beta you can `--force` install them at your own risk instead.

**Comment by gaearon** [comment]
React Hot API still has a peer dep, and since that's the thing that actually reaches out to React's internals, it better stay just there.

**Comment by dariocravero** [comment]
It's perfectly fine! Thanks :)
