### ISSUE TITLE
Blank page after reloading page when a change is made or if error occurs

### ISSUE THREAD

**Issue by dnlgrwd87** [gaearon/react-hot-loader#1556]
### Description
I am experiencing an issue with a blank page appearing after reloading the page, but only after the app has hot reloaded at least once.

### Expected behavior
I want to make a change to the app, have it hot reload, then be able to manually reload the page and not see a blank page and have to restart the app.

### Actual behavior
1. I reload the page before making changes and the page reloads correctly.
2. I make a change to the app, see that it hot reloads and shows the updated changes.
3. I manually reload the page (through the browser or keyboard shortcut)
4. I see a blank page and have to restart the app to see anything.

### Environment
react-hot-loader version 4.12.21
Operating system: Mac OS Catalina or Windows 10
Browser and version: Latest version of Chrome

I have followed the getting started instructions exactly. I am using hooks, but currently only `useState`. I am also using react-router-dom 5.2.0, though this happened before I implementing any routing at all.

**Comment by theKashey** [comment]
1. You haven't provided any information about your use case. It is absolutely impossible to reproduce your problem
2. React-Hot-Loader cannot cause any difference to "reloaded" page. It is a js script, which runs on the client. So with every refresh it works in the same way. Could not result in a "blank page".
3. React-Hot-Loader has been deprecated. Consider using FastRefresh.
