### ISSUE TITLE
GET http://0.0.0.0/socket.io/blah_blah net::ERR_ADDRESS_INVALID

### ISSUE THREAD

**Issue by halt-hammerzeit** [gaearon/react-hot-loader#157]
If I follow you integration walkthrough:
http://gaearon.github.io/react-hot-loader/getstarted/

Then I get this error in the console:
`GET http://0.0.0.0/socket.io/?EIO=3&transport=polling&t=1436636049740-0 net::ERR_ADDRESS_INVALID`

**Comment by halt-hammerzeit** [comment]
Oh, the port was messed up.

But, still, after correcting the port, it outputs the same error:
`GET http://0.0.0.0:3001/socket.io/?EIO=3&transport=polling&t=1436636370722-0 net::ERR_ADDRESS_INVALID`

**Comment by halt-hammerzeit** [comment]
I was only able to fix it that way:

From:
```
	entry:
	{
		application: 
		[
			"webpack-dev-server/client?http://0.0.0.0:" + configuration.development.webpack.development_server.port,
			'webpack/hot/only-dev-server',
			'./client/application.react'
		]
	},
```

To:
```
	entry:
	{
		application: 
		[
			"webpack-dev-server/client?http://127.0.0.1:" + configuration.development.webpack.development_server.port,
			'webpack/hot/only-dev-server',
			'./client/application.react'
		]
	},
```

**Comment by halt-hammerzeit** [comment]
You can close it if you want.
But you may want to reflect this bug in the documentation.

**Comment by gaearon** [comment]
Are you using Windows by chance?

**Comment by halt-hammerzeit** [comment]
Yes, I do

**Comment by minheq** [comment]
It is probably related to paths to where you serve yours assets in bundler and webpack-dev-server. I setup like this:

**webpack.config.js**
```
  output: {
    path: path.resolve(__dirname, 'public/build'),
    publicPath: '/build/',
    ...
   }
```

**server.js**
```
new WebpackDevServer(webpack(config), {
  hot: true,
  publicPath: '/build/',
  contentBase: 'public/build',
  ...
}
```

or with terminal:
```
webpack-dev-server --content-base public/build
```
