### ISSUE TITLE
Incompatibility with exports loader 

### ISSUE THREAD

**Issue by lorefnon** [gaearon/react-hot-loader#160]
I have observed an incompatibility when using react-hot-loader along with [exports-loader](https://github.com/webpack/exports-loader)

So basically, using something like: 
```
let openFB = require('exports?openFB=openFB!../assets/js/openfb.js').openFB;
```

Causes the exports-loader to append the line at the end of the module: 

```
var openFB = (function(){
  // Library code
})()

exports["openFB"] = (openFB);
```

However when using an HMR config like: 
```
{
    include: /\.js$/,
    loaders: ["react-hot", "babel-loader?stage=1&optional=runtime"],
}
```

What happens is that the entire script gets wrapped in a closure so the variables declared through var in global scope in the library are no longer accessible: 

```
    if (true) {
        (function() {
            var ReactHotAPI = __webpack_require__(219),
                RootInstanceProvider = __webpack_require__(61),
                ReactMount = __webpack_require__(63),
                React = __webpack_require__(117);
            module.makeHot = module.hot.data ? module.hot.data.makeHot :
                ReactHotAPI(function() {
                    return RootInstanceProvider.getRootInstances(
                        ReactMount);
                }, React);
        })();
    }(function() {

      var openFB = (function(){
      // Library code
      })();

  }).call(this);

  // ....

  exports["openFB"] = (openFB);
```

An obvious workaround is ofcourse to ignore such files in hot-loader config (which is what I am currently doing). However I wanted to know if this is solvable by some other means. If not I would request documenting this incomaptibility in the README.

**Comment by gaearon** [comment]
I think it works if you move `export-loader` *after* `react-hot-loader` in your loader configuration.
Can you verify?

(This would require you to put loader into config instead of inline `require` but it's a better style anyway.)

**Comment by lorefnon** [comment]
Yes, it indeed does. Thanks for pointing that out.
