### ISSUE TITLE
Chrome Extensions dev

### ISSUE THREAD

**Issue by Dharmoslap** [gaearon/react-hot-loader#161]
Would be great to make hot-loader ready for Chrome Extensions development. 
I'm using React.js in popup and having there webpack with this loader would be such a killing workflow setup!

**Comment by gaearon** [comment]
Is there anything we can do on RHL side?

**Comment by gaearon** [comment]
Closing as non-actionable.

**Comment by Dharmoslap** [comment]
There is already repo for it https://github.com/schovi/webpack-chrome-extension :) now I'm contributing to that.

**Comment by gaearon** [comment]
Thanks, great to know!
