### ISSUE TITLE
Force reload if hot update isn't possible

### ISSUE THREAD

**Issue by smussell** [gaearon/react-hot-loader#162]
First, thanks for the awesome project, its been immensely helpful.  Not sure if the change needs to be made here or in webpack-dev-server, but I keep getting the following error:

```
[Warning] [HMR] The following modules couldn't be hot updated: (They would need a full reload!)
```

I'm not incredibly bothered that the error occurs, however what I'd like is that, if the hot update is not possible, the browser should force a full reload automatically, that way I don't have to tab over and hit reload.  I'm sorry if this config exists already, but I couldn't find it.

Thanks

**Comment by gaearon** [comment]
I think changing `hot/only-dev-server` to `hot/dev-server` in your Webpack config's `entry` should do the trick. Can you try it?

**Comment by smussell** [comment]
That works, thanks.
