### ISSUE TITLE
2 copies of React in build output

### ISSUE THREAD

**Issue by khankuan** [gaearon/react-hot-loader#165]
Hey, I've noticed that the hot-loader includes the React library in its build output. In my project, I have also imported React. The final build file contained 2 copies of React library and as a result the app became buggy (100% cpu onClick). Any hint if the behaviour is expected?

Thanks!

**Comment by gaearon** [comment]
Do you mean in development, or in production?
You shouldn't be using React Hot Loader in production.

**Comment by cgarvis** [comment]
Looks like this is happening if you are trying to use the 0.14 rc of react.

**Comment by fortruce** [comment]
I see this too when using `react@0.14.0-beta3`. I was able to resolve it by changing the peer dependency in `react-hot-api` to include the version I'm using:

```
  "peerDependencies": {
    "react": ">=0.11.0 || 0.13.0-beta.1 || 0.13.0-rc1 || 0.13.0-rc2 || 0.14.0-beta3"
  },
```

And I had to remove the older version of react from `react-hot-loader`'s node_modules.

**Comment by gaearon** [comment]
React Hot API peerDep is now more relaxed.
