### ISSUE TITLE
Webpack configuration deprecated (hot:true)

### ISSUE THREAD

**Issue by pebie** [gaearon/react-hot-loader#170]
Related issue : https://github.com/gaearon/react-hot-loader/issues/10
I'm using hot-react-loader within gulp.
I'm forced to add 'hot: true' options to my webpack config to prevent browser reloading the page when my react component change. But when I do that I've got a depracated warning message : 

WARNING in webpack options:
DEPRECATED option 'hot' will be moved to the HotModuleReplacementPlugin. Use this instead.
For more info about the usage of the HotModuleReplacementPlugin see http://webpack.github.io/docs/list-of-plugins.html

Of course, I use this plugin in development.

Could you help me to figure out what I miss ?

**Comment by gaearon** [comment]
Can you please go through [Troubleshooting](https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md)? If it doesn't help, check out [React Hot Boilerplate](https://github.com/gaearon/react-hot-boilerplate) and compare your configuration to it. If it still doesn't work, please publish a sample project so I can take a look.

You certainly don't need `hot: true` in the Webpack config. You need it in `WebpackDevServer` options though.

**Comment by pebie** [comment]
Hi,
My configuration is a little different but I start my works from yours by forking [React Hot Boilerplate](https://github.com/gaearon/react-hot-boilerplate)
You may test my work on this repository : https://github.com/pebie/ecodex/branches by checking out ***config*** branch.

**Comment by pebie** [comment]
I found my mistake.
You can checkout [default branch](https://github.com/pebie/ecodex) on my git hub repository it works now like a charm. Just launch `gulp` after `npm install`

I did not put `hot` in the right place (webpack-dev-server config instead of webpack config).

And, thanks to [Troubleshootings](https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md) page, to prevent browser reloading each time I modify a React component I forgot these in my `entry`webpack config : `webpack/hot/only-dev-server`

`{
        module: [path.join(options.srcPath, 'index.js'), 'webpack/hot/only-dev-server'],
        common: ['react', 'react-router', 'webpack/hot/only-dev-server'],
        client: ['webpack-dev-server/client?http://localhost:8080']
}`

Hope it could help !

Thanks for your answers and apologize for my mistake :)
