### ISSUE TITLE
Reacting to nested function reloading

### ISSUE THREAD

**Issue by peterKaleta** [gaearon/react-hot-loader#172]
Hi

I cannot bring hte example beneath to reload due to the nested function:

```
...
renderSth = () => {
  return ({
    <div>STH</div>
  }); 
}

render() {
  <div>
   {this.renderSth()}
  </div>
}
...
```

as long as I'm changing anything in `render` method - reload occurs without any problem. But when I change `renderSth` hot reload does not work.

**Comment by syranide** [comment]
`renderSth = () => {` binds the method to each instance (at least when transpiled I would assume), so when the class is patched each bound method still refers to the initial method.

**Comment by gaearon** [comment]
There is no way we can make this work. We're going to support [autobind-decorator](https://github.com/andreypopp/autobind-decorator) soon though, so you might want to start using it.

Eventually we'll figure out something to support property syntax, but probably in form of a Babel plugin that will deprecate React Hot Loader.

**Comment by peterKaleta** [comment]
thanks!
