### ISSUE TITLE
Components in subdirectory doesn't reload

### ISSUE THREAD

**Issue by Anahkiasen** [gaearon/react-hot-loader#175]
Not sure why, I trimmed this down to the smallest possible app:

**public/app/js/index.js**
```js
import React from 'react';
import App from './App';
import AppBis from './Components/App';

React.render(<div><App /><AppBis /></div>, document.getElementById('app'));
```

**public/app/js/App.js**
```js
import React, { Component } from 'react';

export default class App extends Component {
    render() {
        return <h1>Hello, world.</h1>;
    }
}
```

**public/app/js/Components/App.js**
```js
import React, { Component } from 'react';

export default class App extends Component {
    render() {
        return <h1>Hello, world.</h1>;
    }
}
```

Modifying `js/App.js` triggers RHL fine, but modifying `js/Components/App.js` doesn't do anything. Nothing at all in the console, no polling, nothing. 

Webpack config:

```js
var path    = require('path');
var webpack = require('webpack');

module.exports = {
    devtool:   'eval',
    entry:     [
        'webpack/hot/only-dev-server',
        './public/assets/js'
    ],
    output:    {
        path:       path.join(__dirname, 'public/builds'),
        filename:   'bundle.js',
        publicPath: '/builds/'
    },
    devServer: {
        contentBase: __dirname + '/public',
        hot:         true,
    },
    plugins:   [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin()
    ],
    resolve:   {
        extensions: ['', '.js', '.jsx']
    },
    module:    {
        loaders: [{
            test:    /\.jsx?$/,
            loaders: ['react-hot', 'babel'],
            include: path.join(__dirname, 'public/assets/js')
        }]
    }
};
```

**public/index.html**
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Budger</title>
</head>
<body>
    <div id="app"></div>
    <script src="builds/bundle.js"></script>
</body>
</html>
```

Am I doing something wrong here? I checked Troubleshooting and everything but nothing that fixed it. This is pretty much straight up the example from [react-hot-boilerplate](https://github.com/gaearon/react-hot-boilerplate) so I don't see where I could have gone wrong. I tried using a node server instead of Webpack's `devServer` option in the config, but same thing.

**Comment by Anahkiasen** [comment]
Oh for christ's sake. Ok I found the issue, I spent hours changing my codebase, my Webpack config, my folder structure, etc. And it was a goddamn casing issue. My folder was named `assets/js/components` instead of `assets/js/Components` which was ok to JS but not to RHL (or Webpack dev server, don't know).

**Comment by nickw444** [comment]
+1 Thank you for coming back and writing your resolution here! Saved me a few hours of debugging! Cheers

**Comment by wzup** [comment]
@Anahkiasen 
what exactly have you done to solve it? It is not clear from your answer. Could you pls add more details?

**Comment by Anahkiasen** [comment]
I updated my path to match the casing in my actual filesystem. You can install [this plugin](https://www.npmjs.com/package/case-sensitive-paths-webpack-plugin) to help you and prevent further similar errors.

**Comment by baterson** [comment]
@Anahkiasen thanks a lot! I tried to fix it several hours
