### ISSUE TITLE
hot-loader crashes the app

### ISSUE THREAD

**Issue by sehyoc** [gaearon/react-hot-loader#178]
When I tries to use react-hot-loader, my application fails to load due to null pointer.  It seems props were not properly cloned.

// code is transpiled using babel
{
	        key: 'viewKey',
	        get: function get() {
	            return this.props.view;
	        }
	    }]);

In our case, this.props. is null.

**Comment by Raigen** [comment]
I have the same problem with `this.state` to be `undefined` in getter when using hot-loader.
Newest version of webpack and react-hot-loader
```javascript
// transpiled by babel
	  _createClass(Plugin, [{
	    key: 'editLabel',
	    get: function get() {
	      return this.state.mode === 'view' ? 'Edit' : 'Save';
	    }
```

**Comment by gaearon** [comment]
It would actually help to see the source code, not the generated one. ;-)

**Comment by gaearon** [comment]
My guess is that you're using getters, and React Hot Loader doesn't support them yet.
Support is coming!

**Comment by gaearon** [comment]
Stay tuned for the next beta release that is going to fix it and drop very soon.

**Comment by gaearon** [comment]
Can I ask you to check whether `react-hot-loader@2.0.0-alpha` solves this issue?
Please provide any feedback on it in this PR: https://github.com/gaearon/react-hot-loader/pull/182
