### ISSUE TITLE
Source maps don't update

### ISSUE THREAD

**Issue by brownieboy** [gaearon/react-hot-loader#180]
Are source maps supposed to update when using react-hot-loader?

They are not updating in my testing.  I've tried with devtool set to 'eval', 'source-map' and 'eval-source-map'.

**Comment by gaearon** [comment]
There is nothing we can do until Chrome fixes this: https://code.google.com/p/chromium/issues/detail?id=492902.

**Comment by brownieboy** [comment]
@Gaearon,

Thanks for your response.

Is there a similar bug in Firefox?  My source maps don't update there either.

Only Safari seems to be updating them, which is a bit of a bummer if you're not on a Mac!

**Comment by gaearon** [comment]
>Is there a similar bug in Firefox? My source maps don't update there either.

Yes, Firefox also has this problem. I remember @jlongster wanting to take a look someday but he's probably super busy with Firefox devtools React overhaul.

**Comment by zivni** [comment]
@gaearon - the Chrome bug is reported to be fixed in Chrome version 48. but my source maps still do not update. I'm using `devtool: 'eval-source-map'`

**Comment by gaearon** [comment]
It works with `devtool: 'eval'` in Chrome 48, but source maps indeed are still broken.

**Comment by xjccc** [comment]
i try to use devtool:'eval-source-map',can not usefull
