### ISSUE TITLE
react-hot-loader with library providing more functional interface to react

### ISSUE THREAD

**Issue by Gozala** [gaearon/react-hot-loader#191]
I am trying to integrate react-hot-loader into our toolchain for the [browser.html](https://github.com/mozilla/browser.html) project that uses react with a more functional interface modeled after [Elm architecture tutorial](https://github.com/evancz/elm-architecture-tutorial) that is described in the following [architecture overview](https://github.com/mozilla/browser.html/blob/master/docs/architecture.md).

Unfortunately I was unsuccessful to get hot reloading working with the [most primitive example](https://github.com/Gozala/reflex/pull/34/files) presumably because react-hot-loader does not attempts to create proxies for the module exports. This is what I see in the output:

```
12:32:32.542 [HMR] Waiting for update signal from WDS... only-dev-server.js:74:2
12:32:33.159 [WDS] Hot Module Replacement enabled. client:15:2
12:32:40.361 [WDS] App updated. Recompiling... client:19:2
12:32:41.139 [WDS] App hot update... client:65:3
12:32:41.158 [HMR] Checking for updates on the server... only-dev-server.js:69:5
12:32:41.234 [HMR] The following modules couldn't be hot updated: (They would need a full reload!) log-apply-result.js:11:3
12:32:41.236 [HMR]  - 225 log-apply-result.js:13:4
12:32:41.239 [HMR] Nothing hot updated. log-apply-result.js:18:3
12:32:41.240 [HMR] App is up to date.
```

I've tried to gain better understanding of how module hot swapping works and also looked at the [react-proxy](https://github.com/gaearon/react-proxy) and I as far as I understand it is not going to cover interface that we chose to use for interacting with react.

That being said I was hoping to maybe get some guidance on how I could try to change react-hot-loader to handle such cases, or if it's just better to take ideas from react-hot-loader and create completely new API ?

**Comment by Gozala** [comment]
In theory it should be easier to hot swap app written in this interface since all of the app state is one place and there is only top level `view` and `update` functions (usually composed out diff component view and updates) so in practice I should be able to just swap the whole thing and re-render but when manually trying that I run into issue with two reacts versions :(

**Comment by gaearon** [comment]
React Hot Loader looks for module exports that are *React components*.
In your case, there are no React components at all: you are exporting functions.
This is what causes the problem: React Hot Loader thinks there's nothing to reload.

**Comment by gaearon** [comment]
Please see https://github.com/Gozala/reflex/pull/35.

**Comment by tugberkugurlu** [comment]
I have the below content for example:

```
var React = require('react');
var ReactDom = require('react-dom');

var HelloWorld = () => {
    return <div>Hello World!</div>;
};

ReactDom.render(
    <HelloWorld />, 
    document.getElementById('app')
);
```

Any change I make to `HelloWorld` component gives the below warning:

```
[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
[HMR]  - 76
```

> you are exporting functions.

@gaearon I guess `HelloWorld` is what you were referring there as function, correct?
