### ISSUE TITLE
App updated. Recompiling...  but nothing happens

### ISSUE THREAD

**Issue by dontlemmedown** [gaearon/react-hot-loader#192]
I just wanna make kinda boilerplate to tech Webpack and ReactJS as well, but you know, i just get nothing, when I'm changing my components.. 

### browser console.log
```
Error: [HMR] Hot Module Replacement is disabled. app.bundle.4ce2f5ca49e19b0a82ac.js line 62 > eval:76:7
[WDS] Hot Module Replacement enabled. client:15:2
[WDS] App updated. Recompiling... client:19:2
[WDS] App hot update... client:65:3
[WDS] App updated. Recompiling... client:19:2
[WDS] App hot update... client:65:3
[WDS] App updated. Recompiling... client:19:2
[WDS] App hot update... client:65:3
[WDS] App updated. Recompiling... client:19:2
[WDS] App hot update... client:65:3

```
### Parts of webpack.config.js
```js
entry: {
	app: [ path.resolve('app', 'entry', 'index.jsx'), 'webpack/hot/only-dev-server' ],
	vendors: Object.keys(dependencies),
}

module: {
	loaders: [
		{
			test: /\.(jsx|js)$/,
			exclude: path.resolve('node_modules'),
			loader:'react-hot!babel-loader'
		},
	]
}
```
btw. running webpack-dev-server via ```npm run```

What is this, can you help me?

**Sorry for my English,**

**Comment by gaearon** [comment]
I don't see `webpack-dev-server/client?http://localhost:3000` in your `entry`.

**Comment by dontlemmedown** [comment]
Yes, i did it...

```js
entry: {
    app: [ path.resolve('app', 'entry', 'index.jsx'), 'webpack/hot/only-dev-server' ],
    vendors: Object.keys(dependencies),
    client: 'webpack-dev-server/client?http://localhost:3000'
}
```js

**Comment by dontlemmedown** [comment]
### This, when I start the server.

![screenshot from 2015-09-05 08 12 35](https://cloud.githubusercontent.com/assets/7820359/9697825/57c22044-53a6-11e5-8d83-1bdf54631a7c.png)

### This, when I try to update a data

**Comment by dontlemmedown** [comment]
I tough, that ```hot: true``` in devServer settings equals ```webpack-dev-server --hot``` or 
```js
 new webpack.HotModuleReplacementPlugin()
```
i was wrong =)
