### ISSUE TITLE
issues with 'createBrowserHistory'

### ISSUE THREAD

**Issue by pdeva** [gaearon/react-hot-loader#194]
The following problem occurs only when using:
```
import createHistory = require('history/lib/createBrowserHistory');
```

it goes away when using

```
import createHistory = require('history/lib/createHashHistory');
```

Problem:

I have react components in `components` and `components/account` dirs.

Using command 
```
webpack-dev-server --progress --hot 
```

The components do reload fine when the components in `components` dir are edited.
However, when components in `components/account` dir is edited, I see this error message in the console:

```
GET http://localhost:8080/account/6bf2198fa1154a505ad5.hot-update.json 404 (Not Found) hotDownloadManifest @ bundle.js:26hotCheck @ bundle.js:210check @ bundle.js:7883(anonymous function) @ bundle.js:7941
bundle.js:7898 
[HMR] Cannot find update. Need to do a full reload! bundle.js:7899 
[HMR] (Probably because of restarting the webpack-dev-server)
```
This is when i edited a file `components\account\profile.tsx`

Here is the contents of my `webpack.config.json`:

```
var path = require('path');
var webpack = require('webpack');

module.exports = {
  devServer: {
        hot: true,
        progress: true,
        colors: true,
        historyApiFallback: true
    },
    entry: [
      'webpack-dev-server/client?http://localhost:8080', // WebpackDevServer host and port
      'webpack/hot/only-dev-server', // "only" prevents reload on syntax errors
      "./ts/main.js"
    ],
    output: {
        path: '.',
        filename: "bundle.js"
    },
    module: {
      loaders: [
          {
            test: /components\\(.*)\.js$/,
            loaders: ['react-hot'],
            include: path.join(__dirname, 'ts')
          }
    ]

    }
};

```

**Comment by gaearon** [comment]
Please provide a full project reproducing the error. It is preferable that this project is in JavaScript.

**Comment by seburgi** [comment]
I can confirm the described behavior: when I edit a component that is located on a deep linked part of the application (e.g, http://localhost:3000/items/) I see a failed http request:

GET http://localhost:3000/items/699c0d87-fd01-4aee-a5e8-eb1d08b306c6/34f89fad62976d0397c3.hot-update.json 404 Not Found

When I manually load http://localhost:3000/699c0d87-fd01-4aee-a5e8-eb1d08b306c6/34f89fad62976d0397c3.hot-update.json (without "/items") I get a valid response.

I will try to reproduce this in a sample project and will report back.

**Comment by seburgi** [comment]
@pdeva could you try adding " publicPath: '/' " so it looks like this:

 output: {
    path: '.',
    filename: 'bundle.js',
    publicPath: '/'
  },

That fixed the problem for me.
