### ISSUE TITLE
Clarify situation between react-hot-loader and react-transform-boilerplate

### ISSUE THREAD

**Issue by lionelB** [gaearon/react-hot-loader#195]
Hi!

First, I would say an huge thank you for your awesome work (I know, that sound a bit like an apple event)
I would like to know what is the current state of the art for hot reloading & react
Should I use [react-hot-loader](https://github.com/gaearon/react-hot-loader) or should I go with the [react-transform-boiler-plate](https://github.com/gaearon/react-transform-boilerplate) ? 

I see there is an issue open for a react-hot-loader v2 
So I'm confuse.

**Comment by gaearon** [comment]
React Hot Loader is going away. I'm going to post about it soon.

**Comment by dlong500** [comment]
Any updates on this?  I'd like to move to your recommended way of doing things but without a migration guide I just don't have the time or expertise to fiddle around with it at the moment.

**Comment by gaearon** [comment]
There'll be more instructions, but at the moment RT is still work in progress.
Please give it some more time.

**Comment by lionelB** [comment]
thanks for clarification.
