### ISSUE TITLE
React DevTools `Show Source` is not working

### ISSUE THREAD

**Issue by simongong** [gaearon/react-hot-loader#196]
I tried to view source of component in React Panel

![63cf1e54-bb59-4605-af03-4f8683ac69cd](https://cloud.githubusercontent.com/assets/729479/9897157/d8e880bc-5c77-11e5-908f-febfaee9938c.png)

But it ended up with somewhere in `makeAssimilatePrototype.js`

```
module.exports = function makeAssimilatePrototype() {
  var storedPrototype,
      knownPrototypes = [];

  function wrapMethod(key) {
    return function () {
      if (storedPrototype[key]) {
        return storedPrototype[key].apply(this, arguments);
      }
    };
  }
```

**Comment by gaearon** [comment]
@jaredly, is there any way I can tell React DevTools to look at a different function? Right not it points to the proxied method, but I can set something like `__originalMethod` on the proxy if we can come up with a convention you're happy with.

**Comment by jaredly** [comment]
Yeah, that sounds reasonable. [Here's the code](https://github.com/facebook/react-devtools/blob/master/shells/chrome/src/panel.js#L43) for jumping to a function's source (it uses the chrome console api fn `inspect` that jumps you to any function's source).
If it's an es6 class then I jump to the constructor, otherwise I jump to the render fn.

I imagine the constructor doesn't get proxied, right? So the only change would be for the render function?

**Comment by gaearon** [comment]
@jaredly The constructor is proxied too. Never mind React Hot Loader though—it's deprecated and the new proxying mechanism is in [React Proxy](https://github.com/gaearon/react-proxy). I'm proxying both constructor and all prototype methods there.

**Comment by gaearon** [comment]
I can’t repro this with React Hot Loader 3 so it somehow got fixed.
¯\_(ツ)_/¯

**Comment by Bnaya** [comment]
I'm having this issue on `v4.3.12` and i think with all 4.x

**Comment by theKashey** [comment]
Yeah, lets reopen this.
https://github.com/facebook/react-devtools/pull/1191

**Comment by theKashey** [comment]
Fixed in 4.5.0 (beta) - https://github.com/gaearon/react-hot-loader#setconfigconfig

**Comment by Bnaya** [comment]
@theKashey Thanks!
Which config should make it work?

**Comment by theKashey** [comment]
@Bnaya - you need `setConfig({pureRender: true});`

**Comment by Bnaya** [comment]
I tried to understand what that means, and how it will effect me and i didn't manage to understand  :(

**Comment by theKashey** [comment]
@Bnaya  - https://github.com/gaearon/react-hot-loader#-hot-labs-

```js
import { setConfig } from 'react-hot-loader'

setConfig({
  pureRender: true, // RHL will not change render method
})
```

**Comment by Bnaya** [comment]
yes, but why its not on by default?
What is the effect on RHMR?

**Comment by theKashey** [comment]
It was an experimental option. There are a few tests, which goes red with this option enabled.
