### ISSUE TITLE
Add support for React stateless components (new in v0.14)

### ISSUE THREAD

**Issue by Jadaw1n** [gaearon/react-hot-loader#198]
New with React v0.14 are statless components. https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html#stateless-function-components

They're super useful, but sadly not hot reloadable.

Please add support for them :)

**Comment by gaearon** [comment]
React Hot Loader is deprecated in favor of [React Transform plugin for Babel](https://github.com/gaearon/babel-plugin-react-transform) and [React Transform HMR](https://github.com/gaearon/react-transform-hmr). I don't plan to add support for stateless components to React Hot Loader, but I do plan to add it to those projects. Please track https://github.com/gaearon/react-transform-hmr/issues/6.

**Comment by Jadaw1n** [comment]
Oh, didn't see that, thanks!
