### ISSUE TITLE
updateStoredPrototype calls property getters

### ISSUE THREAD

**Issue by DanielHeath** [gaearon/react-hot-loader#200]
I'm running into an issue where a property defined on my component is getting invoked, causing an error which prevents hot-loading from working.

An example:
```js
class Foo extends React.Component {
    get propval(): string {
        return this.props.val;
    }
}
```
This causes `updateStoredPrototype` to assign propval using `storedPrototype[key] = freshPrototype[key];`, which invokes the getter (causing an error since `props` isn't present on the prototype).

**Comment by gaearon** [comment]
This is fixed with React Transform.
Please see [the deprecation notice](https://github.com/gaearon/react-hot-loader#deprecation-notice).
