### ISSUE TITLE
React-hot-loader produces error for inherited components

### ISSUE THREAD

**Issue by smashercosmo** [gaearon/react-hot-loader#205]
react-hot-loader v2.0.0-alpha-4 produces the following error
```
Uncaught TypeError: Cannot read property 'bind' of undefined
```
when component was inherited from other component, that was created with React.createClass. v1.3.0 handles this situation correctly. Here is the [demo repo](https://github.com/smashercosmo/react-hot-loader-inheritance-issue).

**Comment by gaearon** [comment]
Can you check whether updating `react-proxy` to the very latest version fixes it?
(`react-proxy` is a dependency of `react-hot-api@0.5.0`)

That said we don't plan to support components inherited from `createClass` components—even React [doesn't officially support them](https://github.com/facebook/react/pull/4620#issuecomment-130471512). Inheritance is a [terrible solution](https://medium.com/@dan_abramov/how-to-use-classes-and-sleep-at-night-9af8de78ccb4) to code reuse in React so we won't encourage it.

**Comment by smashercosmo** [comment]
>  Inheritance is a terrible solution to code reuse
Totally agree) But sometimes it's the only way to extend third-party component and add some extra-functionality that you need. Of course you can always make a fork... but also not the best solution.

**Comment by smashercosmo** [comment]
Nope, updating to the latest react-proxy doesn't solve the problem

**Comment by smashercosmo** [comment]
By the way, what is your best solution in case you need to use some third-party component, but slightly change its render function?

**Comment by gaearon** [comment]
@smashercosmo What do you mean by “slightly change”? As long as you wrap it, just use it as is. If you want to *change* its internals, fork. It's like “what if you want to use third-party function but change its source”.

**Comment by smashercosmo** [comment]
@gaearon Yes, of course I was saying about changing the internals. So the only acceptable solution is a fork then. Ok, got it, but not satisfied with this option))
