### ISSUE TITLE
Could you explain how you did a live demo?

### ISSUE THREAD

**Issue by faergeek** [gaearon/react-hot-loader#207]
I'm excited by the live demo editing. Could you explain how you did it? May be in a blog post?

**Comment by mik01aj** [comment]
+1.

In particular, I'd like to know how did you make CodeMirror work nicely with JSX. We need it in https://github.com/sapegin/react-styleguidist/issues/19.

**Comment by gaearon** [comment]
It’s on `gh-pages` branch, feel free to inspect it, e.g. https://github.com/gaearon/react-hot-loader/blob/gh-pages/public/js/live_editor.js
