### ISSUE TITLE
question: is this compatible with react V 0.14?

### ISSUE THREAD

**Issue by goldensunliu** [gaearon/react-hot-loader#208]

**Comment by gaearon** [comment]
Which version are you referring to?
Regardless, the project is deprecated, please see https://github.com/gaearon/react-transform-boilerplate instead. It will get full 0.14 support soon.

**Comment by goldensunliu** [comment]
particularly 0.14.0

**Comment by gaearon** [comment]
No, I meant which version of RHL.
There's 1.x and 2.x betas.

**Comment by gaearon** [comment]
RHL is compatible with 0.14 AFAIK. It isn’t currently compatible with React 15, but that’s in the works.
