### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by sqrtroot** [gaearon/react-hot-loader#209]
Unfortunatly this plugin doesn't seem to work alright with typescript.
It hot reloads the render function alright, but functions other then that don't seem to hotreload alright
When using this code:

    export let Timer = React.createClass({
      getInitialState: function() {
        return {secondsElapsed: 0};
      },
      tick: function() {
        this.setState({secondsElapsed: this.state.secondsElapsed + 1});
      },
      componentDidMount: function() {
        this.interval = setInterval(this.tick, 1000);
      },
      componentWillUnmount: function() {
        clearInterval(this.interval);
      },
      render: function() {
        return (
          <div>Seconds Elapsed: {this.state.secondsElapsed}</div>
        );
      }
    });

It works alright. if i change the tick function it hotreloads without a problem but when writing this in typescript:

    import * as React from "react";

    interface ITimerState {
        count: number;
    }

    export class Timer extends React.Component<any, ITimerState>{

        private _interval: any;

        constructor() {
            super();
            this.state = {
                count: 0
            };
            this._interval = setInterval(this.count, 1000);
        }

        count = () => {
            this.setState({ count: this.state.count + 10 });
        }

        componentWillUnmount() {
            clearInterval(this._interval);
        }

        render() {
            return (
                <div>Seconds Elapsed: {this.state.count}</div>
            );
        }
    }

Updating the count function doesn't hotreload it.
If it's any help, this is what it compiles to:

    var __extends = (this && this.__extends) || function (d, b) {
        for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
    var React = require("react");
    var Timer = (function (_super) {
        __extends(Timer, _super);
        function Timer() {
            var _this = this;
            _super.call(this);
            this.count = function () {
                _this.setState({ count: _this.state.count + 10 });
            };
            this.state = {
                count: 0
            };
            this._interval = setInterval(this.count, 1000);
        }
        Timer.prototype.componentWillUnmount = function () {
            clearInterval(this._interval);
        };
        Timer.prototype.render = function () {
            return (React.createElement("div", null, "Seconds Elapsed: ", this.state.count));
        };
        return Timer;
    })(React.Component);
    exports.Timer = Timer;

**Comment by sqrtroot** [comment]
bump

**Comment by akania** [comment]
+1

**Comment by sqrtroot** [comment]
Okay i've found the problem

If you use ```() => {} ```functions typescript compiles this to:

```
function Timer() {
    var _this = this;
    _super.call(this);
    this.FUNCTION = function () {
        _this.setState({ count: _this.state.count + 10 });
    };
}
```
hot reloader doesn't re-execute this Timer() function so the function is never actualy reasigned.
a workaround is this

```
constructor(){
	this.tick = this.tick.bind(this);
}

tick(){
	this.setState({count: this.state.count + 10})
}
```

this compiles into

```
function App() {
    this.tick = this.tick.bind(this);
}
App.prototype.tick = function () {
    this.setState({ count: this.state.count + 10 });
};
```
The protoype function does reload an hotreloading works. I don't know if this is a issue for hot-reloader or for typescript.

**Comment by sqrtroot** [comment]
full example of the time:
``` typescript
import * as React from "react";

interface ITimerState {
    count: number;
}

export class Timer extends React.Component<any, ITimerState>{

    private _interval: any;

    constructor() {
        super();
        this.state = {
            count: 0
        };
        this.count = this.count.bind(this);
        this._interval = setInterval(this.count, 1000);
    }

    count(){
        this.setState({ count: this.state.count + 10 });
    }

    componentWillUnmount() {
        clearInterval(this._interval);
    }

    render() {
        return (
            <div>Seconds Elapsed: {this.state.count}</div>
        );
    }
}
```

**Comment by alexgorbatchev** [comment]
I have this working with TypeScript very well https://github.com/alexgorbatchev/gulp-typescript-webpack-react-hotreload

**Comment by gaearon** [comment]
Functions defined inside constructor can’t be reloaded. This is more or less by design—no easy way to get around it.
