### ISSUE TITLE
How to get it working with npm linked module?

### ISSUE THREAD

**Issue by elado** [gaearon/react-hot-loader#211]
I have 2 modules, **host** and **toolkit**. I `npm link ../toolkit` in **host**.
**toolkit** exports some React components.
**host** has a full app with `react-hot-loader` set up and renders some of **toolkit** components.
How do I make **host** hot-reload changes when I save one of **toolkit** files? It doesn't work with a simple set up like suggested in the starter.

**Comment by gaearon** [comment]
There are two parts to this:

1. Make sure your symlinked folders end up included in the loader configuration for the transform. For example if you have something like `include: __dirname` in Webpack config, symlinked folders will be excluded.

2. If RHL wants some dependencies like `react`, you can symlink them back, e.g. `cd ../toolkit` and `npm link ../app/node_modules/react`.

None of this is specific to RHL though so I’m closing.

**Comment by em-yuanbo** [comment]
great. it really save me.
