### ISSUE TITLE
FOUC when using source-map.

### ISSUE THREAD

**Issue by danauclair** [gaearon/react-hot-loader#214]
When I use hot-module-reloading with sourcemaps I see what used to be inline style tags in the head turn into link tags with blob: hrefs. For some reason this change is causing a flash of unstyled content before the link tags are injected into the head.

Are there any workarounds for this?

**Comment by danmartinez101** [comment]
Are you using extract text plugin?

**Comment by gaearon** [comment]
In any case this is not React Hot Loader issue.
