### ISSUE TITLE
Live-Reload when HotReload not possible + Other questions

### ISSUE THREAD

**Issue by nsisodiya** [gaearon/react-hot-loader#215]
I have recently use hot-reload and I am using following configuration in webpack.config.js

```entry: [
		'webpack-dev-server/client?http://localhost:8000',
		'webpack/hot/only-dev-server',
		'./src/entry.js'
],```

Questions !

1) How to specify multiple entry points? react-hot-boilerplate has only one entry point. I have two entry point and second entry point is a DOM-less code (code which will run in web-workers)

2) I noticed that, If I am using hot-reload, then it only hot-reload render function. If I change anything in other functions then it will not do a hot update. So there are some cases I found, live-reload is needed. How to do live-reload when hot-update not possible.

**Comment by gaearon** [comment]
>1) How to specify multiple entry points? react-hot-boilerplate has only one entry point. I have two entry point and second entry point is a DOM-less code (code which will run in web-workers)

Here is an example: https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#i-see-hmr-nothing-hot-updated-and-nothing-happens-when-i-edit-appjs

>I noticed that, If I am using hot-reload, then it only hot-reload render function. If I change anything in other functions then it will not do a hot update. 

If this is the case, it’s a bug. It should hot reload any functions on the components. I’m in the middle of a rewrite so this is probably going to be irrelevant afterwards so I’m closing. Keep an eye for React Hot Loader 3 release—it should be more stable, and if you have this issue again, please feel free to file it as a bug with a sample project reproducing it.

**Comment by nsisodiya** [comment]
Thanks !
