### ISSUE TITLE
No future support for non-Babel users?

### ISSUE THREAD

**Issue by chrisvfritz** [gaearon/react-hot-loader#216]
Since the deprecation notice was posted, it doesn't look like v2 is being actively developed, with focus shifting to coupling future hot loading to Babel. Is my assessment correct?

**Comment by gaearon** [comment]
It's not coupled. The underlying part (https://github.com/gaearon/react-proxy) is agnostic of any build tools. It is possible to build something like https://github.com/gaearon/babel-plugin-react-transform but for Webpack (think "react-transform-loader") that would work with existing transforms such as https://github.com/gaearon/react-transform-hmr. In fact I'm curious why no one did that yet. Would you like to try?

**Comment by gaearon** [comment]
If somebody does it, I'll happily port RHL to use that loader internally, and everyone would be happy. Babel users would enjoy more thorough support (there are benefits to static analysis!) but current users of RHL would also use the same underlying codebase.

**Comment by chrisvfritz** [comment]
@gaearon Ahh, thanks for clarifying. Maybe as things slow down for the holidays, I'll take a stab at coding myself a new loader for Christmas. :smiley:

**Comment by alexgorbatchev** [comment]
@chrisvfritz have you made any progress on this? I was also caught off guard that decision was made to go from a generic webpack loader to babel specific implementation.

**Comment by gaearon** [comment]
>I was also caught off guard that decision was made to go from a generic webpack loader to babel specific implementation.

As I said before [react-proxy](https://github.com/gaearon/react-proxy) is completely independent from Babel. That I currently don't work on React Hot Loader doesn't mean you can't use it to build something specifically for Webpack using React Proxy or React Transform HMR. ;-)

**Comment by gaearon** [comment]
An important factor is that “Babel specific implementation” is more generic than “generic Webpack loader” because it can be used with alternative packagers such as Browserify and (most interestingly) React Native packager.

**Comment by chrisvfritz** [comment]
@alexgorbatchev I haven't gotten a chance to work on anything yet - free free to take a swing at it yourself! And thanks again @gaearon for taking the time to explain things. Now that I understand a little better, I really appreciate how you've architected react-proxy to avoid _any_ kind of ecosystem lock-in. :smiley:
