### ISSUE TITLE
Deprecation?

### ISSUE THREAD

**Issue by alexgorbatchev** [gaearon/react-hot-loader#217]
@gaearon From what I can tell `react-transform-hmr` anchors around Babel, which is a problem for everyone who isn't using Babel. I have a TypeScript project and don't need Babel. Is there a way to use `react-transform-hmr` without Babel?

re: https://github.com/alexgorbatchev/gulp-typescript-webpack-react-hotreload/issues/1

**Comment by gaearon** [comment]
It's totally possible (with some limitations) to use React Transforms without Babel. Please see #216 which is exactly the same question. I left some hints on how to approach this.

If you're familiar with how Webpack loaders work and read React Hot Loader source code, it shouldn't take you more than a few days. Unfortunately nobody expressed interest in implementing this so far.

**Comment by alexgorbatchev** [comment]
Thanks, I'll look into it.

**Comment by gaearon** [comment]
:+1:
