### ISSUE TITLE
loader order with `babel-loader`

### ISSUE THREAD

**Issue by chbdetta** [gaearon/react-hot-loader#218]
the order of this loader is always prior to `babel-loader`
```js
loaders: ['react-hot', 'babel?preset[]=es2015,preset[]=react']
```
and `babel-loader` give an error complaining that `import` need to be at the top level which should be caused by the wrapper from `react-hot`

I fix it by putting `babel` to pre-loader.

Maybe react-hot just ignore the loader order? It will be appreciated if the start-up how-to page mention this.

**Comment by gaearon** [comment]
We mention this in the Troubleshooting guide:

https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#syntaxerror-import-and-export-may-only-appear-at-the-top-level

We can't ignore this unfortunately.

**Comment by gaearon** [comment]
Feel free to create a PR to add this to Getting Started page though!

**Comment by mdreizin** [comment]
@gaearon Unlucky `react-hot-loader` + `babel-loader` + `webpack 2` = :broken_heart:

```js
{
	test: /\.jsx$/,
	loaders: [
		'react-hot', {
			loader: 'babel',
			query: {
				babelrc: false,
  				cacheDirectory: true,
  				presets: [
  					'es2015-webpack',
  					'react'
  				]
  			}
	}],
 	exclude: [
 		/node_modules/
 	]
 }
```

```
'import' and 'export' may only appear at the top level (7:0)
You may need an appropriate loader to handle this file type.
```

```json
{
	"webpack": "^2.1.0-beta.4",
	"react-hot-loader": "^1.3.0"
}
```

**Comment by gaearon** [comment]
@mdreizin 

Yes, that wouldn’t work with the code we generate. Please feel free to send a PR to make this Webpack 2-friendly. We might need a separate branch that only works with WP2.

**Comment by seanadkinson** [comment]
I had assumed the `2.0.0-alpha` releases of `react-hot-loader` would have addressed any obvious webpack 2 issues, but I see the same error above `'import' and 'export' may only appear at the top level`, due to the `"use strict"` at the top of the hot file.

Can there just be a `query` option to disable the `"use strict"` or something?  I can certainly look into a PR for this if you think this would be a good way of solving this @gaearon

**Comment by lauterry** [comment]
Hi @mdreizin

Still react-hot-loader + babel-loader + webpack 2 = :broken_heart: ?

Have you found a solution or a workaround ?

Best regards

**Comment by mdreizin** [comment]
@lauterry I don't use `react-hot-loader ` for now and just use full page refresh.

**Comment by jwdomingo** [comment]
Hello all, any updates on Webpack 2 support?

**Comment by ctrlplusb** [comment]
@jwdomingo I have RHL working with Webpack 2.

See here: https://github.com/ctrlplusb/react-universally

**Comment by jwdomingo** [comment]
Thanks @ctrlplusb I will look into it and update back

**Comment by thj-dk** [comment]
Any solutions to this?

**Comment by purple-force** [comment]
@mdreizin same to you, react-hot-loader + babel-loader + webpack 2 = 💔!
any solutions?

**Comment by wkwiatek** [comment]
@purple-force make sure you're using `react-hot-loader@next` which means 3.0 beta.

**Comment by purple-force** [comment]
@wkwiatek ,i tried,when compiling,there is no error now.But it doesn't work(HMR) anyway,even refresh mannually.
here is part of my config:
```javascript
{
	test:/\.(js|jsx)$/,
	exclude:/node_modules/,
	use:[{
		loader:"react-hot-loader/webpack"
	},{
		loader:"babel-loader",
		options:{
			presets:[["es2015",{modules:false}],"react"]
		}
	}]
}
```
part of package.json:

```javascript
"devDependencies": {
    "babel-core": "^6.22.1",
    "babel-loader": "^6.2.10",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.22.0",
    "css-loader": "^0.26.1",
    "extract-text-webpack-plugin": "beta",
    "react-hot-loader": "next",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.3.0"
  },
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  }
```

ps:i use `webpack-dev-server --hot --inline --open`

**Comment by wkwiatek** [comment]
You may miss `react-hot-loader/babel` from babel plugins and `react-hot-loader/patch` in source code. 

Here is the one which I'm working on and works just fine: https://github.com/wkwiatek/react-webpack2-hmr . See it as a reference. 

Docs are still in progress so sorry for the lack of information.

**Comment by purple-force** [comment]
Hmm,it does work!I saw your source code,too much invasive code.
Is there any way to achieve this just by configuring webpack.configure.js with react-hot-loader?
