### ISSUE TITLE
isReactClassish.js crash in ie8

### ISSUE THREAD

**Issue by WwupengP** [gaearon/react-hot-loader#219]
in ie8:

    var Base = Object.getPrototypeOf(Class);
    while (Base) {
    if (Base === React.Component) {
        return true;
    }

crash on second line in isReactClassish.js

**Comment by WwupengP** [comment]
reference to [issue#98](https://github.com/gaearon/react-hot-loader/issues/98)

**Comment by gaearon** [comment]
I don't think we support hot reloading in IE8 either way.
