### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by cornerolive** [gaearon/react-hot-loader#223]
Hi, 

I have a problem with webpack. I have updated my package.json and I have this error:

    Uncaught ReferenceError: global is not defined

In chrome inspector, I see the error coming from a autocreated file **VM33816** and inside it it has the following:

    'use strict';

    if (global.crypto && global.crypto.getRandomValues) {
      module.exports.randomBytes = function(length) {
        var bytes = new Uint8Array(length);
        global.crypto.getRandomValues(bytes);
        return bytes;
      };
    } else {
    module.exports.randomBytes = function(length) {
      var bytes = new Array(length);
      for (var i = 0; i < length; i++) {
        bytes[i] = Math.floor(Math.random() * 256);
       }
       return bytes;
      };
    }

This is my config file:

    module.exports = {
    resolve: {
        root: __dirname + "/src",
        extensions: ['', '.js', '.jsx'],
        alias: {
            vex: 'vex-js',
            modernizr$: __dirname + "/.modernizrrc"
        }
    },
    entry: {
        app: [
            'webpack-dev-server/client?http://localhost:8080',
            'webpack/hot/dev-server',
            'app.js'
        ],
        vendor: ["jquery", "bootstrap", "react", "metismenu", "vendor/sb-admin-2", "lodash", "vex-js" , "vendor/bootstrap-notify.min", "utils/crypto"]
    },
    output: {
        path: __dirname + "/",
        filename: "bundle.js"
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.bundle.js'),
        new webpack.ProvidePlugin({
            $: 'jquery',
            _: 'lodash'
        }),
        new ExtractTextPlugin("component.css")
    ],
    module: {
        loaders: [
            { 
                test: /\.jsx?$/, 
                loaders: ['react-hot', 'babel'], 
                include: "app.js" ,
                exclude: /node_modules/
            },
            { 
                test: /\.css$/, 
                loader: ExtractTextPlugin.extract('style-loader', 'css-loader!autoprefixer-loader')
            },
            { 
                test: /\.scss$/, 
                loader: ExtractTextPlugin.extract(
                    'style-loader', 
                    'css-loader?sourceMap!autoprefixer-loader!sass-loader?outputStyle=expanded&sourceMap=true&sourceMapContents=true'
                )
            },
            { 
                test: /^((?!config).)*\.jsx?$/, 
                exclude: /(node_modules|app\/components)/, 
                loader: "babel",
                query: {
                    presets: ['react', 'es2015', 'stage-1'],
                    plugins: ['transform-runtime']
                }
            },
            { 
                test: /\.html$/, 
                loader: 'raw' 
            },
            {
              test: /\.(png|jpg|gif)$/,
              loader: 'url-loader?limit=5000&name=img/img-[hash:6].[ext]'
            },
            { 
                test: /\.woff$/, 
                loader: "url-loader?limit=10000&minetype=application/font-woff" 
            },
            { 
                test: /\.ttf$/,    
                loader: "file-loader" 
            },
            { 
                test: /\.eot$/,    
                loader: "file-loader" 
            },
            { 
                test: /\.svg$/,    
                loader: "file-loader" 
            },
            { 
                test: /[\/\\]node_modules[\/\\]jquery[\/\\]dist[\/\\]jquery\.js$/,
                loader: "expose?$" 
            },
            { 
                test: /[\/\\]node_modules[\/\\]jquery[\/\\]dist[\/\\]jquery\.js$/,
                loader: "expose?jQuery" 
            },
            { 
                test: /\.*sb-admin-2\.js$/,
                loader: "script" 
            },
            { 
                test: /\.*crypto\.js$/,
                loader: "script" 
            },
            {
                test: /\.modernizrrc$/,
                loader: "modernizr"
            }
        ]
    },
    devtool: 'source-map'
    };

I don't know if it's babel or something else. This is making me crasy.

Thank you!

**Comment by gaearon** [comment]
Hi! This is a React Hot Loader issue tracker rather than a Webpack support forum, so I’m afraid we can’t help you with this one. Cheers!

**Comment by matsch01** [comment]
@cornerolive did you find a solution to this issue? Having the same problem and can't find a solution.

**Comment by albertolive** [comment]
Yes, I had to update react-hot-loader to latest version and added to webpack dev file this:

 `
query: {
    presets: ['react-hmre']
  }
`

**Comment by gaearon** [comment]
It doesn't really make sense to use `react-hot-loader` and `react-hmre` together.
