### ISSUE TITLE
why does my config work at all?

### ISSUE THREAD

**Issue by pdeva** [gaearon/react-hot-loader#227]
My webpack config is a lot smaller than what is described in the docs and doesnt have the extra entry points defined. why does it still manage to hot reload components then?

```
module.exports = {
	devtool: "cheap-eval-source-map",
	entry: [
		"./app/main.js"
	],
	output: {
		path: "./js",
		filename: "bundle.js"
	},
	module: {
		loaders: [
			{ test: /\.css$/, loader: "style-loader!css-loader"},
			{ test: /\.js$/,  exclude: /node_modules/, loaders: ["react-hot"] }
		]
	}
};
```

my webpack command line:

```
webpack-dev-server --hot --inline --progress --colors --port 8082
```

are the other entry points defined in the docs simply not needed? how am i able to hot reload components then?

**Comment by gaearon** [comment]
The CLI options of `webpack-dev-server` do some of the tricks but they also cause issues in some cases so we don’t recommend them.
