### ISSUE TITLE
Nothing follows after [Waiting for update signal from WDS...]

### ISSUE THREAD

**Issue by KaiseR-sama** [gaearon/react-hot-loader#228]
I'm trying hot-reload on a simple react,yet i can't seem to enable it. The terminal says that the webpack is built but i still need to refresh the page for the changes to be seen.

I am stuck in [HMR] Waiting for update signal from WDS... in the browser console. Any clue as to how to solve this problem will be very helpful, Thanks in advance

**Comment by gaearon** [comment]
Very hard to say without a project reproducing the issue.
