### ISSUE TITLE
Please create a new project Repo for Angular2 and Hot reload...

### ISSUE THREAD

**Issue by born2net** [gaearon/react-hot-loader#229]
I think it would be awesome if we had our own Angular2 hot reload Github repo with source and samples. 

IMHO ng2 will revolutionize the JS world, I believe in a +1 year you will see almost all new projects adopting ng2 (tx to google and microsoft both standing behind ng2, and google calling ng2 - One Framework and consolidating the JS world into 1 platform that does it all and very well,, i.e.: ng2-univeral, ng2-animate, etc, all coming from google and ts from microsoft ;) and so let's get this Hot reload to be the de-fact tool for ng2, but we need a new project repo and most impotently, no dependencies on React!

tx

Sean

**Comment by SeriousM** [comment]
Oh yes, that would be sooo awesome! Please!

**Comment by filoxo** [comment]
You mean like what's already available with [`angular2-hot-loader`](https://github.com/mgechev/angular2-hot-loader)? More info on [Minko's blog post about Angular 2 Hot Loader](http://blog.mgechev.com/2015/10/26/angular2-hot-loader-hot-loading-tooling/). It is still rough, but then again Angular is still in beta so... use at your own discretion with that caveat.

**Comment by gaearon** [comment]
This is a React specific project but it’s great to see similar tools exist for Angular!
