### ISSUE TITLE
Relay and React hot loader

### ISSUE THREAD

**Issue by peterpine83** [gaearon/react-hot-loader#230]
I have gone through the troubleshooting in the the documentation but I cant seem to figure out why I keep getting [HMR] The following modules couldn't be hot updated: (They would need a full reload!) message. I am wondering if it because relay wraps the react components in containers. I would love to be able to use this tool, any help would be appreciated.

**Comment by Schniz** [comment]
@peterpine83 have you fixed it?

**Comment by Schniz** [comment]
as stated in https://github.com/fortruce/relay-skeleton/issues/1#issuecomment-131881653, we can in the meantime split the containers and the stateless components into 2 separate files (and making sure the stateless component is a `class`)

**Comment by Willianvdv** [comment]
fwiw: I fixed this by exporting the container and the component, no need to split into multiple files.

My `person.js`:
```
import React from 'react';
import Relay from 'react-relay';

export class _Person extends React.Component { ... }
export var Person = Relay.createContainer(_Person, { ... })
```

My `application.js`:
```
import { Person } from './Person'
```

**Comment by cdroulers** [comment]
It would be very useful to have this small workaround in the docs! Google sent me here and it solved my problem immediately!

**Comment by Glavin001** [comment]
Thank you, @Willianvdv ! 😃

**Comment by nsuthar0914** [comment]
@Willianvdv thanks !
