### ISSUE TITLE
Throws error with class properties that only have getters

### ISSUE THREAD

**Issue by georeith** [gaearon/react-hot-loader#231]
Throws error:
`Uncaught TypeError: Cannot set property x of #<Y> which has only a getter`

The culprit is in **makeAssimilatePrototype.js**:

```
 function patchProperty(proto, key) {
    proto[key] = storedPrototype[key];

    if (typeof proto[key] !== 'function' ||
      key === 'type' ||
      key === 'constructor') {
      return;
    }

    proto[key] = wrapMethod(key);

    if (storedPrototype[key].isReactClassApproved) {
      proto[key].isReactClassApproved = storedPrototype[key].isReactClassApproved;
    }

    if (proto.__reactAutoBindMap && proto.__reactAutoBindMap[key]) {
      proto.__reactAutoBindMap[key] = proto[key];
    }
 }
```

Specifically:

`proto[key] = storedPrototype[key];` and  `proto[key] = wrapMethod(key);`

In this case a React component class referenced an instance of another non-react class that has only getters for some of its properties and this error occured.

Tested on both v1.3.0 and v2.0.0-alpha-4

**Comment by gaearon** [comment]
`v2.0.0-alpha-4` uses [`react-hot-api@0.5.0-alpha.3`](https://github.com/gaearon/react-hot-loader/blob/v2.0.0-alpha-4/package.json#L7) which [doesn’t contain](https://github.com/gaearon/react-hot-api/tree/v0.5.0-alpha-3/modules) `makeAssimilatePrototype`.

I’m closing as it doesn’t affect v2 alpha, and won’t affect v3 that I’m working on right now. I don’t have plans to backport the fixes to v1.x, sorry!
