### ISSUE TITLE
Why does my browser refresh instead of just push the changes?

### ISSUE THREAD

**Issue by mjhamm75** [gaearon/react-hot-loader#232]
I am trying to set up Hot Module Replacement (HMR), but my browser refreshes instead of just hot swapping.  Here is my `webpack.config.js`:

    module.exports = {
    	devtool: 'eval-source-map',
    	entry: {
    		app: [
    			path.join(__dirname, './App.js'),
    			'webpack-hot-middleware/client?reload=true'
    		],
    		vendors: ['react', 'react-router']
    	},
    	output: {
    		filename: './bundle.[hash].js',
    		chunkFilename: './[id].[hash].js',
    		path: path.join(__dirname,'/dist'),
    		publicPath: '/'
    	},
    	module: {
    		loaders: [
    			{
    				test: /\.js?$/,
    				exclude: /(node_modules)/,
    				loader: 'babel',
    				query: {
    					presets: ['react', 'es2015']
    				}
    			}, {
    				test: /\.scss$/,
    				loaders: ["style", "css", "sass"]
    			},
    			{
    				test: /\.(png|jpg)$/,
    				loader: 'url-loader?limit=8192'
    			}
    		]
    	},
    	plugins: [
    		new HtmlWebpackPlugin({
    			template: 'index.ejs'
    		}),
    
    		new CommonsPlugin({
    			name: 'vendors',
    			filename: 'vendors.js',
    			minChunks: Infinity
    		}),
    
    		new CleanWebpackPlugin(['dist'], {
    			root: __dirname,
    			verbose: true,
    			dry: false
    		}),
    
    		new webpack.HotModuleReplacementPlugin()
    	]
    };

I am serving it up with `express`

    var app = express();
    
    var compiler = webpack(config);
    var middleware = webpackMiddleware(compiler, {
      publicPath: config.output.publicPath,
      contentBase: 'src',
      stats: {
        colors: true,
        hash: false,
        timings: true,
        chunks: false,
        chunkModules: false,
        modules: false
      }
    });
    
    app.use(middleware);
    app.use(webpackHotMiddleware(compiler));
    
    app.use(express.static('./dist'));
    
    app.get('*', function(req, res) {
      res.write(middleware.fileSystem.readFileSync(path.join(__dirname, 'dist/index.html')));
      res.end();
    });
    
    var server = app.listen(3000, function () {
      var host = server.address().address;
      var port = server.address().port;
    
      console.log('Example app listening at http://%s:%s', host, port);
    });

Here is my `App.js`

    const rootRoute = {
    	component: 'div',
    	childRoutes: [ {
    		path: '/',
    		component: Main,
    		childRoutes: [
    			require('./routes/reports')
    		]
    	} ]
    };
    
    render(
    	<Router history={browserHistory} routes={rootRoute} />, document.getElementById('app')
    );

Which `require` in my `reports`

    module.exports = {
    	path: 'reports',
    	getComponents(location, cb) {
    		require.ensure([], (require) => {
    			cb(null, require('./components/Reports'))
    		})
    	}
    }

And that particular `component`:

    class Reports extends React.Component {
    	render() {
    		let style = {
    			background: 'green'
    		};
    		return (
    				<div style={style}>
    					<h2>Reports</h2>
    				</div>
    		)
    	}
    }
    
    module.exports = Reports;

When I change the `style` color in my `component`, the `style` is updated, but it refreshes the whole page.  

What is wrong with my `config`?

**Comment by yazonnile** [comment]
just a quick shot :)
```js
'webpack-hot-middleware/client?reload=true'
```
`reload=true` ??
`reload` - Set to true to auto-reload the page when webpack gets stuck.
https://www.npmjs.com/package/webpack-hot-middleware

**Comment by mjhamm75** [comment]
Thanks, I tried that.  It didn't work for me.

**Comment by gaearon** [comment]
You are using `react-hot-loader` yet there is no `react-hot-loader` in your `loaders` configuration. So it’s never really used.
