### ISSUE TITLE
prototypes of 3rd-party libs corrupted with storedPrototype

### ISSUE THREAD

**Issue by acthp** [gaearon/react-hot-loader#233]
I'm rendering a highchart graph inside a `<div>` from a react component. The react-hot-api appears to be corrupting the prototypes of the classes of the highchart lib. The chart fails when a method is missing, and the prototype is a function referencing storedPrototype, instead of the correct highchart class.

Not sure what rhl is doing here, so not sure how to work around it.

**Comment by gaearon** [comment]
Can you show the relevant code? This is a bit vague to help you.

**Comment by acthp** [comment]
yeah, I'm not sure what code would be helpful. The react component is roughly like this (pattern for making react ignore DOM manipulation by 3rd party lib):

```javascript
render(): {return <div ref='root'/>},
shouldComponentUpdate(): {return false},
componentDidMount(): { drawHighchart(this.refs.root, this.props); }
````

The result is an error thrown on 1st load (not after a hot load event) in highcharts, on this line:
```javascript
series.pointClass.prototype.applyOptions.apply(pt, [data[i]]);
```

because series.pointClass is some react-hot-api thing instead of the Highchart object. From chrom devtools:

```javascript
series.pointClass
function () {
      if (storedPrototype[key]) {
        return storedPrototype[key].apply(this, arguments);
      }
    }
```

From a brief inspection of the code, it looks like react-hot-api walks a list of components & modifies them in this way, but I'm not sure how it's discovering & modifying the highchart object.

**Comment by acthp** [comment]
Also, it works fine with hmr disabled.

**Comment by acthp** [comment]
It looks a bit like rhl modifies any exported object with a render() function. Is that correct?

**Comment by acthp** [comment]
That does appear to be the issue. If I wrap the export in another object, like

```javascript
module.exports = {Highcharts: Highcharts}
```

the problem goes away, presumably because only the top-level keys are searched for objects with `render` method.

Might be nice to document this behavior, as the failure mode is inscrutable.

**Comment by gaearon** [comment]
Yeah. I’m closing as it’s not directly actionable right now. This is fixed in the upcoming rewrite (RHL 3), and there are no plans to fix this in earlier versions. Please feel free to watch the repo for the RHL 3 announcement which might be up in a few weeks.
