### ISSUE TITLE
"Page reload require"

### ISSUE THREAD

**Issue by yazonnile** [gaearon/react-hot-loader#234]
Hi there. Maybe it would be a stupid question, but I can't recognize, how to get any event or method call when this comes
`The following modules couldn't be hot updated: (They would need a full reload!)`

So, all I need, just a possibility to reload the page via browser-sync for example when get this message.
Thx!

**Comment by gaearon** [comment]
I think replacing `webpack/hot/only-dev-server` with `webpack/dev-server` in your `entry` configuration in `webpack.config.js` should have the desired effect.
