### ISSUE TITLE
Future of React Hot Loader

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#235]
FYI, I published a post today:
https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf

**Comment by Prophet32j** [comment]
I'm guessing that the react transform library will remove the "highly experimental" language from it?

**Comment by gaearon** [comment]
Nah, they’re all highly experimental 😄 . This doesn’t mean you shouldn’t use them—I’m just a bit frustrated by the trend of piling experimental tools on top of each other, calling it a “boilerplate”, marketing it as a best practice, and thus alienating beginners from JavaScript development who rightly think these setups are crazy.

As for the future—I’m merging these projects with some lessons learned. Stay tuned.
