### ISSUE TITLE
[HMR]  - 76 Warning Message

### ISSUE THREAD

**Issue by caiyongmin** [gaearon/react-hot-loader#237]
Components are rendered on Node Experss server, I'm getting this warning when I edit all my React components instead have refresh:

```bash
[HMR] Waiting for update signal from WDS...
bundle.js:605 [WDS] Hot Module Replacement enabled.
2bundle.js:608 [WDS] App updated. Recompiling...
bundle.js:673 [WDS] App hot update...
bundle.js:8043 [HMR] Checking for updates on the server...
bundle.js:8068 [HMR] The following modules couldn't be hot updated: (They would need a full reload!)
bundle.js:8070 [HMR]  - 76
bundle.js:8075 [HMR] Nothing hot updated.
bundle.js:8029 [HMR] App is up to date.
```

webpack config:

```javascript
var path = require('path')
var webpack = require('webpack')

module.exports = {
	entry: {
		bundle: [
			'webpack-dev-server/client?http://127.0.0.1:3000/',
			'webpack/hot/only-dev-server',
			path.resolve(__dirname, './assets/index')
		]
	},
	output: {
		path: path.resolve(__dirname, 'build'),
		filename: '[name].js',
		publicPath: 'http://127.0.0.1:3000/dev/'
	},
	resolve: {
		extensions: ['', '.js', '.jsx']
	},
	module: {
		loaders: [
			{
				test: /\.js[x]?$/,
				exclude: /node_modules/,
				loaders: ['react-hot', 'babel-loader']
			}
		]
	},
	plugins: [
		new webpack.HotModuleReplacementPlugin(),
    	new webpack.NoErrorsPlugin()
	]
}
```

webpack dev server:

```javascript
var webpack = require('webpack');
var WebpackDevServer = require('webpack-dev-server');
var config = require('../webpack.config');

new WebpackDevServer(webpack(config), {
	publicPath: config.output.publicPath,
	hot: true,
	stats: { colors: true },
	headers: { 'Access-Control-Allow-Origin': '*'},
	historyApiFallback: true
}).listen(3000, 'localhost', function (err, result) {
  	if (err) console.log(err);
  	console.log('Webpack dev server listening at localhost:3000');
});
```

index.ejs:

```html
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <link rel='stylesheet' href='/stylesheets/style.css' />
  </head>
  <body>
    <h1><%= title %></h1>
    <p>Welcome to <%= title %></p>

    <div id="container"></div>

    <script src="http://127.0.0.1:3000/dev/bundle.js"></script>
  </body>
</html>
```

**Comment by caiyongmin** [comment]
it maybe about `unacceptedModules` field. when see the source code.

![image](https://cloud.githubusercontent.com/assets/11053605/14210751/fc8943d6-f85c-11e5-9a72-e5851464f5d3.png)

**Comment by caiyongmin** [comment]
I fix it, the problem is not about above three files, it's my fault, I straight edit root component, I should separate to some file and require what i need. Like below said:

> ###The following modules couldn't be hot updated: (They would need a full reload!)
> If you get this warning when editing a root component, this may be because you don't export anything > > from it, and call React.render from there. Put your root component in a separate file (e.g. App.jsx) and > require it from index.js where you call React.render.

**Comment by caiyongmin** [comment]
I fix it, the problem is not about above three files, it's my fault, I straight edit root component, I should separate to some file and require what I need. Reference your [Troubleshooting.md](https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md) doc.

**Comment by gaearon** [comment]
👍

**Comment by jDeppen** [comment]
My issue was fixed when I switched my root component from
`class LayoutContainer extends React.PureComponent {`
to
`class LayoutContainer extends React.Component {`

Note: this is [solved in 3.x](https://github.com/gaearon/react-hot-loader/pull/270#issuecomment-216218478)
