### ISSUE TITLE
Cannot read property 'length' of undefined in bundle.js (hotDownloadManifest)

### ISSUE THREAD

**Issue by EliasJorgensen** [gaearon/react-hot-loader#239]
Hi, i'm not really sure what's going on. I can't find anything about it in the troubleshooting page.
It's been working fine for some time, but now whenever the browser is trying to hot reload, i get the following error:
 `Uncaught TypeError: Cannot read property 'length' of undefined - bundle.js:256`

I opened up bundle.js to find the error, and the following showed up:
![bundle.js](http://i.imgur.com/lXg9lkq.png)

**Comment by gaearon** [comment]
This is an issue in Webpack, please feel free to report it there. We can’t fix it here.

**Comment by srinivasdamam** [comment]
@EliasJorgensen Did you found the solution? I'm also facing the same issue.
