### ISSUE TITLE
Consider making <AppContainer> take children

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#244]
Currently it looks like this:

```js
<AppContainer
  component={Root}
  props={{ store }} /* depending on what you want to pass */
/>
```

As suggested by @halt-hammerzeit in https://github.com/gaearon/redux-devtools/commit/64f58b7010a1b2a71ad16716eb37ac1031f93915#commitcomment-17142917 we might want to make it accept children instead:

```js
<AppContainer>
  <Root store={store} />
</AppContainer>
```

I think I’m on board with this. A pull request is welcome!

**Comment by alexisvincent** [comment]
@gaearon This can be closed now I think
