### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#247]
Can you imagine we managed so far without it?
3.0 has some tests so we should do it.

**Comment by nfcampos** [comment]
@gaearon I think you have to be the one to enable Travis no?

**Comment by gaearon** [comment]
I just activated it. Can you try adding `.travis.yml` to `next`?

**Comment by nfcampos** [comment]
yep I'll do that

**Comment by nfcampos** [comment]
I've added it. it appears to be working

**Comment by gaearon** [comment]
Appreciated!
