### ISSUE TITLE
Get Working with JSPM

### ISSUE THREAD

**Issue by alexisvincent** [gaearon/react-hot-loader#256]
@guybedford, for some reason ```jspm install npm:react-hot-loader@^3.0.0-alpha``` results in index.js not being downloaded. So importing AppContainer fails here. Any ideas?

**Comment by guybedford** [comment]
@alexisvincent thanks for testing this. I've added a fix in https://github.com/jspm/npm/commit/f8cbbd9bdfbdad5281a9df2d97cf37392dd7bf35#diff-59adaa9915a15ff8ed1f21fd655d5378R297 for the next release of jspm - we weren't treating the `index.js` file as an exception to the `files` array.

This will apply in the next jspm beta, so this can be closed here.

**Comment by alexisvincent** [comment]
Cool Cool 👍
