### ISSUE TITLE
Pattern for component updates outside the import chain

### ISSUE THREAD

**Issue by gadicc** [gaearon/react-hot-loader#259]
In my current project we support optional packages which add React components via it's own registration system, along the lines of.

```js
import Extension from 'extensions';
import Something from './component/something';

Extension.addComponent(Something);
```

The app itself also imports from `extensions`, so the import chain is broken; but in any case, the component is not directly imported and *is rendered via an array passed in as a prop* that may by modified during the life of the app.

This worked before with `transform-hmre` where components self-accepted.  For RHLv3, I've solved this by catching updates at the point where the component is first passed on, like this:

**Package entry point**:

```js
import ComponentUpdater from 'component-updater'; // see below
import Extension from 'extensions';
import OrigSomething from './component/something';

const Something = ComponentUpdater(OrigSomething);
Extension.addComponent(Something);

if (module.hot) {
  module.hot.accept('./component/something', function() {
    const NextSomething = require('./component/something').default;
    Something.updateWith(NextSomething);
  }
}
```

**"ComponentUpdater" HOC that keeps track of current instances**

```js
import React, { Component } from 'react';
import deepForceUpdate from 'react-deep-force-update';

const ComponentUpdater = (component) => {
  return class ComponentUpdater extends Component {
    static instances = new Set();

    static updateWith(component) {
      for (let instance of ComponentUpdater.instances)
        instance.setState({ component })
    }

    constructor(props) {
      super(props);
      this.state = { component };
      ComponentUpdater.instances.add(this);
    }

    componentDidUpdate(prevProps, prevState) {
      if (prevState.component !== this.state.component)
        deepForceUpdate(this);
    }

    componentWillUnmount() {
      ComponentUpdater.instances.delete(this);
    }

    render() {
      const ComposedComponent = this.state.component;
      return ( <ComposedComponent {...this.props} /> );
    }
  }
}

export default ComponentUpdater;
```

Not sure how good a pattern this is but it works pretty well for my use-case.  If it's an acceptable pattern maybe it could be included in the package, as I'm sure others might run into this.  In theory it could be it's own package, but the way it ties into `deepForceUpdate` makes it more useful for react hotloading, specifically.

**Comment by gaearon** [comment]
Let’s keep this open for now.
It would be helpful if you could reduce this to a simple example based on https://github.com/gaearon/react-hot-boilerplate/pull/61.
We can look into simplifying it then, or providing a utility for this.

**Comment by gadicc** [comment]
Thanks.  I'm away for the long weekend but will set something up next week.

**Comment by gadicc** [comment]
Actually, let me close this.  I don't think many other people will use this pattern (necessitated by historical reasons).  I'm going to refactor the project and I'll re-open if I come across something that needs this again.
