### ISSUE TITLE
Frozen Reload

### ISSUE THREAD

**Issue by onzag** [gaearon/react-hot-loader#261]
Basing myself on the boilerplate I tried to create a small hot reload scenario and what I got was totally mind blowing.

Here the configuration https://gist.github.com/onzag/49147a75b45a53131935f7c52541b7df

1. Reloads would totally fail; they would complain about the missing json file (404) message with the updates and said I'll need to reload.
2. After I reloaded the state of the screens will keep the same no matter what, I tried reloading the webpack server, changing the configuration, hard reloading the browser, clearing the cache; etc... it doesn't webpack by itself I have to do it manually.

**Comment by hawkup** [comment]
I think you didn't install react-hot-loader and config.
Install [react-hot-loader](https://github.com/gaearon/react-hot-boilerplate/blob/master/package.json#L39)
and I think should to seperate babel config to [.babelrc](https://github.com/gaearon/react-hot-boilerplate/blob/master/.babelrc) file, it easier to setup.
Change the config and try run server again.
```
# .babelrc
{
  "presets": ["react", "es2015", "stage-0"],
  "plugins": ["transform-decorators-legacy"]
}
```
```
# webpack.config.js
module: {
	loaders: [
		{
			test: /\.jsx?$/,
			loaders: ['react-hot-loader', 'babel'],
			exclude: /node_modules/
		}
	]
}
```

referrence: [react-hot-boilerplate](https://github.com/gaearon/react-hot-boilerplate)

**Comment by gaearon** [comment]
Yeah, you are not using `react-hot-loader` anywhere so it doesn’t work.
Please use https://github.com/gaearon/react-hot-boilerplate.
Also check out 3.0 branch which is the next major release: https://github.com/gaearon/react-hot-boilerplate/pull/61.
