### ISSUE TITLE
Please review my blog: "Enabling Webpack’s HMR In React — The Missing Manual"

### ISSUE THREAD

**Issue by rajaraodv** [gaearon/react-hot-loader#268]
"Enabling Webpack’s HMR In React — The Missing Manual" https://medium.com/@rajaraodv/232336dc0d96

If you have suggestions or corrections, please select the text and Medium will show a tooltip w/ a lock symbol. If you click on that tooltip, it will allow you to add "private" comments and I'll get notifications.

I plan to post this Saturday afternoon. *You can make suggestion anytime, even after it's posted and I'll update the blog 😃

**Comment by VladShcherbin** [comment]
@rajaraodv hey, an app with a router example would be great

**Comment by gaearon** [comment]
This looks amazing! I wish you wrote our docs 😄 .
I’d appreciate you updating the article when version 3 is out.
