### ISSUE TITLE
Enable ESLint

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#274]
I’d go with airbnb config. Semicolons ftw 😄 .
If somebody gets to it, might as well enable Travis (#247).
This should be done before 3.0.

Don’t forget the development happens on the `next` branch.

**Comment by nfcampos** [comment]
airbnb config is too agressive for the tests, I was trying to get this set up but found myself having to disable disabling at least these for the tests (at least these, I only looked at one file, this is kind of boring haha)
<img width="351" alt="screenshot 2016-05-02 20 18 30" src="https://cloud.githubusercontent.com/assets/56902/14965073/3c4dfb02-10a3-11e6-93fe-946111c0e15e.png">

Should we have a different .eslintrc for the tests folder?

**Comment by gaearon** [comment]
>Should we have a different .eslintrc for the tests folder?

Yea, this is usually sensible.

**Comment by gaearon** [comment]
Done in #280.
