### ISSUE TITLE
Doesn’t work with React.createFactory()

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#277]
The issue is explained here: https://github.com/gaearon/react-hot-loader/issues/276#issuecomment-216302815. It seems like we’d need to monkeypatch `React.createFactory` because it bypasses `React.createElement` and uses the internal `ReactElement` module directly.

**Comment by nfcampos** [comment]
theres no need to patch React.DOM.* beause we only care about conposite components right?

**Comment by gaearon** [comment]
Haha, excellent point! I’m being silly.

**Comment by nfcampos** [comment]
:) also, how about patching only the internal react/lib/ReactElement? surely they all import createElement from that one no?

**Comment by gaearon** [comment]
We could do this. It wouldn’t work in the future though when React ships [flat bundles](https://github.com/facebook/react/issues/6351). Also doesn’t work for people who use precompiled builds of React. (Not sure we really want to support it, but right now we do.)

**Comment by nfcampos** [comment]
I've the failing test case for this on #278

**Comment by gaearon** [comment]
Fixed in 3.0.0-beta.2.
