### ISSUE TITLE
Crashes during server rendering

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#283]
https://github.com/gaearon/redux-devtools/commit/64f58b7010a1b2a71ad16716eb37ac1031f93915#commitcomment-17332926
https://github.com/facebook/react/issues/6689

For now, we should do something like

```js
class AppContainer {
 ...
}

if (typeof window !== 'undefined') {
  AppContainer.prototype.unstable_handleError = ...
}
```

**Comment by calesce** [comment]
Closing this since the original React issue was fixed. I've also tested rendering `<AppContainer />` on the server and it doesn't crash (even though most people will only need to use it in the client bundle)
