### ISSUE TITLE
hot loader do not work on my project

### ISSUE THREAD

**Issue by javaxiu** [gaearon/react-hot-loader#286]
my webpack.config.js looks like
```
entry: {
        vendor : [
            'webpack-dev-server/client?http://localhost:3000',
            "webpack/hot/only-dev-server",
            'webpack-hot-middleware/client'
        ],
        index : [
            path.resolve(__dirname, 'src/index.jsx')
        ]
    },
    output: {
        path: path.resolve(__dirname, '/build'),
        filename: '[name].js',
        publicPath: '/build'
    },
    module: {
        loaders: [
            { test: /\.jsx?$/, loaders: ['react-hot', 'jsx?harmony'], include: path.join(__dirname, 'src') }
        ]
    },
    devServer: {
        hot: true,
        inline: true
    },
    plugins: [
        new webpack.NoErrorsPlugin(),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.js')
    ],
    externals:{
        'react':"React",
        'react-dom':"ReactDOM"
    }
```
it works when i reload page manually, but when i edit index.jsx file...
[HMR] Checking for updates on the server...
vendor.js:8255 [HMR] The following modules couldn't be hot updated: (They would need a full reload!)
vendor.js:8257 [HMR]  - 1
vendor.js:8262 [HMR] Nothing hot updated.
vendor.js:8216 [HMR] App is up to date.
 
react-hot-loader version : 1.3.0
any suggest? thanks

**Comment by zdavis** [comment]
Hard to say what the problem is without seeing a repo that reproduces the problem. It's a shot in the dark, but I ran into similar behavior on my project after I'd set everything up, but had neglected to include the conditional ReactDom.render call that you see here in the example:

https://github.com/gaearon/react-hot-boilerplate/blob/next/src/index.js#L14

**Comment by gaearon** [comment]
This is an issue about 1.x. Unfortunately 1.x is no longer supported so this is not actionable for us.
Please try 3.x beta: https://github.com/gaearon/react-hot-boilerplate/pull/61.
