### ISSUE TITLE
Asynchronous React Router v3 routes fail to hot-reload

### ISSUE THREAD

**Issue by phyllisstein** [gaearon/react-hot-loader#288]
Hey there! I'm having some difficulty getting `react-hot-loader@3.0.0-beta.1` to hot-reload changes to views that are passed to React Router as lazy-loaded POJOs. Updating a view class triggers the usual console messages and throws the warning about changing `<Router history>`, but the rendered output doesn't refresh. Curiously, though, changing the components that the views require immediately hot-reloads them, even within the selfsame non-reloading async views.

Here's a quick screencast demonstrating the issue:
![](http://g.recordit.co/eTEtzVqvpM.gif)

...and here's the code base that screencast's taken from: https://github.com/phyllisstein/hildy/tree/react-hot-3. (The `master` branch of which repo is still using `react-transform-hmr` without any evident issues.)

I'd be grateful for any suggestions you can provide, and happy to offer more troubleshooting info if I can! Thanks for looking into this.

**Comment by gaearon** [comment]
Thanks for a repro case. Here’s another great repro case: https://github.com/gaearon/react-hot-boilerplate/pull/61#issuecomment-218835358.

We’ll need to look into this before releasing 3.0. Probably something funky related to how `require.ensure` works with hot reloading. Also would be great to check if it’s still an issue with Webpack 2 ES modules.

**Comment by phyllisstein** [comment]
It looks like this has something to do with using the `es2015-webpack` Babel preset, so I think you may be right. Another repo I've been working with (<https://github.com/ignota/issue-0/tree/react-hot-3>) is able to do _some_ view reloading using `es2015-loose` in place of `es2015-webpack-loose`. Seems to still have some issues---in particular, the hot update usually fires once or twice then stops---but I think they could have something to do with `redux-saga`. Gonna try switching to `redux-thunk` and seeing if that improves things at all.

**Comment by phyllisstein** [comment]
`redux-thunk`, lovely though it is, didn't get me too much further. The first change to a view registers with HMR, but logs a warning to the console: "[HMR] Unexpected `require(583)` from disposed module 581." (581 is my main `App` component, and 583 is the view that's being hot-updated.) After that, every subsequent change is detected by the dev server and the hot reloader and loaded by the browser, but fails to update the view. Quick screencast again:

![2016-05-21 05_35_49](https://cloud.githubusercontent.com/assets/2207980/15447604/5287073e-1f16-11e6-9a2e-591e23bad17a.gif)

**Comment by MrEfrem** [comment]
With webpack 2 in System.import HMR too doesn't work.

**Comment by hoschi** [comment]
Beta.2 has the same issue.

MrEfrem <notifications@github.com> schrieb am So., 12. Juni 2016, 22:41:

**Comment by leecade** [comment]
👍

**Comment by rosskevin** [comment]
I'm using this with [bundle-loader?lazy](https://github.com/webpack/bundle-loader), which ultimately uses `require.ensure`.  I'm hoping that the fix for this will ultimately work for me as well.  [Sample repo](https://github.com/rosskevin/my-relay-starter-kit)

**Comment by hoschi** [comment]
Now it stopped working for me with beta.0. I had this case already some days ago, which was fixed by a `rm -rf node_modules; npm install` but no luck this time. I cleaned up my `/tmp`, npm cache, babel-cache, but still broken.

**Comment by rosskevin** [comment]
I noticed a small difference - working scenarios I have seen are using `node` to run the server, whereas I'm running `babel-node`, just wondering if this transpilation is affecting the hot reloader?

**Comment by rosskevin** [comment]
When routes/history are imported in the `index.js` and passed down as props to the `<App/>`, it appears to kill hot reloading and issues `full reload needed`.  I only moved my routes/history up to the index to avoid `[react-router] You cannot change <Router routes>; it will be ignored`.

I'll move my routes/history back as hot reloading is more important, then I'll try to add back the async routes.

**Comment by rosskevin** [comment]
With async routes, it appears that `Foo` **will** reload, while `FooComponent` **will not** reload:

```javascript
import React from 'react'

export default function (props:any) {
  return (
    <div>Foo3</div>
  )
}
```

```javascript
import React, {Component} from 'react'

export default class FooComponent extends Component {
  render () {
    return (<div>FooComponent2</div>)
  }
}
```

**Comment by dkulichkin** [comment]
@dferber90, @gaearon, @rosskevin 
Guys, what is the last status with an issue? Is it still really no way to leverage hot reloading and chunking working together simultaneously when in development so f.e. when I want a hot reloading to work I need to sacrifice chunking and assemble everything into a main bundle?

`if (process.env.NODE_ENV !== 'production') {
    require('...')
    require('...')
    ... // and so on - listing of all async top react components, f.e. redux containers
}`

**Comment by dferber90** [comment]
@dkulichkin Yes, that workaround seems to be the only way for now. As the *sacrifice* of not being able to use code-splitting is only for development, this isn't that much of a problem is it?

Of course it would be nice if this wasn't necessary, but I don't even know why that fixes the problem in the first place so a lot of investigation would be necessary.

The code you provided isn't helpful because it leaves out the important parts (importing the component that is being split out in the second snippet). Your snippets only contain `...` there.
See https://github.com/gaearon/react-hot-boilerplate/pull/61#issuecomment-218982382 for how to set things up.

**Comment by dkulichkin** [comment]
@dferber90 the main point of having a chunking in development is the profiling, f.e. with help of such tools like webpack-dashboard. That allows for instance immediately see an impact of the changes to files size without necessity to build and switch to prod. So the drawback is pretty much serious.

Anyway what's a main bottleneck in this issue making only pure stateless components reloaded in chunks? Router, react-hot-reloader, bundler?

Regarding '...' character in my snippet - that's just skipped pathes to component files, nothing else

**Comment by sthzg** [comment]
Not sure if I am on the same page and if it is really related, but I ran into this problem and got the views updating by additionally registering a`module.hot.accept` in the `require.ensure()` callbacks. E.g. like this

```js
getChildRoutes(partialNextState, callback) {
  require.ensure([], function (require) { // eslint-disable-line

    if (module.hot) {
      module.hot.accept('../routes/Blog', function () {
        callback(null, [
          require('../routes/Blog').default,
        ]);
      });
      module.hot.accept('../routes/Errors', function () {
        callback(null, [
          require('../routes/Errors').default,
        ]);
      });
    }

    callback(null, [
      require('../routes/Blog').default,
      require('../routes/Errors').default
    ]);
  });
},
```

**Comment by dkulichkin** [comment]
@sthzg Did you by chance also manage to make it working with a webpack-bundle loader?

**Comment by sthzg** [comment]
@dkulichkin No, sorry. So far I have only tried it with an app that uses code splitting based on the `react-router` async routes.

**Comment by calesce** [comment]
Just wanted to add that I was playing around with `require.ensure` and RR, using @sthzg's solution, and it seems to work fine with `getChildRoutes`, but not `getComponent`.

It looks like the `getComponent` callback can't be called multiple times (tested out with `setTimeout` loading a different component). Another reason to move on to RR4? 😛

**Comment by flut1** [comment]
I worked around the getComponent() issue by adding a key prop to Router that changes on each hot update. This will force a different Router instance to be created, and re-executing getComponent() calls. This also fixed the `You cannot change <Router router>` warnings. Not sure if creating new Router instances causes other (performance) issues but it seems to work for me. 

```
// create key variable
let routerKey = 0;

// initial router rendering
<Router key={routerKey} ... />

if (module.hot) {
 module.hot.accept('./containers/Root', () => {
  ...
  // first bump the key
  renderKey++;
  // re-render
  render(
    <AppContainer>
       ...
      <Router key={renderKey} ... />
    </AppContainer>
  , mountNode);
 });
}
```

**Comment by calesce** [comment]
@flut1 yeah that will allow updates to happen, but component state is lost because it's deeply re-rendering all of the components, so it's not the ideal workaround.

**Comment by phyllisstein** [comment]
Grain of salt and all, but it seems this issue has mysteriously resolved itself with Webpack 2.2.0. Previously, in order to make hot reloading work, I was manually adding chunks of code like this to any parent view that asynchronously loaded children:

```js
if (process.env.NODE_ENV === 'development') {
  require('./child1');
  require('./child2');
  require('./child3);
}
```

I removed all such lines on a whim to see what it'd break, and much to my surprise and delight, HMR continued to function beautifully.

I don't _think_ anything relevant has changed in my setup other than the Webpack version, but this wasn't carefully tested. Would be glad to see if others could corroborate my story.

**Comment by MrEfrem** [comment]
Good news.

**Comment by jharris4** [comment]
I ran into the same issue where HMR was not working with react-router, and I managed to work around the issue, so I thought I'd share my solution:

```
class SplitComponent extends Component {

  constructor(props) {
    super(props);
    this.state = { Component: false }
  }

  componentWillMount() {
    const { componentPath } = this.props;

    const that = this;

    require('bundle-loader?lazy&name=model-[name]!./' + componentPath)(
      Component => {
        that.setState( { Component });
      }
    );
  }

  render() {
    const { Component } = this.state;
    if (Component) {
      return <Component {...this.props}/>;
    }
    else {
      return false;
    }
  }
}

SplitComponent.propTypes = {
  componentPath: PropTypes.string.isRequired
};

function loadComponent(componentPath) {
  return function (location, callback) {
    callback(null, props => <SplitComponent {...props} componentPath={componentPath}/> );
  };
}
```

Used with the Router like this:

```
<Router history={browserHistory}>
  <Route path="/" component={App}>
    <IndexRoute component={Home}/>
    <Route path="/pages" getComponent={loadComponent('pages/PagesRoot')}>
      <IndexRoute getComponent={loadComponent('pages/PagesHome')}/>
      <Route path="/pages/:id" getComponent={loadComponent('pages/PagesDetail')}/>
    </Route>
    <Route path="/chapters" getComponent={loadComponent('chapters/ChaptersRoot')}>
      <IndexRoute getComponent={loadComponent('chapters/ChaptersHome')}/>
      <Route path="/chapters/:id" getComponent={loadComponent('chapters/ChaptersDetail')}/>
    </Route>
  </Route>
</Router>
```

**Comment by Dreem-Devices** [comment]
@sthzg Made it for me with async routes and react-router 3.x (Did not try yet react-router 4.x with history 4.x)
Unfortunately transition to webpack 2.2 broke live reloading, In the console, I only get
```
client:37 [HMR] Waiting for update signal from WDS...
client:37 [WDS] Hot Module Replacement enabled.
client:37 [WDS] App updated. Recompiling...
client:37 [WDS] App hot update...
```

It seems like the `dev-server.js` code is not executed.
I don't know what I'm missing.
I'm using `WebpackDevServer` node API for launching my development server, and live reloading worked well using transform-hmre or react-hot-loader (though react-hot-loader need module.hot.accept for all my childRoutes and the first component to be synchrone...)

The logs missings are:

- with hmre
```
dev-server.js:55 [HMR] Checking for updates on the server...
index.js:81 [React Transform HMR] Patching Index
log-apply-result.js: 20 [HMR] Updated modules:
log-apply-result.js: 22 [HMR]   - 598
```

- with react-hot-loader
```

dev-server.js:55 [HMR] Checking for updates on the server...
log-apply-result.js:20 [HMR] Updated modules:
log-apply-result.js:22 [HMR]  - 806
log-apply-result.js:22 [HMR]  - 804
log-apply-result.js:22 [HMR]  - 320
dev-server.js:41 [HMR] App is up to date.
```

If anyone has an idea? Does someone has the same issue?
I've just updated to webpack 2 following the migration guide.

What do you think @gaearon? (sorry for hard poking)

**Comment by satazor** [comment]
Hello guys!

For those we want to make routes to work with `react-hot-loader` without sacrificing generating chunks for each async route:

```js
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: {
                             // babel options here
                        },
                    },
                    !options.build ? 'preprocess-loader?+DEV' : 'preprocess-loader',
                ],
            },
           // Other rules...
        ],
    },
```

And then use [preprocess](https://github.com/jsoverson/preprocess) in your async routes:

```js
// Example with import() but works with require.ensure too

{
   path: 'about',
   // @ifdef DEV
   // Ensure component is required synchronously in DEV so that it works with react-hot-loader
   component: require('./About').default,
   // @endif
   getComponent: () =>import('./About'),
}
```

Enjoy!

**Comment by Kovensky** [comment]
Using anything that is not an `ES6` import is probably the biggest complicating factor for hot reloading.

Also note that, if you save the `require('./About').default` in the `component` property, it will _never ever get updated_ if you don't write code to do it. This would also be the case with ES6 `import` though (imports are live, but if you save a copy of the current value elsewhere the copy isn't).

**Comment by satazor** [comment]
@Kovensky I've tested using ES6 imports like so:

```
// @ifdef DEV
import About from './About';
// @endif

export default [
    {
        path: 'about',
        getComponent: () => {
            // @ifdef DEV
            return Promise.resolve(About);
            // @endif
            return import('./About');
        },
    },
];
```

but it always needs `module.hot.accept` to integrate with react-router, see: https://github.com/moxystudio/react-with-moxy/blob/master/src/client-renderer.js#L49

I've got all of this working great in https://github.com/moxystudio/react-with-moxy if you guys want to see how all the pieces are glued together.

**Comment by kettanaito** [comment]
Is there any update regarding this issue?

So far there has been only a few suggestions, each having its own drawbacks and all being but workarounds:

### Provide "key" prop to `<Route />`
Fixed the problem, but as mentioned causes deep re-render, therefore loosing components' state.
However, you can find this workaround in officially listed examples of `react-hot-loader` (i.e. [here](https://github.com/krasevych/react-redux-styled-hot-universal/blob/master/src/client/root.js)).

### Using `asyncComponent` from `react-async-component`
As suggested [here](https://github.com/ctrlplusb/react-universally), it is possible to wrap the modules you wish to load async with `asyncComponent` and pass them as `component` prop to `Route` directly. This will eliminate hot-reloading issue, however forces you to create additional files doing nothing but resolving modules async.

### Various other workarounds
Which are not meant for good code maintenance.

So, it this somehow being solved, or already has been solved with the new release of `react-hot-loader`?

**Comment by morajabi** [comment]
@kettanaito Why don't you migrate to react-router 4?

**Comment by kettanaito** [comment]
@morajabi I haven't got enough time to read about it. So far, I don't see how to migrate my code to use `react-router` 4, especially since my SSR relies on `match`, which was removed from the fourth version.

**Comment by morajabi** [comment]
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md

**Comment by kettanaito** [comment]
@morajabi sorry, there is nothing about SSR in the migration guide.
Regardless, the issue with v3 still remains, and there should be some statement how to cope with it.

**Comment by morajabi** [comment]
> Known limitations
> 
> React Router v3 is not fully supported (e.g. async routes). If you want to get most of React Hot Loader, consider switching to React Router v4. If you want to understand the reasoning, it's good to start in React Router v4 FAQ

And maybe it's worth a reading: https://github.com/ReactTraining/react-router/tree/v4.0.0-beta.8#why-did-you-get-rid-of-feature-x

**Comment by neoziro** [comment]
I close it. React Router v4 is supported and stable.

**Comment by HonestDev** [comment]
thanks. this is the best solution.
