### ISSUE TITLE
ReactHotAPI is not a function - For files not included with test regex

### ISSUE THREAD

**Issue by resistdesign** [gaearon/react-hot-loader#289]
RHL seems to be trying to process files other than what I'm asking it to include with my loader's `test` regex.

Here is my loader:

```js
{
  test: /\.(js|jsx)$/,
  loader: require.resolve('react-hot-loader') + '!' + require.resolve('babel-loader') + '?stage=0'
}
```

This is the error:

```
ERROR in ./src/sub/style.css?CSSEntryPoint
    Module build failed: TypeError: ReactHotAPI is not a function
```

The file `./src/sub/style.css?CSSEntryPoint` is an entry point that I am using the `ExtractTextPlugin` on.

If I remove the `require.resolve('react-hot-loader') + '!' + ` portion of my loader everything compiles fine, but I don't get hot loading obviously :)

Other details:

1. I am using the `HotModuleReplacementPlugin` explicitly and setting `hot` to `false` in the `WDS` config.
1. I am constructing a tool to be globally installed but executed in a project directory as the current working directory, hence the `require.resolve` in my loader string.
1. Setting `exclude` to `/\?CSSEntryPoint/` on the loader has no effect. (Which does not seem surprising given that `test` is only including `.js` and `.jsx` files in the first place! :P)

**Comment by gaearon** [comment]
React Hot Loader 1.x is deprecated and will not be supported anymore.
This shouldn’t be an issue with React Hot Loader 3.
Please track progress on it in https://github.com/gaearon/react-hot-boilerplate/pull/61.

Thanks!

**Comment by resistdesign** [comment]
@gaearon Thank you for your response, I know about v3, I commented here: https://github.com/gaearon/redux-devtools/commit/64f58b7010a1b2a71ad16716eb37ac1031f93915

Ultimately I have been unable to get it working due to an error: `Module build failed: TypeError: The plugin "react-hot-loader/babel" didn't export a Plugin instance at PluginManager.validate`. Is it not compatible with Babel 5 or something?

**Comment by gaearon** [comment]
@resistdesign Can you provide a complete project reproducing the issue?

**Comment by resistdesign** [comment]
@gaearon Sort of, I reverted to 1.3.0 after I added the babel plugin and couldn't find a fix.

This project in the state that it's in at this commit is the setup I had with v3: https://github.com/resistdesign/rdx/blob/4f9611951b5e3be77e4621613fc98024be7153d6/src/Config/WebPack/Loaders/Common/JS.js

The Babel plugin just needs to be added to that loader in that file. (Using `require.resolve`)

The project is intended to be a globally installed build tool with HTML entry points.
To use it you just go into a project where you have an `HTML` file with a `JS` `script` tag in it and run: `rdx serve -a ./src/index.html`.

It's still in the works but that much should work in that commit I think.

**Comment by gaearon** [comment]
Sorry to bother you but can you please file a separate issue with a link to the exact commit that breaks with v3? This is a project I do in my free time, and every extra step like “The Babel plugin just needs to be added to that loader in that file. (Using require.resolve)” means I might do it wrong way and waste the little time I have to work on this. So I’d really appreciate if you could file a bug report with a complete project that is ready to be tested.

**Comment by resistdesign** [comment]
HOnestly, I wouldn't worry about it at this point, I really think it's a Babel version issue and I'm content to use v1 until you've had time to really release v3. Thanks man :)
