### ISSUE TITLE
doesn't work for css/jsx files outside directory

### ISSUE THREAD

**Issue by DannyThomas** [gaearon/react-hot-loader#291]
the only reason I have to believe this comes from react-hot-loader is
  https://github.com/webpack/webpack/issues/1742

    import Title_Bar       from 'lib/components/Title-Bar.jsx';

with `webpack.config.js` containing

      resolve: {
        alias: {
          lib: '/opt/uq.cis.repo/system/web-app/lib'
        },
        extensions: ['', '.js', '.jsx']
     },

where it chokes on the first bit of jsx

    ERROR in ../lib/components/UQ-Title-Bar.jsx
    Module parse failed: /Users/dthomas/Documents/Repo/system/web-app/lib/components/Title-    Bar.jsx Unexpected token (92:6)
    You may need an appropriate loader to handle this file type.

Same behaviour after trying react-hot-loader@3.0.0-beta.1

NB this happens on `npm start` as well as hot reloads, which doesn't sound
like it would come from react-hot-loader.

But if it was, would be good to fix it before v3 release.
Open to suggestions on narrowing down the cause.

thanks.

**Comment by gaearon** [comment]
Can you please provide a minimal project reproducing this?
The smaller the better.

**Comment by gaearon** [comment]
However I don’t see why you think this is caused by React Hot Loader.

Could it be that your Babel loader is only configured to run on the files inside a certain directory?
That would explain the issue.

**Comment by calesce** [comment]
agreed with @gaearon, this doesn't look to be related to RHL, it looks like the JSX files aren't being run through Babel. Please re-open if you can isolate the issue to be RHL itself.
