### ISSUE TITLE
Texts disappear after hot-reload perhaps due to font load

### ISSUE THREAD

**Issue by lichao-hulu** [gaearon/react-hot-loader#306]
1. Define font classes using @font-face
2. Define font mixins using font classes
3. Use font mixins in scss
4. Use webpack css-loader!scss-loader to load the scss files
5. access web application

Observed:
All texts are there after first load
After make a css code change, which triggers hot load, all texts are gone
Make any css change within browser, all texts will be back

In console, font file will be reloaded due to @font-face src attribute, not sure whether the problem is caused by this.

**Comment by huijian3139** [comment]
Good catch ! Super sister

**Comment by krzysztofpniak** [comment]
Have you found any solution for this?

**Comment by calesce** [comment]
Yeah, this doesn't seem related to React Hot Loader, I'd recommend taking a look at one of the CSS/SCSS loaders, or possibly Webpack itself.

**Comment by ramilzakirov** [comment]
I had an identical problem. It has turned out to solve through the use of `url-loader` instead of `file-loader`

**Comment by ponelat** [comment]
@ramilzakirov thank you. This has been a PITA for a while!
