### ISSUE TITLE
Stop outputting of hot-upload.js to output

### ISSUE THREAD

**Issue by mikeLspohn** [gaearon/react-hot-loader#310]
I'm not sure if it's an issue with this plugin, or somewhere else, but when my code gets rebuilt it puts my `bundle.js` in the correct place, but also puts a file like `0.7c5887de541c4a3698e9.hot-update.js` in the folder where the built code goes. Is there anyway to prevent this?

Here's my webpack config currently. I'm using the WriteFileWebpackPlugin because I'm using the webpack node api due to some other issues with reloading. I've tried without that plugin without using node, and still the same thing happened at one point.

```
var webpack = require('webpack')
var path = require('path')
var WriteFilePlugin = require('write-file-webpack-plugin')

module.exports = {
  // watchOptions: {
  //   poll: true
  // },
  context: __dirname + '/app/assets/javascripts',
  entry: {
    App: [
      'webpack-dev-server/client?http://localhost:8080/',
      'webpack/hot/only-dev-server',
      path.resolve(__dirname, 'app/assets/source/index.js')
    ]
  },
  output: {
    path: path.resolve(__dirname, 'app/assets/javascripts'),
    publicPath: 'http://localhost:8080',
    filename: 'bundle.js'
  },
  module: {
    loaders: [
      { test: /\.js$/,
        loaders: ["react-hot", "babel"],
        include: path.resolve(__dirname, 'app/assets/source')
      }
    ]
  },
  devtool: 'source-map',
  devServer: {
    outputPath: path.resolve(__dirname, 'app/assets/javascripts')
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new WriteFilePlugin
  ]
}

```

**Comment by calesce** [comment]
Don't think this is related to RHL, since you'll receive those hot updates from Webpack HMR whether or not you have RHL configured. This appears to be a Webpack/WDS configuration problem.
