### ISSUE TITLE
Why can this not be chained?

### ISSUE THREAD

**Issue by Tjorriemorrie** [gaearon/react-hot-loader#311]
Looking at [webpack loaders](https://webpack.github.io/docs/using-loaders.html) it states:

> Loaders can be chained. They are applied in a pipeline to the resource.

Why would this not work then:
```
        loaders: [
            {
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                loaders: 'react-hot'
            },
            {
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                loaders: 'babel'
            },
```

Does it have to do with the node web server? Do you mind explaining it? I don't understand the difference between chained loaders and a loaders' list? TYIA

**Comment by kkirby** [comment]
Because you're doing it wrong:

```
        loaders: [
            {
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                loaders: ['react-hot','babel']
            }

**Comment by Tjorriemorrie** [comment]
@kkirby thanks, do you have more info on this? i.e. why you cannot have them set up seperately?
