### ISSUE TITLE
[3.0] Troubles with native classes

### ISSUE THREAD

**Issue by s-panferov** [gaearon/react-hot-loader#316]
Hello, I'm trying to use `react-hot-loader@3.0.0-beta.2` in my Electron-based app with native classes. And sometimes I have strange errors. Very simplified structure of my app looks like this:

`github-app.tsx`:

```
import { Accordion } from 'dasb-core/ui/accordion'
import { AccordionPanel } from 'dasb-core/ui/accordion/panel'

@connect(state => {
	return {
	}
})
export class GitHubApp extends React.Component<P, void> {
	render() {
		return (
			<div style={ s.app }>
				<Accordion>
					<AccordionPanel style={ s.projects } key='projects'></AccordionPanel>
					<AccordionPanel style={ s.issues } key='issues'></AccordionPanel>
				</Accordion>
			</div>
		)
	}
}
```

`github.tsx`:

```
import { GitHubApp } from './ui/app'
import { Provider } from 'react-redux'

export class GitHub {
	name = 'dasb-github'
	store: Store

	constructor() {
		this.store = setupRedux()
	}

	render() {
		return (
			<Provider store={ this.store }>
				<GitHubApp />
			</Provider>
		)
	}
}
```

`index.tsx`:

```
import { GitHub } from './github'

export function renderWithHot(reactApp: HTMLElement, app: React.ReactNode) {
	ReactDOM.render(
		<AppContainer>
			{ app }
		</AppContainer>,
		reactApp
	)
}

let gitHub = new GitHub();
renderWithHot(appEl, GitHub.render())
```

The error is:

```
Warning: GitHub(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
```

If I remove `Accordion` component from the `github-app.tsx` the error disappears. But `Accordion` is just a normal component without any issues. And the error is about `GitHub`, but it's not a component, it's just a `class` with `render` method (it's not derived from React.Component).

The app works good if I disable `react-hot-loader`. Do you have any thoughts? I think I can make some minimal example, but it will take some time.

Detailed env:

```
react-hot-loader@3.0.0-beta.2
webpack@2.1.0-beta.14
electron@1.2.5
react@15.2.0
```

**Comment by prewk** [comment]
I think I'm having the same problems.. can you try switching out the code in `github.tsx` with a stateless component and see if it renders?

Just do something like: `export const GitHub = () => <div>Github test</div>;`

**Comment by prewk** [comment]
FWIW: I tried downgrading to `react-hotloader@3.0.0.beta.0` which sort of solves the import issue, but the hot loading stopped working entirely.

**Comment by calesce** [comment]
@s-panferov it'd be helpful if you could get a minimal example repository, perhaps removing Redux/Typescript if they're not related to the issue.

**Comment by calesce** [comment]
@s-panferov Also, I see a bug in your example, where you call `Github.render()`, which is the class and not the `gitHub` instance.

Another issue is that you're using `@connect`, and currently, decorated components don't get reloaded (#279).

I'm going to close this because I first responded 4 weeks ago, but please re-open if you still need help.
