### ISSUE TITLE
[3.0] react-hot-loader breaks react-art

### ISSUE THREAD

**Issue by jkeljo** [gaearon/react-hot-loader#317]
See repro case at https://github.com/jkeljo/react-hot-loader-and-art-bug. Tested in Chrome  51.0.2704.103 (64-bit) on OSX.

**Comment by calesce** [comment]
Thanks for the simple project, I was also able to reproduce. This is definitely a problem with RHL. I'm not familiar with React-ART, but since it uses React internals, it might break some assumptions that React Hot Loader makes.

**Comment by neoziro** [comment]
[Upgraded all things](https://github.com/neoziro/react-hot-loader-and-art-bug) and it seems to be fixed with [v4](https://github.com/gaearon/react-hot-loader/tree).
