### ISSUE TITLE
Storing components by 'displayName' make wrapping unavailable 

### ISSUE THREAD

**Issue by mbektimirov** [gaearon/react-hot-loader#32]
In [Moreartyjs](https://github.com/moreartyjs/moreartyjs) we use [text fields wrappers](https://github.com/moreartyjs/moreartyjs/blob/master/src/DOM.js) to render with `requestAnimationFrame`. React does not support setting `displayName` property directly into wrapped component (it throws `Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs...`)

So now hot loader claims it already have an undefined component:
`Found duplicate displayName in DOM.js: "undefined".
react-hot-loader uses displayName to distinguish between several components in one file.`

Is it possible to generate component unique id and use it instead displayName?

**Comment by jedwards1211** [comment]
I'm having an issue with React being loaded twice, but I don't understand what's causing it to be loaded twice.  Do you guys have any tips?

**Comment by gaearon** [comment]
@jedwards1211 Those are not two Reacts, it's just the way Babel names variables.

**Comment by jedwards1211** [comment]
@gaearon yes, I understood those aren't two Reacts.  I think what was happening though was a second version of React was being loaded from `google-map-react`'s own `node_modules`, even though its webpack bundle declares react as an external.  I still haven't had time to get to the bottom of this issue

**Comment by gaearon** [comment]
@jedwards1211 NPM doesn't care what Webpack says. If `google-map-react`'s version of React declared as `peerDependency` is not compatible with the one in the outer project, NPM will install its own version of React inside there. That's the big problem with NPM 2, and it will be fixed in NPM 3.

**Comment by jedwards1211** [comment]
Huh, it was compatible as far as I know, but that's good to know anyway.  Thanks!
