### ISSUE TITLE
breaking when change is on a Store, yet not when on a Component

### ISSUE THREAD

**Issue by bitttttten** [gaearon/react-hot-loader#320]
(or, breaking whilst change is in the dispatchToken, yet not when the change is outside of the callback)

It seems that the loader is causing my dispatchToken inside my store to fire n times, where n is how many times the hot loader has hot loaded in my store.

I will try my best to explain the bug, although I have recorded it as it may be easier to watch. [Please find the video here](http://sendvid.com/cy4jialu).

My component triggers an action which provides the dispatcher with a new action with a payload of data. In my case, it's an amount in which to increase a player's health. My store registers itself to the dispatcher, reading the payload amount and updating the player's health and then emitting a change. Something like this:

# component
```
	increaseHealth() {
		Dispatcher.dispatch({
			type: ActionTypes.PLAYER_HEALED,
			amount: 5
		})
	}
```

# store
```
	increaseHealth(amount) {
		state.health += amount
		this.emit('change')
	}
```

..and this is great. If I have react hot loader working, I can change the amount in the component to say 7, and it reloads and now the player's health will increase 7. Although now if I move this amount into the store:

# component
```
	increaseHealth() {
		Dispatcher.dispatch({
			type: ActionTypes.PLAYER_HEALED
		})
	}
```

# store
```
	increaseHealth() {
		state.health += 5
		this.emit('change')
	}
```

..this is where problems come in. Without hot loading, the code runs fine. Although if I change this 5 to a 7 in the store, now my dispatchToken in my store is being fired twice.

**Comment by calesce** [comment]
Is this using Facebook Flux? This issue doesn't look to be related to React Hot Loader itself, but an issue with how Flux Stores don't get reloaded by Webpack HMR (which is why Dan initially developed Redux).

If you can provide a minimal, runnable example, I can try to help debug your issue.

**Comment by calesce** [comment]
Closing because no response from OP, and this doesn't seem like a RHL issue.

**Comment by bitttttten** [comment]
I moved on from this example and so I do not have the code any longer. I could try and reproduce, however, since I have moved on it's no longer a priority or close to critical. I am sure, like you said, that I was encountering this behaviour since stores cannot be hot reloaded.. that's all. 

Apologises for the late reply, I'm happy for it to be closed.
