### ISSUE TITLE
About babel-preset-react-hmre and react-hot-loader

### ISSUE THREAD

**Issue by minooo** [gaearon/react-hot-loader#323]
I find this two packages, any one can achieve HMR, then, which is better, or what is your recommend?  thank you so much!

**Comment by calesce** [comment]
React Hot Loader 3 will be the best to use when it is released, see [react-hot-boilerplate](https://github.com/gaearon/react-hot-boilerplate/tree/next) (`next` branch) for sample usage. 

Even though 3 is still in beta, it's already quite good. I'd recommend using it over RHL 1.x or React Transform (which that Babel preset covers, and is basically RHL 2). Those will be deprecated when 3 is released.

**Comment by minooo** [comment]
Thank you!
