### ISSUE TITLE
Up to date react-hot-loader example using express

### ISSUE THREAD

**Issue by sandysaders** [gaearon/react-hot-loader#327]
I've spent many hours trying to get react-hot-loader to work through webpack and express and I've been able to get content to show however I get a ton of `event source` errors on the network logs and 'mime type' errors in the console. Content is being reloaded constantly even if code hasn't changed causing my computers fan to start going crazy. After giving up and looking for examples online I was not able to find example repos that are up to date or articles that aren't from a year ago. All articles seem to do things differently and it's pretty confusing. Is there any example you can point me to a github repository that sets up react-hot-loader with webpack and express (to use with existing web server) and no isomorphic/universal setup?

This is for `react-hot-loader v1.3.0`

**Comment by avizaviz** [comment]
Same issue frustrating!!!

**Comment by calesce** [comment]
I don't have an example at hand using both Express and RHL 1.3.0, but I've used an existing Express app with the RHL 3 beta without a problem.

You'll need both [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware) and [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware). See the webpack-hot-middleware README for setup.

**Comment by tststs** [comment]
Hi @sandysaders,

i had to showcase `react-hot-loader` yesterday and made a quick and dirty example for a colleague with express. feel free to pick the parts you need if they're suitable for you. it's based on `react-hot-loader@3.0.0-beta.3`.

https://github.com/tststs/react-hot-loader-3-express-example

**Comment by calesce** [comment]
Changed `react-hot-boilerplate/next` to use RHL 1 [here](https://github.com/calesce/react-hot-boilerplate/tree/89c39ffe617fc8aab647a0089d085905c1a76536).

**Comment by ethan-deng** [comment]
How about using Webpack dev server "proxy"?

http://nikolay.rocks/2016-01-13-connect-webpack-to-backend
https://medium.com/@rajaraodv/webpacks-hmr-react-hot-loader-the-missing-manual-232336dc0d96#.e6zvsjd9m
