### ISSUE TITLE
method argument length seems wrong (and thus...breaks react-router onEnter)

### ISSUE THREAD

**Issue by dpwrussell** [gaearon/react-hot-loader#329]
One of the things that react-router has is an [`onEnter` property that can be set to a function](https://github.com/reactjs/react-router/blob/master/docs/API.md#onenternextstate-replace-callback). react-router looks at the 'arity' of the passed function to determine what behaviour is used when this hook is executed. Long story short, they do `if (hook.length < asyncArity)` where `hook` is the function.

Usually, this works fine and even with hot-loader seems to function correctly if I pass in a standalone function as the hook.

However, if I pass in a method as this hook, I think hot-loader is affecting it. The hook length will always be reported as being zero. I know there were issues with react-router before, but https://github.com/gaearon/react-hot-loader/pull/272 suggests they are fixed now.

I am running react-hot-loader 3.0.0-beta.2': '2016-05-05T02:06:35.900Z.

I have prepared a fairly simple test case which I've put in this repository: https://github.com/dpwrussell/hotload-react-router-failure-example `master` is without hot-loading. `hot` branch is with.

In this example I make use of react-router as when I started making the testcase I thought that was the origin of the problem. I added the following lines into `node_modules/react-router/lib/TransitionUtils.js` function `createTransitionHook` inside the anonymous function.

``` js
    console.log('Transition Hook');
    console.log(hook.length);
    console.log(hook);
```

When I load the `/somewhere` route without hot-loader the route loads correctly and I get the console output as expected.

```
Transition Hook
3
function requireAuth(nextState, replace, callback) {
          console.log('requireAuth');
          // replace('/login');
          callback();
        }
```

Introduce hot-loading and I get:

```
Transition Hook
0
function requireAuth(nextState, replace, callback) {
          console.log('requireAuth');
          // replace('/login');
          callback();
        }
```

Which is incorrect as the `requireAuth` method has 3 arguments.

**Comment by nfcampos** [comment]
Hi @dpwrussell! Thanks for bringing this to our attention. This should be fixed upstream in react-proxy (by making the `length` property of proxied methods track the `length` of the underlying method, will only be possible in browsers that support configurable `length` property on functions, http://kangax.github.io/compat-table/es6/#test-miscellaneous_function_'length'_is_configurable). I'm working on a fix and hope to have it out soon-ish.

**Comment by phyllisstein** [comment]
Just got bit by this myself. Looks like the relevant `react-proxy` PR has been open for some time---any chance of getting that merged through, @nfcampos and @gaearon?

**Comment by neoziro** [comment]
React router v4 is now the standard. I close it as it is now outdated.
