### ISSUE TITLE
Unable to use v3-beta.1 with Server rendering and react-router and redux

### ISSUE THREAD

**Issue by morajabi** [gaearon/react-hot-loader#330]
It's my render part in client:
```
// Render app in browser
const rootCompProps = { store: store, history: history, routes: routes };
render(
  <Root {...rootCompProps} />,
  rootElement
);

// Hot module replacment for dev purpose

if (module.hot) {
  module.hot.accept( () => {
    const NextRoot = require('../common/containers/Root').default;
    render(
      <AppContainer>
        <NextRoot {...rootCompProps} />
      </AppContainer>,
      rootElement
    );
  });
}
```

There's no error until I change something in App component and i will get one of these errors:
- <Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically.

- Warning: [react-router] You cannot change <Router history>; it will be ignored

- Warning: [react-router] You cannot change <Router routes>; it will be ignored

or when I add this: 
`module.hot.accept('../common/containers/Root', () => {`
I will get:
- [HMR] The following modules couldn't be hot updated: (Full reload needed)

**Comment by paulwithap** [comment]
Try importing `routes` into `Root.js` rather than passing it as a prop.

**Comment by morajabi** [comment]
OK, I will try ASAP, but "... does not support changing `store` on the fly. ..." won't be solve IMO.

**Comment by paulwithap** [comment]
My fix will solve your second error. You have to pass the path you what to hot replace in as the first parameter to module.hot.accept(), so your code should look like this:

```javascript
// Render app in browser
const rootCompProps = { store: store, history: history }; // import routes in Root.js
render(
  <Root {...rootCompProps} />,
  rootElement
);

// Hot module replacment for dev purpose

if (module.hot) {
  module.hot.accept('../common/containers/Root', () => {
    const NextRoot = require('../common/containers/Root').default;
    render(
      <AppContainer>
        <NextRoot {...rootCompProps} />
      </AppContainer>,
      rootElement
    );
  });
}
```

**Comment by morajabi** [comment]
I said i tested this way in last part of my issue.

**Comment by paulwithap** [comment]
Look at my code again. It is not the same as your original code. I'm not passing `routes` in as a prop to `<Root />`, I'm importing it directly into `Root.js`.

Here is how the file should look:

**Root.js**
```javascript
import React, { PropTypes as T } from 'react';
import { Provider } from 'react-redux';
import { Router } from 'react-router';
import routes from '../routes';

const Root = ({ store, history }) => (
  <Provider store={store}>
    <Router history={history} routes={routes} />
  </Provider>
);

Root.propTypes = {
  store: T.object,
  history: T.object
};

export default Root;
```

**Comment by morajabi** [comment]
Why when I add this line:
`module.hot.accept('../common/containers/Root', () => {`
instead of this:
`module.hot.accept( () => {`
It fails with a warning:
`[HMR] The following modules couldn't be hot updated: (Full reload needed)
`

**Comment by max-mykhailenko** [comment]
I have same errors, but hot reloading works correct. Any progress with it?

> does not support changing store on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically.

> Warning: [react-router] You cannot change ; it will be ignored

> Warning: [react-router] You cannot change ; it will be ignored

**Comment by morajabi** [comment]
I **do** hot reload reducers myself, it's not the problem.

**Comment by calesce** [comment]
@morajabi have you tried defining your routes in a separate module and `accepting` that module, like [this](https://github.com/calesce/react-hot-loader-examples/blob/439ac1e0623da8d84cbbc851aa9993c29fbaa931/src/index.js)? Also, there won't be a way to get rid of the warning unless you patch console.error, see #298.

It shouldn't have an impact on using with Redux, since you only need to create the store once and reload the reducers. I'll push up an additional example of using RHL with both libs if you're interested.

**Comment by morajabi** [comment]
@calesce Thx. I will try that out ASAP.

**Comment by morajabi** [comment]
I think it worked! but with the following error:
`Warning: [react-router] You cannot change <Router routes>; it will be ignored`

**Comment by calesce** [comment]
Yeah, unfortunately that's something that probably won't be fixed in React Router 2/3. For now, it's probably best to either ignore it, or [patch `console.error` to ignore that specific warning](https://github.com/gaearon/react-hot-loader/issues/298#issuecomment-236510239) (which is relatively safe but shouldn't be necessary).

**Comment by morajabi** [comment]
I've got a problem with this solution, errors within a component will become: check render method of AppContainer

**Comment by morajabi** [comment]
Hey, Can we solve this problem?
