### ISSUE TITLE
Why it works only with sudo?

### ISSUE THREAD

**Issue by mqklin** [gaearon/react-hot-loader#331]
The problem is that hot reload works only with `sudo npm start`.
I know that it's probably my system problem, but can anyone explain, what it can be? Console output is the same in both, but hot reload works only with `sudo`

**Comment by DimitryDushkin** [comment]
Definitely it is not react-hot-loader issue. It works fine within my project.

**Comment by gaearon** [comment]
Yeah, we couldn’t possibly be responsible for this.
Something’s likely messed up with your `npm` setup.

**Comment by mqklin** [comment]
Yes, thank you! I've reinstalled `node` an now it works
