### ISSUE TITLE
NPM extraneous library issue

### ISSUE THREAD

**Issue by antoinejaussoin** [gaearon/react-hot-loader#333]
Hi,

I realise this is not an issue impacting a lot of people, but on the latest release (3.0.0-beta.2), you pushed the "history" dependency to NPM, although it is not present in the package.json file.

One of our tool (a dependency analyser) at work does break because of this.

Would it be possible to push a new version to NPM without this extraneous dependency please?

Thanks!!

**Comment by gaearon** [comment]
I don’t understand what you mean.
How is `react-hot-loader` related to `history`?
These are completely different projects, and neither is each other’s dependency.

**Comment by antoinejaussoin** [comment]
I made a wrong assumption. I'm basically using a corporate NPM proxy at work, and, somehow, your package (in its 3.0.0-beta.2) version get installed with "history" in its node_modules directory even though it's not specified in package.json. So I (wrongly it appears) assumed you must have pushed it by mistake on NPM... 

I guess the issue lies with our corporate NPM repo at work... i'll investigate further.

Sorry for the mistake!

**Comment by gaearon** [comment]
Yea, AFAIK it’s not really possible to push a module with something in `node_modules`.

**Comment by emyk** [comment]
I'm seeing the same thing, not using any npm proxy. history is in react-hot-loader/node_modules when npm-installing. 

Try downloading https://registry.npmjs.org/react-hot-loader/-/react-hot-loader-3.0.0-beta.2.tgz, history is already in there

**Comment by antoinejaussoin** [comment]
I wasn't crazy then :)

**Comment by gaearon** [comment]
This is an npm bug: https://github.com/npm/npm/issues/11582.
Can you try with npm 3.8.7?

**Comment by antoinejaussoin** [comment]
@gaearon: That's why I couldn't reproduce on my Mac. The problem arise in a corporate environment, and I don't have any way to update NPM there (it will be updated at some point, but it's totally out of my control).
In the meantime, I just copy-pasted your code into a /lib/ directory on my project, until we switch to NPM3 at work. This is hacky (and temporary) but it's the only way I can see with the limited means I have :)

**Comment by emyk** [comment]
FYI, this is not an issue with beta.4.
