### ISSUE TITLE
my components keeps mounting. 

### ISSUE THREAD

**Issue by aalpgiray** [gaearon/react-hot-loader#336]
no meter what I tried i couldn't be able to hot replace my code without unmounting the react components, so

`componentWillUnmount() {
    alert('I knew Dan lied about hot reloading.');
  },`

keeps firing,

I know i did something wrong but what? 

here is the repository i put together ,

https://github.com/aalpgiray/react-redux-typescript.git

**Comment by calesce** [comment]
This might not be the only issue, but I do see that you use [decorators](https://github.com/aalpgiray/react-redux-typescript/blob/master/src/components/user/index.tsx#L15), and decorated components currently don't hot reload (#279).

**Comment by aalpgiray** [comment]
I have edited the official boilerplate. Now everything works.

[typescript react-redux-hot-reload](https://github.com/aalpgiray/react-hot-boilerplate-ts)
