### ISSUE TITLE
Cannot apply update. Need to do a full reload!

### ISSUE THREAD

**Issue by sir-marc** [gaearon/react-hot-loader#339]
```
[HMR] Cannot apply update. Need to do a full reload!          dev-server.js:18
[HMR] Error: Aborted because 0 is not accepted         dev-server.js:19 
    at hotApply (http://localhost:8080/dist/bundle.js:391:31)
    at hotUpdateDownloaded (http://localhost:8080/dist/bundle.js:304:13)
    at hotAddUpdateChunk (http://localhost:8080/dist/bundle.js:284:13)
    at webpackHotUpdateCallback (http://localhost:8080/dist/bundle.js:5:12)
    at http://localhost:8080/dist/0.8d6bf624843b11c26b47.hot-update.js:1:1
```
Get this error, when hitting save.
My config looks like:

```
var webpack = require('webpack');
var path = require('path');
module.exports = {
	context: __dirname,
	entry: [
		'webpack-dev-server/client?http://localhost:8080/', // WebpackDevServer host and port
		'webpack/hot/only-dev-server', // "only" prevents reload on syntax errors
		'./src/index' // Your appʼs entry point
	],
	output: {
		path: __dirname + "/dist",
		publicPath: "/dist/",
		filename: "bundle.js"
	},
	devtool: "source-map",
	devServer: {
		publicPath: "/dist/",
		headers: {
			'Access-Control-Allow-Origin': '*',
			'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept'
		}
	},
	module: {
		loaders: [
			{
				test: /\.jsx?$/,
				loader: 'react-hot',
				include: path.join(__dirname, 'src')
			},
			{
				test: /\.jsx?$/,
				loader: 'babel-loader',
				exclude: /node_modules/,
				query: {
					plugins: ['transform-object-rest-spread', 'transform-decorators-legacy'],
					presets: ['react', 'es2015']
				}
			}
		]
	}
};
```

**Comment by morajabi** [comment]
Same.

**Comment by nodkz** [comment]
Problem with `transform-decorators-legacy`. 
Without it all works perfectly.

**Comment by nodkz** [comment]
But your problem that you made wrong configs see [boilerplate branch **NEXT**](https://github.com/gaearon/react-hot-boilerplate/blob/next/src/index.js):

```js
import { AppContainer } from 'react-hot-loader';
...
if (module.hot) {
  module.hot.accept('./App', () => {
    // If you use Webpack 2 in ES modules mode, you can
    // use <App /> here rather than require() a <NextApp />.
    const NextApp = require('./App').default;
    ReactDOM.render(
      <AppContainer>
         <NextApp />
      </AppContainer>,
      rootEl
    );
  });
}
```

`AppContainer` is required
`if (module.hot) {` is required

Without them  react-hot-loader v3 beta does not work.

Also exists another working example https://github.com/nodkz/react-webpack-babel-hotreload-example

**Comment by nodkz** [comment]
If you use `decorators` (eg. `@withStyles`) and `transform-decorators-legacy`, then `state` in components will be cleared with every update. 

Components without decorators updates as expected, without nullifying the `state`.

**Comment by sir-marc** [comment]
@nodkz So if i have `@connect` decorator, I can't use hotreload?

**Comment by nodkz** [comment]
@sir-marc You may use hot-reload. But your `component` will be totally reloaded and you loose its `state`.

I can not confirm this with `@connect`, because I'm not using Redux. 
But if your component losing `state` after hot update, then you know that problem with decorator now.

Issue about decorators problem: https://github.com/gaearon/react-hot-loader/issues/279

**Comment by fkrauthan** [comment]
I have that module.hot code but I still get that it needs to do a full reload. I compared my code with the example code and from a config perspective there is no difference.

**Comment by calesce** [comment]
@sir-marc do you have the issue when you use `connect()(Component)` instead of the decorator form?

**Comment by fkrauthan** [comment]
Could it be because I use JSX for my route config instead of the JSON Object format? Is that not supported at the moment (react-router)?

**Comment by calesce** [comment]
@fkrauthan [both](https://github.com/reactjs/react-router/blob/master/docs/guides/RouteConfiguration.md#configuration-with-plain-routes) should be fine, but I don't think React Router is related to this issue, feel free to open a new one.

**Comment by fkrauthan** [comment]
The weird thing is the log shows me a bundle id path but the root components ID is not listed. I will play a bit more and then publish my test project and open a new ticket.

**Comment by calesce** [comment]
@sir-marc I'm going to close this because it looks to be either another case of the #279, or something else that needs more context than just the webpack config. If it's the latter case, please re-open!
