### ISSUE TITLE
How write entry

### ISSUE THREAD

**Issue by NumerHero** [gaearon/react-hot-loader#345]
I meet some problem when I use hot-loader

I cant comprehend why entry's type must replace a Array of Object

Meanwhile, I cant know how write entry when I need pack a lot of entrypoint like these code : 

```javascript
entry: {
	// 并起的文件一定要写在一起
	path: ["./jsx/app.jsx","./style/app.less"],
	vendor: [
		"./js/util.js",
		"react",
		"react-dom"
	]
},
...

new webpack.optimize.CommonsChunkPlugin("vendor", "vendor.bundle.js"),
```

I need pack my code together with using react-hot howevery I dont know how write the entry Array

Thank you anyway

**Comment by calesce** [comment]
This is more of a Webpack-specific question, so I'd look into Webpack resources. [SurviveJS](http://survivejs.com/webpack/introduction/) has some great walkthroughs.

In development, you can do normal `require('./app.less')` with Less/CSS/style loaders, and HMR will still work.

You can separate your CSS in your production config using [ExtractTextPlugin](https://github.com/webpack/extract-text-webpack-plugin).
