### ISSUE TITLE
Can't force a reload in tests when Component methods change

### ISSUE THREAD

**Issue by valscion** [gaearon/react-hot-loader#35]
I have been trying to get my head around making my test runner automatically refresh the page (that is, declining the hot module replacement) when any of my component codes change.

But as this package currently makes the Component file [accept changes to itself without notifying parents](https://github.com/gaearon/react-hot-loader/blob/4892b118731b78f7aed192f0517bc900e0fbb1c2/index.js#L34) I haven't been able to disable hot loading on a per-component basis and I've had to revert back to manually re-running the test suite.

**Comment by gaearon** [comment]
Some good news https://github.com/gaearon/react-hot-loader/issues/30#issuecomment-72126754
