### ISSUE TITLE
Migrating to webpack

### ISSUE THREAD

**Issue by ArunRamachandran** [gaearon/react-hot-loader#350]
Hello.. I have just read your article about getting started with react-hot-loader.  Also found a good resource about migrating to [webpack](https://www.codementor.io/reactjs/tutorial/beginner-guide-setup-reactjs-environment-npm-babel-6-webpack). Please link this with your article if it is a useful article ! Thanks .

**Comment by calesce** [comment]
Feel free to make a pull request with documentation. As a heads up, we'll be moving to React Hot Loader 3 soon, so it'd be best to make a PR against the `next-docs` branch.
