### ISSUE TITLE
Seems to rely on settings.json when run in Cordova

### ISSUE THREAD

**Issue by damonmaria** [gaearon/react-hot-loader#351]
This section of code in `gadicc_modules-runtime-hot.js` causes hot reloading to fail to boot in Cordova unless a `settings.json` has been used:

````js
// On both the client & server this means no hotloading is present                   
if (!Meteor.settings.public.HOT_PORT)                                                                
  return;                                                                                            
````

`Meteor.settings` is `undefined`.

Using a `settings.json` like so solves the problem:
````js
{
  "public": {
    "nothing": "to see here"
  }
}
````

**Comment by calesce** [comment]
This doesn't seem to be an issue with `react-hot-loader` itself, but something to do with Cordova or Meteor. `react-hot-loader` doesn't use any sort of `settings.json`.

**Comment by damonmaria** [comment]
The code posted at the top of the issue is `react-hot-loader` code. So it tries to access settings which if they have not been initialised (which it appears they are not in Cordova builds) will cause a `TypeError`.

**Comment by calesce** [comment]
[That code](https://github.com/gadicc/meteor-hmr/blob/master/packages/modules-runtime-hot/hot/main.js#L17) seems to come from [`meteor-hmr`](https://github.com/gadicc/meteor-hmr), not RHL. From what I can tell, `meteor-hmr` doesn't depend on RHL either, so the issue probably should be opened over there.

**Comment by damonmaria** [comment]
Apologies. You are totally correct. I should be posting to the other project.
