### ISSUE TITLE
Is it even possible to use hot reloading with webpack hash?

### ISSUE THREAD

**Issue by nmaves** [gaearon/react-hot-loader#355]
Cna you use the hash option and hot-reloading at the same time?

I have 

```
output: {
	path: PATHS.build,
	filename: '/bundle.[hash].js'
}
```

Any changes are seen buy the hot reloader but a page refresh is done every time.  Is there any way around this?

**Comment by calesce** [comment]
I'd recommend not using `bundle.[hash].js` in development, personally.

You can probably add a webpack plugin to update the hash in `index.html` (or wherever you need it) on file change. Otherwise, page refreshes will go back to the original bundle, which is what I think you're saying is the issue.
