### ISSUE TITLE
Getting an error when using `babel-polyfill` in the browser

### ISSUE THREAD

**Issue by Industrial** [gaearon/react-hot-loader#356]
Hi.

When I do an `import 'babel-polyfill'` it's code includes this:

`;(function register() { /* react-hot-loader/webpack */ if (process.env.NODE_ENV !== 'production') { if (typeof __REACT_HOT_LOADER__ === 'undefined') { return; } if (typeof module.exports === 'function') { __REACT_HOT_LOADER__.register(module.exports, 'module.exports', "_task.js"); return; } for (var key in module.exports) { if (!Object.prototype.hasOwnProperty.call(module.exports, key)) { continue; } var namedExport = void 0; try { namedExport = module.exports[key]; } catch (err) { continue; } __REACT_HOT_LOADER__.register(namedExport, key, "_task.js"); } } })();`

This code references `process.env.NODE_ENV` which isn't available so I get an `env of undefined` error.

**Comment by calesce** [comment]
From my testing, `process.env` should be an empty object by default in Webpack (without doing something like `DefinePlugin`), so checking `process.env.NODE_ENV` is ok. Would you mind posting what a reproducible example, or at least what your webpack config looks ?

**Comment by Industrial** [comment]
Hi!

this is the code/line it breaks on; https://github.com/sytac/resumator/blob/e2d1cdf7f528f121bdf02f7f1d36395e053bf45d/services/app/src/client/js/app.js

**Comment by Industrial** [comment]
I've fixed this issue for my project by not using `babel-polyfill` in the application entry file and instead using the `transform-runtime` babel plugin.
