### ISSUE TITLE
This is a really good and easy walk through of how to load up Webpack

### ISSUE THREAD

**Issue by michaelolo24** [gaearon/react-hot-loader#358]
https://tylermcginnis.com/react-js-tutorial-1-5-utilizing-webpack-and-babel-to-build-a-react-js-app-5f804d729d3b#.nnlsc2vdz

**Comment by calesce** [comment]
Thanks for the link! Yeah, our [docs for 3.0](https://github.com/gaearon/react-hot-loader/tree/next-docs/docs) could use some more explanation of the Webpack/Babel trickiness.
