### ISSUE TITLE
Full reload needed version 3.0.0-beta.4

### ISSUE THREAD

**Issue by maestroh** [gaearon/react-hot-loader#362]
I'm getting an error that a full reload is needed for any changes to my Typescript project. I know this error comes up regularly, so I apologize in advance if this has been resolved previously. I'm using RHL beta 4 and the webpack hot middleware instead of the dev server. 

Here's my webpack config:

```
var path = require('path');
var webpack = require('webpack');

module.exports = {
  devtool: 'source-map',
  entry: [
    'webpack-hot-middleware/client',
    'react-hot-loader/patch',
    './src/client/index.tsx'
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: ''
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ],
  module: {
    preLoaders: [
      { test: /\.js$/, loader: "source-map-loader" }
    ],
    loaders: [{
      test: /\.tsx?$/,
      loaders: [
        'react-hot-loader/webpack',
        'ts-loader'
      ],
      include: path.join(__dirname, 'src')
    }]
  }
};
```

Here's the relevant bits in my server:

```
app.use(webpackDevMiddleware(
    compiler, {
      hot:true,
      stats: {
        colors: true
      }
    }
  ));
  app.use(webpackHotMiddleware(compiler));
```

index.tsx is responsible for rendering and wraps another simple component. When I make changes to my simple component, I get the "Full reload needed" error.

Any ideas on what I'm doing wrong here?

**Comment by calesce** [comment]
Thanks, any way you can put up a minimal project reproducing the issue? The smaller, the better 😄

**Comment by maestroh** [comment]
Here's an example. I tried to keep it as simple as I could.

https://github.com/maestroh/rhl_error_362

Thanks for looking into it.

**Comment by calesce** [comment]
Hey @maestroh, I tried to install/run and it looks like it's expecting a `typings/index.d.ts` file which keeps it from building. I'm trying to "force compile" but I'm not familiar with TypeScript.

**Comment by maestroh** [comment]
You may need to get the typescript definition files. Try this:
```
npm install typings --global
typings install
```

**Comment by calesce** [comment]
Opened https://github.com/maestroh/rhl_error_362/pull/1 for the fix, let me know what you think.

**Comment by maestroh** [comment]
That fixes the problem. It looks like you made two main changes: wrapping my root component, `<Home/>` with the `<AppContainer>` component & adding the `module.hot.accept` bits. I seem to have overlooked that code in the boilerplate. Could you point me to the docs that could explain why you had to make those changes?

**Comment by calesce** [comment]
@maestroh: The [`next-docs` branch](https://github.com/gaearon/react-hot-loader/tree/next-docs/docs) is the best place (for now) showing the changes needed, and [react-hot-boilerplace](https://github.com/gaearon/react-hot-boilerplate/tree/next) has the simplest complete example.

**Comment by maestroh** [comment]
@calesce Thanks for the help
