### ISSUE TITLE
Full reload needed version 3.0.0-beta.4

### ISSUE THREAD

**Issue by vivaxy** [gaearon/react-hot-loader#363]
- [added AppContainer](https://github.com/vivaxy/react-scaffold/blob/master/source/library/render.js#L10)
- [added react-hot-loader/webpack in webpack.config](https://github.com/vivaxy/react-scaffold/blob/master/webpack.config.js#L148)
- [added react-hot-loader/patch in entry](https://github.com/vivaxy/react-scaffold/blob/master/webpack.config.js#L132)

edit component/DemoButton.js, instead of hot replacement, it needs a full reload.
```
[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
log-apply-result.js:13 [HMR]  - 1022
```

The whole project is [here](https://github.com/vivaxy/react-scaffold).
Why cannot it be hot replaced?

**Comment by calesce** [comment]
Hi, I see two things:

* You'll need to implement `module.hot.accept` in [`render.js`](https://github.com/vivaxy/react-scaffold/blob/master/source/library/render.js#L37), see [here](https://github.com/gaearon/redux-devtools/blob/master/examples/todomvc/index.js) for an example of how to do it with Redux.
* I see you're using `@connect`, unfortunately we don't yet support hot-reloading components with decorators, see #279.

Let me know if those help solve your issue.

**Comment by vivaxy** [comment]
@calesce Thanks.
Seems react-hot-loader@3.0 is a little bit difficult to use. Maybe I'll consider switch back to 1.0.

**Comment by calesce** [comment]
@vivaxy No problem, it'll be easier to get started once 3.0 is fully released and all of the information is in one place.
