### ISSUE TITLE
"If you know a good guide on migrating to Webpack, let me know and Iʼll link to it"...

### ISSUE THREAD

**Issue by saniko** [gaearon/react-hot-loader#365]
Found this:

Migrating to webpack from require.js:
https://gist.github.com/xjamundx/b1c800e9282e16a6a18e
https://www.youtube.com/watch?v=NEJyIBwo-ik
https://github.com/kentcdodds/require-to-webpack-todomvc

Hot reload for backbone/Marionette apps:
http://avitureblog.com/2016/09/01/webpack-hot-reloading.html

FYI

**Comment by calesce** [comment]
Thanks! The website's a bit out of date now (update soon!), and there are tons of Webpack articles at this point. We'll probably just point to the Webpack docs in the future.
