### ISSUE TITLE
Returns Proxy object instead event object

### ISSUE THREAD

**Issue by BrunoQuaresma** [gaearon/react-hot-loader#368]
i'm handle a onSubmit event in a form. But it always returns a Proxy object instead event object. 

```
<form onSubmit={values => {
          console.log("========>", values);
          return false;
        }}>
        <div>
          <label htmlFor="firstName">First Name</label>
          <input name="firstName" type="text"/>
        </div>
        <div>
          <label htmlFor="lastName">Last Name</label>
          <input name="lastName" type="text"/>
        </div>
        <div>
          <label htmlFor="email">Email</label>
          <input name="email" type="email"/>
        </div>
        <button type="submit">Submit</button>
      </form>
```

Console output: 
->Proxy {dispatchConfig: Object, _targetInst: ReactDOMComponent, _dispatchInstances: ReactDOMComponent, nativeEvent: Event, type: "submit"…}

**Comment by calesce** [comment]
React seems to always pass a proxy object to `onSubmit`, and I just tested with no React Hot Loader.

Also, it looks like the issue you were having was resolved in https://github.com/erikras/redux-form/issues/1818.

**Comment by BrunoQuaresma** [comment]
Thanks @calesce !
