### ISSUE TITLE
[Request] Please keep changelog up to date

### ISSUE THREAD

**Issue by paulwithap** [gaearon/react-hot-loader#369]
I'm not sure that an issue is the proper avenue for this, but this is just a request to **please** keep the changelog up to date. I'm currently on v3.0.0.beta.1, and I have no idea if I can safely update to beta.4.

This is a crucial element for anyone who is using your library in a serious project. Thank you in advance!

**Comment by calesce** [comment]
Hi. I've been keeping track of changes in [releases](https://github.com/gaearon/react-hot-loader/releases). I'll update the CHANGELOG.md when I have more time. There aren't any breaking changes between beta.1 and beta.4, just added features and bugfixes.

**Comment by calesce** [comment]
Updated the CHANGELOG.md.
