### ISSUE TITLE
after syntax error encountered, subsequent patches fail to apply (even if the syntax error is fixed)

### ISSUE THREAD

**Issue by faceyspacey** [gaearon/react-hot-loader#371]
I'm getting this issue using `react-hot-loader 3.0.0-beta.4` and `webpack-dev-server`(***without*** the sometimes problematic webpack command line functionality). 

I'm getting the following messages: 

```
[WDS] Errors while compiling.
<-- INFO ABOUT MY SYNTAX ERROR -->
[WDS] App hot update...
[HMR] Checking for updates on the server...
[HMR] Cannot apply update. Need to do a full reload! only-dev-server.js:40
[HMR] Error: Cannot find module "../widgets/Modal"...
[WDS] App updated. Recompiling...
[WDS] App hot update...
```

I could be wrong, but I'm pretty sure in another app I was working on, such issues were able to be resolved without a full reload. Have I missed a configuration option? Or are manual reloads standard fare in this case?

The relevant part of my Webpack config looks like this:

```
module.exports = {
  entry: [
    'react-hot-loader/patch',
    'webpack-dev-server/client?http://localhost:3000',
    'webpack/hot/only-dev-server',
    path.join(__dirname, '../index.web.js')
  ],
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          "presets": ["es2015", "stage-0", "react"],
          "plugins": ["react-hot-loader/babel", "transform-decorators-legacy"],
          cacheDirectory: true,
        },
      },

    ]
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
  ],
}

```

**Comment by calesce** [comment]
I personally use `webpack-hot-middleware` with `webpack-dev-middleware` instead of WDS, and `webpack-hot-middleware` actually shows a nice overlay on syntax errors, which disappears after fixing the error, and you can continue without refreshing:

<img width="1680" alt="screen shot 2016-09-20 at 9 50 21 am" src="https://cloud.githubusercontent.com/assets/5377524/18675336/ab057754-7f17-11e6-848a-3e9511994417.png">

The drawback is that you have to install a few more dependencies, but this should be solvable in WebpackDevServer.

**Comment by calesce** [comment]
Closing because this is related to WDS.

**Comment by bochen2014** [comment]
@calesce  like you said , if we use `webpack-hot-middleware` and `webpack-dev-middleware`,  yes we will have a nice error box popping out in the case of syntax error -- I have already got it work with my project.. But do we still need RHL in such case?

I thought RHL only works with WDS (according to tutorials), and the whole idea is to replace `webpack-hot-middleware` & `webpack-dev-middleware` and providing better experience. Please correct me if i'm wrong

**Comment by calesce** [comment]
No, it works with any tool that integrates with Webpack and passes HMR updates.
