### ISSUE TITLE
Module build failed: Error: React Hot Loader

### ISSUE THREAD

**Issue by wdd119** [gaearon/react-hot-loader#377]
error message:
ModuleBuildError: Module build failed: Error: React Hot Loader: The Webpack loader is now exported separately. If you use Babel, we recommend that you remove "react-hot-loader" from the "loaders" section of your Webpack configuration altogether, and instead add "react-hot-loader/babel" to the "plugins" section of your .babelrc file. If you prefer not to use Babel, replace "react-hot-loader" or "react-hot" with "react-hot-loader/webpack" in the "loaders" section of your Webpack configuration.

It works when I use babel instead of react-hot

**Comment by calesce** [comment]
This is documented [here](https://github.com/gaearon/react-hot-loader/tree/next-docs/docs), the `react-hot` loader is deprecated in 3.0.
