### ISSUE TITLE
React  Hot Loader3 is too slow.

### ISSUE THREAD

**Issue by xianshannan** [gaearon/react-hot-loader#380]
Just a small demo，the rebuilding time is nearly 6000ms.Is there any solution?

**Comment by calesce** [comment]
Hi, do you have an example repo demonstrating the issue? In my experience, startup can take around 5-20 seconds depending on project size (but that's mostly due to Webpack/Babel, haven't benchmarked RHL itself), but hot updates are <1 or 2s.

**Comment by xianshannan** [comment]
Here is the demo ,[https://github.com/sn-demo/webpack-react-demo](https://github.com/sn-demo/webpack-react-demo)(see demo10).When i add a ui library，it spend nearly 30s to rebuid!And React Hot Loader3  is failed!

**Comment by xianshannan** [comment]
The libray i add is [ant-design](https://github.com/ant-design/ant-design) .

**Comment by xianshannan** [comment]
I was wrong.I forget to set NODE_ENV to development.It's slow because of using UglifyJsPlugin!
