### ISSUE TITLE
Didn't work with older version of Node.  Should package.json specify 'engine'?  

### ISSUE THREAD

**Issue by uglycoyote** [gaearon/react-hot-loader#384]
Hi,

 I was following this tutorial on setting up Typescript and React:  http://blog.tomduncalf.com/posts/setting-up-typescript-and-react/

 The author's project template failed to work at first, giving the following error:

```
Module build failed: ReferenceError: Symbol is not defined
at plugin (/Users/mike/development/web/TypeScriptExamples/typescript-react-template/node_modules/react-hot-loader/lib/babel/index.js:53:23)
```

Digging in to this a bit more, it seemed like this was a symptom of using an old version of Node.  So I upgraded to v6.6.0 and it ran without errors (was on 0.10.28 previously), and this problem went away.

I'm fairly new to Node.js, but I understand that the packages.json file is supposed to specify all of the dependencies of that particular packages, so I was surprised that it would report an error like this rather than just telling me I don't have the version of Node that's required by one of the dependencies.   

It turns out that there is a way in packages.json to specify the version of Node that you depend on:

{ "engines" : { "node" : ">=0.10.3 <0.12" } }

though neither his template project nor your react-hot-loader specify an "engines" requirement in the packages.json.   I mentioned this in his comments section, but since the problem is actually under react-hot-loader, I thought I would mention it here, since specifying the engine requirements in the react-hot-loader package.json would have probably saved me from this problem as well. 

 Perhaps it's not common practice to specify which version of Node is required?

**Comment by calesce** [comment]
Thanks for the report! You're right. We need to either include the [Babel runtime](http://babeljs.io/docs/plugins/transform-runtime/) so `Symbol()` gets turned into something that works in those environments, or alternatively not support 0.12 and lower.

I know Node 0.12 will [no longer be receive updates](https://github.com/nodejs/LTS) at the end of the year, for what it's worth.

I don't feel too strongly either way, thoughts @nfcampos?

**Comment by calesce** [comment]
Added a requirement for the Node version to be 4 or higher in 2ce0b3c27520777ae78b6050efbf5891577fb4c8.
