### ISSUE TITLE
This is maybe a bug.

### ISSUE THREAD

**Issue by xianshannan** [gaearon/react-hot-loader#387]
React Hot Loader work correctly,But after Hot-reload,it will has warning like below.
```
warning.js:36 Warning: setState(...): Can only update a mounted or mounting component.
This usually means you called setState() on an unmounted component. This is a no-op. 
Please check the code for the Component component.
```
[Demo is here.](https://github.com/sn-demo/webpack-react-demo),please see demo13.

**Comment by calesce** [comment]
Hi, I don't see `react-hot-loader/patch` anywhere in demo13. Try putting that in `entry` of your Webpack config.

**Comment by xianshannan** [comment]
But when I put `react-hot-loader/patch` in the `entry`,it's no use while using `require.ensure`.See Demo 13 again.

**Comment by calesce** [comment]
Ah yes, there's a known issue with `require.ensure`, see #288. The workaround is to add extra `module.hot.accept` callbacks for each separate module (which is annoying).

`System.import` may be a good alternative if you can use Webpack 2, see https://github.com/gaearon/react-hot-loader/issues/303#issuecomment-249870741.

**Comment by penx** [comment]
I had this issue when trying to switch from `babel-preset-es2015` to `babel-preset-env`. Adding `transform-es2015-classes` to the included transforms resolved it for me:

    presets: [
      ['env', {
        targets: {
          chrome: 60
        },
        include: ['transform-es2015-classes']
      }],
      'stage-1',
      'react'
    ],
    plugins: ['react-hot-loader/babel']
