### ISSUE TITLE
does not support displaying syntax errors

### ISSUE THREAD

**Issue by bochen2014** [gaearon/react-hot-loader#388]
I previously used webpack-hot-middleware with HotModuleReplacementPlugin to do hot re-loading, and I also used redbox-react  to  display a nice error page in case of syntax errors. My source code is something like below
```
webpack.config
entry:[
  'webpack-hot-middleware/client',
    './src/index'
]
 plugins: [
    new webpack.HotModuleReplacementPlugin()
  ]


index.js :
render = ()=>{
const App = require('./App').default
ReactDOM.render(<App />, root)
}

if(module.hot){
module.hot.accept('./App',()=>{

try{
   render() //hot re-render  after module change
}catch(err){
   const RedBox = require('redbox-react')
    ReactDOM.render(
      <RedBox error={error} className="redbox"/>,
      root)

})}

render(); //do the initial render;

```
above code works fine and will gives me a nice error page whenever there is a syntax error in my updated module

I then switched to react-hot-loader , latest version (react-hot-loader@3.0.0-beta.5), something like

```
import HomePage  from './components'

const store = configureStore()
const render=(App)=>{
  ReactDOM.render(
    <Provider store={store}>
        <MuiThemeProvider muiTheme={getMuiTheme()}>
          { App }
        </MuiThemeProvider>
    </Provider>, dest)
}

if (module.hot) {
  module.hot.accept('./components', () => {
    // If you use Webpack 2 in ES modules mode, you can
    // use <App /> here rather than require() a <NextApp />.
    try{
    const NextApp = require('./components').default
    render(<AppContainer>
              <NextApp />
           </AppContainer>)
    } catch(error){
       const RedBox = require('redbox-react')
       ReactDOM.render(<RedBox error={error} className="redbox"/>, dest)
    }
  })
}

render( <AppContainer>
           <HomePage  />
        </AppContainer>)

```

it works as expected, , just not showing the RedBox i was expecting in case of syntax error. I reckon it's because of  'webpack/hot/only-dev-server' that prevent hot reloading when syntax errors. why?

**Comment by bochen2014** [comment]
btw, the Bare minimum hot loader example is too minimum ,, I mean, it's quite rare that `<App />` is at the top of dom tree, in most cases, it's wrapped by `<router>` or redux `<provider>` .We may not want to include Router/Redux into hot loader, as they are unlikely to change. Also, the store is a bit tricky, we don't want to create a new store instance on every re-render (which I did, and then corrected the mistake following  https://github.com/reactjs/react-redux/issues/259 ). 

Anyway, not sure if you want to flesh it out a bit, maybe just make it work with 
```
<Wrapper>
  <AppContainer>
       <App />
</AppContainer>
</Wrapper>
```

which is what I was doing in my opening question. I'm happy to make a pull request if you think is worth it. thanks

**Comment by calesce** [comment]
RHL uses Redbox-React just to display errors caught in `render` when a component mounts (unfortunately not yet on updates, see https://github.com/facebook/react/pull/6020). Syntax errors aren't handled by RHL. Personally (as I said in #371), I recommend using [`webpack-dev-middleware`](https://github.com/webpack/webpack-dev-middleware) and [`webpack-hot-middleware`](https://github.com/glenjamin/webpack-hot-middleware) alongside Express, the syntax error overlay is very nice.

A simple example of using RHL3 with Redux is [here](https://github.com/gaearon/redux-devtools/blob/7513b96f8ed751436698113666d1a08c1e46425f/examples/counter/src/index.js). I agree we more simple examples using common libs in our docs.

**Comment by bochen2014** [comment]
@calesce  thanks for answering my question.

If I understand you correctly, RHL can't handle syntax errors, if we want handle that, we have to switch to `webpack-dev-middleware` with `webpack-hot-middleware`. Please correct me if I'm wrong. 

why can't we make RHL handle syntax errors like webpack-hot-middleware do?
(I've also replied in #371 )

**Comment by calesce** [comment]
Syntax errors aren't the concern of React Hot Loader, but since it integrates with Webpack, I'm just recommending the surrounding tools for the best (in my opinion) dev experience. Right now those choices are either WDS or dev+hot middleware (both work with RHL).

When I say syntax errors, I'm talking about errors that fail at parse/compile-time, which would be before they get to RHL or a `try-catch` in running code. The error gets passed from Webpack to `hot-middleware` as a hot update. I don't know exactly what it looks like, but `hot-middleware` is able to take that error, display the chunk of broken code, and inject that onto the page.

Hope that's helpful.
