### ISSUE TITLE
Updates no longer working after fixing syntax error

### ISSUE THREAD

**Issue by aoshi321** [gaearon/react-hot-loader#389]
Hi

I've found when trying the following boilerplate: https://github.com/gaearon/react-hot-boilerplate/tree/next  the following occurs:

When I add a syntax error to a component it correctly show's me an error in the console.
When I fix the error it rebuilds correctly but further changes are no longer picked up.

I've had the same issues when adding the new react hot loader to my own project.

thanks

Aoshi

**Comment by calesce** [comment]
This is an issue with Webpack Dev Server, and I recommend using `webpack-dev-middleware`/`webpack-hot-middleware`, see my responses in #371, #388.

**Comment by aoshi321** [comment]
Im currently using webpack-dev-middleware/webpack-hot-middleware in my current project and I'm still experiencing the same issue.

**Comment by mikeengland** [comment]
I am experiencing the same issue. I posted an issue on webpack-dev-server as you can see above, but I am still unsure which project is the culprit here. https://github.com/webpack/webpack-dev-server/issues/655

**Comment by calesce** [comment]
Thanks for the follow up @mikeengland, too bad the fix isn't coming to WDS 1.x.
