### ISSUE TITLE
Dev version of <AppContainer> used with NODE_ENV=test

### ISSUE THREAD

**Issue by esturcke** [gaearon/react-hot-loader#396]
Not sure if this is a misunderstanding/misconfiguration on my part, but while generating code coverage with Istanbul I'm seeing:

```
React Hot Loader: It appears that "react-hot-loader/patch" did not run immediately before the app started. Make sure that it runs before any other code. For example, if you use Webpack, you can add "react-hot-loader/patch" as the very first item to the "entry" array in its config. Alternatively, you can add require("react-hot-loader/patch") as the very first line in the application code, before any other imports.
```

It [looks to me](https://github.com/gaearon/react-hot-loader/blob/v3.0.0-beta.5/src/AppContainer.js#L5) that with `NODE_ENV=test` we're using the dev version of `<AppContainer>`.

Should that be something like the following?

```js
if (!module.hot || process.env.NODE_ENV === 'production') {
  module.exports = require('./AppContainer.prod');
} else {
  module.exports = require('./AppContainer.dev');
}
```

**Comment by calesce** [comment]
Yep, you're right. Really we should never use the dev version of `AppContainer` or `patch` whenever `module.hot` isn't present. I'll try to fix this and release a beta 6 tonight. Thanks!

**Comment by calesce** [comment]
Out in `3.0.0-beta.6`
