### ISSUE TITLE
Cannot find module './lib/babel'

### ISSUE THREAD

**Issue by cgotcu** [gaearon/react-hot-loader#397]
I am getting the following error: Module build failed: Error: Cannot find module './lib/babel' using react-hot-loader@3.0.0-beta.5

Looking at node_modules/react-hot-loader/babel.js it indeed does a require('./lib/babel') which seems odd because there is no lib dir under the module.

Any thoughts?

From my package.json:
```
    "babel": "^6.5.2",
    "babel-core": "6.16.x",
    "babel-loader": "^6.2.5",
    "babel-preset-es2015": "6.16.x",
    "babel-preset-react": "6.16.x",
     ...
    "react-hot-loader": "https://github.com/gaearon/react-hot-loader/tarball/next",
     ...
```

.babelrc:
```
{
  "presets": ["es2015", "react"],
  "plugins": ["react-hot-loader/babel"]
}
```

**Comment by calesce** [comment]
I'd recommend changing the `package.json` to `"react-hot-loader": "3.0.0-beta.5"`.

We compile (via Babel) [before publishing to NPM](https://github.com/gaearon/react-hot-loader/blob/8fab49ed2f229b6ec9858fe3000204b600b1cc73/package.json#L18), so when users install it, the pre-built `lib/` directory is already there.

If you pull directly from GitHub, that build step hasn't been run, so you won't have `lib/`.

**Comment by cgotcu** [comment]
Thank you!
