### ISSUE TITLE
if(element.loader) return element.loader.split("!"); ^  TypeError: element.loader.split is not a function

### ISSUE THREAD

**Issue by daisy-github** [gaearon/react-hot-loader#399]
**webpack.config.js file code**

var path = require('path');
var webpack = require('webpack')

module.exports = {
    entry: path.resolve(__dirname, 'lib', 'client.js'),
    output: {
        filename: 'app.js',
        path: path.resolve(__dirname, 'lib'),
    },

    module: {
    loaders: [
      { test: /\.js$/, exclude: /node_modules/, loader: ['react-hot'] }
    ]
  },

  plugins: [
    
    new webpack.HotModuleReplacementPlugin()
  ]
};

**Comment by calesce** [comment]
I think because you're using singular `loader`, it needs to be a `string` instead of `Array<string>`
