### ISSUE TITLE
Make a landing page

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#40]
I think react-hot-loader needs a simple landing page with

* short intro video
* explanation of what it does
* link to boilerplate

http://gaearon.github.io/react-hot-loader/ is a long blog post and doesn't solve this problem.

I hope @kkga can help me with this!

**Comment by pburtchaell** [comment]
@gaearon I can help out with this. Planning to host on GH Pages?

**Comment by gaearon** [comment]
There's work in progress in `1.0-styles` branch but we haven't finished it (need to finish the logo and header, add styling to example & replace long article with a simple Getting Started).

@kkga Do you think we can get it done?

@pburtchaell What would you like to contribute? I haven't even gotten to writing a small Getting Started so that's something you can take, if you'd like. It's a challenging task because this page has to be both short, concise and useful.

**Comment by gaearon** [comment]
Fixed.
Seriously.
It's awesome and has a live demo.
You've got to see it!

http://gaearon.github.io/react-hot-loader/

+ new guide http://gaearon.github.io/react-hot-loader/getstarted/
