### ISSUE TITLE
Error on React 15.4.0-rc.4

### ISSUE THREAD

**Issue by wellyshen** [gaearon/react-hot-loader#400]
Hi I am using react-hot-loader v3 beta.6 for my [opensource](https://github.com/wellyshen/react-cool-starter). It's cool. Today I upgrade my react to 15.4.0-rc.4 and when I was running my project the error occurs, it said:

> ERROR in ./~/redbox-react/~/react-dom/index.js
> Module not found: Error: Can't resolve 'react/lib/ReactDOM' in '/Users/Welly/Desktop/react-cool-starter/node_modules/redbox-react/node_modules/react-dom'
>  @ ./~/redbox-react/~/react-dom/index.js 3:17-46
>  @ ./~/redbox-react/lib/index.js
>  @ ./~/react-hot-loader/lib/AppContainer.dev.js
>  @ ./~/react-hot-loader/lib/AppContainer.js
>  @ ./~/react-hot-loader/lib/index.js
>  @ ./~/react-hot-loader/index.js
>  @ ./src/client.js
>  @ multi main

I think it's because of the [redbox-react](https://github.com/commissure/redbox-react) doesn't support for 15.4.0-rc.4, does anyone have idea for it?

**Comment by calesce** [comment]
It doesn't look like `redbox-react` uses any internal React modules, which is the [only change that can break libraries](https://github.com/facebook/react/issues/7770#issuecomment-253899837), maybe you have installed incompatible versions of React/React DOM?

**Comment by wellyshen** [comment]
OKAY, thanks you

**Comment by gaearon** [comment]
Please see https://github.com/facebook/react/issues/7985#issuecomment-253979300.

**Comment by gaearon** [comment]
This should be fixed with `redbox-react@1.3.2`. You will need to delete `node_modules/redbox-react/node_modules/react-dom` if it's there after updating.
