### ISSUE TITLE
Updating to react-hot-loader@3.0.0-beta.6 broke HMR on Webpack 2 System.import

### ISSUE THREAD

**Issue by ctrlplusb** [gaearon/react-hot-loader#401]
As soon as I updated the HMR of my `System.import` components broke.

Tech stack:
> react router 4.0.0-alpha.4
> webpack 2.1.0-beta.25
> babel-core 6.17.0
> react hot loader 3.0.0-beta.6

I have an example of it working [`here`](https://github.com/ctrlplusb/code-split-component).

```
git clone https://github.com/ctrlplusb/code-split-component
npm install
npm run example
```

You will see HMR works when editing a component that was resolved via `System.import`. If you then upgrade to the latest beta of `react-hot-loader` it breaks the HMR feature.  Luckily this project includes a babel plugin to transpile any `System.import` statements into synchronous `require` statements.  I configured the babel plugin to do this for my development builds everything works great again.

Just a heads up for anyone else who is experiencing this after upgrading.

**Comment by calesce** [comment]
It [doesn't look like](https://github.com/ctrlplusb/code-split-component/blob/master/example/webpack.config.js#L36-L39) the example includes the RHL babel plugin. I also tried the example with the Beta 6 and hot reloading seemed to work.

There are only [two changes in Beta 6](https://github.com/gaearon/react-hot-loader/releases/tag/v3.0.0-beta.6). Is it possible the first change breaks any assumptions we're making? It opts out if there is no `module.hot`.

**Comment by ctrlplusb** [comment]
DOH! Closing.
