### ISSUE TITLE
Can't apply update, Need to do a full reload.

### ISSUE THREAD

**Issue by shikelong** [gaearon/react-hot-loader#403]
### Env  
+ react-hot-loader 3.0.0-beta.5
+ webpack 1.9.11

### error info
![react-hot-loader-error1](https://cloud.githubusercontent.com/assets/4499997/19585400/b786c1d4-977e-11e6-9839-39cf217d3850.png)

### code

+ webpack.config.js

```js
...
module.exports = {
  devtool: 'cheap-module-source-map',
  devServer: {
    contentBase: path.join(__dirname, config.buildPath),
    port: config.port,
    colors: true,
    historyApiFallback: true,
    inline: true,
    hot: true
  },
  entry: {
    index: [
      'react-hot-loader/patch',
      appConfig.entry
    ],
    vendor: vendorPackages
  },
  ....

```

+ .babelrc

```js
...
"plugins": [
    "react-hot-loader/babel"
]
...
```
+ js

 + index.js

```js
...
const loginAlready = loginAuth();

const rootEl = document.getElementById('root');

if (loginAlready){
  Promise.all([getRoutes(), getFunctionalities()]).then(() => {
    const store = configureStore();
    attachHistoryCheck(browserHistory);
    const history = syncHistoryWithStore(browserHistory, store);

    render(
      <Root
        store={store}
        history={history}
        rootRoute={rootRoute}
      />,
      rootEl
    );

    if (module.hot) {
      module.hot.accept('./Root', () => {
          // If you use Webpack 2 in ES modules mode, you can
          // use <App /> here rather than require() a <NextApp />.
          const NextApp = require('./Root').default;
          ReactDOM.render(
            <NextApp
              store={store}
              history={history}
              rootRoute={rootRoute}
            />,
            rootEl
          );
      });
    }
  });
}

```

+ Root.js

```js

import React, {Component, PropTypes} from 'react';
import {Provider} from 'react-redux';
import {Router} from 'react-router';
import DevTools from '../DevTools';
import { AppContainer } from 'react-hot-loader';

export default class Root extends Component{
  render(){
    const {store, history, rootRoute} = this.props;

    return (
      <AppContainer>
        <Provider store={store}>
          <div>
            <Router
              history={history}
              routes={rootRoute}
            />
            <DevTools />
          </div>
        </Provider>
      </AppContainer>
    );
  }
}

Root.propTypes = {
  store: PropTypes.object.isRequired,
  history: PropTypes.object.isRequired,
  rootRoute: PropTypes.object.isRequired
};

```

Regards.

**Comment by roebuk** [comment]
I've just hit a very similar, if not the same issue as yourself. After a number of hours not making any progress I reverted back to version `1.3.0`. I'll list my changes to downgrade below, just incase it helps you.

In `.babelrc` remove `react-hot-loader/babel` from your plugins
```
{
  "presets": ["es2015", "react"],
  "plugins": ["react-hot-loader/babel"]		
}
```

In `webpack.config.dev.js` make sure you add `react-hot` to your JS loaders

`loaders: ['react-hot', 'babel'],`

In `package.json` downgrade from`3.0.0-beta.6` to `1.3.0`.

It's a shame I never got to the bottom of what was causing this issue on version 3.

**Comment by roebuk** [comment]
Ahhh, so we may have had a similar issue to yourself, a colleague of mine managed to get it working. From looking at your code the I've noticed the following:

Within your `webpack.config.js` make sure you have the `webpack-dev-server` and `webpack/hot/only-dev-server` after your `react-hot-loader/patch`
```
entry: [
  'react-hot-loader/patch',
  'webpack-dev-server/client?http://localhost:3000',
  'webpack/hot/only-dev-server',
  './src/index'
]
```

**Comment by shikelong** [comment]
Thank you. I will try your method.

**Comment by shikelong** [comment]
It no work.  

```js

entry: {
    index: [
      'react-hot-loader/patch',
      'webpack-dev-server/client?http://localhost:3001',
      'webpack/hot/only-dev-server',
      appConfig.entry
    ],
    vendor: vendorPackages
  },

```

**Comment by calesce** [comment]
@shikelong You need to either pass `rootRoute` into `module.hot.accept` and re-require it (and pass as props), or import it from `<Root>`. I have a simple RR example [here](https://github.com/calesce/react-hot-loader-examples).

Since the routes are the "entry point" to importing components, you need to make sure those are being hot replaced, otherwise it breaks the HMR chain. Note that you'll get a warning about "You cannot change <Router routes>", but you can ignore it.
