### ISSUE TITLE
Update "Get started" guide

### ISSUE THREAD

**Issue by milworm** [gaearon/react-hot-loader#407]
Thanks for an amazing project.

I've found a problem in your "get started" guide. Basically if `--hot --inline` is used to run your server one doesn't need to do this:

> It is time to configure Webpack itself. In your webpack.config.js, configure the entry to include 
the  dev server and the hot reloading server. Put them in array before your appʼs entry point:

Otherwise, console shows 2 messages that hot reloading works, because those flags will automatically inject hot reloading server to your entry point [(http://webpack.github.io/docs/webpack-dev-server.html#inline-mode)](http://webpack.github.io/docs/webpack-dev-server.html#inline-mode)

**Comment by calesce** [comment]
We're working on documentation updates for the new version of React Hot Loader over in #257 and #260. We probably won't do any more updates to RHL 1 docs/website, but pull requests are welcome.
