### ISSUE TITLE
Isomorphic Example?

### ISSUE THREAD

**Issue by irvinebroque** [gaearon/react-hot-loader#41]
Using the hot-loader with server-side react rendering is tricky. I'm not sure if this is the best approach, but here's what I'm trying to do:

https://github.com/irvinebroque/isomorphic-hot-loader

There's a bunch of configuration complexity here -- `hotLoadServer.js` runs on a different port than the main server, the path to client-side assets are different in development vs. production, you can't run a watcher process on the hotLoadServer (otherwise the web sockets die), timing issues between nodemon and webpackDevServer (since they're both essentially watching the same set of files), etc.

I still have some work to do to get it all working properly together, but when I finish, I'd be happy to put it up as an example starter project.

(or, if anyone's seen a better implementation of this, let me know!)

**Comment by gaearon** [comment]
There's now plenty of RHL examples with server rendering, so I'm closing this out.
