### ISSUE TITLE
react-hot-loader's babel plugin leaves system's path information inside production build

### ISSUE THREAD

**Issue by NSLS** [gaearon/react-hot-loader#414]
### Description

To get the latest v3 beta to work with babel, you should include "react-hot-loader/babel" inside your babel plugins to get it to work. However, this plugin will write the information about user's home directory and also the paths to the source files inside the build if you use `resolve.alias` inside your webpack config.

In my case, I get a bunch of such code inside my production build.
(__REACT_HOT_LOADER__.register(r,"isAbsoluteURL","/home/nsls/project/src/utils/index.js")

### Expected behavior

I would expect this project to either leave a recommendation inside the README of this repo to exclude the react-hot-loader/babel from the production babel's plugins. In my case, now the .babelrc looks like this:
```
{
  "presets":
  [
    "react",
    ["es2015", {"modules": "commonjs"}],
    "stage-0"
  ],
  "env": {
    "production": {
      "plugins": [
        "transform-runtime",
        "add-module-exports",
        "transform-decorators-legacy",
        "transform-react-display-name"
      ]
    },
    development: {
      "plugins": [
        "react-hot-loader/babel",
        "transform-runtime",
        "add-module-exports",
        "transform-decorators-legacy",
        "transform-react-display-name"
      ]
    }
  }
}
```

Or to prevent the plugin from writing this code inside the bundle when NODE_ENV or BABEL_ENV is set to "production", just like AppContainer simply renders the children when NODE_ENV === "production".

### Reproducible Demo

You can refer to [this](https://github.com/NSLS/universal-webpack-boilerplate) repo as an example and look inside the js bundle, searching for __REACT_HOT_LOADER__.register.

**Comment by calesce** [comment]
Check out #357, you'll need to make sure the webpack process is running with `NODE_ENV=production` (with something like [cross-env](https://github.com/kentcdodds/cross-env) for Windows support). `DefinePlugin` only sets `NODE_ENV` for the client-side bundle, but doesn't affect Babel loader.

**Comment by NSLS** [comment]
Got it. Thanks.
