### ISSUE TITLE
run successfully but nothing changes in the view

### ISSUE THREAD

**Issue by lovetingyuan** [gaearon/react-hot-loader#415]
### Description

Hello, I am using react-hot-loader 3, but nothing changes when I change my code

### Expected behavior

the web page should change without reload

### Actual behavior

the process of hot-loading looks normal, no errors reported, but nothing changes in the page, when I reload browser, changes will show, I don't know why. When I remove 'react-hot-loader/babel' from plugins option in .babelrc, everything is normal, hot-loading will be successful. That is so strange.

### Environment

React Hot Loader version: 3.0.0-beta.6

Run these commands in the project folder and fill in their results:

1. `node -v`: 7.0.0
2. `npm -v`: 4.0.2

Then, specify:

1. Operating system: windows 64 bit
2. Browser and version: chrome 54.0.2840.99 m (64-bit)

### Reproducible Demo

[my-react-hot-load.zip](https://github.com/gaearon/react-hot-loader/files/591105/my-react-hot-load.zip)

**Comment by calesce** [comment]
This appears to be an incomplete demo. Can you share something that is runnable? That will make it much easier to debug what's going wrong.

Also, if you're using WebpackDevServer, you don't need `webpack-hot-middleware`.

**Comment by calesce** [comment]
I'm going to close this out because you haven't responded, feel free to re-open if you haven't resolved the issue (and with a runnable demo, please).

**Comment by lovetingyuan** [comment]
so sorry for no response in time. now I just use `webpack-hot-middleware` without `RHL`, and it works for me, thank you a lot
