### ISSUE TITLE
RHL won't reload

### ISSUE THREAD

**Issue by yleclanche** [gaearon/react-hot-loader#419]
Hello,

I'm having trouble making RHL working with my project. It works if I change something directly in root.js.
But, for any changes in other component, the console displays `The following modules couldn't be hot updated: (Full reload needed)`

Some of my top level components use decorators, but not all of them.

index.js : 

```javascript
    ReactDOM.render(<AppContainer><MyApp/></AppContainer>, document.getElementById('root'));
    if (module.hot) {
        module.hot.accept('./root', () => {
            ReactDOM.render(
                <AppContainer>
                    <MyApp />
                </AppContainer>
                , document.getElementById('root'));
        });
    }
```

root.js

```javascript
export default class Root extends Component {
    render() {
        return (
            <div>
                <Provider store={store}>
                    <Router history={appHistory}>
                        {AppRoutes}
                    </Router>
                </Provider>
            </div>
        );
    }
}
```

**Comment by justinkwanlee** [comment]
+1 This has started happening since upgrading to react 15.4

**Comment by yleclanche** [comment]
Not sure if it's the same issue, I'm still on React 0.14

**Comment by calesce** [comment]
You'll need to make sure you're re-importing your route config, since that will link to your components. I'm not sure where `AppRoutes` comes from in this case. A runnable example would be more helpful, as we say in the issue template.

**Comment by yleclanche** [comment]
Here is an example : https://github.com/yleclanche/react-hot-loader-example
I didn't manage to get the same exact behavior..
Now I don't have the full reload message. Logs looks fine, but hot reload doesn't work.

**Comment by calesce** [comment]
So one issue is that with Webpack 2 and Babel, you'll need to disable Babel from compiling ES2015 modules to CommonJS modules, see [our docs](https://github.com/gaearon/react-hot-loader/tree/next/docs#webpack-2)

The other issue is that you're using the `@connect` decorator, which is currently not supported by RHL, see #279. A workaround is to instead do this:

```jsx
class App extends React.Component {
    render() {
        return (
            <div>
                <ul>
                    <li><Link to={'counter'}>Counter</Link></li>
                    <li><Link to={'field'}>Field</Link></li>
                    <li><Link to={'redux'}>Redux</Link></li>
                </ul>
                {this.props.children}
            </div>
        )
    }
}

export default connect(
    (state) => ({
        routing: state.routing,
    }),
    (dispatch) => ({})
)(App);
```

That way React Hot Loader can "see" the original `<App />` declaration and be able to hot-reload it.

I've tested these fixes with your project, and it fixes the issue, so I'm going to close this out.
