### ISSUE TITLE
Index error handling unnecessary in production builds

### ISSUE THREAD

**Issue by novemberborn** [gaearon/react-hot-loader#420]
This is in the `next` branch.

I'd like to `import { AppContainer } from 'react-hot-loader'`. However that includes [a whole bunch of error messages](https://github.com/gaearon/react-hot-loader/blob/2ce0b3c27520777ae78b6050efbf5891577fb4c8/src/index.js) meant to help people who use `react-hot-loader` incorrectly.

Instead I need to import from `react-hot-loader/lib/AppContainer` which is a bit silly. Perhaps this requires an `index.dev.js` and `index.prod.js` approach?

**Comment by calesce** [comment]
I don't think this is a big issue personally, but I'd accept a PR for this.

**Comment by calesce** [comment]
Fixed by #429, will be out in next beta!
