### ISSUE TITLE
Mixed JS/React Projects without React root component

### ISSUE THREAD

**Issue by mulles3008** [gaearon/react-hot-loader#426]
Hi, I recently switched from v1.3.0. to 3.0.0-beta.6. Previously HMR (an rerendering) worked out of the box without having to ''mess around'' with `module.hot.accept` and `AppContainer`. However with v3.0.0 this seems to have all changed which causes me some major difficulties.
The project (SP webapp) I'm working on has started as a pure JS-project, a year ago we then started to use React. Still the project is pure JS in its core and there is no React root component you could point at. So I'm wondering if there is any way around using `AppContainer` just like before with v1.x?

Thanks for any help

**Comment by calesce** [comment]
There's not a way around it for React Hot Loader 3, it forces you to explicitly opt into HMR. RHL 1.X inserted `module.hot.accept` into every module.

You can still probably put an `AppContainer` around every React "entry point".

**Comment by mulles3008** [comment]
Thanks for your quick reply. So adding `module.hot.accept` manually to the respective modules is not sufficient anymore with RHL 3? At least it did not worked for the module I have tried it right now...

**Comment by calesce** [comment]
You'll need to add `module.hot.accept` manually, as well as AppContainer. You can also go without React Hot Loader and use plain Webpack HMR if you don't care about retaining state in components when they're reloaded (say if you're using Redux).

Sorry if I wasn't clear before.

**Comment by mulles3008** [comment]
Ok, thanks for clarifying.

**Comment by calesce** [comment]
Going to close this out, please re-open if you have further issues!
