### ISSUE TITLE
v1.x compatibility with react-hot-api@0.5.0 ?

### ISSUE THREAD

**Issue by saifelse** [gaearon/react-hot-loader#431]
package.json specifies ^0.4.5 for react-hot-api, however, this excludes 0.5.0 due to some [silliness around major version 0 having special meaning](https://nodesource.com/blog/semver-tilde-and-caret/#caretmajorzero). There seems to be a bug fix in 0.5 that I'd like to use, but sadly shrinkwrap doesn't like forcibly installing a version outside of the specified semver:

> invalid: react-hot-api@0.5.0 myproj/node_modules/react-hot-loader/node_modules/react-hot-api

**Comment by calesce** [comment]
You can make a PR, we're not actively working on React Hot Loader 1.

**Comment by wkwiatek** [comment]
I'm closing it as we're going to focus on v3.
