### ISSUE TITLE
Hot-Reloading@3 not working

### ISSUE THREAD

**Issue by bboysathish** [gaearon/react-hot-loader#432]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

What you are reporting: Hot Reloading not working

### Expected behavior

What you think should happen: Hot Reloading should work 

### Actual behavior

What actually happens: Hot Reloading not working, but it was working previously on another system. 

### Environment

React Hot Loader version: 3.0.0-beta.6

Run these commands in the project folder and fill in their results:

1. `node -v`:  6.0.0
2. `npm -v`: 3.8.6

Then, specify:

1. Operating system: Windows 8.1
2. Browser and version: Chrome 55

### Reproducible Demo

Repro Repo
https://github.com/bboysathish/repro-hot-loading

**Comment by bboysathish** [comment]
@calesce Can you please take a look into it, if you have time. It should be some configuration issue as i am not getting error while running i am not able to figure it out, 

Note: This was working on one another system.

**Comment by alex-shamshurin** [comment]
This is something wrong with webpack configuration there. `new webpack.HotModuleReplacementPlugin()` is missing, besides,  I do not see that HMR is enabled in console.

**Comment by bboysathish** [comment]
It is there https://github.com/bboysathish/repro-hot-loading/blob/master/configuration/webpack/dev.js#L73 @alex-shamshurin

**Comment by calesce** [comment]
@bboysathish I haven't had time to look closely, but for `webpack-hot-middleware` you'll need `OccurenceOrderPlugin` and `NoErrorsPlugin`. Also make sure you're using `transform-es2015-classes`, there's a bug with built-in classes (#313).

**Comment by bboysathish** [comment]
@calesce Now that i have added those 2 plugins, still i am not able to see HMR in console 

https://github.com/bboysathish/repro-hot-loading/blob/master/configuration/webpack/dev.js#L73-L74

**Comment by alex-shamshurin** [comment]
Me too... Something is totally wrong.

**Comment by bboysathish** [comment]
@alex-shamshurin Have you tried forking my repo and run from your local ?

**Comment by alex-shamshurin** [comment]
Yes, I've done it just before write here. No "HMR"

**Comment by bboysathish** [comment]
@alex-shamshurin In that case, i can ping @gaearon here.

**Comment by calesce** [comment]
If it's not an issue specifically with React Hot Loader (as it looks like here), please go to StackOverflow, [Webpack's gitter](https://gitter.im/webpack/webpack), or [Reactiflux](http://www.reactiflux.com/).

**Comment by bboysathish** [comment]
@calesce I don't think it is error on webpack. How can i narrow down it is webpack or RHL ? i can open a same issue in webpack repo also.

**Comment by calesce** [comment]
If you're not even seeing HMR messages in the console, then it's likely not RHL, because it needs HMR to be able to work. I'd recommend looking at a [working example](https://github.com/gaearon/react-hot-boilerplate/tree/next), and making your project match that piece-by-piece until it works.

**Comment by bboysathish** [comment]
@alex-shamshurin  & @calesce Found the issue, removing `reload=true` from `webpack-hot-client` makes the RHL working https://github.com/bboysathish/repro-hot-loading/commit/0fb699e9e62be5cd69fa5ce1c93146c6982acdcc

**Comment by alex-shamshurin** [comment]
@bboysathish I have tried already but it doesn't help.
