### ISSUE TITLE
is v3 full update?

### ISSUE THREAD

**Issue by zombieJ** [gaearon/react-hot-loader#436]
Hi, I use the [adminLTE](https://almsaeedstudio.com/) front end theme. It will call jquery to adjust the content div height by window resize event.

For v1, it works fine for me. But for v3, I found when I update the code. The full dom will be refreshed which cause the height of the div also be rebuild.

Is there any config can I let the RHL-v3 only rebuild the changed component?

Thanks

**Comment by calesce** [comment]
Yes, see [the next branch](https://github.com/gaearon/react-hot-loader/tree/next/docs).
