### ISSUE TITLE
Cant get static files

### ISSUE THREAD

**Issue by Infonautica** [gaearon/react-hot-loader#437]
### Description
Have a trouble with static files
`entry: [
    'webpack-hot-middleware/client',
    './src/app',
],
output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/static/',
}`

React applications is works fine, but without css and other static files. I put them in "dist" folder, but still cant get them, so:
`<script src="/static/bundle.js"></script>` // Works fine
`<link href="/static/css/main.min.css" rel="stylesheet">` // Cant get

### Environment
React Hot Loader version: 1.3.1
1. `node -v`: 4.4.7
2. `npm -v`: 3.10.5
1. Operating system: Windows
2. Browser and version: Chrome

**Comment by calesce** [comment]
This looks like a Webpack configuration problem, and doesn't have anything to do with React Hot Loader. Please check their [docs](https://webpack.github.io/docs/configuration.html), [gitter chat room](https://gitter.im/webpack/webpack), or StackOverflow for help.

**Comment by Infonautica** [comment]
No, cuz i used yours boilerplate

**Comment by calesce** [comment]
The boilerplate doesn't deal with CSS because it's focused only on getting React Hot Loader up and running.

**Comment by Infonautica** [comment]
Boilerplate has an idea of sharing static files, but i cant implement it. It would be awesome, if you show me how to use static files in this boilerplate, thanks
