### ISSUE TITLE
Add starter kit to documentation

### ISSUE THREAD

**Issue by agrcrobles** [gaearon/react-hot-loader#438]
Hi,

I have created a simple starter with react-native-web and react-hot-loader.
(react-native-web, webpack with dev server, hot reloading and flow coming soon...)

If you find it interesting add it to documentation.
https://github.com/agrcrobles/react-native-web-webpack-starter

Thanks 
Alejandro

**Comment by calesce** [comment]
Cool, looks good. Can you open a pull request and add it to the list?

**Comment by agrcrobles** [comment]
Great, sure, it is done.
