### ISSUE TITLE
React Hot Loader Next installing outdated version 

### ISSUE THREAD

**Issue by bboysathish** [gaearon/react-hot-loader#441]
### Description

`npm install react-hot-loader@next` installs the outdated version see the below screenshot

### Expected behavior

it should install the latest beta version (3.0.0-beta.6)

### Actual behavior

installs (3.0.0-beta.2)

### Environment

React Hot Loader version:

Run these commands in the project folder and fill in their results:

1. `node -v`: 4.4.2
2. `npm -v`: 3.8.6

Then, specify:

1. Operating system: Windows 10
2. Browser and version: N/A

### Reproducible Demo

![hot-loader-bug](https://cloud.githubusercontent.com/assets/8023447/20865518/eea46822-ba3a-11e6-9ad2-e2bad3681253.PNG)

**Comment by calesce** [comment]
Updated `next` to point to  3.0.0-beta.6. Thanks.
