### ISSUE TITLE
Where is this project headed?

### ISSUE THREAD

**Issue by resistdesign** [gaearon/react-hot-loader#445]
The stable version is now broken with the latest version of React because `ReactMount` has been removed and the new version is still ["on the horizon"](https://github.com/gaearon/react-hot-loader/pull/240).

So I'm just wondering, where is this project headed?

**Comment by calesce** [comment]
There's already a similar discussion in #385. I'm helping to maintain this project in my spare time. I'd like to release 3.0 but the docs aren't there and there's a few bugs I want to iron out. But 3.0 works really well for many use cases.

Also, stable isn't broken, there was a fix released to support React 15.4.

**Comment by resistdesign** [comment]
@calesce Awesome news! Thank you for that! :)
