### ISSUE TITLE
Warning: setState(...): Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by didierfranc** [gaearon/react-hot-loader#446]
### Description

Any idea why I'm getting this when hot reloading happened ?

<img width="571" alt="capture d ecran 2016-12-09 a 15 59 45" src="https://cloud.githubusercontent.com/assets/14132464/21053284/03c2dbde-be29-11e6-8e97-4199020cb902.png">

### Expected behavior

To not have this error

### Actual behavior

Everything seems fine but console log errors like that 👆

### Environment

React Hot Loader version: 3.0.0-beta.6

Run these commands in the project folder and fill in their results:

```
yarn && yarn start
```

1. Operating system: macOS
2. Browser and version: Chrome 54

### Reproducible Demo

Run the project, editing some code from this https://github.com/didierfranc/redux-react-starter and error appear on stateful components.

**Comment by calesce** [comment]
This error is usually caused by #313, but it looks like you have the `es2015` preset. I'll try running your project later today and see what's going on.

**Comment by didierfranc** [comment]
Solved https://github.com/didierfranc/redux-react-starter/commit/e66ab1f3e5be6558f537632529c3e7a5b054b813

It seems that 
```
render()
```
and
```
module.hot.accept('../src', render)
```
must be in the same file 🤔

**Comment by ianks** [comment]
@didierfranc I tried this and although the error is gone, hot reloading is not working. Did you experience this at all?

**Comment by penx** [comment]
I had this issue when trying to switch from `babel-preset-es2015` to `babel-preset-env`. Adding `transform-es2015-classes` to the included transforms resolved it for me:

    presets: [
      ['env', {
        targets: {
          chrome: 60
        },
        include: ['transform-es2015-classes']
      }],
      'stage-1',
      'react'
    ],
    plugins: ['react-hot-loader/babel']

**Comment by Koenkk** [comment]
@penx thanks! It solved the problem in my case. 😄

**Comment by edorivai** [comment]
Just leaving a note for fellow Typescript googlers. A TS equivalent of @penx's babel solution would be:

```
// tsconfig.json
{
	"compilerOptions": {
		"target": "es5"
	}
}
```

**Comment by theKashey** [comment]
The root cause - arrow functions. You have to avoid them yet.

**Comment by mehdijjz** [comment]
@penx thanks! you saved my week!

**Comment by theKashey** [comment]
Everyone  - version 4 solves this. Update today.

**Comment by vkosovskikh** [comment]
Same problem with version **4.0.0-beta.18** of **react-hot-loader**. Error occurs when I save some changes on component and change route by clicking a button. Any help?
.babelrc:
```
presets: [
  ['es2015', { modules: false }],
  'stage-0',
  'react'
],
plugins: [
  'react-hot-loader/babel'
]
````
![rhl_error](https://user-images.githubusercontent.com/3707638/35911474-b944689c-0c1b-11e8-94cb-37ad3fa71580.png)

**Comment by theKashey** [comment]
@vkosovskikh, gonna to fix this in next release.
Keep in mind - this is not an errors, just a warning.

**Comment by neoziro** [comment]
@theKashey yes but this is very very annoying. In a big application it is a ton of warnings.

**Comment by theKashey** [comment]
One warning for a one component 🤷‍♂️

**Comment by theKashey** [comment]
@vkosovskikh - could you try the last beta version?

**Comment by koledaivan** [comment]
@theKashey had the same issue just now with version 4.0.0-beta.21, updating for 4.0.0-beta.22 solved the problem

**Comment by vkosovskikh** [comment]
@theKashey seems solved, ty

**Comment by Cottin** [comment]
I've been trying to research this for a while now and I'm still getting this warning. Is it just me?

https://github.com/Cottin/some-boilerplates/tree/master/react-hot-warning
If somebody wants to reproduce, I made a minimal example above.

**Comment by theKashey** [comment]
@Cottin - here is an explanation
```js
class Hello extends React.Component {
  constructor(props) {
    super(props)
    this.state = {name: '...'};

    this.getNameAndSet = this.getNameAndSet.bind(this)

    this.getNameAndSet() <-- will be executed on Class(Component) creation
  }
  getNameAndSet() {
    console.log(this)
    setTimeout((() => this.setState({name: 'Worrrld'})), 100) <-- will _always_ be fired
  }
```
During update RHL trying to undertand wich changes were made, and creating an old and a new class to compare them.
Creating, and throwing away, not adding to the tree.

You shall not trigger state change mechanics in the constructor. Move this logic to componentDidMount.

**Comment by Cottin** [comment]
@theKashey Thanks a lot for explanation! Works great with `componentDidMount`!
