### ISSUE TITLE
README.md should mention to install react-hot-loader@1.3.1

### ISSUE THREAD

**Issue by raarts** [gaearon/react-hot-loader#451]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

What you are reporting:

### Expected behavior

following the readme should work

### Actual behavior

It does not work, because the version in npm is v3 beta, and now following the readme does not work any more. The naive user - like me - gets stuck, and I lost a lot of time chasing the problems

**Comment by calesce** [comment]
We want to encourage people to use the v3 beta (and similarly discourage v1). I agree it's confusing, but 3 will be fully released soon.

**Comment by raarts** [comment]
Well I think this is the wrong way to do it, as following the readme as it is, will lead to failure, and this will lead to bad user experience.  So there.

**Comment by calesce** [comment]
Fair enough. Please make a PR to add the `npm install` to README and I'll merge it.

**Comment by calesce** [comment]
Actually I just double-checked, and `npm install react-hot-loader` still installs 1.3.1.

Only installing `react-hot-loader@next` or specific betas will install 3.0. I'm not sure where the confusion comes from.

**Comment by raarts** [comment]
Right. My sincere apologies. (Sits in a corner with a brown bag over his head). 

I use sinopia to cache npm downloads, which works so well, that I entirely forget about using it, and apparently sinopia had 3.0.0-beta cached, and thus sent me that version.

I apologise for my grumpiness, it was entirely unwarranted. Thanks for all the good work.

**Comment by calesce** [comment]
No worries, I sometimes have that problem myself, and it's very frustrating.
