### ISSUE TITLE
You cannot change <Router routes>; it will be ignored

### ISSUE THREAD

**Issue by wonbyte** [gaearon/react-hot-loader#454]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description
Receive the warning `You cannot change <Router routes>; it will be ignored` in chrome console when using react-hot-loader@3.0.0-beta.6

What you are reporting:
that it appears the routes get re-rendered every time a hmr runs.
### Expected behavior

What you think should happen:
There should be a way to not have the routes get re-rendered.
### Actual behavior

What actually happens:
routes re-rendered and warning is displayed in chrome console.
### Environment

React Hot Loader version:
3.0.0-beta.6
Run these commands in the project folder and fill in their results:

1. `node -v`: v7.3.0
2. `npm -v`: 4.0.5

Then, specify:

1. Operating system: macOS 10.12.2
2. Browser and version: latest chrome

### Reproducible Demo

https://github.com/jpsierens/webpack-react-redux

run this project and you will see the warning. Since the code is following the setup instructions per the hot-loader docs how can we prevent the routes from being re-rendered and having warnings clutter the chrome console?

interestingly in the following code snippet:
```
render(
    <AppContainer>
        <Root store={store} history={history} />
    </AppContainer>,
    document.getElementById('root')
);

if (module.hot) {
    module.hot.accept('./containers/Root', () => {
        const NewRoot = require('./containers/Root').default;
        render(
            <AppContainer>
                <NewRoot store={store} history={history} />
            </AppContainer>,
            document.getElementById('root')
        );
    });
}
``` 

if I remove the \<AppContainer\> around the render method, the warning will go away and hmr works as I would expect. So like this:

```
render(
        <Root store={store} history={history} />,
    document.getElementById('root')
);
```

**Comment by calesce** [comment]
Yeah, this is unavoidable when using HMR + React Router, see discussion in #249. The fix will have to come from React Router, but reloading routes still works. You can [patch `console.error` to ignore the warning](https://github.com/gaearon/react-hot-loader/issues/298#issuecomment-236510239) if it really bothers you.
