### ISSUE TITLE
Removal of *.hot-update.json files

### ISSUE THREAD

**Issue by joetidee** [gaearon/react-hot-loader#456]
I am using Webpack and have noticed that there is a build-up of *.hot-loader.json files in my designated output directory. Is there a way to ensure that this directory is cleared of any unecessary hot-loader files?

**Comment by calesce** [comment]
You'll get HMR updates (via sockets) in the browser from Webpack Dev Server (or dev-middleware), but not saved to disk in your project. Would you mind sharing a project demonstrating this issue? Also, this doesn't appear to be caused by React Hot Loader itself.

**Comment by eisisig** [comment]
Do you have a plugin to save to disk while dev server is running? That seems to be happening to me so I had to exclude those files

```js
new plugins.WriteFilePlugin({
	// exclude hot-update files
	test: /^(?!.*(hot)).*/,
}),
```

**Comment by joetidee** [comment]
No, I do not.

**Comment by calesce** [comment]
@joetidee can you share a small project reproducing the issue?

**Comment by joetidee** [comment]
It would be difficult to share this project, but here is my webpack.conf.js file:

```
const path = require('path');
const merge = require("webpack-merge");
const webpack = require("webpack");

const TARGET = process.env.npm_lifecycle_event;
const PATHS = {
    app: path.join(__dirname, '/client/src/app.jsx'),
    build: path.join(__dirname, '/client/dist'),
    test: path.join(__dirname, 'tests')
};


const common = {
    entry: [
        PATHS.app
    ],
    output: {
        path: PATHS.build
    },
    module: {
        loaders: [{
            test: /\.js?$/,
            loaders: ['babel'],
            include: path.join(__dirname, '/shared')
        },{
            test: /\.jsx?$/,
            loaders: ['react-hot','babel?' + JSON.stringify({
                presets: ["es2015", "stage-0", "react"]
            })],
            include: path.join(__dirname, '/client/src')
        },{
            test: /\.less$/,
            loaders: ['style', 'css', 'less']
        },
        {
            test: /\.ico$/,
            loader: "file-loader"
        },
        {
            test: /\.png$/,
            loader: "url-loader?limit=100000"
        },
        {
            test: /\.jpg$/,
            loader: "file-loader"
        },
        {
            test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+)?$/,
            loader: 'url?limit=10000&mimetype=application/font-woff'
        },
        {
            test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
            loader: 'url'
        },
        {
            test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
            loader: 'file'
        },
        {
            test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
            loader: 'url?limit=10000&mimetype=image/svg+xml'
        },{
            test: /\.json$/,
            loader: "json-loader"
        },{
            test: /\.css$/,
            loaders: ['style', 'css']
        }]
    },
    plugins: [
        new webpack.ProvidePlugin({
            "$":"jquery",
            "jQuery":"jquery",
            'global.jQuery': 'jquery'
        }),
        new webpack.optimize.OccurenceOrderPlugin(),
        new webpack.DefinePlugin({ 'typeof window': '\"object\"' })
    ],
    resolve: {
        extensions: ['', '.js', '.jsx', '.less', '.css'],
        alias: {
            'jquery-ui': 'jquery-ui-dist/jquery-ui.js'
        }
    }
};

// Default config.
if(TARGET === 'start' || TARGET){
    module.exports = merge(common, {
        devtool: 'eval-source-map',
        entry: [
            'eventsource-polyfill',
            'webpack-hot-middleware/client',
            'webpack/hot/only-dev-server',
            'babel-polyfill'
        ],
        output: {
            filename: 'app.js',
            publicPath: '/public/'
        },
        plugins: [
            new webpack.HotModuleReplacementPlugin(),
            new webpack.NoErrorsPlugin(),
            new webpack.DefinePlugin({
                'process.env': {
                    'NODE_ENV': JSON.stringify('development')
                }
            })
        ],
        resolve: {
            root: path.resolve('./client/src')
        },
        watch: true
    });
}

// Tests config.
if(TARGET === 'test' || TARGET === 'tdd'){
    module.exports = merge(common, {
        devtool: 'inline-source-map',
        resolve: {
            alias: {
                'app': PATHS.app
            }
        },
        module: {
            preLoaders:[
                {
                    test: /\.jsx?$/,
                    loaders: ['isparta-instrumenter'],
                    include: PATHS.app
                }
            ],
            loaders: [
                {
                    test: /\.jsx?$/,
                    loaders: ['babel?cacheDirectory'],
                    include: PATHS.test
                }
            ]
        }
    });
}

// Build config.
if(TARGET === 'build' || TARGET === 'stats'){
    var CompressionPlugin = require('compression-webpack-plugin');
    const HtmlWebpackPlugin = require('html-webpack-plugin');
    const CleanPlugin = require('clean-webpack-plugin');
    const ExtractTextPlugin = require('extract-text-webpack-plugin');
    const Visualizer = require('webpack-visualizer-plugin');
    //const pkg = require("./package.json");

    module.exports = merge(common, {
        entry: [
            /*vendor: Object.keys(pkg.dependencies).filter(function (v) {
             return v;
             }),*/
        ],
        module: {
            loaders: [
                {
                    test: /\.css$/,
                    loader: ExtractTextPlugin.extract('style', 'css')
                }
            ]
        },
        output: {
            filename: 'app.[chunkhash].js',
            /*filename: '[name].js',*/
            publicPath: 'http://auditor.tidee.com/public/'
        },
        plugins: [
            new webpack.DefinePlugin({
                'process.env': {
                    'NODE_ENV': JSON.stringify('production')
                }
            }),
            new webpack.optimize.DedupePlugin(),
            new webpack.optimize.UglifyJsPlugin({
                compress: {
                    warnings: false
                }
            }),
            /*new webpack.optimize.AggressiveMergingPlugin(), //Merge chunks*/
            new CompressionPlugin({
                asset: "[path].gz[query]",
                algorithm: "gzip",
                test: /\.js$|\.css$|\.html$/,
                threshold: 10240,
                minRatio: 0.8
            }),
            new HtmlWebpackPlugin({
                template: 'node_modules/html-webpack-template/index.ejs',
                title: 'Tidee',
                appMountId: 'app',
                inject: false
            }),
            new CleanPlugin(path.join(__dirname, '/client/dist')),
            new ExtractTextPlugin('[name].[chunkhash].css'),
            new Visualizer({
                filename: './statistics.html'
            })
        ],
        resolve: {
            root: path.resolve('./client/dist')
        }
    });
}
```

**Comment by calesce** [comment]
I don't know if you're using `WebpackDevServer` or `dev-middleware`/`hot-middleware`, but you're referencing both in your `entry` array.

You'll need `entry` to include both `webpack-dev-server/client?http://localhost:${PORT}` and `webpack/hot/only-dev-server` for WDS.

For `hot-middleware` you'll just need `webpack-hot-middleware/client`

Regardless, this is a Webpack configuration issue and not a React Hot Loader issue, so I'm going to close.

**Comment by edweena** [comment]
@joetidee did you ever get this solved? having exact same issue

**Comment by joetidee** [comment]
No, I did not solve my issue :(

**Comment by edweena** [comment]
@joetidee  one more question... are you using browser sync for dev server by chance?

**Comment by joetidee** [comment]
No I am not - should I be?

**Comment by DPangerl** [comment]
Having the same issue using webpack --watch.
On every file update, [hash].hot.update.js and [hash].hot.update.json is written in my output folder

**Comment by weichenghsu** [comment]
@DPangerl  any solution so far?

**Comment by sejo2016** [comment]
having this issue too,any solution for it?

**Comment by ryandhaase** [comment]
+1

**Comment by cliffordfajardo** [comment]
I was using the [`WriteFilePlugin`](https://github.com/gajus/write-file-webpack-plugin) and I excluded the hot files thanks to [eisisig](https://github.com/gaearon/react-hot-loader/issues/456#issuecomment-273216602) 's comment

```js
        new WriteFilePlugin({
          test: /^(?!.*(hot)).*/,
        }),
```

**Comment by skrzepij** [comment]
Those HMR chunks are created by HotModuleReplacementPlugin when we use `--watch` flag running webpack:
```webpack -d --watch```

The best way I found till now is to define specific folder and file for those chunks. We can do this in the output section, for example:
```  output: {
    path: path.join(root, "dist"),
    filename: "bundle.js",
    hotUpdateChunkFilename: 'hot/hot-update.js',
    hotUpdateMainFilename: 'hot/hot-update.json'
  }```

After this change, we will have only those two files created. So we can simply add them (or whole folder) to the .gitignore.

It's not the best solution, I know.. But I didn't find anything better for now.

**Comment by IAMtheIAM** [comment]
@skrzepij  That is a fantastic solution to control how many files get produced by hot-updates. Also thanks because I did not know about the `hotUpdateChunkFilename`  and `hotUpdateMainFilename` options for specifying location and name. Perfect

**Comment by eybarta** [comment]
@skrzepij beats having a million hot.update json files in my dist folder :) thx!

**Comment by johnstew** [comment]
@skrzepij this is what I needed, thank you!!

**Comment by ShaojieLiu** [comment]
@skrzepij  you save my folder, man

**Comment by danielkalbasi** [comment]
This is happening when file changes watch by both webpack and the webpack dev server. webpack --watch will generate the files as pointed in their doc, and that's normal. 

In order to fix this, you need to turn off the webpack watch and only let the dev server watch the file changes. Hope it helps!

`output: {`
`     ` `		publicPath: '/',`
`	},
`
`watch: false,`
`devServer: {`
`     ` `index: 'index.ejs',`
`     ` `		compress: true,`
`     ` `		port: 9000,`
`     ` `		clientLogLevel: 'none',`
`     ` `		watchContentBase: true,`
	},

**Comment by remi2j** [comment]
@skrzepij I'm using your solution but when I edit a file, I get an infinite loop of `[HMR] Updated modules:` of that file.  
Any idea what my cause this? I works fine otherwise

**Comment by Absvep** [comment]
> Those HMR chunks are created by HotModuleReplacementPlugin when we use `--watch` flag running webpack:
> `webpack -d --watch`
> 
> The best way I found till now is to define specific folder and file for those chunks. We can do this in the output section, for example:
> 
> ```
> output: {
>     path: path.join(root, "dist"),
>     filename: "bundle.js",
>     hotUpdateChunkFilename: 'hot/hot-update.js',
>     hotUpdateMainFilename: 'hot/hot-update.json'
> }
> ```
> After this change, we will have only those two files created. So we can simply add them (or whole folder) to the .gitignore.
> 
> I know It's not the best solution, but I didn't found anything better for now.

I get "Cannot apply update" when using hotUpdateChunkFilename and hotUpdateMainFilename :/

**Comment by andrewl64** [comment]
@skrzepij Where exactly should I add the following in?

```
output: {
    path: path.join(root, "dist"),
    filename: "bundle.js",
    hotUpdateChunkFilename: 'hot/hot-update.js',
    hotUpdateMainFilename: 'hot/hot-update.json'
}
```

**Comment by Absvep** [comment]
@andrewl64 in webpack config file :)

**Comment by kimgysen** [comment]
I also got the infinite loop problem. I fixed the problem with https://github.com/johnagan/clean-webpack-plugin.

**Comment by Mesqalito** [comment]
Yeah, [CleanWebpackPlugin ](https://github.com/johnagan/clean-webpack-plugin)solves the problem with config like this:
```
new CleanWebpackPlugin({
    cleanOnceBeforeBuildPatterns: [`${outputPath}/*.hot-update.*`],
    dry: false,
    dangerouslyAllowCleanPatternsOutsideProject: true
}),
```
The latter two required if your dist folder is outside project dir.
This also works fine with `webpack-dev-server` HMR.

**Comment by shareefhadid** [comment]
I think I figured it out. Are you using dev server middleware to write to disk by any chance? I was, and I was able to fix it using a function instead of setting it to true. Here is a snippet from my webpack.config:

`
devServer: {
    // ...
    devMiddleware: {
   // ...
        writeToDisk: (filePath) => {
        return /^(?!.*(hot)).*/.test(filePath);
      },
    },
}
`
