### ISSUE TITLE
Usage with an existing webserver

### ISSUE THREAD

**Issue by bilalq** [gaearon/react-hot-loader#46]
Before anything else, I wanted to express just how awesome I think this is. 

That aside, I ran into some issues getting this to work in the kind of setup I wanted. I have an Express server that I want to use as a RESTful API and have the `/` route serve the React app. In prod, I just have it build out and serve the static assets, so there's no problem there. 

However, I found it a little tricky to get the hot reload working with that kind of setup in development. 

I saw [this section](http://webpack.github.io/docs/webpack-dev-server.html#combining-with-an-existing-server) on using the webpack dev server with an existing server on the docs, and that worked well enough for basic usage, but hot reloading failed since it would try to make requests against my main server rather than the webpack one for hot reload updates.

I managed to work around this by defining a set of webpack routes to proxy through all requests for static assets. 

In `/server/routes/webpack.js`, I have:

```javascript
var express = require('express')
  , request = require('request')
  , router = express.Router();

var webpackServerUrl = 'http://localhost:3001/';

// Proxy all requests through to the webpack server
router.get('/*', function(req, res) {
  request(webpackServerUrl.concat(req.baseUrl, req.url))
  .pipe(res);
});

module.exports = router;
```

and in `/server/app.js`:
```javascript
// Use webpack server to serve static assets in development and express.static 
// for all other stages
if (app.get('env') === 'development') {
  var webPackServer = require('./routes/webpack');
  app.use('/scripts', webPackServer);
  app.use('/styles', webPackServer);
} else {
  app.use(express.static(path.join(__dirname, '..', 'build', 'client')));
}
```

And this is a rough skeleton of how things are structured:
```
.
├── client
│   ├── components
│   │   └── MyView.jsx
│   └── app.js
├── package.json
├── server
│   ├── app.js
│   ├── bin
│   │   ├── webpackDevServer
│   │   └── appServer
│   ├── middleware
│   │   └── errorHandler.js
│   ├── routes
│   │   ├── index.js
│   │   ├── users.js
│   │   └── webpack.js
│   ├── services
│   └── views
│       ├── error.jade
│       ├── index.jade
│       └── layout.jade
├── styles
│   └── app.scss
└── webpack.config.js
```

While this works, it seems like it's the wrong way to do it. I imagine this is a fairly common use-case, but I couldn't find any decent examples to support this. Is there a better approach to this than setting up a proxy like that?

**Comment by gpbl** [comment]
I prefer to use a proxy so I can open the web app on other devices maintaining relative urls.

**Comment by bilalq** [comment]
Thanks for sharing the approach.

**Comment by kurtharriger** [comment]
i use a proxy as it avoids issues with cross origin resource requests.  While you can and should handle cors headers for apis, browsers do not return good error information on 500 errors and using a proxy simplifies debugging during development.  
Instead of having your api proxy requests you can do it the ither way around as well. 
Webpack-dev-server can proxy request instead of redirecting by using contentBase: {target: 'http://localhost:8000' }.  Note contentBase is now an object with a target instead of a string. This tells webpack to proxy rather than redirect.

**Comment by kuchumovn** [comment]
Don't know if it works uniformly (on server) but with new webpack and its new "proxy" parameter it works for me with webpack-dev-server and existing node webserver

**Comment by gaearon** [comment]
Not really an issue. Closing. See above for many working approaches :-).
