### ISSUE TITLE
Expected Hot Reload Latency

### ISSUE THREAD

**Issue by francoislaberge** [gaearon/react-hot-loader#461]
Hi, 

For every webpack based live reloader I try, it takes what seems like >500ms to reload. Am I just doing it wrong? I have the best MacBook Pro you can get. Shouldn't we be able to have reloads be practically per keystroke? I tried https://github.com/gaearon/react-hot-boilerplate and this not near instantaneous experience.

Not complaining, just wondering if this is what I should expect and what I can do to help make it faster.

Francois

**Comment by francoislaberge** [comment]
This gif shows it takes 2s + to reload from hitting save to change appearing. Notice when the blue dot disapears and the s appears on the right

![reload-speed](https://cloud.githubusercontent.com/assets/1845/22039190/504175bc-dccc-11e6-97c8-4c8e26c98476.gif)

**Comment by juice49** [comment]
I'm a new Webpack user, but I've been playing around with HMR and code splitting to try and figure everything out. One suggestion I saw on an another issue is to change your [devtool](https://webpack.js.org/configuration/devtool/#devtool) to `inline-eval-cheap-source-map`.

It might be a placebo, but my React app seems to hot reload a little faster now. It's definitely snappier than in your example, and I'm using a 12" MacBook.

**Comment by calesce** [comment]
There hasn't yet been any significant perf-related work on React Hot Loader to my knowledge, so I'm sure there are optimizations we can make.

Also, keep in mind that HMR is not just React Hot Loader, there's also the Webpack process itself, WebpackDevServer (or webpack-dev-middleware), and potentially other loaders such as Babel or TypeScript.

You might have better luck with Webpack 2.2, since `react-hot-boilerplate` is still using Webpack 1.14.

**Comment by BirdLeeSCUT** [comment]
This is mostly the cost of compiler side( xx-loader), not the React Hot Loader.
When I use webpack 2.2 + typescript (at-loader) + react, the compiling time can reducer to less then 700 ms, but the web page can update just in an instant after recompilation.
![image](https://cloud.githubusercontent.com/assets/10753131/22796731/7db14b68-ef36-11e6-9985-6ac149823161.png)

**Comment by neoziro** [comment]
HMR is mostly done by Webpack, when Webpack notifies a new update, React Hot Loader handles it  almost instantly.
