### ISSUE TITLE
[3.0] Ability to display errors in console instead of redbox

### ISSUE THREAD

**Issue by icek** [gaearon/react-hot-loader#462]
Errors displayed in Redbox are useless for me especially when it comes to line numbers.

When sourcemaps are used, Chrome console can show exact error location (eg: `SomeComponent.js:12:13`) and you can jump directly into that file and chrome will highlight line causing error. Redbox on the other hand show line number in a bundled file (eg: `bundle.js:33052:13`) if you are patient you can search for this line...

Example of how useless it is:
![screen shot 2017-01-19 at 03 15 52](https://cloud.githubusercontent.com/assets/150243/22091172/d3b58292-ddf5-11e6-951a-10bcfcc1d4b8.png)

I digged a little and found that there is a property `errorReporter` on `AppContainer` so I tried to implement custom component for redirecting errors back to console, but I don't know how to make it work. Here is my initial approach:

``` jsx
import React from "react";

export default class NormalConsoleErrorInsteadOfRedbox extends React.Component {
    componentDidMount() {
        console.error(this.props.error);
    }

    componentDidUpdate () {
        console.error(this.props.error);
    }

    render() {
        return null; // <div/>
    }
}
```

used like this:
``` jsx
ReactDOM.render(
    <AppContainer errorReporter="NormalConsoleErrorInsteadOfRedbox">
        <Root/>
    </AppContainer>,
    rootEl
);
```

and now I get:
```
Warning: Unknown prop `error` on <NormalConsoleErrorInsteadOfRedbox> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in NormalConsoleErrorInsteadOfRedbox (created by AppContainer)
    in AppContainer
```

React 15.4.2, react-hot-loader 3.0.0-beta.6

**Comment by icek** [comment]
Nevermind, here is quick workaround:

```js
delete AppContainer.prototype.unstable_handleError;

React.render(
```

and same error in console:

![screen shot 2017-01-19 at 03 37 36](https://cloud.githubusercontent.com/assets/150243/22091735/b75dc5ac-ddf8-11e6-869d-0ede0bc83479.png)

**Comment by jtomaszewski** [comment]
Same here. Thanks for the workaround @icek , it works for me for now.

**Comment by calesce** [comment]
I'm thinking we can add an `<AppContainer>` without a `unstable_handleError` method. Until we either get better (or faster) source maps as well as better error boundaries in React, the Redbox is far from perfect.

**Comment by AlexKvazos** [comment]
Can't we make it so that Redbox doesn't stop the error from logging into the console with proper sourcemaps?

**Comment by wkwiatek** [comment]
I updated PR #494 so that the default behaviour will be `console.error`. 

However, if you like `RedBox` for some reason there will be a possibility to add custom error catcher (documented in [docs/TipsAndTricks.md](https://github.com/gaearon/react-hot-loader/blob/1ac0f5faeec7a4064ebc2f1d91468753a620fd48/docs/TipsAndTricks.md)). 

There's still an issue opened for tracking errors #164, so I believe we can continue thinking about better approach. Nice solution would be to have 'redbox' only on a component that fails, and it can be achieved on `react-proxy` level.

Would that work for most of you guys?

**Comment by vincent-ly** [comment]
@icek Thanks for the quick fix!

**Comment by jeswin** [comment]
@icek The workaround saved my day. The red box is a poor developer experience compared to full call stack information in the console.

**Comment by twig-openlearning** [comment]
Workaround saved my sanity. I don't know why we're forced to use something like RedBox that provides little benefit.

**Comment by adamchenwei** [comment]
Sound stupid.... but restart the webpack build help the react somehow start throwing the correct error.
