### ISSUE TITLE
3.0.0-beta.6 this is undefined for async arrow function class property

### ISSUE THREAD

**Issue by cl1ck** [gaearon/react-hot-loader#463]
### Description

Using 3.0.0.-beta.6 `this`  is undefined for an async arrow function class property.
Without the `react-hot-loader/babel` plugin they are transpiled correctly.

### Expected behavior

The async arrow function should be autobound.

### Actual behavior

`this` is undefined.

### Environment

React Hot Loader version: 3.0.0-beta.6
Node: 6.4.0
npm: 3.10.3
babel: 6.21.0

### Reproducible Demo

[minimal repro](https://github.com/cl1ck/react-hot-loader-async-class-property-error)
`npm run fail` transpiles index.js with the react-hotloader/babel plugin and `npm run success` without.

**Comment by calesce** [comment]
Thanks, since this looks like the same issue as #391 so I'm going to close this as a duplicate.
