### ISSUE TITLE
Cannot read property 'listeners' of null

### ISSUE THREAD

**Issue by iDuuck** [gaearon/react-hot-loader#466]
### Description

I just updated to RHL 3.0 and I am experiencing the same error for different ones (sounds awkward, but have a look yourself:

And this one is the current behaviour, when the app is "wrapped" by the `AppContainer` and react-hot-loader

### Expected behavior

![screen shot 2017-01-24 at 3 41 18 pm](https://cloud.githubusercontent.com/assets/325241/22251592/a7a9a0ac-e24b-11e6-9da3-1c89507db79c.png)

### Actual behavior

![screen shot 2017-01-24 at 3 41 32 pm](https://cloud.githubusercontent.com/assets/325241/22251607/bae1a4ee-e24b-11e6-9968-143f35f32410.png)

### Environment

React Hot Loader version: `next`

Run these commands in the project folder and fill in their results:

1. `node -v`: v6.3.1
2. `npm -v`: 3.10.3
3. `yarn -v`: 0.16.1

Then, specify:

1. Operating system: macOS 10.21.1
2. Browser and version: Chrome 55

### Reproducible Demo

I am working on a private project and really don't have the time to reproduce in an external project. If you want to help, I can provide the source code.

**Comment by iDuuck** [comment]
A quick heads up. I just stumbled (out of curiousity) over this error: #462 and if I am adding the `delete` command everything is working again. But there must be an fix for this without this line, shouldn't it?

**Comment by calesce** [comment]
Yeah this is the same issue as #462. Going to close this issue so we can focus on the discussion in there.

**Comment by adamchenwei** [comment]
Sound stupid.... but restart the webpack build help the react somehow start throwing the correct error.
