### ISSUE TITLE
Distribution version (npm@next) has been built in development mode

### ISSUE THREAD

**Issue by bebraw** [gaearon/react-hot-loader#471]
### Description

Distribution version (npm@next) has been built in development mode meaning it contains development specific `console.log`s you may want to eliminate from a production build.

### Expected behavior

It should use the production version instead. The source is there, but the distribution version eliminates that.

### Actual behavior

If you build an application against react-hot-loader@next, it will contain unnecessary debug prints in the source.

### Environment

React Hot Loader version: 3.0.0-beta.6

Run these commands in the project folder and fill in their results:

1. `node -v`: v6.9.1
2. `npm -v`: 4.0.5

Then, specify:

1. Operating system: macOS 10.12.3
2. Browser and version: Chrome 56.0.2924.76

### Reproducible Demo

1. `mkdir demo`
2. `cd demo`
3. `npm init -y`
4. `npm i react-hot-loader@next -D`
5. `vim node_modules/react-hot-loader/lib/index.js`
6. Note how the distribution version contains only development specific code. The built version is missing the branches needed for optimization when bundling.

**Comment by calesce** [comment]
#429 fixes this, but `beta.7` hasn't been published.

**Comment by bebraw** [comment]
Cool. 👍 

Any ETA on a new beta?

**Comment by calesce** [comment]
I want to get #464 merged first, but no time right now to do a thorough review.
