### ISSUE TITLE
HMR with react-hot-loader doesn't hot update for react functional components

### ISSUE THREAD

**Issue by fijiwebdesign** [gaearon/react-hot-loader#476]
### Description

I'm using the react-hot-boilerplate
https://github.com/gaearon/react-hot-boilerplate

Changed the App.js to
```
export default () => (
  <div>
    <h1>Hello world!</h1>
  </div>
)
```
see: https://github.com/fijiwebdesign/react-hot-boilerplate/commit/03867453cde11596ed0c998701b2b8db98f58d58

I then change some code to trigger HMR

### Expected behavior
The App.js should HMR as it does with an ES6 class component.

### Actual behavior

The following warning is in the console
> [HMR] The following modules couldn't be hot updated: (Full reload needed)
> This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.

### Environment

React Hot Loader version: **1.3.1**

Run these commands in the project folder and fill in their results:

1. `node -v`: **v5.5.0**

2. `npm -v`: **3.3.12**

Then, specify:

1. Operating system: **Max OSX Yosemite 10.10.5**
2. Browser and version: **Chrome 55.0.2883.95 (64-bit)**

### Reproducible Demo

Please take the time to create a new project that reproduces the issue.

`git clone https://github.com/gaearon/react-hot-boilerplate`

`npm install`

modify App.js to: 

```
import React, { Component } from 'react';

export default () => (
  <div>
    <h1>Hello world!</h1>
  </div>
)
```

`npm start`

Or clone this repo: 

`git clone git@github.com:fijiwebdesign/react-hot-boilerplate.git && cd react-hot-boilerplate`

`git checkout hmr-bug-react-functional-component`

`npm install && npm start`

**Comment by nikolaipaul** [comment]
stateless components do not work with react-hot-loader 1.3.1

Try the newer version 3. It's still beta though.

**Comment by fijiwebdesign** [comment]
Note: I had to add this before rendering the component for stateless components to always reload with HMR. 

> if (module.hot) {
>   module.hot.accept()
> }

**Comment by earnubs** [comment]
If you also need to update state this gist might be helpful https://gist.github.com/earnubs/c566cf6e3d85e5655907a876379c0d84

**Comment by calesce** [comment]
RHL 1.x doesn't support functional components, which is partly why we are working on RHL 3. You can also not use React Hot Loader if you app is primarily stateless functional components and the state lives in something like Redux; just using Webpack Hot Module Replacement would be suitable.
