### ISSUE TITLE
newer AppContainer implementation breaks hot loader

### ISSUE THREAD

**Issue by akhayoon** [gaearon/react-hot-loader#477]
I am using 

webpack": "^1.13.2"
"webpack-dev-server": "^1.15.0"
"react-hot-loader": "^3.0.0-beta.6"

My problem is that the new implementation of `<AppContainer>` without the `props` and `component` props breaks the hot-loader

**This Does Not Work**
```
const rootEl = document.getElementById('root');
const render = Component =>
  ReactDOM.render(
    <AppContainer>
      <Component store={store} />
    </AppContainer>,
    rootEl
  );

render(Root);
if (module.hot)
{
    module.hot.accept('./Root', () => render(Root));
}
```

**This Works with AppContainer deprecation warnings**
```
ReactDOM.render(
 	<AppContainer
		component={Root}
		props={{ store }}
	/>,
	document.getElementById('root')
);

if (module.hot) 
{
	module.hot.accept('./Root', () => 
	{
		console.log('here')
		ReactDOM.render(
 			<AppContainer
				component={require('./Root').default}
				props={{ store }}
			/>,
			document.getElementById('root')
		);
	});
}
```

I am I doing something wrong with the new way of using `<AppContainer>`? 
The code does not seem to enter `module.hot` when editing.

**Comment by calesce** [comment]
Hi, the `component` and `props` props were deprecated as of `beta.0`, see AppContainer usage [in the `next` branch](https://github.com/gaearon/react-hot-loader/tree/51dae3f4c86f21c143db838ff5d880433e4bc739/docs).

**Comment by akhayoon** [comment]
sorry I think you misunderstood. I'm saying the newer implementation of AppContainer is breaking the hot loader for me, but the deprecated way of using it works perfectly.

**Comment by calesce** [comment]
In your first example you don't re-'require' Root

**Comment by akhayoon** [comment]
that was it, thank you.
