### ISSUE TITLE
PhantomJS blows up when using react-hot-loader/patch

### ISSUE THREAD

**Issue by sontek** [gaearon/react-hot-loader#481]
### Description

I use Selenium + PhantomJS for testing my react application.  We've recently wanted our developers to run the selenium tests locally but the tests always fail.  I've tracked it down to the inclusion of `react-hot-loader/patch` but we aren't sure why.  There are no JS errors that we see.

### Expected behavior

I assume the issue is that react-hot-loader is using some feature than PhantomJS doesn't support.  Is there a way to make this safer?  Or a good way to debug/track this down?

### Environment

React Hot Loader version:

next

Run these commands in the project folder and fill in their results:

1. `node -v`:
v7.4.0

2. `npm -v`:
4.0.5

Then, specify:

1. Operating system:
OSX

2. Browser and version:
PhantomJS

**Comment by sontek** [comment]
I figured this out.  You need to include the polyfills *BEFORE* patch.  I was following the docs that it should be the first thing in the entry but it should be the first thing *AFTER* babel-polyfill

**Comment by arjun810** [comment]
Had the same issue, but moving it after babel-polyfill makes phantomjs die for me now.

**Comment by wkwiatek** [comment]
@arjun810 are you able to provide some min repro scenario?

**Comment by peter-mouland** [comment]
I would suggest to only use react-hot-loader in dev. and ensure that your test environment doesn't load/use the react-hot-loader code.  This would also have the benefit of making the tests run on a more prod-like setup.

sorry for not _truely_ answering the question being asked, but i think altering the approach to how the tests are run is probably worth while.

**Comment by sontek** [comment]
@peter-mouland Yeah, thats actually what we've been doing.  We are trying to stop doing that. The reason is because we want to have our developers run the selenium tests on their codebase before sending the code up for review.  Currently they just push up and let the CI server run it because they can't run it against their dev instance.

They can't just do `yarn run selenium` because then it has to spin up a whole new instance of the apps and run webpack and all that which takes forever.  We want them to be able to target their already running and already compiled site.

**Comment by peter-mouland** [comment]
I think running at least a subset of e2e tests, in a single browser, on the dev machine using the prod build (or prod-like using fixtures) is a small ask.  Even if the build takes a minute to complete, having e2e tests on a pre-push is very much worth it and something we, as dev's, should get use to i.e. take responsibility for testing our own code.

Are you able to set the apps up so that each app can be started with fixtures rather having a hard dependency on another, separate, app? If the apps are are started in isolation (i.e. using fixtures), do they still take a long time to start?

**Comment by neoziro** [comment]
Documented.
