### ISSUE TITLE
Reload plays all updates one by one

### ISSUE THREAD

**Issue by msathis** [gaearon/react-hot-loader#482]
### Description

I'm using webpack 2.2 with webpack-dev-middleware, webpack-hot-middleware and react-hot-loader v3. Hot reloading works fine normally when i make a change in editor. But when i do browser reload (refresh), all changes since the server started, getting applied one by one. 

### Environment

React Hot Loader version: 3

1. `node -v`: 7.3.0
2. yarn 0.20.0

**Comment by calesce** [comment]
Can you please share an example project demonstrating the issue? We put that section in the issue template so it'll be easier for maintainers to reproduce and triage your problem.

**Comment by msathis** [comment]
Sure. Will create a minimal reproducible repo.

**Comment by msathis** [comment]
This was an issue with webpack-hot-middleware. After removing it, this issue isnt occurring any more.
