### ISSUE TITLE
Code doesn't get updated although console says otherways

### ISSUE THREAD

**Issue by dKab** [gaearon/react-hot-loader#484]
### Description
I'm having issue with setting up react-hot-loader:

When I open the page I see in console:
[HMR] connected
Then I update my component and I have no errors in console and I see following log (which is seemingly indicate that hot-loader works or at least doing  something):

client.js?3ac5:199 [HMR] bundle rebuilding
client.js?3ac5:207 [HMR] bundle rebuilt in 1642ms
process-update.js?e13e:27 [HMR] Checking for updates on the server...
process-update.js?e13e:100 [HMR] Updated modules:
process-update.js?e13e:102 [HMR]  - ./src/components/App.jsx
process-update.js?e13e:107 [HMR] App is up to date.

### Expected behavior
I expect the page to be updated with my changes
### Actual behavior
Page stays the same although some logs are spitted in console (see above)

### Environment

React Hot Loader version: 3.0.0-beta.6

Run these commands in the project folder and fill in their results:

1. `node -v`: v7.4.0
2. `npm -v`: 4.0.5
Then, specify:

1. Operating system: 16.04.1 LTS
2. Browser and version: Chromium 52.0.2743.116 Built on Ubuntu 

### Reproducible Demo
https://github.com/dKab/recipy-book/tree/hot-reload
npm run dev

**Comment by dKab** [comment]
http://giphy.com/gifs/26xBBgDwvWc4wjzeE here's animation of described behavior

**Comment by dKab** [comment]
Ok, so apparently something was wrong with my server setup because when a I tweaked a few things it  finally worked. Thanks!

**Comment by jainprash** [comment]
@dKab - Can you let us know, what did you tweak to fix it. I am facing the same issue, with exact same setup as you had ( webpack-middleware integrated with node) . The console log is correclty reflected, but browser does not refresh automatically.
