### ISSUE TITLE
What is the difference using webpack-hot-middleware and using this react-hot-loader

### ISSUE THREAD

**Issue by okaprinarjaya** [gaearon/react-hot-loader#489]
Hi,

I very curious, What is the difference using webpack-hot-middleware and using this react-hot-loader. Whether react-hot-loader can be combined with express ? 

Thank You :)

**Comment by calesce** [comment]
Hi, React Hot Loader can be used alongside `webpack-hot-middleware` and Express. You'll also need to include [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware). I actually have an example using both together [here](https://github.com/calesce/react-hot-loader-examples).

**Comment by lsdriscoll** [comment]
@calesce that's not a difference :)

**Comment by abzfarah** [comment]
+1 
confused as well

**Comment by AntonioRedondo** [comment]
I understand that `react-hot-loader` makes a per-component hot reload rather than a full-page refresh and that it pairs nicely with `webpack-dev-server`. But if you're using `webpack-hot-middleware` with some Express server and without `webpack-dev-server`, why would you like to use `reload-hot-loader` together with `webpack-hot-middleware` if this last already implements per-component hot reload?

**Comment by eugeniaguerrero** [comment]
+1
I'd love to understand why, like @AntonioRedondo mentioned, you'd also use `react-hot-loader` if `webpack-hot-middleware` already implements per-component hot reloads?

**Comment by jordilondoner** [comment]
@AntonioRedondo after researching a bit on the matter, it looks to me that `react-hot-loader` adds some extra features on the mix if you are using `React` and or `Redux` [such as keep the component state upon hot reloading](http://gaearon.github.io/react-hot-loader/getstarted/#step-3-of-3-adding-react-hot-loader-to-preserve-component-state) and it also facilitates the use of some other specific [Redux dev tools] (https://github.com/gaearon/redux-devtools) whereas [`webpack-hot-middleware`](https://github.com/glenjamin/webpack-hot-middleware) takes care only of hot reloading a module.

**Comment by always-sunny** [comment]
So you don't need to use webpack-hot-middleware to use react-hot-loader? 

If I were to use just react-hot-loader, what would the setup be like? Do I need to use the HMR plugin still?

**Comment by dpoint01** [comment]
+1 to @Always-Sunny's question. Should we be using  react-hot-loader in combination with webpack-hot-middleware or instead of?

**Comment by ajGingrich** [comment]
@dpoint01 I believe it is in combination but I currently working on setting something up myself. 

>This module is only concerned with the mechanisms to connect a browser client to a webpack server & receive updates. It will subscribe to changes from the server and execute those changes using webpack's HMR API. Actually making your application capable of using hot reloading to make seamless changes is out of scope, and usually handled by another library.

> If you're using React then some common options are react-transform-hmr and react-hot-loader.

from [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware) readme

**Comment by chshouyu** [comment]
In my project, I use webpack-hot-middleware with react-hot-loader on my own express server, when I totally remove react-hot-loader, I found it actually behave the same result.

**Comment by theKashey** [comment]
Webpack-hot-middleware stands for Server-Side. It detects changes and informs client side about it. 
It is actually is the Hot Module Replacement. 

In the same time react-hot-loader... do nothing. It’s goal is to stop and prevent updates. It’s purely front end and starts working after webpack did its job. 

So, correct answer is simple - this is 2 different things, but they supposed to work together.

**Comment by chenfanggm** [comment]
I can't get react-hot-loader work together with webpack-hot-middleware.
Anyone has successful example to share?

**Comment by kvn1351** [comment]
Why does this have to be so damn complicated? And why isn't this written on one and the same doc page?

**Comment by DominicTobias** [comment]
Sooo, any examples?

**Comment by fatfatson** [comment]
@jordilondoner could you give some example for what could not be done when only use webpack-hot-middleware? I found it nearly does all the things of hot update I want, I don't know whether I need still put react-hot-loader to my config.

**Comment by AndrejGajdos** [comment]
I would also like to know if `react-hot-loader` makes sense alongside `webpack-hot-middleware`.

**Comment by theKashey** [comment]
@AndrejGajdos  - react-hot-loader is Cliffside react-specific library, while webpack-hot-middleware is library-agnostic mostly backend solution.
React-Hot-Loader would not work without webpack hot module replacement(no mater how you call it or activate it), while HMR would work without RHL.

RHL is just keeping React Components state while they being updated.

**Comment by AndrejGajdos** [comment]
@theKashey thanks

**Comment by Umbrellagun** [comment]
Agreed that this is all not as clear as it should be. There's still a mountain of dependencies to install (used to be larger) and the configuration for any direction you went was (is still) heavy. A notably unclear/confusing part of this is how react-hot-loader and webpack-hot-middleware interact with each other when it comes to the script that should run. For react-hot-loader the docs say you should use "webpack-dev-server --hot", but my understanding is that if you use webpack-hot-middleware, you are no longer using webpack-dev-server. But there are no comments that I found about this.

**Comment by Umbrellagun** [comment]
It seems like react-hot-loader forces you to use webpack-dev-server. But my understanding is that one of the reasons you might use webpack-hot-middleware is to specifically not use webpack-dev-server so you can instead use your own server file instead of running two servers. Am I off base?
