### ISSUE TITLE
Not work with typescipt please help

### ISSUE THREAD

**Issue by und3fined** [gaearon/react-hot-loader#493]
### Description

I've converted your code to run features HMR, but not work.
I get full browser logs.

Screen 1
![IMG1](https://github.com/und3fined/react-hot-ts/blob/master/assets/Screen%20Shot%202017-02-28%20at%2015.52.54.png?raw=true)

Screen 2
![IMG2](https://github.com/und3fined/react-hot-ts/blob/master/assets/Screen%20Shot%202017-02-28%20at%2015.53.20.png?raw=true)

Screen 3
![IMG3](https://github.com/und3fined/react-hot-ts/blob/master/assets/Screen%20Shot%202017-02-28%20at%2015.53.40.png)

### Environment

React Hot Loader version: "react-hot-loader": "next",

Run these commands in the project folder and fill in their results:

1. `node -v`: v6.10.0
2. `npm -v`: v3.10.10
3. `yarn --version`: v0.21.3

Then, specify:

1. Operating system: mac OS 10.12.3
2. Browser and version: Version 55.0.2883.95 (64-bit)

### Reproducible Demo
My repo: https://github.com/und3fined/react-hot-ts

**Comment by und3fined** [comment]
Now it work. 
I change
```
import App from './App';

const rootEl = document.getElementById('root');
const render = (Component: any) => {
    ReactDOM.render(<AppContainer><Component /></AppContainer>, rootEl)
};

render(App);

if (module.hot) {
    module.hot.accept('./App', () => render(App))
}
```
to

```
import App from './App';

const rootEl = document.getElementById('root');
const render = (Component: any) => {
    ReactDOM.render(<AppContainer><Component /></AppContainer>, rootEl)
};

render(App);

if (module.hot) {
    module.hot.accept('./App', () => {

        // I do not know why!
        // if without this line, the hot reload not work!!!
        // no document for this issue.
        const NextApp = require("./App").default; 

        // You can use 'App' or 'NextApp'
        render(NextApp);
    });
}

**Comment by izhaknys** [comment]
This is odd!

This actually goes against the [docs](https://github.com/gaearon/react-hot-loader/tree/master/docs#webpack-2).

So I wonder if the docs are wrong?

**Comment by izhaknys** [comment]
Could be related to https://github.com/gaearon/react-hot-loader/issues/514#issuecomment-288482049
