### ISSUE TITLE
Consolidate packages

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#496]
I suggest moving code from `react-proxy` and `react-deep-force-update` into this repo.
It doesn’t make sense to keep them apart.

The packages would still be separate, but live in one repository.
This is easy to do with [`lerna import`](https://github.com/lerna/lerna#import).

**Comment by neoziro** [comment]
@gaearon I think it is a good idea, I can do it.

**Comment by neoziro** [comment]
[React Hot Loader v4](https://github.com/gaearon/react-hot-loader/tree/next) is coming as a Lerna project 🐉.
