### ISSUE TITLE
react-hot-loader results hard reloading instead of HMR

### ISSUE THREAD

**Issue by jeud** [gaearon/react-hot-loader#503]
I'm executing the webpack-dev-server using `webpack-dev-server` (no arguments) with the configuration file as shown below

*webpack.config.js*

```js
const path = require('path')
const webpack = require('webpack')

module.exports = {
    entry: [
        'webpack-dev-server/client?http://0.0.0.0:8080',
        'webpack/hot/only-dev-server',
        path.resolve(__dirname, 'src', 'entry.js')
    ],
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.js'
    },
    devServer: {
        contentBase: './dist',
        hot: true,
    },
    module: {
        loaders: [
            {
                test: /\.js?$/,
                loader: 'babel-loader?cacheDirectory',
                exclude: /(node_modules)/
            }
        ]
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),

        new webpack.NamedModulesPlugin(),
    ]
}
```

*.babelrc*

```
{
    presets: ['stage-0', 'es2015', 'react'],
    plugins: ['react-hot-loader/babel']
}
```

![](https://i.stack.imgur.com/8Dp8S.png)

### Expected behavior

I expected HMR without hard refreshing the page

### Actual behavior

It results in hard reloading instead of HMR

### Environment

1. `node -v`: 7.7.1
2. `npm -v`: 4.3.0
3. Operating system: Windows 10
4. Browser and version: Chrome 56.0.2924.87
5. React Hot Loader version: 3.0.0-beta.6

**Comment by wkwiatek** [comment]
We need more info. How you're adding `AppContainer`?

**Comment by jeud** [comment]
Finally I have fixed it, thanks

**Comment by ambethia** [comment]
> Finally I have fixed it, thanks

Can you let the rest of us know how you fixed it? Thanks!

**Comment by jeud** [comment]
@ambethia, this configuration is working for me

*Terminal*

    npm install react-hot-loader@next

*webpack.config.js*

```js
const path = require('path')
const webpack = require('webpack')

module.exports = {
    entry: './entry.js',
    devServer: {
        inline: true
        hot: true,
    },
    module: {
        loaders: [
            {
                test: /\.js?$/,
                loader: 'babel-loader?cacheDirectory',
                exclude: /(node_modules)/
            }
        ]
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
    ]
}
```

*entry.js*

    ...
    if (module.hot) {
        module.hot.accept()
    }

*.babelrc*

```
{
    presets: ['stage-0', 'es2015', 'react'],
    plugins: ['react-hot-loader/babel']
}
```

**Comment by ambethia** [comment]
@jeud Thanks, which version of webpack are you running?

**Comment by jeud** [comment]
@ambethia i'm using webpack 2.x but I still prefer to setup the `loader` using webpack 1.x syntax style

**Comment by MmtBkn** [comment]
I was just setting up new project. I had same problem and accept() solved it. 

It also works without ["env" , {modules : false}], is it safe?
