### ISSUE TITLE
Do not work width babel-plugin-transform-es2015-modules-commonjs

### ISSUE THREAD

**Issue by xianshannan** [gaearon/react-hot-loader#505]
When using `babel-plugin-transform-es2015-modules-commonjs` in projects, react-hot-loader 3 did not work!

I clone the project below,and add `babel-plugin-transform-es2015-modules-commonjs`,react-hot-loader 3  did not work too.
[https://github.com/gaearon/react-hot-boilerplate/tree/next](https://github.com/gaearon/react-hot-boilerplate/tree/next)
.babelrc
```
{
  "presets": [
    ["es2015", {"modules": false}],
    "stage-2",
    "react"
  ],
  "plugins": [
    "transform-es2015-modules-commonjs",
    "react-hot-loader/babel",
  ]
}
```

**Comment by wkwiatek** [comment]
You have two plugins that will not play together. You should either decide if you want to go with `["es2015", {"modules": false}]` or `"transform-es2015-modules-commonjs"`. `modules: false` says to disable `transform-es2015-modules-commonjs`. 

Depending on the version you're using you can either use (for `"transform-es2015-modules-commonjs"`): 
```jsx
module.hot.accept('./containers/App', () => {
    const NextApp = require('./containers/App').default; // <--- this line is required for babel modules
    ReactDOM.render(
      <AppContainer>
        <NextApp/>
      </AppContainer>,
      document.getElementById('root')
    );
  });
```
or for webpack es2015 modules (`modules: false`):
```jsx
module.hot.accept('./containers/App', () => {
    ReactDOM.render(
      <AppContainer>
        <App/>
      </AppContainer>,
      document.getElementById('root')
    );
  });
```
