### ISSUE TITLE
Difference between module.hot.accept("./Comp") and module.hot.accept("./Comp.jsx")

### ISSUE THREAD

**Issue by JasonKid** [gaearon/react-hot-loader#510]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description
`module.hot.accept("./Comp")` works fine while `module.hot.accept("./Comp.jsx")` doesn't work without any error;

What you are reporting:
Doubt
### Expected behavior

What you think should happen:

### Actual behavior

What actually happens:
hot-update.js transferred but not rerender

### Environment

React Hot Loader version:
v3.0 beta.6
Run these commands in the project folder and fill in their results:

1. `node -v`:v6.9.1
2. `npm -v`:3.10.8

Then, specify:

1. Operating system:
2. Browser and version:

### Reproducible Demo

Please take the time to create a new project that reproduces the issue.

You can copy your project that experiences the problem and start removing things until you’re left with the minimal reproducible demo. This helps contributors, and you might get to the root of your problem during that process.

Push to GitHub and paste the link here.

**Comment by neoziro** [comment]
This is a Webpack issue, `module.hot.accept` is relative to Webpack, not React Hot Loader. You should try to ask Webpack team if your problem is not solved.
