### ISSUE TITLE
[3.0.0-beta.6]react-dnd hot loader Bug

### ISSUE THREAD

**Issue by linsmalldragon** [gaearon/react-hot-loader#513]
version:react-dnd:
 "react-dnd": "^2.2.4",
 "react-dnd-html5-backend": "^2.2.4",
    "react-hot-loader": "^3.0.0-beta.6"

When i add react-dnd into https://github.com/gaearon/react-hot-boilerplate/tree/next project.
It will reload whole page. But if I delete   DragDropContext(HTML5Backend) in the last .It will work.
Here is my code which modify Counter:

```


import React, { Component } from 'react';
import {compose} from 'redux';
import {connect} from 'react-redux'
import {DragDropContext} from 'react-dnd';
import HTML5Backend from 'react-dnd-html5-backend';

class Counter extends Component {
  constructor(props) {
    super(props);
    this.state = { counter: 0 };
  }

  componentDidMount() {
    this.interval = setInterval(this.tick.bind(this), 1000);
  }


  componentWillUnmount() {
    clearInterval(this.interval);
  }

    tick() {
        this.setState({ counter: this.state.counter + 1 });
    }
  render() {
    return <h2>test:{this.state.counter}</h2>;
  }
}

Counter.propTypes = {
}


function mapStateToProps(state, ownProps) {
    return {

    }
}

export default compose(
    DragDropContext(HTML5Backend),
    connect(mapStateToProps, {})
)(Counter);

```

**Comment by linsmalldragon** [comment]
my redux version:
"react-dom": "^15.4.2",
"react": "^15.4.2",
"redux": "^3.6.0"
"react-redux": "^5.0.1"
"webpack": "^2.2.0", 
 "webpack-dev-server": "^2.2.0"

**Comment by neoziro** [comment]
It is a known issue, please refer to https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#react-hot-loader-this-component-is-not-accepted-by-hot-loader
