### ISSUE TITLE
Cannot get V3.0-beta6 working with typescript project

### ISSUE THREAD

**Issue by Derek-X-Wang** [gaearon/react-hot-loader#514]
### Description

I'm using this [boilerplate](https://github.com/wkwiatek/react-hot-loader-minimal-boilerplate). It works great. However, it doesn't work in typescript. In browser's console, it show:
![screen shot 2017-03-10 at 3 07 25 pm](https://cloud.githubusercontent.com/assets/6364170/23816762/604896c0-05a3-11e7-96cc-394557958c12.png)

But, the modified content is not updated unless I manually refresh the page.

### Expected behavior

Automatic updates on modified content.

### Actual behavior

The content isn't updated unless you do it manually.

### Environment

React Hot Loader version: 3.0.0-beta.6

Run these commands in the project folder and fill in their results:

1. `node -v`: v7.3.0
2. `npm -v`: 3.10.10

Then, specify:

1. Operating system: MacOS Sierra version 10.12.3
2. Browser and version: Chrome Version 56.0.2924.87 (64-bit)

### Reproducible Demo

[demo](https://github.com/Derek-X-Wang/react-ts-hot-loader-minimal-boilerplate)

```
npm i
npm run dev
```

**Comment by izhaknys** [comment]
I'm having the same issue, albeit using a different config than yours.

For all the debugging I've done, it seems that `awesome-typescript-loader` might have something to do with it.

When comparing the updates (the added sources on the source tab in chrome) between `babel-loader` and `awesome-typescript-loader` (that uses babel), they are similar with one exception.

This is `babel-loader`:

```
var _temp = function () {
  if (typeof __REACT_HOT_LOADER__ === 'undefined') {
    return;
  }

  __REACT_HOT_LOADER__.register(Root, 'Root', '/Users/roey/Development/react-hot-loader-minimal-boilerplate/src/containers/Root.tsx');

  __REACT_HOT_LOADER__.register(_default, 'default', '/Users/roey/Development/react-hot-loader-minimal-boilerplate/src/containers/Root.tsx');
}();
```

And this is `awesome-typescript-loader`:

```
var _temp = function () {
  if (typeof __REACT_HOT_LOADER__ === 'undefined') {
    return;
  }

  __REACT_HOT_LOADER__.register(Root, "Root", "/Users/roey/Development/react-hot-loader-minimal-boilerplate/src/containers/Root.tsx");
}();
```

So as you can see, the latter is missing the 'default' export, which could be the source of the problem.

**Comment by izhaknys** [comment]
I managed to get it to work by setting `useTranspileModule` to true in the `awesome-typescript-loader`

**Comment by Derek-X-Wang** [comment]
@izhaknys 
Thanks a lot for the tips.

But I still cannot get it work. 

My current tsconfig.json is

```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "target": "es5",
    "jsx": "react"
  },
  "awesomeTypescriptLoaderOptions": {
    "useTranspileModule": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

Making "jsx": "preserve" will cause the loader unable to parse react component.

error:
<img width="512" alt="screen shot 2017-03-23 at 3 49 40 am" src="https://cloud.githubusercontent.com/assets/6364170/24244383/d216afe4-0f7b-11e7-9800-ccb3050bc5b7.png">


However, with "jsx": "react", react-hot-loader still doesn't work.

Reproducible Demo

[demo](https://github.com/Derek-X-Wang/react-ts-hot-loader-minimal-boilerplate)

Also, I had tried ts-loader. Its will cause an automatic page refresh which is strange.

**Comment by izhaknys** [comment]
Forgot to mention (`tsconfig.json`):

        "module": "none",

As for `jsx` - that error makes sense since if it is not `tsc` that transpiles them, what will? In my setup I'm using `babel`.

**Comment by izhaknys** [comment]
Here's the setup that works for me:

I've actually branched from your https://github.com/Derek-X-Wang/react-ts-hot-loader-minimal-boilerplate

`tsconfig.json`:

```json
{
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": false,
        "noImplicitAny": true,
        "isolatedModules": true,
        "module": "none",
        "target": "es6",
        "jsx": "preserve",
        "moduleResolution": "node"
    },
    "exclude": [
        "node_modules"
    ]
}
```

`server.js`:

```javascript
var path = require('path');
var webpack = require('webpack');
var express = require('express');
var config = require('./webpack.config');

var app = express();
var compiler = webpack(config);

app.use(require('webpack-dev-middleware')(compiler, {
  publicPath: config.output.publicPath
}));

app.use(require('webpack-hot-middleware')(compiler));

app.get('*', function(req, res) {
  res.sendFile(path.join(__dirname, 'index.html'));
});

app.listen(3000, function(err) {
  if (err) {
    return console.error(err);
  }

  console.log('Listening at http://localhost:3000/');
});
```

`webpack.config.js`:

```javascript
const webpack = require('webpack')
const path = require('path')

module.exports = {
  devtool: 'source-map',

  entry: {
    'app': [
      'babel-polyfill',
      'react-hot-loader/patch',
      'webpack-hot-middleware/client',
      './src/index'
    ]
  },

  resolve: {
        extensions: [ '.ts', '.tsx', '.js', '.jsx' ]
  },

  output: {
    path: path.resolve(__dirname, './dist'),
    publicPath: '/',
    filename: '[name].js'
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin()
  ],
  module: {
    rules: [
      {
        test: /\.tsx$/,
        exclude: /node_modules/,

        loader: 'awesome-typescript-loader',
        query: {
            useTranspileModule: true,
            useBabel: true,
            useCache: true,
        }
      }
    ]
  }
}
```

`.babelrc`:

```json
{
  "presets": [
      ["es2015", {"modules": false}],
      "react"
  ],
  "plugins": [
    "react-hot-loader/babel"
  ]
}
```

**Comment by Derek-X-Wang** [comment]
Thanks a lot for your patient answer!

It may be a good idea to open an issue at [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader).

If awesome-typescript-loader is fixed, the setup will be a lot easier.

**Comment by wkwiatek** [comment]
Hi @Derek-X-Wang, is your issue solved? Haven't had time to see what's going on in this topic yet. 

Thanks @izhaknys for your help!

**Comment by Derek-X-Wang** [comment]
Hi @wkwiatek,

izhaknys' solution is more like a walkaround.  However, this issue probably has more things to do with awesome-typescript-loader than react-hot-loader.

**Comment by autozimu** [comment]
I came across the same issue recently and finally figured a way out.

Just replace the update part in `index.tsx`:
```typescript
declare var module: any;
declare var require: any;
if (module.hot) {
  module.hot.accept('./containers/Root', () => {
      require("./containers/Root");   // THIS IS IT!
      render(Root);
  })
}
```

**Comment by rodogir** [comment]
@autozimu thanks for the hint!

For my setup this works:

```
if (module.hot) {
  module.hot.accept("./containers/Root", () => {
    render(require("./containers/Root").default);
  });
}
```

I'm using `awesome-typescript-loader` without babel. 

Here my `tsconfig.json`  `compilerOptions`:
```
{
    "outDir": "./dist",
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "target": "es5",
    "jsx": "react"
}
```

**Comment by Kitanotori** [comment]
https://github.com/gaearon/react-hot-loader/issues/514#issuecomment-299716674 fixed it for me also.

I wonder if there's a way to get rid of the require, as I'm using 'import' everywhere in my app, and I prefer to keep the syntax uniform?
