### ISSUE TITLE
react-hot-loader/babel inside .babelrc plugins breaking child.type reference

### ISSUE THREAD

**Issue by baldore** [gaearon/react-hot-loader#516]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

When `child.type` is used with react-hot-loader@next, react-router-dom@next and webpack@2.2.1, it doesn't recognize the original class/function.

### Expected behavior

child.type should recognize the type when checked with the class/function, returning `true`.

### Actual behavior

The comparison `child.type === ComponentClass` returns `false`.

### Environment

React Hot Loader version:

Run these commands in the project folder and fill in their results:

1. `node -v`: 7.2.1
2. `npm -v`: 3.10.10

Then, specify:

1. Operating system: Linux Mint 17
2. Browser and version: Any browser

### Reproducible Demo

Clone https://github.com/baldore/react-tips-and-tricks-workshop/tree/issue-react-hot-loader, run `yarn install` and `yarn start`.

Open http://localhost:3000/solution-02 to see the problem.

In .babelrc, uncomment `react-hot-loader/babel` . If you open the file `src/topics/02/solution.js` in line 20 and check with a debugger or console.log, you can see that somehow react-hot-loader is modifying the reference.

**Comment by calesce** [comment]
Hi, thanks for the issue. This is already being tracked in #304, so I'm going to close this one.
