### ISSUE TITLE
Dependencies are incorrect when modules are re-exported from an index.js causing unnecessary module updates

### ISSUE THREAD

**Issue by groovydaz** [gaearon/react-hot-loader#520]
### Description

In my application I use index.js files extensively to re-export components but I'm finding that this causes react-hot-loader 3 to hot reload (update) modules unnecessarily, whereas react-hot-loader 1 did not exhibit this behaviour.

I've put together an example branched from 'react-hot-boilerplate' to demonstrate the issue:
https://github.com/groovydaz/react-hot-boilerplate/tree/next

In the example a batch of similar components may live in the "Components" folder and be re-exported from an index file as:

**src/Components/index.js**
```js
export {default as Counter} from './Counter'
export {default as Counter2} from './Counter2'
```

Then elsewhere be imported, for example
```js
import {Counter1} from './Components';
```

Some widgets may import {Counter} and others {Counter2}, or both. 

In the example the main **App.js** imports {Counter} and **Widget.js** imports {Counter2}, 

The components render the following JSX

**[App.js](https://github.com/groovydaz/react-hot-boilerplate/blob/next/src/App.js)**
```jsx
<Layout>
   <Counter />
    <Widget/>
</Layout>
```

**[Widget.js](https://github.com/groovydaz/react-hot-boilerplate/blob/next/src/Widget.js)**
```   
<div>
  <h1>Widget</h1>
  <Counter2 />
</div>
```

### Actual behavior
The issue is that if I change **[Counter.js](https://github.com/groovydaz/react-hot-boilerplate/blob/next/src/Components/Counter.js)** then the [Widget.js](https://github.com/groovydaz/react-hot-boilerplate/blob/next/src/Widget.js) component will also update, even though [Widget.js](https://github.com/groovydaz/react-hot-boilerplate/blob/next/src/Widget.js) only depends on {Counter2} and has no dependency on {Counter}

E.g. a modification to  **[Counter.js](https://github.com/groovydaz/react-hot-boilerplate/blob/next/src/Components/Counter.js)** produces the following output:
```
[HMR] Updated modules:
[HMR]  - ./src/Components/Counter.js
[HMR]  - ./src/Components/index.js
[HMR]  - ./src/App.js
[HMR]  - ./src/Widget.js
```

### Expected behavior

When modifying Counter.js it is the only module which is updated (as in react-hot-loader 1) output seen should be:
```
[HMR] Updated modules:
[HMR]  - ./src/Components/Counter.js
```

### Environment

React Hot Loader version: 3.0.0-beta.6

Run these commands in the project folder and fill in their results:

1. `node -v`: v6.9.2
2. `npm -v`: 3.10.9

Then, specify:

1. Operating system: Windows 10 Professional
2. Browser and version: Google Chrome Version 56.0.2924.87 (64-bit)

### Reproducible Demo
Available at:
https://github.com/groovydaz/react-hot-boilerplate/tree/next

**Comment by neoziro** [comment]
What you described here is relative to Webpack, not to React Hot Loader. These logs came from Webpack not from React Hot Loader.

```
[HMR] Updated modules:
[HMR]  - ./src/Components/Counter.js
[HMR]  - ./src/Components/index.js
[HMR]  - ./src/App.js
[HMR]  - ./src/Widget.js
```

So this is not a React Hot Loader issue and it should probably be fixed now.
