### ISSUE TITLE
Problems with specifying dev/prod env.

### ISSUE THREAD

**Issue by MocanuMarius** [gaearon/react-hot-loader#524]
Hey, i think this code below is a little bit "hard-coded" to be considered as a suitable switcher for a webpack production config.

I use Webpack 2 --env flag and i cannot get my prod bundle to recognize <AppContainer> from production module and thus it fails compiling.

Is there a smarter way to do this ? Because for windows it's a problem with setting NODE_ENV to test bundle size and everything. 

I'm talking abot the lines below, excerpt from the coedbase:
```
/* eslint-disable global-require */

'use strict';

if (!module.hot || process.env.NODE_ENV === 'production') {
  module.exports = require('./AppContainer.prod');
} else {
  module.exports = require('./AppContainer.dev');
}
```

**Comment by bebraw** [comment]
Hi,

My understanding is that they'll fix it in the next beta. Currently react-hot-loader has been packaged in a such way that it's not possible to process through webpack to inject the right code paths depending on the environment. Once they alter the way react-hot-loader is built, this will be fixed.

You have to solve this on the user space for now. I've [documented what to change and how](https://survivejs.com/webpack/appendices/hmr-with-react/). Ideally user space hacks wouldn't be needed. 😄

**Comment by neoziro** [comment]
If you use React, you have to compile using "NODE_ENV=production", compiling in another environment is not a good idea.
