### ISSUE TITLE
Actions dispatched again when reducers are hot reloaded

### ISSUE THREAD

**Issue by cyberhck** [gaearon/react-hot-loader#527]
### Description
This is a question. Not sure if I'm doing something wrong or it's intended behavior.
What you are reporting:
I'm trying react hot reloading, along with reducers. It's working perfectly, although I'm not sure about reducers.

Let's say I've this reducer:
```JavaScript
  switch (action.type) {
    case INCREMENT:
      return {
        count: state.count + 2
      };

    case DECREMENT:
      return {
        count: ((state.count - 1 > 0) ? state.count - 1 : 0)
      };

    default:
      return state;
  }
```
I dispatched `INCREMENT` 3 times, and my UI shows "6"
I change `INCREMENT` case and save `count:state.count + 1`

### Expected behavior
Hot reloaded, UI should still show 6, but when I dispatch `INCREMENT` again, it should become 7

### Actual behavior
Hot reloaded, UI shows 3 (actions are dispatched again), and when I dispatch `INCREMENT` it does become 4.

It does work, but replays actions again. Any idea what I'm doing wrong?
### Environment

It's a general question, so I'll skip this for now.

**Comment by wkwiatek** [comment]
Actually it depends also how you achieved hot reload for reducers. If you could give us some repo, we could maybe help somehow. Now we can only guess.

**Comment by cyberhck** [comment]
```JavaScript
if (appConfig.env === "development" && (module as any).hot) {
  (module as any).hot.accept("./rootReducer", () => {
    store.replaceReducer((require("./rootReducer").default));
  });
}
```
That's how I did that.

**Comment by cyberhck** [comment]
Additional info: I had something like the following:
```JavaScript
const composeEnhancers = (appConfig.env !== "production" &&
  typeof window === "object" &&
  window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__) || compose;

const store = createStore(rootReducer, initialState, composeEnhancers(
  applyMiddleware(...middlewares)
));

if (appConfig.env === "development" && (module as any).hot) {
  (module as any).hot.accept("./rootReducer", () => {
    store.replaceReducer((require("./rootReducer").default));
  });
}
```
Then I went ahead and disabled my redux-devtools browser extension, and it works as expected. Although, I don't want to disable those, right now I'm waiting for a confirmation if I can post the code online, does the additional information point to any direction?

Thanks in advance.

**Comment by cyberhck** [comment]
looks like this is due to: gaearon/redux-devtools#304 as a work around I did:
```JavaScript
const composeEnhancers = (appConfig.env !== "production" &&
  typeof window === "object" &&
  (typeof window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ === "function") &&
  window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({shouldHotReload: false})) || compose;
```
But I'm not sure if `shouldHotReload` is intended to be used somewhere else.
