### ISSUE TITLE
Request for a new starter kit

### ISSUE THREAD

**Issue by thomasthiebaud** [gaearon/react-hot-loader#528]
I created a starter kit with :
- `react-hot-loader`: `3.0.0-beta.6`
- `react-router`: `4.0.0` (and code splitting !!!)
- `redux`
- `reselect`
- `jest` (and some tests)

I also have a `development`, `test` and `production` configuration. The code is located [here](https://github.com/thomasthiebaud/react-kit.git)

Do you think it is relevant to put it in the starter kit page ?

**Comment by calesce** [comment]
Sure! Just make a PR.
