### ISSUE TITLE
[Bug] Cannot read property 'split' of undefined at react-hot-loader/lib/webpack/makeIdentitySourceMap

### ISSUE THREAD

**Issue by dknlinh** [gaearon/react-hot-loader#529]
**Description**
What you are reporting: bug

**Expected behavior**
run successfully

**Actual behavior**
got error

**Environment**
React Hot Loader v3

Run these commands in the project folder and fill in their results:
node -v: v6.9.1
npm -v: 3.10.8
Then, specify:

Operating system: macOS
Browser and version: safari

**Reproducible Demo**
[https://github.com/dknlinh/typescipt-react-webpack](url)

**Comment by ncphillips** [comment]
I am also experiencing this. 

The problem is in the hot loader code of my app, it's getting transpiled to this.

```
if (true) {
	    module.hot.accept("./js/components/Root.tsx""./js/components/Root.tsx", function () {
	        var NextRoot = __webpack_require__("./js/components/Root.tsx").App;
	        renderApp(NextRoot);
	    });
	}
```

**Comment by ncphillips** [comment]
@dknlinh this wasn't a react-hot-loader issue for me, it was a webpack issue

I had both `--hot` and the HMR plugin in play

**Comment by Ziriax** [comment]
We encounter the same issue when compiling with Typescript 2.3, when the `actionCreator` in the module below is exported and used:

```
export interface Action<T, P> {
    type: T;
    payload: P;
}

export function actionCreator<A extends Action<any, any>>(type: A["type"]): (payload: A["payload"]) => A {
    return payload => ({type, payload}) as A;
};
```
When the `actionCreator` is moved to the module that uses it, the problem does not occur.

Maybe that helps.

**Comment by heaplabs** [comment]
Any updates on this one ?

**Comment by neoziro** [comment]
@heaplabs I think it is a transpilation error, it could be easily reproduced in a test. I don't have time to work on it but you could investigate by adding a test and looking at the output. After [this PR](https://github.com/gaearon/react-hot-loader/pull/638) it will be easier.

**Comment by neoziro** [comment]
Should be fixed now, if not will be in [v4](https://github.com/gaearon/react-hot-loader/tree/next/).
