### ISSUE TITLE
React Hot Loader doesn't work if React is external (CDN)

### ISSUE THREAD

**Issue by bjfletcher** [gaearon/react-hot-loader#53]
Hi there,

Given:
```
module.exports = {
  externals: {
    react: 'React',
    'react/addons': 'React',
    'react-router': 'ReactRouter'
  }, ...
```

and:
```
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/react/0.12.2/react-with-addons.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/react-router/0.11.6/react-router.min.js"></script>
```

in the `html`.  Then the React Hot Loader doesn't work.  I see this in the `console`:
```
[HMR] Waiting for update signal from WDS...
[WDS] Hot Module Replacement enabled.
[WDS] App updated. Recompiling...
[WDS] App updated. Recompiling...
[WDS] App hot update...
[HMR] Checking for updates on the server...
[HMR] Updated modules:
[HMR]  - 20
[HMR] App is up to date.
```

but I don't see the changes getting reflected in the view.  It'd work however If I commented out the `externals` configuration and the `script` lines in the `html` (getting webpack to use NPM react packages).

The `console` output is almost the same as above except that `[HMR] - 20` was `[HMR] - 19`.

Any suggestions on how to debug/fix this would be welcome.  Confirmation that anyone has successfully used React Hot Loader with external React resources would be great too.

**Comment by gaearon** [comment]
Good catch. We [depend on](https://github.com/gaearon/react-hot-loader/blob/master/getRootInstances.js#L4) internal `react/lib/ReactMount`.

In your case, it seems that external packages are being used for React itself, but `react/lib/ReactMount` is taken from NPM package. This doesn't work because they correspond to two independent copies of React. If you delete NPM packages, it should no longer build at all.

I think it would be nice to avoid depending on `ReactMount` but then we'd need another way to get list of root instances. This could be made injectable by user but I'm not sure if it's worth the complexity.

What practical benefit does it give you to use externals in dev?

**Comment by gaearon** [comment]
Please see if this works for you:

https://github.com/gaearon/react-hot-loader/blob/master/docs/README.md#usage-with-external-react

**Comment by bjfletcher** [comment]
Hello @gaearon! That's a great turnaround. :)

A reason for asking about this is because, for me, If there's any way to reduce the differences between development and production environments without impacting on their productivity and performance respectively, then I feel that's worth exploring. :)

I wonder if Facebook or the React people have been asked about providing some way of accessing `ReactMount` with the precompiled version?  Worth asking them, do you think?

**Comment by gaearon** [comment]
As they're aiming for smaller API surface I doubt they'd be inclined to do it.

There *is* a devtools hook that can be used to get internal objects (React Chrome DevTools uses it), however this hooks is meant to only be set once so it's inconvenient and error-prone to try to use it here. I'll raise an issue though.

**Comment by gaearon** [comment]
Filed as https://github.com/facebook/react/issues/2797

**Comment by frankychung** [comment]
Just wanted to chime in this works great for our project that has React as an external. Thank you!

**Comment by gaearon** [comment]
@frankychung I'm glad to hear this!

**Comment by davibe** [comment]
I think this happens even if you use react from npm and you require('react/addons') which is the version with all the addons.
At least it happens to me with react 0.11.1

**Comment by gaearon** [comment]
Davide, can’t find your comment, have you figured it out, or is Github glitching?

**Comment by davibe** [comment]
I had a second look. Basically I wanted to require react+addons without modifying my code (its code that works fine with plain require.js and now i am making it work with webpack too). So i set up an alias { 'react': 'react/addons' } in webpack.config.js but if you do that then again react-hot-loader can't find 'react/lib/ReactMount' anymore. Which makes sense. It's just one more case similar to the previous ones.

**Comment by gaearon** [comment]
Yeah I also bumped into that before. You can actually work around it in a terrible-ish way:

```js
       'react': 'react/addons',
      // A workaround for react/lib to be resolved correctly:
      'react/addons/lib': 'react/../lib',
```

**Comment by davibe** [comment]
ahaha, my god. I like the hot realoding thing. Its why i am tryin webpack. But the amount of unclean hacks I had to apply is making me sick. Thank you though, nice one.

**Comment by gaearon** [comment]
With `react-hot-loader@2.0.0-alpha` you'll no longer need this `Injection` nonsense, it will just work.
Please provide any feedback on it in this PR: https://github.com/gaearon/react-hot-loader/pull/182

**Comment by Giioaj** [comment]
@gaearon but now appears this if i use ReactDOM to render (the correct way):

> ERROR in ./~/react-dom/index.js
> /bower_components/react/react.min.js/lib/ReactDOM

**Comment by codelegant** [comment]
@gaearon In product env, use externals, and the addons had to declare like this `const update=React.addons.update`. But in dev env, use NPM package, you should `import update from 'react-addons-update`.
That made me confused, for consistency, I had to  use externals in dev.
Is there any solution? I'm waiting online. Thank you.
