### ISSUE TITLE
inputRef(property of FormControl in react-bootstrap) is undefined in componentDidMount

### ISSUE THREAD

**Issue by kinglywork** [gaearon/react-hot-loader#537]
### Description

while using react-hot-loader@3.0.0-beta.6, the inputRef will be undefined in componentDidMount.
inputRef is property of FormControl in react-bootstrap package.
PS. 
1. use ref and then with ReactDOM.findDomNode to get dom works well.
2. use react-hot-loader@1.3.0 with inputRef  also works well.

### Expected behavior

inputRef should be the input dom node

### Actual behavior

inputRef is undefined

### Environment

React Hot Loader version:3.0.0-beta.6

Run these commands in the project folder and fill in their results:

1. `node -v`: 6.9.4
2. `npm -v`: 4.4.4

Then, specify:

1. Operating system: Windows 10
2. Browser and version: Chrome57

**Comment by rjdestigter** [comment]
Having the same issue

**Comment by luigi-rosso** [comment]
Seeing this same issue. 

Has anyone found a workaround? It seems like the props and state object references are identical within the two different component objects.

**Comment by luigi-rosso** [comment]
I think I found a workaround, this issue seems to be caused by the proxying logic in react-proxy. One trick is to store an object to hold your references, this will get copied to the proxy by react-proxy and will be available in the proxy version of "this".

```
constructor(props)
{
	super(props);
	this.myRefs = {};
	this.setMyRef = this.setMyRef.bind(this);
}

componentDidMount()
{
	console.log(this.myRefs.div); // <-- Not null!
}

setMyRef(ref)
{
	this.myRefs.div = ref;
}

render()
{
	return <div ref={this.setMyRef}></div>;
}
```

**Comment by luigi-rosso** [comment]
Even easier way is to make sure your function bindings are done in componentWillMount:

```
constructor(props)
{
	super(props);
	// Do not bind here, "this" will get proxied.
}

componentWillMount()
{
	// Proxy "this" is now available. Bind here.
	this.setMyRef = this.setMyRef.bind(this);
}

componentDidMount()
{
	console.log(this.div); // <-- Not null!
}

setMyRef(ref)
{
	this.div = ref;
}

render()
{
	return <div ref={this.setMyRef}></div>;
}
```

**Comment by neoziro** [comment]
This is all solved in [v4](https://github.com/gaearon/react-hot-loader/tree/). Also added an [example using react-bootstrap](https://github.com/gaearon/react-hot-loader/tree/next/examples/bootstrap).
