### ISSUE TITLE
support React 15.5 deprecations

### ISSUE THREAD

**Issue by rockchalkwushock** [gaearon/react-hot-loader#541]
### Description

Package currently still uses `propTypes` from `react`. As per `react@15.5` this has been deprecated and an external [package](https://github.com/reactjs/prop-types) can be used instead.
### Expected behavior

Package functions as anticipated this is just an update that needs to be made to the code base to stay current with the `react` ecosystem.
### Actual behavior

Following error message is showing in the browser console:
![screen shot 2017-04-08 at 12 04 32 pm](https://cloud.githubusercontent.com/assets/19720404/24831956/77de819a-1c6a-11e7-8ded-c2a61ef3bf76.png)

### Environment

React Hot Loader version:
```json
"react-hot-loader": "3.0.0-beta.6",
```
Run these commands in the project folder and fill in their results:

1. `node -v`: `7.7.2`
2. `npm -v`: `4.1.2`

Then, specify:

1. Operating system: `MacOS Sierra 10.12.4`
2. Browser and version: `Google Chrome Version 57.0.2987.133 (64-bit)`

Opening a PR will reference Issue there and PR here.

**Comment by rockchalkwushock** [comment]
Closing. I was mistake with the use of `propTypes` in the package. Issue was coming from [`redbox-react`](https://github.com/commissure/redbox-react/releases) not this package.

**Comment by EvNaverniouk** [comment]
I think this issue is still relevant since `redbox-react` is a dependency of `react-hot-loader`. The dependency should be upgraded to `1.3.6` to fix the warnings.

**Comment by reintroducing** [comment]
Yeah, I think this needs to be re-opened. Seeing this as well and I think this is the last item that needs to be updated in my project(s) to use `prop-types` but its hard to tell because it doesn't tell you exactly where its being used still.
