### ISSUE TITLE
Content not updated when used with webpacks resolve.modules

### ISSUE THREAD

**Issue by zacbarton** [gaearon/react-hot-loader#545]
### Description

Hot reloading fails to update content if used with webpack (2.2) resolve.modules config.

### Expected behavior

webpack:
```
resolve.modules = [ paths.src, paths.nodeModules ]
```

app:
```
import RootApp from 'layouts/RootApp'; // note using resolve.module to resolve this to '/my/path/src/layouts/RootApp'
```

Updating "RootApp" should hot update browser.

### Actual behavior

Update "RootApp":
```
[HMR] Updated modules:
log-apply-result.js?e2ce:22 [HMR]  - ./layouts/RootApp/index.js
[HMR] App is up to date.
```

Content is not updated.

If the import was however:
```
import RootApp from './layouts/RootApp'; // note not using resolve.modules
```

And you update "RootApp" the content is updated in the browser.

### Environment

rhl: 3.0.0-beta.6
node: v7.4.0
npm: 4.0.5

os: Linux
Browser: chrome latest

**Comment by neoziro** [comment]
Probably a Webpack HMR issue already fixed. I don't have any problem using Webpack 3.
