### ISSUE TITLE
Typescript Config Module: ES6 Causes State Reset

### ISSUE THREAD

**Issue by jdolle** [gaearon/react-hot-loader#548]
### Description

I'm not sure if this is specifically a react-hot-loader issue or some strange compatibility issue with typescript, but using Typescript to compile with `tsconfig.json`
```
{
  "compilerOptions": {
    "module": "ES6",
  }
}
```
will cause the entire component to re-create, destroying the state.

### Expected behavior

The state should remain

### Actual behavior

The entire component to re-create, destroying the state.

### Environment

Typescript version: 2.2.0

React Hot Loader version: 3.0.0-beta.6

1. `node -v`: v7.5.0
2. `npm -v`: 4.1.2

1. Operating system: macOS Sierra
2. Browser and version: Chrome  Version 57.0.2987.133 (64-bit)

### Reproducible Demo

https://github.com/jdolle/react-hot-loader-typescript-issue

**Comment by piotrwitek** [comment]
@jdolle I confirm the same issue.
When I switch to `module: "common"` and use require everything works fine, but when I switch to `module: "es2015"` state is lost

**Comment by avivshafir** [comment]
@jdolle @piotrwitek I also just encountered the same issue exactly...

**Comment by jtmthf** [comment]
Has anyone else tried piping the output through Babel. I have TypeScript compile to es2015 and then use Babel to transpile to es5 and React-Hot-Loader works in this configuration.

**Comment by cybrown** [comment]
I have the same issue with the files generated by typescript, but then processed by babel with {modules: false}.
It must be an issue with the es2015 modules and not a typescript specific issue.
I've tried react-hot-loader 3.0.0-beta.7.
