### ISSUE TITLE
react & react-dom 16.0.0-alpha no re-rendering happens

### ISSUE THREAD

**Issue by reactima** [gaearon/react-hot-loader#552]
### Description

Bumping react & react-dom to 16.0.0-alpha will broke react-hot-loader re-rendering. 

[HMR] Updated modules:
log-apply-result.js:22 [HMR]  - ./src/components/App.js
dev-server.js:27 [HMR] App is up to date.

Even log "App is up to date." redrawing of App is not happening. 

### Reproducible Demo

Bump dependencies to the latest here
https://github.com/nganbread/bare-minimum-react-hot-rr4-redux

    "react": "16.0.0-alpha.10",
    "react-dom": "^16.0.0-alpha.10",

**Comment by reactima** [comment]
Bouncing back to   "react": "~15.5.0", "react-dom": "~15.5.0" solved the issue

**Comment by neoziro** [comment]
Alpha is not an issue, we have to target the fresh new React 16 now.
