### ISSUE TITLE
Is React.PureComponent supported in v3?

### ISSUE THREAD

**Issue by andylhansen** [gaearon/react-hot-loader#553]
Is React.PureComponent supported in v3?
I have been able to get React.Component to work and stateless functional components to work, but not PureComponent.

**Comment by chrisblossom** [comment]
``PureComponent`` works for me after I followed all of the [migration-to-30](https://github.com/gaearon/react-hot-loader/tree/master/docs#migration-to-30) steps.

I was missing ``<AppContainer>``

**Comment by neoziro** [comment]
Yes it works.
