### ISSUE TITLE
Stack trace includes no useful information about the origin of the error

### ISSUE THREAD

**Issue by gajus** [gaearon/react-hot-loader#556]
### Description

Using `react-hot-loader/babel` obscures the stack trace to the point of the original error being untraceable.

In this particular case, the subject component is:

```js
const TransactionSummary = (props: PropsType) => {
  const {
    movie,
    reservationFee,
    tickets,
    time,
    timestamp,
    venue
  } = props;

  const ticketQuantityMap = createTicketQuantityMap(tickets);

  const products = _
    .uniqBy(tickets, 'type.nid')
    .map((product) => {
      const quantity = ticketQuantityMap.get(product.id);

      return {
        name: product.type.name,
        price: product.price,
        quantity,
        type: product.type
      };
    });

[..]
```

The error is that `price` gets `undefined` value which is incompatible with a later transformation.

### Expected behavior

This is the stack trace I'd get without `react-hot-loader`, which points clearly to the `products.map.ticket`.

<img width="988" alt="screen shot 2017-05-01 at 10 11 10" src="https://cloud.githubusercontent.com/assets/973543/25576395/89736c4c-2e56-11e7-8952-a48193c7aeaa.png">

### Actual behavior

This is the behaviour with `react-hot-loader` transpilation enabled:

<img width="988" alt="screen shot 2017-05-01 at 10 09 59" src="https://cloud.githubusercontent.com/assets/973543/25576397/8deab208-2e56-11e7-8603-27b6adf69b56.png">

This gives me absolutely no indication what is the origin of the error.

### Environment

React Hot Loader version:

^3.0.0-beta.6

Run these commands in the project folder and fill in their results:

1. `node -v`: v7.9.0
2. `npm -v`: v4.2.0

Then, specify:

1. Operating system: OS
2. Browser and version: Chrome v58

### Reproducible Demo

N/A

**Comment by 0x80** [comment]
I was having a similar issue when I came across this, but eventually I solved it by changing my `devtool` setting in the webpack config. You could try setting it to `eval` and see if that helps.

**Comment by neoziro** [comment]
Not related to React Hot Loader. [Webpack devtool](https://webpack.js.org/configuration/devtool/#devtool) + [Error boundaries](https://reactjs.org/docs/error-boundaries.html#introducing-error-boundaries) are the solution.
