### ISSUE TITLE
Access Control Allow Origin?

### ISSUE THREAD

**Issue by ronag** [gaearon/react-hot-loader#56]
What is might be the problem here? Do I need to set some setting on the dev server for this to work?

```
Failed to load resource: the server responded with a status of 404 (Not Found)
10.0.1.27/:1 XMLHttpRequest cannot load http://10.0.1.27:9090/build/2590dcf104e749604e15.hot-update.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.0.1.27:8080' is therefore not allowed access. The response had HTTP status code 404.
```

**Comment by gaearon** [comment]
Does hot reload actually fail, or does it just output this message?
There was some in issue in Webpack about errors which are not "errors" per se.

**Comment by ronag** [comment]
Hm, the issue went away by itself after a reload.

**Comment by gpbl** [comment]
@ronag i've seen this as well - maybe is your server restarting itself (nodemon)?

**Comment by Dakuan** [comment]
I also have this

```
items:1 XMLHttpRequest cannot load http://0.0.0.0:3000/6a5bec410cd2f01435bc.hot-update.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4130' is therefore not allowed access. The response had HTTP status code 404.
```

**Comment by Dakuan** [comment]
This patch to `webpack-dev-server` fixes this issue for me https://github.com/webpack/webpack-dev-server/pull/110

**Comment by gaearon** [comment]
Let's leave this open for posterity.

**Comment by jbasdf** [comment]
I'm seeing the same issue when serving pages from node on 8888 and using the webpack dev server on 8080:
XMLHttpRequest cannot load http://localhost:8080/build/377563fabf427177f203.hot-update.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8888' is therefore not allowed access. The response had HTTP status code 404.

**Comment by Dakuan** [comment]
@jbasdf add cors middleware to your webpack-dev-server

**Comment by jbasdf** [comment]
Thanks @Dakuan, I ended up setting the headers when I start the server. Here's the code: 

var webpackDevServer = require('webpack-dev-server');
new webpackDevServer(webpack(webpackConfig), {
  publicPath: "http://localhost:8080/build",
  hot: true,
  headers: { "Access-Control-Allow-Origin": "*" }
}).listen(settings.ports.hotPort, 'localhost', function(err, result){
  if(err){
    console.PluginError(err);
  }
  console.log('Webpack hot load server listening on port ' + settings.ports.hotPort);
});

**Comment by troutowicz** [comment]
CORS should not need to be enabled locally. If you want to access the dev server from another device in your local network, have your web servers listen on your devices local IP instead if localhost. You can do this with webpack-dev-server by passing the `--host` flag.

**Comment by jbasdf** [comment]
I serve the page using node.js and the assets via the webpack-dev-server. They run on different ports so CORS has to be enabled or the browser will give you same origin errors.

**Comment by troutowicz** [comment]
Ports do not matter, the domain does. As long as your servers are running on an internal IP other than localhost, CORS is not needed when accessing server resources from another device in the network.

**Comment by jbasdf** [comment]
That was my assumption, but the version of Chrome I'm using wouldn't allow the socket connect until I added Access-Control-Allow-Origin": "*".

**Comment by troutowicz** [comment]
I have not been using Chrome, but I just went and tested in Chrome v40.0.2214.115 m, and everything works as expected.

**Comment by gaearon** [comment]
This is on [Troubleshooting](https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#no-access-control-allow-origin-header-is-present-on-the-requested-resource) page now, so closing.

**Comment by DominicTobias** [comment]
Thank @jbasdf ! Was having the same issue on Chrome 43

**Comment by halt-hammerzeit** [comment]
I'm having this issue by the way, and I've set the headers in the config.
I'll go google for possible solutions.

**Comment by halt-hammerzeit** [comment]
Oh, I'm not having this issue anymore: my port number in the corresponding webpack entry point `"webpack-dev-server/client?http://127.0.0.1:...` was messed up and that caused the error.

**Comment by gaearon** [comment]
@halt-hammerzeit Can you send a PR to Troubleshooting doc describing how you fixed the problem? Others may have the same issue.

**Comment by halt-hammerzeit** [comment]
@gaearon Ok, here's how it was:

webpack.config.js
```
... [
    "webpack-dev-server/client?http://0.0.0.0:" + configuration.development.webpack.development_server.port,
...
```

And the variable `configuration.development.webpack.development_server.port` was basically undefined.

**Comment by jedwards1211** [comment]
@troutowicz ports do matter.  According to [MDN](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), "Two pages have the same origin if the protocol, port (if one is specified), and host are the same for both pages."

**Comment by troutowicz** [comment]
@jedwards1211 Strange. When I was working with this project I never had CORS issues when using private ip-ranges.

**Comment by hugotox** [comment]
I'm having this issue with webpack-dev-server 2.4.2 and react-hot-loader 3.0.0-beta-6. Adding { 'Access-Control-Allow-Origin': '*' } did not work

**Comment by jedwards1211** [comment]
@troutowicz that is strange.  I have no idea if browsers don't enforce CORS for `localhost` or `0.0.0.0`, but [at least one person has seen it happen](http://stackoverflow.com/questions/25853319/why-is-cors-needed-for-localhost)

**Comment by michaelBenin** [comment]
Also running into the same issue as @hugotox with v2.

**Comment by michaelBenin** [comment]
@hugotox in your webpack config, try adding this: 

```
devServer: {
    headers: { "Access-Control-Allow-Origin": "*" }
  },
```

**Comment by hugotox** [comment]
@michaelBenin thanks a lot that fixed it!

**Comment by sheprdinc** [comment]
great that everyone is showing how to do it with the devServer, but what about the production server? where/how do i do that?

where/how do i add this:
headers: { "Access-Control-Allow-Origin": "*" }
to my production build?

**Comment by michaelBenin** [comment]
That's something configured in the cdn or web server serving the file. What are you using?

**Comment by DmacMcgreg** [comment]
Try adding this:
`app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
})`

**Comment by SylarRuby** [comment]
You guys are the boss! Thanks for `headers: { 'Access-Control-Allow-Origin': '*' }` on https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#no-access-control-allow-origin-header-is-present-on-the-requested-resource
