### ISSUE TITLE
getting error trying to use with webpack

### ISSUE THREAD

**Issue by anthonyettinger** [gaearon/react-hot-loader#561]
Using the following code when I run `npm run start` which does `webpack --watch --display-error-details`

```
import React from 'react';
import { render } from 'react-dom';
import { AppContainer } from 'react-hot-loader';
import Icon from './icon.js';

document.querySelector('#app'));
render(<AppContainer></AppContainer>, document.querySelector('#app'));

if (module && module.hot) {
  module.hot.accept('./icon.js', () => {
    const App = require('./icon.js').default;
    render(
      <AppContainer>
        <Icon name="checkmark" />
      </AppContainer>,
      document.querySelector('#app')
    );
  });
}
```

This is the error: `Module build failed: SyntaxError: Unexpected token (7:7)` which is the start of the `<AppContainer>`

**Comment by philiiiiiipp** [comment]
I think you are missing <Icon name="checkmark" /> in between.

**Comment by neoziro** [comment]
@anthonyettinger you are missing App in AppContainer, your config is not good. Please follow the migration guide.
