### ISSUE TITLE
`myFunc = () => {}` doesn't work (?)

### ISSUE THREAD

**Issue by kud** [gaearon/react-hot-loader#564]
Hey,

I've got a little problem with hot-loader (I've got the latest version)).

If I do this:

```javascript
renderA() = {
  return (<div />)
}

render() {
  return (
    {this.renderA()}
  )
}
```

it refreshes correctly the render.

But if I do the trick to keep the right `this`:

```javascript
renderA = () => {
  return (<div />)
}

render() {
  return (
    {this.renderA()}
  )
}
```

Nothing happens about the render.

Is it normal?

**Comment by kud** [comment]
Related https://github.com/gaearon/react-hot-loader/issues/242

**Comment by MaxInMoon** [comment]
@kud did you try this?

```
renderA = () => {
  return (<div />)
}
```

**Comment by gajus** [comment]
Duplicate of https://github.com/gaearon/react-hot-loader/issues/554
