### ISSUE TITLE
Can't resolve 'react-hot-loader/patch'

### ISSUE THREAD

**Issue by ddydeveloper** [gaearon/react-hot-loader#569]
I have this error then I try to webpack bundle. A few days early it worked fine, but now it fails. I tried to downgrade react-hot-loader version but it did't work.

I tried to find same issues, but all of them was closed with same solutions: downgrading to previous versions or waiting for fixes in new version. I hope, anybode has same problems. 

### Description

In console i have this output:

> ERROR in multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev
> -server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 w
> ebpack/hot/only-dev-server ./index.js
> Module not found: Error: Can't resolve 'react-hot-loader/patch' in 'd:\Projects\
> ReactRedux\src'
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-serve
> r react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack
> /hot/only-dev-server ./index.js
> 
> ERROR in ./src/index.js
> Module build failed: ReferenceError: Unknown plugin "react-hot-loader/babel" spe
> cified in "d:\\Projects\\ReactRedux\\.babelrc" at 0, attempted to resolve relati
> ve to "d:\\Projects\\ReactRedux"
>     at d:\Projects\ReactRedux\node_modules\babel-core\lib\transformation\file\op
> tions\option-manager.js:180:17
>     at Array.map (native)
>     at Function.normalisePlugins (d:\Projects\ReactRedux\node_modules\babel-core
> \lib\transformation\file\options\option-manager.js:158:20)
>     at OptionManager.mergeOptions (d:\Projects\ReactRedux\node_modules\babel-cor
> e\lib\transformation\file\options\option-manager.js:234:36)
>     at OptionManager.init (d:\Projects\ReactRedux\node_modules\babel-core\lib\tr
> ansformation\file\options\option-manager.js:368:12)
>     at File.initOptions (d:\Projects\ReactRedux\node_modules\babel-core\lib\tran
> sformation\file\index.js:212:65)
>     at new File (d:\Projects\ReactRedux\node_modules\babel-core\lib\transformati
> on\file\index.js:135:24)
>     at Pipeline.transform (d:\Projects\ReactRedux\node_modules\babel-core\lib\tr
> ansformation\pipeline.js:46:16)
>     at transpile (d:\Projects\ReactRedux\node_modules\babel-loader\lib\index.js:
> 48:20)
>     at Object.module.exports (d:\Projects\ReactRedux\node_modules\babel-loader\l
> ib\index.js:163:20)
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-serve
> r react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack
> /hot/only-dev-server ./index.js
> webpack: Failed to compile.

### Environment
React Hot Loader version: ^1.3.1
node version: 6.10.0
npm version: 4.4.0

Then, specify:

1. Operating system: windows 8.1
2. Browser and version: chrome 58.0.3029.110 (64-bit)

### Reproducible Demo
Link to repository: https://github.com/ddydeveloper/ReactRedux.

**Comment by satiewaltz** [comment]
Getting this error as well after running a `yarn upgrade`. 

Not sure what could cause this, but I'll update this issue if I find anything.

**Comment by satiewaltz** [comment]
@ddydeveloper I ended up fixing this by:
1. Deleting `node_modules`.
2. Updating all packages on my `package.json`.
2. Running `yarn install`.
3. Then lastly `yarn check`.

I believe this issue was caused by a recent update by one of the packages that `react-hot-loader/patch` uses.

**Comment by satiewaltz** [comment]
@ddydeveloper I look at your repository for a moment:

It seems that you have  `"react-hot-loader": "^1.3.1",` in your `package.json`,
instead of `"react-hot-loader": "next"`.

`next` branch contains the latest working version of react-hot-loader 3, you should be using that.

**Comment by ddydeveloper** [comment]
@satiewaltz , Your solution is works, thanks a lot! By I don't understand, why it worked two weeks ago, before install and check yarn? Could you explain, please?

**Comment by satiewaltz** [comment]
@ddydeveloper You had `"^1.3.1"` in your `package.json`. This gets an old version of react-hot-loader (v1) instead of v3. 

React Hot Loader v1 is now deprecated and is expected to break. The most current version of React Hot Loader is v3, and is on the `next` branch. Its the one you should be using.

If you install React Hot Loader via `npm install react-hot-loader` it will get the deprecated version instead of the newest one.

`npm install react-hot-loader@next` is the command that should be ran with this library until v3 becomes `master` branch.

**Comment by satiewaltz** [comment]
Feel free to close this issue if things work well for you!

**Comment by ddydeveloper** [comment]
Thanks for explanation, it is very useful information! Close the issue.

**Comment by Ciantic** [comment]
I had this in the package.json `"react-hot-loader": "next"` but if one then run `yarn upgrade react-hot-loader` it changes the package.json version to the `1.3.1`.

In order to install right version I had to upgrade more verbosely: `yarn upgrade react-hot-loader@next`. Something to keep in mind when upgrading.

**Comment by codrex** [comment]
thanks man

**Comment by hassanamin994** [comment]
For people coming here in the future, you can run `npm install --save-dev react-hot-loader@^3` for v3

**Comment by theKashey** [comment]
Please don't use v3. If you are looking for webpack plugin it's here - https://github.com/gaearon/react-hot-loader/releases/tag/v4.4.0

PD: Just `yarn add react-hot-loader` would bump it to the maximal possible version .

**Comment by callmejm** [comment]
for me remove `node_module`s folder , `npm install` again

**Comment by Ploppz** [comment]
Trying `yarn add react-hot-loader` as @theKashey suggested, I get this error
```
ERROR in Loader /tmp/react-treeview/node_modules/react-hot-loader/index.js didn't return a function
 @ multi main
```

When I try `npm install ; npm start` in this repo https://github.com/chenglou/react-treeview
