### ISSUE TITLE
Dynamic require rewriting not working

### ISSUE THREAD

**Issue by SaphuA** [gaearon/react-hot-loader#570]
### Description

I'm trying to include HMR in our project, but having issues with our dynamic components. Is this even supported?

### Actual behavior

It seems to ignore the updates. Not writing any errors or anything.

### Environment

"react-hot-loader": "3.0.0-beta.7"
"webpack": "2.6.0"
"webpack-dev-server": "2.4.5"
Win10, Chrome

Note: using typescript and not babel

### Code
```
const render = (element, instance, props) => {
    Logger.writeDebug("render");
    const reactElement = React.createElement(AppContainer, null, React.createElement(instance, props));
    ReactDOM.render(reactElement, element);
};

// does not work
const component = require("portal/components/" + componentPath);

// works
const component = require("portal/components/my/component");

((e, c, p) => {
    render(e, c.default, p);
    if (module.hot) {
        module.hot.accept(c.id, () => { render(e, c.default, p); });
    }
})(element, component, props);
```

Workable demo is being worked on.

**Comment by SaphuA** [comment]
Finally got around to creating a sample project. Check it out here: https://github.com/SaphuA/DynamicReactHotReloading

As shown in the sample above, the issue happens when using dynamic rewritten components:
https://github.com/SaphuA/DynamicReactHotReloading/blob/master/main.ts#L28

**Comment by neoziro** [comment]
Actually, we do not plan to support dynamic require. Dynamic import is coming and it is supported by [React Hot Loader v4](https://github.com/gaearon/react-hot-loader/tree/next).

**Comment by maciej-gurban** [comment]
@neoziro The link you posted is dead (404s)

**Comment by neoziro** [comment]
You have to mark all your module dynamic imported with `hot`. We are currently experimenting something in Loadable Components to make things easier. https://github.com/smooth-code/loadable-components/pull/53

**Comment by maciej-gurban** [comment]
Thanks. It does work indeed this way. I tried wrapping my react-loadable component with hot(), but no dice. I guess it'd need to be baked into that component to work.

**Comment by neoziro** [comment]
No it must be in the module you load, so you have to duplicate it in each file dynamically loaded.
