### ISSUE TITLE
Cannot set property createElement of #<Object> which is only a getter

### ISSUE THREAD

**Issue by abarcenas29** [gaearon/react-hot-loader#571]
### Description

What you are reporting: I am following this [set of instructions](https://gaearon.github.io/react-hot-loader/getstarted/) on how to setup React hot loarder. But when I go to step 3 where I put the patch, it breaks in to the one below.

### Expected behavior

What you think should happen: Should work properly

### Actual behavior

![image](https://cloud.githubusercontent.com/assets/2470226/26530172/6ef0e036-4402-11e7-8b51-7b81f40af711.png)

### Environment

React Hot Loader version: next

Run these commands in the project folder and fill in their results:

1. `node -v`: 7.9.0
2. `npm -v`: 4.2.0

Then, specify:

1. Operating system: Windows 10
2. Browser and version: Latest Chrome

### Reproducible Demo

https://github.com/abarcenas29/preact-sandbox-v0/blob/wip/hot-reloader/src/main.js

branch: wip-hot-reloader

Instructions:

* `yarn`
* `yarn run postinstall`
* `yarn run start:dev`

**Comment by zhirzh** [comment]
I had the same problem a while back. This solved it: https://github.com/developit/preact-compat/issues/337#issuecomment-290215007

**Comment by robertklep** [comment]
I'm running into the same issue, and it's related to `preact`. Not sure (yet) what's going on.

**Comment by neoziro** [comment]
I you still experienced some issues, give a try to [React Hot Loader v4](https://github.com/gaearon/react-hot-loader/tree/next#getting-started). It has been entirely rewritten. I close this issue, feel free to reopen one if you experienced an issue.
