### ISSUE TITLE
Uncaught SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by Opty1712** [gaearon/react-hot-loader#573]
### Description

**Bug in module.hot.accept:**  _Uncaught SyntaxError: missing ) after argument list ......... bundle.js:46413_

**bundle.js**
```
if (true) {
  module.hot.accept("./src/ProcessReissue/dev.jsx""./src/ProcessReissue/dev.jsx", function(__WEBPACK_OUTDATED_DEPENDENCIES__) { /* harmony import */ __WEBPACK_IMPORTED_MODULE_3__dev__ = __webpack_require__("./src/ProcessReissue/dev.jsx"); (function(__WEBPACK_OUTDATED_DEPENDENCIES__) { /* harmony import */ __WEBPACK_IMPORTED_MODULE_3__dev__ = __webpack_require__("./src/ProcessReissue/dev.jsx"); (1)(__WEBPACK_OUTDATED_DEPENDENCIES__); })(__WEBPACK_OUTDATED_DEPENDENCIES__); }, function () {
    render(__WEBPACK_IMPORTED_MODULE_3__dev__["default"]);
  });
}
```

this **"./src/ProcessReissue/dev.jsx""./src/ProcessReissue/dev.jsx"** should be **"./src/ProcessReissue/dev.jsx"**

### Expected behavior

What you think should happen: browser should show "Hello"

### Actual behavior

What actually happens:

### Environment

React Hot Loader version: react-hot-loader@3.0.0.-beta.7

Run these commands in the project folder and fill in their results:

1. `node -v`: 7.1.0
2. `npm -v`: 3.10.9

Then, specify:

1. Operating system: Win7
2. Browser and version: any

### Reproducible Demo

**src/ProcessReissue/hot.jsx**
```
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { AppContainer } from 'react-hot-loader';
import App from './dev';
const render = (Component) => {
  ReactDOM.render(
    <AppContainer>
      <Component />
    </AppContainer>,
    document.getElementById('application')
  );
};
render(App);
module.hot.accept('./dev', () => {
  render(App);
});
```

**src/ProcessReissue/dev.jsx**
```
import * as React from 'react';
const App = () => (
  <h2>Hello</h2>
);
export default App;
```

**webpack.config.js**
```
entry = [
  'react-hot-loader/patch',
  path.resolve(__dirname, 'src/ProcessReissue/hot.jsx')
];
```

**Comment by yexingxia** [comment]
I got the same error, cause i applied the HotModuleReplacementPlugin twice. 1. with --hot and 2. in plugins
Hope to help

**Comment by Opty1712** [comment]
@yexingxia thank you, it helps!

**Comment by zhanghj819** [comment]
@yexingxia thank you, it helps!!!

**Comment by Sirotyann** [comment]
@yexingxia thank a lot !!!
