### ISSUE TITLE
Cannot Hot Reload with React Router v3

### ISSUE THREAD

**Issue by eezhal92** [gaearon/react-hot-loader#578]
Hi,

I'm newbie. I tried to set `react-hot-loader v3.0.0-beta.7` with `react-router v3.0.5` up, but it hot reloading didn't work when scene/page component changed. I also tried to follow this [instruction](https://github.com/ReactTraining/react-router/issues/2704#issuecomment-212936927)  but no luck.

I keep getting this error `Warning: [react-router] You cannot change <Router routes>; it will be ignored`;

Here's the repro:
- https://github.com/eezhal92/react-router-hmr-case.
- https://github.com/eezhal92/react-router-hmr-case/commit/180a90a2b51da2bf870fb5c84033b09307181379

Hope some folks can come up with solution and explanation.

Thanks A Lot.

**Comment by zation** [comment]
Seems we got the same problem, https://github.com/gaearon/react-hot-loader/issues/592, my project is here: https://github.com/zation/react-admin-starter

**Comment by eugeniaguerrero** [comment]
Hi @eezhal92, have you tried implementing handling of runtime errors as described in [this comment](https://github.com/gaearon/react-hot-loader/issues/580#issuecomment-316081633)?

**Comment by neoziro** [comment]
It is a known limitation, it is solved in v4. https://github.com/gaearon/react-hot-loader#known-limitations
