### ISSUE TITLE
Bundle overhead in production

### ISSUE THREAD

**Issue by drcmda** [gaearon/react-hot-loader#579]
### Description

Maybe i am doing something wrong but i've exhausted all means to track this down. All references to react-hot-loader are out in our webpack.config.prod.js, webpack is on hot: false, HotModuleReplacementPlugin is out, NODE_ENV is on production. The apps index.js remains unchanged:

```js
import { AppContainer } from 'react-hot-loader'

...
   render(<AppContainer>...</AppContainer>, document.getElementById('app'))

process.env.NODE_ENV !== 'production'
    && module.hot 
    && module.hot.accept('./views/App', () => ... )
```

But it still puts lots of weight into the bundle, for instance (stat-size):

* react-hot-loader 9kb
* redbox-react 25kb
* sourcemapped-stacktrace 76kb

![rhl](https://user-images.githubusercontent.com/2223602/26926280-5100174c-4c4d-11e7-9ea1-1fe3f67b345a.jpg)

### Expected behavior

Additional weight should be zero.

### Environment

React Hot Loader version: 3.0.0.beta-7

**Comment by chrisblossom** [comment]
@drcmda did you find the issue?

**Comment by starandtina** [comment]
@drcmda @chrisblossom  I had encountered the same issue with you, any comments?
