### ISSUE TITLE
Hard reloading instead of hot loading

### ISSUE THREAD

**Issue by natew** [gaearon/react-hot-loader#58]
Not sure if this is related to #55 because I did recently split out my app into separate modules and so it's symlinking pieces of the app. I've also made quite a lot of changes though lately so not sure where to start here.

Here's a screen of my setup, the dirs with the extra icon are symlinked:

![screen shot 2015-01-11 at 2 07 55 pm](https://cloud.githubusercontent.com/assets/12100/5697110/4a62d2dc-999c-11e4-8711-080844681bb4.png)

I'm running my server in a separate repo, which symlinks in it's dependencies into server_modules in the app folder.

What I see happening in the app now is the "Reloading..." comes up just fine. Before it would even show the "reloaded" message but nothing would change. But recently it started refreshing the browser instead, no matter what I change. So I see Reloading... then browser refreshes.

I had tried the NewWatching plugin, but reverted that. Other than that not sure whats new. Using 1.0.7 of react-hot-loader.

**Comment by gaearon** [comment]
Does this happen with 1.0.6?

**Comment by gaearon** [comment]
By the way, to avoid refreshing completely (even when you have syntax errors), use hot/only-dev-server and NoErrorsPlugin. This setup is shown in react-hot-boilerplate.

But let's figure out the main issue first..

**Comment by gaearon** [comment]
If you don't feel comfortable sharing the source we can arrange a 15min TeamViewer session to figure this out once and for all. Ping me at email or on Skype (dan.ex) if you'd like to do that.

**Comment by natew** [comment]
Would love to do a screen share because I'd bet you have some good insight into how I'm structuring things as well. I'll add you on Skype.

**Comment by gaearon** [comment]
btw you can give it another go with 1.1.0, `node_modules` issues should be fixed

**Comment by gaearon** [comment]
Fixed with 1.1.1
