### ISSUE TITLE
Hot updates not apply component which wrapped by redux connect

### ISSUE THREAD

**Issue by gcfeng** [gaearon/react-hot-loader#585]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description
Hot updates not apply component which wrapper by redux connect. But if I change the component second time, it will apply the updates.

### Expected behavior
When change the component, it will apply hot updates.

### Actual behavior
It only updates when change even times.

### Environment
- react: 15.5.4
- react-router: 4.1.1
- redux: 3.6.0
- react-redux: 5.0.5

React Hot Loader version: 3.0.0-beta.7

**Comment by moustacheful** [comment]
I'm having a similar issue as you describe, not 100% if it's the same though, as in my particular case the redux-connected component will not update by itself ever.

Redux-connected components will not update until their state changes explicitly, whereas vanilla components will update just fine.

**Comment by iframeskills** [comment]
Having the same exact issue; if not wrapped by connect method of react-redux hot module reloading works perfectly.  
When react-redux connect method is used, HMR logs say the app is updated but the components do not actually update at all.

**Comment by Mr-Binary** [comment]
Any updates on this?
I have the same issue.
and posted an issue here: https://github.com/reactjs/react-redux/issues/787
Has the steps to reproduce it.

**Comment by neoziro** [comment]
I am just starting on the project. I have not yet had time to investigate it.

**Comment by Mr-Binary** [comment]
@neoziro Thanks for the reply. My bad, I forgot to wrap the `<AppContainer>`..... Now everything works. But still curious, when I don't add the `<AppContainer>`, how could the `<App>` get the HMR?

**Comment by neoziro** [comment]
@Mr-Binary the AppContainer just force a reload of the application. The core of this package is to register every classes and hot replacing them.

**Comment by neoziro** [comment]
@Mr-Binary so I can close this issue?

**Comment by Mr-Binary** [comment]
@neoziro Thanks for the answer. However, I don't know if my case matches the OP's case or not.
 Seems so according to the symptoms. Consider it's already been a long time without any code to reproduce the issue, I think you can safely close this :)
