### ISSUE TITLE
Infinite Page Reload on Change

### ISSUE THREAD

**Issue by MrDesjardins** [gaearon/react-hot-loader#586]
### Description

When using React-Hot-Loader, the first render is good, but any subsequent change create an infinite refresh of the browser.

### Expected behavior

I expect that the component is reloaded without refreshing the page infinitely.

### Actual behavior

Webpack build the code once and the browser reload infinitely.

### Environment

React Hot Loader version: 
    "webpack": "^2.6.1",
    "webpack-dev-middleware": "^1.10.2",
    "webpack-dev-server": "^2.4.5",
    "webpack-hot-middleware": "^2.18.0",
    "react-hot-loader": "^3.0.0-beta.7",

Run these commands in the project folder and fill in their results:

1. `node -v`:  7.4.0
2. `npm -v`: 4.0.5

Then, specify:

1. Operating system: Windows 10
2. Browser and version: Chrome 59

### Reproducible Demo

I create a simple project here : https://github.com/MrDesjardins/TypeScriptReactBoilerplate 

Steps:
1. npm run build
2. npm run server
3. open browser to http://localhost:8080
4. Change a string in HelloComponent.tsx 
5. Step 4 will make Webpack to rebuild
6. Look at the browser, it will infinitely refresh the page (my ram goes up, fan goes crazy)

**Comment by neoziro** [comment]
@MrDesjardins I tried to reproduce it but I can't make it work, I got some errors.

Can you please give a try to [React Hot Loader v4](https://github.com/gaearon/react-hot-loader/tree/next) and tell us if your issue is fixed?

**Comment by neoziro** [comment]
As @theKashey it should be fixed even before v4. I mark it as fixed. Feel free to reopen a new issue if you experience some problems with [v4](https://github.com/gaearon/react-hot-loader/tree/next).
