### ISSUE TITLE
Uncaught TypeError: createProxy is not a function

### ISSUE THREAD

**Issue by hengkx** [gaearon/react-hot-loader#589]
### Description
Uncaught TypeError: createProxy is not a function

### Expected behavior

What you think should happen:

### Actual behavior

What actually happens:

### Environment

React Hot Loader version:3.0.0-beta.7

Run these commands in the project folder and fill in their results:

1. `node -v`:8.1.2
2. `npm -v`:5.0.3

Then, specify:

1. Operating system:windows 7
2. Browser and version:chrome latest

### Reproducible Demo

``` javascript
var React = require('react');
var createProxy = require('react-proxy').default;
// var createProxy = require('react-proxy').createProxy;
var global = require('global');
console.log('createProxy-------');
console.log(createProxy);// Uncaught TypeError: createProxy is not a function
console.log(require('react-proxy').createProxy);// right
```

**Comment by hengkx** [comment]
https://github.com/gaearon/react-proxy

`import { createProxy, getForceUpdate } from 'react-proxy';`

**Comment by nealoke** [comment]
@hengkx this solves my issue but I'm not sure if the ideal solution is adjusting files in the `node_modules` folder after an install. Thoughts?

**Comment by neoziro** [comment]
Should be fixed in v3.
