### ISSUE TITLE
When will be the final v3.0.0 released?

### ISSUE THREAD

**Issue by AlesMenzel** [gaearon/react-hot-loader#591]
When will be the final v3.0.0 released?

**Comment by manubamba** [comment]
is the project dead?

**Comment by skipjack** [comment]
@manubamba yeah idk it kind of seems that way. Unfortunate if it is because the beta has been working great for me, definitely an improvement over `babel-preset-react-hmre`.

**Comment by neoziro** [comment]
Project is not dead! Will try to release v3 soon!
