### ISSUE TITLE
Migration guide for create-react-app seems outdated

### ISSUE THREAD

**Issue by bernatfortet** [gaearon/react-hot-loader#595]
Described migration for create-react-app results in errors.
https://github.com/gaearon/react-hot-loader/tree/master/docs#migrating-from-create-react-app

From fresh install, I followed the instructions from the docs, and when I change a component the app refreshes completely instead of hot-reloading components

Also, it's not said, but it's required to import findCacheDir:
`const findCacheDir = require('find-cache-dir');`

**Comment by ivanwolf15** [comment]
Same issue here.
I removed the options in the babel loader in order to add the query. Then add ```AppContainer``` to the root ```index.js``` including the ```module.hot``` stuff.
It worked for me.

**Comment by jonathanphz** [comment]
Hey @ivanwolf15  can you explain a bit the changes you made to get this to work?

Can you provide the code you changed here? Been dealing with this for days now.

Thanks

**Comment by wangsongiam** [comment]
Hi @jonathanphz If you are still trying to figure this out, I create a repo to show you how. [create-react-app-with-hot-loader](https://github.com/wangsongiam/create-react-with-hot-loader)

**Comment by jonathanphz** [comment]
Hey @wangsongiam thanks so much for this - I was able to figure it out slowly a few days ago. 

BTW - I love your editor. Is that vim using Hyper?

**Comment by wangsongiam** [comment]
@jonathanphz thanks! It's Neovim on iTerm, you can check my [config repo](https://github.com/wangsongiam/dotfiles) for all the details.

**Comment by jonathanphz** [comment]
Just tried following along the docs in here: https://github.com/gaearon/react-hot-loader/tree/master/docs#migrating-from-create-react-app

Using a fresh install of CRA and react-hot-loader@next.

When attempting to yarn start I get this error:`Provided options and query in use
error Command failed with exit code 1.`

**Comment by neoziro** [comment]
@jonathanphz if you fixed it can you please update the documentation?

**Comment by Grimones** [comment]
Same issue here. Using latest RHL and CRA.
followed https://github.com/gaearon/react-hot-loader/tree/master/docs#migrating-from-create-react-app
still reloads page.
I Also have cloned https://github.com/wangsongiam/create-react-with-hot-loader and made fresh install. Added simple counter and the counter resets on code change, obviously page refreshes.

Tried to use `
    require.resolve('webpack-dev-server/client') + '?/',
    require.resolve('webpack/hot/dev-server'),
`

In console shows `[HMR] Waiting for update signal from WDS...` but no `[WDS] Hot Module Replacement enabled.`
I think this is better than silence from HMR when using `require.resolve('react-dev-utils/webpackHotDevClient')`. Or it isn't related to this?

**Comment by Grimones** [comment]
@neoziro 
Hi! You can close this issue. I can confirm that current migration guide is working properly with fresh CRA.
Here is the repository https://github.com/Grimones/cra-rhl
The diff
https://github.com/Grimones/cra-rhl/commit/f9f7b67568f6e8d9f3a8d3293422a9f4d5d2c28a

**Comment by neoziro** [comment]
@Grimones thanks, can you please review it for [v4](https://github.com/gaearon/react-hot-loader/tree/next#migrating-from-create-react-app)?

**Comment by Somebi** [comment]
Problem still persists
