### ISSUE TITLE
How to handle exceptions in e.g. render()

### ISSUE THREAD

**Issue by wmertens** [gaearon/react-hot-loader#598]
### Description

When I hot update a component and there is some error in e.g. render(), this causes a whole bunch of React errors to fire and most of the time I need to reload. The redbox only shows sometimes.

### Expected behavior

All errors during hot reload should pop up a Redbox, and in the console there should be the full error so the line numbers can be clicked to go to the source

### Actual behavior

Bunch of react errors. If you have "pause on uncaught exception" enabled, it means a lot of clicking.

### Environment

React Hot Loader version: 3b7

Run these commands in the project folder and fill in their results:

1. `node -v`: 7.10.0
2. `npm -v`: 4.2.0

Then, specify:

1. Operating system: macOS 10.11
2. Browser and version: Chrome 59

### Reproducible Demo

I can make this if the above is not sufficient information.

**Comment by hallaathrad** [comment]
Just realised this has also been the case for me (over what now seems to have been months), except that I never seem to get redbox at all anymore. Is this a removed feature on the latest versions? or maybe my setup has just been broken for a while?

**Comment by neoziro** [comment]
Now we have [Error Boundaries](https://reactjs.org/docs/error-boundaries.html#introducing-error-boundaries)!
