### ISSUE TITLE
Hot reloading doesn't work with iframes

### ISSUE THREAD

**Issue by ccoffey** [gaearon/react-hot-loader#599]
### Description
My application needs to run within the context of an iframe because its a "widget" and it needs JavaScript isolation from the parent page.

### Expected behavior
Hot reloading should work with iframes.

### Actual behavior
Hot reloading just doesn't work but the app still works perfectly and there are no errors.

### Environment
React Hot Loader version: 3.0.0-beta.6 (see first reproducible demo)
node -v: v7.0.0
npm -v: 3.10.8
Operating system: OS X
Browser and version: Chrome Version 58.0.3029.110 (64-bit)

### Reproducible Demos
https://github.com/ccoffey/react-hot-loader-minimal-boilerplate

Also not working with https://github.com/ccoffey/react-hot-boilerplate

**Edit:** Included demos using both react-hot-loader-minimal-boilerplate & react-hot-boilerplate.

**Comment by ccoffey** [comment]
The more I look into this, the more I think its a webpack issue. Closing now because I no longer think this has anything to do with react-hot-loader.

**Comment by theKashey** [comment]
That was nor webpack, nor reac-hot-loader issue. It even was not an issue.

**Comment by devx97** [comment]
Have someone solved this "problem"?
