### ISSUE TITLE
Hot loader does not reload with new react ES6 syntax

### ISSUE THREAD

**Issue by geowarin** [gaearon/react-hot-loader#60]
Hello there,

First, thank you for your amazing tool, it contributed greatly to my love for react!

I just bumped into a small problem though, when I try to use the [new ES6 syntax](http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html) to declare react components, the loader no longer works.

I've cloned the hot-loader-boilerplate repo to help reproduce the issue : 
Here is the [problematic change](https://github.com/geowarin/react-hot-boilerplate/commit/d1e9b843999604f0878e9f1c24a5c79b70ebbe20)

Steps include:
* [Update to react 0.13](https://github.com/geowarin/react-hot-boilerplate/commit/027564a1a48dd11043057518c2c9c7eac4480d6e) => OK
* [Use 6to5 loader to enable ES6 syntax](https://github.com/geowarin/react-hot-boilerplate/commit/21ac85f7294226dc5e3f11fd85e6d97029b0dd2b) => OK
* [Use the new syntax](https://github.com/geowarin/react-hot-boilerplate/commit/d1e9b843999604f0878e9f1c24a5c79b70ebbe20) => broken

I'm not sure what I can do to help, at first glance, your heuristic to identify react components seems to be compatible with ES6.
Do you have any clue why this shouldn't work?

**Comment by gaearon** [comment]
It works with `jsx?harmony`. Probably something 6to5 does when using `class extends` that hot loader doesn't pick up. I'll take a look, thank you for reporting.

**Comment by gaearon** [comment]
Released with `react-hot-api@0.3.4`. I'll bump the dependency in next release but you should (probably?) get the new version by nuking `node_modules/react-hot-loader/node_modules` and running `npm install` again.

**Comment by geowarin** [comment]
The dependency was picked up fine when I re-npm installed the hot loader.
And it works! Many thanks for the very quick response.
