### ISSUE TITLE
Hot loading doesn't work when on sub-subpages

### ISSUE THREAD

**Issue by Neglexis** [gaearon/react-hot-loader#600]
### Description

When viewing a page that is either on root or on a subpage (e.g. / or /about), and making an edit in a component, the component is hot replaced as expected. When viewing a component on a sub-subpage (e.g. /news/updates), the full page reloads after an edit.

### Expected behavior

Only the specific element should change

### Actual behavior

The whole page reloads

### Environment

React Hot Loader version: 3.0.0-beta.7

Run these commands in the project folder and fill in their results:

1. `node -v`: v8.1.1
2. `npm -v`: 5.0.3

Then, specify:

1. Operating system: OS X
2. Browser and version: Chrome

**Comment by neoziro** [comment]
@Neglexis  This should be fixed in [next](https://github.com/gaearon/react-hot-loader/tree/next). Can you please give a try?

**Comment by neoziro** [comment]
I mark it as fixed, feel free to reopen it if you experienced some issues.
