### ISSUE TITLE
Using webpack 'external'?

### ISSUE THREAD

**Issue by viridia** [gaearon/react-hot-loader#607]
I've spent hours trying to get rid of the 'react-hot-loader/patch' warning with no luck. One different thing about my project is that I'm loading react and react-dom from the cloudfront CDN link (since I'm trying to reduce webpack build times to something reasonable) and declaring them as 'external' in my webpack config. However, that means that these two modules execute before my 'main' module.

I do have react-hot-loader/patch listed as the first line in my webpack 'entry' config. However, I don't know whether that's sufficient if there are additional <script> tags in my index.html that come before my main bundle.

Can anyone clarify this for me? It would at least eliminate one variable in my attempt to diagnose this problem.

**Comment by jasonbarry** [comment]
@viridia I just got HMR working using externals. Perhaps ensure that your `devServer.publicPath` is the same as `output.publicPath`?

**Comment by viridia** [comment]
OK that's good to know - it means one less thing to check.

Yeah my devServer uses the same config object as the regular build; only the 'entry' property is changed.

**Comment by viridia** [comment]
Well, I am stumped. I've been trying to get react-hot-loader to work in my project for about 4 months now, and I've checked and double-checked everything I can think of. I've got the right babel plugins, the right entry points in the webpack config (as far as I can tell), using AppContainer and module.hot, and I still get the same "It appears that "react-hot-loader/patch" did not run immediately before the app started" error. It used to work really well, but about 4 months ago it broke. I've been able to get react-hot-loader to work in other, smaller projects but not this one.

**Comment by neoziro** [comment]
@viridia it's weird, any update on it?

**Comment by viridia** [comment]
Yeah, I figured it out, and it has nothing to do with 'external'. Basically I wanted to be able to import my project sources using absolute paths (import Stuff from "components/Stuff.jsx") and so I added a resolve.modules entry for my source files:

```
resolve: {
  modules: [
    path.resolve(__dirname, 'src'),
    path.resolve(__dirname, 'node_modules'),
    path.resolve(__dirname, 'src/media/icons'),
  ],
},
```

Turns out this is what broke react-hot-loader. Removing the 'src' entry and everything works fine.

**Comment by Flamingo09** [comment]
> Yeah, I figured it out, and it has nothing to do with 'external'. Basically I wanted to be able to import my project sources using absolute paths (import Stuff from "components/Stuff.jsx") and so I added a resolve.modules entry for my source files:
> 
> ```
> resolve: {
>   modules: [
>     path.resolve(__dirname, 'src'),
>     path.resolve(__dirname, 'node_modules'),
>     path.resolve(__dirname, 'src/media/icons'),
>   ],
> },
> ```
> 
> Turns out this is what broke react-hot-loader. Removing the 'src' entry and everything works fine.

I tend to get stuck with weird errors, but your solution saved me hours. I was about to give up the idea of using externals :-) . Thanks a ton.
