### ISSUE TITLE
Hot reload of React 16 PureComponent does not work

### ISSUE THREAD

**Issue by defr0zen** [gaearon/react-hot-loader#609]
### Description

PureComponents from React 16 do not seem to be re-rendered. The hot reloading does happen, however, the component itself is not re-rendered. 
Is there anything special needed for React 16?

### Environment

React Hot Loader version: 3.0.0-beta.7

### Reproducible Demo
- git clone https://github.com/defr0zen/react-hot-boilerplate
- git checkout next
- npm i
- npm start
- Change the contents in App.js -> it is not re-rendered. If you change the App from PureComponent to Component, then everything works fine.

See the following commit for demo changes:
https://github.com/defr0zen/react-hot-boilerplate/commit/dcb445e552f959ce00c129a7b3c94a89311fb7c3

**Comment by leidegre** [comment]
@defr0zen have you tried `beta.5`?

**Comment by defr0zen** [comment]
Thanks, works excellent for with beta.5
