### ISSUE TITLE
Component loses state if default export isn't used

### ISSUE THREAD

**Issue by Aranir** [gaearon/react-hot-loader#612]
I used the following boilerplate:

https://github.com/Glavin001/react-hot-ts

But the same configuration didn't work in my own application and it took me quite some time to figure out where the root cause was.

if the export of the App is done without the default, the component loses its state after hot reloading:

`export default class App extends React.Component<{}, { count: number}> {`

and instead use:

`export  class App extends React.Component<{}, { count: number}> {`

of course the import statement has to be modified in `index.tsx`

from:
`import App from "./App";`

to

`import {App} from "./App";`

It is unclear for me why the change from a named export to a default export should cause the losing of state of the component.

Any idea what the root cause of this could be?

**Comment by theKashey** [comment]
@Aranir - the problem is hidden inside babel plugin. It just did not understand something.
Check sources after babel - file will be appended by hot-loader stuff. And if not - you have to modify your code.
(or fix babel plugin, but this way is harder)

**Comment by Aranir** [comment]
@theKashey thank you for your explanation!

So I will close this issue as its not really related to the react-hot-loader directly.
