### ISSUE TITLE
React-hot-loader doesn't apply changes with Draft.js.

### ISSUE THREAD

**Issue by MikeDevice** [gaearon/react-hot-loader#613]
### Description

I've made a basic setup with [Draft.js](https://github.com/facebook/draft-js) using [CompositeDecorator](https://draftjs.org/docs/advanced-topics-decorators.html#compositedecorator). I pass there my `strategy` and `component`. And when I edit code in `strategy`, browser doesn't show my edits. Only after page refreshing I can see these changes.

Here is a small code example. Every line what you type in editor is logged in console. And if remove or comment line with `console.log()`, you see changes are not applyed. `console.log()` is still working. Only after page refreshing text won't be output to the console.

```jsx
import React, { Component } from 'react';
import { Editor, EditorState, CompositeDecorator } from 'draft-js';

function HandleSpan({ children }) {
  return <span>{children}</span>
}

function handleStrategy(contentBlock, callback) {
  const text = contentBlock.getText();

  // comment this line and type some text in editor
  console.log(text);

  callback(0, 1);
}

export default class MyEditor extends Component {
  constructor(props) {
    super(props);

    const compositeDecorator = new CompositeDecorator([
      {
        strategy: handleStrategy,
        component: HandleSpan,
      },
    ]);

    this.state = { editorState: EditorState.createEmpty(compositeDecorator) };
    this.onChange = editorState => this.setState({editorState});
  }

  render() {
    return (
        <Editor
          editorState={this.state.editorState}
          onChange={this.onChange}
        />
    );
  }
}
```

### Expected behavior
I'd like I do not have to do refresh page and see all changes immediately with hot reloading

### Actual behavior
Hot reloading doesn't apply changes

### Environment

**React Hot Loader version**: 3.0.0-beta.7
**Node version**: 7.10.0
**NPM version**: 4.2.0

**Operating system**: Ubuntu 16.04
**Browser and version**: Google Chrome 59.0.3071.115

### Reproducible Demo

Here is working [DEMO](https://github.com/MikeDevice/react-hot-loader-and-draft-js-example)

**Comment by theKashey** [comment]
This is _expected behavior_ as long `hot reloading` just updates a component. 
Update. Not unmount, destroy, create a new one, and mount a new one.

How to fix - move initialization code off component. And it is possible as long it does not depend on the component.

```js
import React, { Component } from 'react';
import { Editor, EditorState, CompositeDecorator } from 'draft-js';

function HandleSpan({ children }) {
  return <span>{children}</span>
}

function handleStrategy(contentBlock, callback) {
  const text = contentBlock.getText();

  // comment this line and type some text in editor
  console.log(text);

  callback(0, 1);
}


 const compositeDecorator = new CompositeDecorator([
      {
        strategy: handleStrategy,
        component: HandleSpan,
      },
    ]);

const editorStateDecorator = EditorState.createEmpty(compositeDecorator) ;

export default class MyEditor extends Component {
  constructor(props) {
    super(props);

    this.onChange = editorState => this.setState({editorState});
  }

  render() {
    return (
        <Editor
          editorState={editorStateDecorator}
          onChange={this.onChange}
        />
    );
  }
}
```

**Comment by MikeDevice** [comment]
Yes, I understand what you talking about. Thanks! But I think it's not a good idea to change source code because hot loader not working. I think, it's not a good way to adjust the code for developer tools.

**Comment by theKashey** [comment]
@MikeDevice - there is no powerfull Reflection tools in Javascript to perform magical updates. Hot Loader is just a script. It has limits. You have to keep them in mind.

There are others ways to solve this issue, for example force HotLoader to remount this Component, but they all require some actions from you.
