### ISSUE TITLE
When an error is thrown on component update, the page fully reloads

### ISSUE THREAD

**Issue by yachaka** [gaearon/react-hot-loader#618]
Hi,

If I introduce an error in my component, the console output is
`[HMR] Cannot apply update. Need to do a full reload!`
and below, the error.

As far as I understand, [this is a known problem](https://github.com/gaearon/react-hot-loader/blob/master/src/AppContainer.dev.js#L41).

Is there any updates regarding this? How can I get the error box to pop up on component update error?

**Comment by theKashey** [comment]
Not related to React world. This is pure webpack/js related stuff.
Do you forget to `module.hot.accept` changes. If you extract some code as a common chunks plugin - you also have to accept changes from it`s main entry.
See https://medium.com/@antonkorzunov/how-to-hot-load-react-component-in-7-days-part-1-webpack-d8b77eea61eb

**Comment by neoziro** [comment]
Not related to this project.
