### ISSUE TITLE
How to use Hot Loader with git submodules

### ISSUE THREAD

**Issue by alex-mironov** [gaearon/react-hot-loader#622]
### Description
I need to implement HOT reloading of source files which are stored outside `/src` directory, but on the same level - `/shared` (this folder actually added as git submodule).
_What you are reporting:_
```
|__shared
|__src
|__package.json
```
With current folder structure HOT reload is not working for the code in `/shared`.

Config includes:
**webpack**
```
entry: [
  "eventsource-polyfill",
  "webpack-hot-middleware/client?reload=true",
  path.join(process.cwd(), "src/app.js"),
]
```
**.babelrc**
```
    "presets": [
      [
        "latest",
        {
          "es2015": {
            "modules": false
          }
        }
      ],
      "react",
      "stage-0"
    ],
    "plugins": ["react-hot-loader/babel"],
```

### Expected behavior
From my understanding, the hot reload should work for `/shared` folder as well. But it doesn't.
What you think should happen:
I assume I need to tweak either `hot.accept()`  or `module.loaders`

**Comment by theKashey** [comment]
This is HRM related issue, not RHL. You should go the webpack or webpack-dev-server repos.
But, long story short - you should not use `webpack-hot-middleware` - just add --hot to webpackdev-server startup command.

**Comment by alex-mironov** [comment]
@theKashey thank you for a prompt answer and sorry for posting it here :(
ps: it doesn't work with `webpack-dev-server` either. I updated the script to use 
`"cross-env NODE_ENV=development webpack-dev-server --port 3000 --hot --host 0.0.0.0 --config ./internals/webpack/webpack.dev.babel.js",`  and removed `  "webpack-hot-middleware/client?reload=true",` from `entry`. it still doesn't work.. will dig into it

**Comment by theKashey** [comment]
@alex-mironov - add webpack.NamedModulesPlugin(), and do not forget to `module.accept` the changes.
