### ISSUE TITLE
issue with react-hot-reloader when updating to react v16

### ISSUE THREAD

**Issue by Pau1fitz** [gaearon/react-hot-loader#623]
I am trying to update my project to use `react": "16.0.0-beta.5`.

I was previously using `"react": "15.5.4"`.

I have updated  `"react-hot-loader": "^3.0.0-beta.7"` from version `1.3.1`

I am seeing the following error message in my terminal

```
/Desktop/project/node_modules/loader-runner/lib/loadLoader.js:35 
throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
Error: Module '/Desktop/project/node_modules/react-hot-loader/index.js' is not a loader (must have normal or pitch function)
```
I cannot find any guidelines on how to fix this.

**Comment by theKashey** [comment]
@Pau1fitz - not enough information. Please show your webpack configuration.
PS: react-hot-loader v3 and v1 is completely different solutions. You should not use any webpack loaders, and use babel plugin instead.

Check the migration guide.

**Comment by leidegre** [comment]
@Pau1fitz been running with React 16 beta.5 for a while now, and it has been working just fine.
