### ISSUE TITLE
module.hot.accept with two arguments .bug the first has been translated twice

### ISSUE THREAD

**Issue by SnowFlowers** [gaearon/react-hot-loader#626]
I took routes for the frist argument
![image](https://user-images.githubusercontent.com/16875486/29658892-2284cbae-88ef-11e7-9200-cb2ac8a18f0a.png).

but after webpack complie.
![image](https://user-images.githubusercontent.com/16875486/29658956-4df4c91a-88ef-11e7-8a5b-db3a2bd8f4ee.png)
the first argument has been copied twice.why?

**Comment by theKashey** [comment]
@SnowFlowers  - webpack (with hot module loading) and  react-hot-loader - are different projects. Nothing similar between them. You should address your question to the webpack community.
