### ISSUE TITLE
Any feedback on home page example?

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#63]
There's a new live demo on [React Hot Loader landing page](http://gaearon.github.io/react-hot-loader/), but it has some problems:

* It's too long;
* Beginners don't understand the difference between this and [examples on React homepage](http://facebook.github.io/react/).

@kkga suggested we replace the live demo with a new, shorter video, with some simple code / UI.

I'd like to keep both actually, but I agree we could use a better, more obvious example that communicates RHL's strengths and workflow better.

Your suggestions are welcome!

cc @chenglou

**Comment by tcoopman** [comment]
I would have both, a very short video to introduce the concept and the live demo to dig in a bit deeper.

**Comment by gaearon** [comment]
I think that can work nicely, and we can make the video default. By the time person gets to the live demo, she knows what the real workflow looks like.

**Comment by chenglou** [comment]
It's all about seeing state preserved across time. The counter demo from the React home page will do. 

Put an explanation of a short comparison and ask them to modify the "Seconds Elapsed" part. Not sure if you'd even need a video with such a simple demo =). Bonus is that if the site's ever available on mobile they could just tap and delete a few letters and see the point.

**Comment by gaearon** [comment]
Very good point, thanks.

**Comment by pburtchaell** [comment]
IMO, the live demo works as straightforward demonstration that clearly explains the purpose of the loader for devs that are familiar with React. But... I also agree with you that someone new to React might not get it just from the live demo. In that case, the video might be useful to them. If you do include a new video, I'd suggest a more concise example < 2 min long.

**Comment by swirlycheetah** [comment]
Somewhat unrelated (sorry!) but I think a good addition to the landing page would be the first paragraph from the getting started page:

'React Hot Loader is a plugin for Webpack that allows instantaneous live refresh without losing state while editing React components.'

I think that's a concise opening statement for those who may be unsure of what exactly they're looking at, which seemed to be a point which came up in the HN thread.

Personally I'd place that under the navigation items above a demo & video.

**Comment by moimikey** [comment]
'twould be interesting to have the realtime output of the HMR similar to sokra's demo here: http://webpack.github.io/example-app/
