### ISSUE TITLE
contains file path in production build with webpack

### ISSUE THREAD

**Issue by foisonocean** [gaearon/react-hot-loader#630]
### Description

It seems React Hot Loader contains all my file path in production build.
![2017](https://user-images.githubusercontent.com/15059605/29959763-7ce9a3d4-8f2b-11e7-8aa8-cfd65039fa49.png)

### Expected behavior

Shouldn't contains file path.

### Environment

React Hot Loader version: 3.0.0-beta.7
Webpack Version: 3.5.5

Run these commands in the project folder and fill in their results:

1. `node -v`: v8.4.0
2. `yarn -v`: v0.27.5

**Comment by theKashey** [comment]
@foisonocean - do you define current envoroment?
```
defineConstants({
  'process.env.NODE_ENV': environment,
});
```

**Comment by foisonocean** [comment]
@theKashey I use webpack.DefinePlugin:
```js
new webpack.DefinePlugin({
  'process.env': {
    'NODE_ENV': JSON.stringify('production'),
  },
}),
```

**Comment by theKashey** [comment]
And you also have to `not use` babel plugin. 
Unfortunately, there is no simple rule provided, to destroy registers by uglify. 
It exists in webpack plugin, and one should port it into the babel one.

**Comment by foisonocean** [comment]
@theKashey I think `react-hot-loader/babel` plugin is auto removed in production mode.

**Comment by theKashey** [comment]
@foisonocean - by whom? There is no magic(yet) - you have to remove it by yourself.

**Comment by foisonocean** [comment]
@theKashey 
https://github.com/gaearon/react-hot-loader/blob/7ab86ed2daeffe334e453456f25a9a0b27fadec6/src/babel/index.js#L96-L99

**Comment by theKashey** [comment]
But do you have it as process.env.NODE_ENV or you just define a variable with such name in the target script?
PS: You can get rid of RHL code in production by defining
```js
new webpack.DefinePlugin({
  '__REACT_HOT_LOADER__': undefined
}),
```
And next uglify will destroy blocks. (I hope)

**Comment by foisonocean** [comment]
@theKashey 
This is my npm build script:
```json
{
  "scripts": {
    "build": "cross-env NODE_ENV=production webpack --config webpack.config.prod.js"
  }
}
```

**Comment by theKashey** [comment]
@foisonocean - double checked - there is no way to contain RHL into production bundle. Are you sure that you are not getting these codes from third party sources?
Can you share a whole webpack config?

**Comment by foisonocean** [comment]
@theKashey 
```js
// webpack.config.base.js
const { resolve } = require('path');
const webpack = require('webpack');

const config = {
  entry: {
    app: [
      './src/index.jsx',
    ],
  },

  output: {
    path: resolve(__dirname, './dist'),
    publicPath: '/dist/',
  },

  module: {
    rules: [
      {
        test: /\.jsx?/i,
        use: [
          'cache-loader',
          'babel-loader',
        ],
        exclude: /node_modules/,
      },
      {
        test: /\.scss/i,
        use: [
          'style-loader',
          'css-loader',
          'sass-loader',
        ],
      },
    ],
  },

  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify(process.env.NODE_ENV),
      },
    }),

    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks (module) {
        // a module is extracted into the vendor chunk if...
        return (
          // it's inside node_modules
          /node_modules/.test(module.context)
        );
      }
    }),
  ],
};

module.exports = config;
```

```js
// webpack.config.prod.js
const { resolve } = require('path');

const webpack = require('webpack');
const merge = require('webpack-merge');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');

const baseConfig = require('./webpack.config.base');

const config = merge(baseConfig, {
  devtool: false,

  output: {
    filename: '[name].[chunkhash:8].js',
  },

  module: {
    rules: [
      {
        test: /\.css/i,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: {
            loader: 'css-loader',
            options: { minimize: true },
          },
        }),
      },
    ],
  },

  plugins: [
    new webpack.optimize.ModuleConcatenationPlugin(),

    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false,
      },
      output: {
        comments: false,
      },
      sourceMap: false,
    }),

    new ExtractTextPlugin({
      filename: '[name].[contenthash:8].css',
      allChunks: true,
    }),

    new HtmlWebpackPlugin({
      filename: resolve(__dirname, './dist/index.html'),
      template: 'index.html',
      inject: true,
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeAttributeQuotes: true,
      },
      chunksSortMode: 'dependency'
    }),
  ],
});

module.exports = config
```

NPM build scripts:
```json
{
  "scripts": {
    "build": "cross-env NODE_ENV=production webpack --config webpack.config.prod.js"
  }
}
```

**Comment by theKashey** [comment]
Just try to remove a 'cache-loader'. According to the sources it should respect ENV, but I cant see any other reason (and latest babel-loader has internal cache).

**Comment by foisonocean** [comment]
@theKashey 
Thanks. I solved my problem by remove `cache-loader` in production mode.

**Comment by dmnsgn** [comment]
I just hit a similar issue where, although using webpack `mode: production`, the bundled file would contain file paths and  the babel wrapping template for pretty much every module, creating a significant increase in build size:

https://github.com/gaearon/react-hot-loader/blob/e6e4dd7337a6fc3579e85b1cb487a0a5e892f351/src/babel.dev.js#L36-L54

I removed `cache-loader` entirely (relying on babel-loader cacheDirectory option) to solve this issue but it is kind of a hack.
