### ISSUE TITLE
No reason to re-render required root?

### ISSUE THREAD

**Issue by ipostol** [gaearon/react-hot-loader#632]
Hello, why in docs written to render new required element by hot changes?
This my code and he working on many project and nodejs versions
```js
...
import Root from './components/Root';

const renderApp = () => {

  render(
    <AppContainer>
      <Root store={store} history={browserHistory} />
    </AppContainer>,
    dest,
  );

};

renderApp();

if (module.hot) {

  module.hot.accept('./components/Root', () => {

    // eslint-disable-next-line
    require('./components/Root');
    renderApp();

  });

}
```

you need only again require you root (for some magic) for webpack and re-render prev required root component

**Comment by theKashey** [comment]
@ipostol - not sure I understood you, but your code is correct for webpack < v3.

**Comment by ipostol** [comment]
from my package.json > `"webpack": "^3.5.5"`

**Comment by theKashey** [comment]
@ipostol - for webpack 3 you can not re-require component, but you have to re-render Application to trigger component replacement.
