### ISSUE TITLE
Hot Reload Indicator

### ISSUE THREAD

**Issue by noahjohn9259** [gaearon/react-hot-loader#633]
It would be nice if have an option or action creator in  adding a loading indicator.

**Comment by neoziro** [comment]
You can follow the loading progression in console. Usually you have it opened when you develop. I think this is not useful to add a visual indicator on the page.

**Comment by peteruithoven** [comment]
That's an assumption?
If I'm working on style (css etc) I don't need the console to be open and
or I'm using a different panel.
