### ISSUE TITLE
Babel "env" preset breaks RHL

### ISSUE THREAD

**Issue by ChemicalRocketeer** [gaearon/react-hot-loader#635]
### Description

I was struggling with this for hours, all my settings were exactly the same but I couldn't make it load in my changes. And then I realized I was using "env" and the react-hot-loader-minimal-boilerplate was using "2015". I changed it and it finally worked.

### Expected behavior

It should hot load new changes to the browser

### Actual behavior

It says in chrome's dev console that it updated, but react either doesn't re-render at all, or re-renders with the old component instead of the new one, because none of the stuff on the screen changes.

### Environment

React Hot Loader version:
next (3.0.0-beta.7)

`node -v`:
v6.9.4
`npm -v`:
3.10.5

Operating system:
Windows 10

Browser and version:
Chrome 60.0.3112.113

### Reproducible Demo

I just took the working project: /wkwiatek/react-hot-loader-minimal-boilerplate and changed "2015" to "env" (and added the env-preset package)

https://github.com/ChemicalRocketeer/react-hot-loader-minimal-boilerplate

**Comment by neoziro** [comment]
I experienced a problem when we do not transpile everything (classes seems to be the problem). But I looked your project and you use "babel-preset-latest" instead of "env". You should use "babel-preset-env" and do not target anything. It should work.
