### ISSUE TITLE
Opt into unmounting for a specific component for some period of time

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#64]
Sometimes I edit `componentDidMount` or `getInitialState` and I actually want the component to re-mount so these changes take effect. After I'm done with these, I want hot reloading to work as usual.

I couldn't think of a non-obtrusive way to do that yet. If opting into this behavior takes more than a few seconds, I'd rather just hit "Refresh".

Things I'm considering is some “magic” property on component, or a “magic” comment in the file a la `/* cold */` that turns on this behavior.

Any ideas?

**Comment by syranide** [comment]
I usually find it easiest to just "go back out and in again" to accomplish that. An interesting possibility would be to remount components if the keys returned from a call to `getInitialState` differs from the initial mount (but then you'd have to track that).

**Comment by gaearon** [comment]
I was thinking about special casing `getInitialState` but that's too fragile. It may return different keys because store state is different.

I think I'll add some sort of magic comment as an experiment and see whether it helps my workflow. Not a big deal.

**Comment by KyleAMathews** [comment]
I just refresh. I find that rhl gets the code into a weird state sooner or later so have to refresh anyways after enough code edits.

**Comment by tcoopman** [comment]
I also refresh. It would be nice though if you could replay all your actions after an refresh:
Seems like a nice use case for https://github.com/gaearon/flux-hot-loader :)

**Comment by sokra** [comment]
Maybe an optional `stateVersion` property on the component. Everytime it changes state is invalid and component should be remounted...

**Comment by patrickheeney** [comment]
New user to react and hot loader. I have been working on getting this setup for about a day. I incorrectly assumed that state changes should have something happen. I kept debugging with the assumption that this was not standard behavior. I would love a troubleshooting guide or some notes somewhere regarding how react-hot-loader handles state and when we should expect it to refresh.

**Comment by gaearon** [comment]
I think I should split `docs/README` into several files in `docs` and add `Troubleshooting` there. Link to `Troubleshooting` from Get Started on landing, main README and from React Hot Boilerplate README. Makes sense?

**Comment by kibin** [comment]
Any updates on this?

**Comment by gaearon** [comment]
I agree refreshing works fine in these cases and couldn't think of a more obvious way to do that. I'm still open to suggestions tho
