### ISSUE TITLE
Different lifecycle methods order with React 16

### ISSUE THREAD

**Issue by eliseumds** [gaearon/react-hot-loader#640]
### Description

I'm seeing React lifecycle methods being called in a different order with React 16.

### Expected order

* componentWillUnmount
* componentWillMount
* componentDidMount

### Actual order

* componentWillMount
* componentWillUnmount
* componentDidMount

It looks like it's an [expected behaviour](https://twitter.com/dan_abramov/status/843822280132190208) but it leads to issues with the Redux state when components register themselves on `componentWillMount` (e.g. *redux-form*). Does anyone know how to circumvent that?

### Environment

React version: `16.0.0-rc.3`
React Hot Loader version: `3.0.0-beta.7`

* Node v8.5.0
* NPM 5.4.2
* Operating system: macOS 10.12.6 (16G29)
* Browser and version: Chrome 61.0.3163.91 (Official Build) (64-bit)

**Comment by neoziro** [comment]
@eliseumds I understand the problem but what is the link with react-hot-loader?

**Comment by eliseumds** [comment]
@neorizo I was wondering whether there's a new convention to solve this kind of issue. Should components make sure to register themselves on both `willMount` and `didMount`?

**Comment by neoziro** [comment]
@eliseumds I don't know

**Comment by MAPESO** [comment]
@neoziro If this theme does not reach an end, the best thing would be to close it 😄

**Comment by neoziro** [comment]
I close it because I think it is not related to react-hot-loader

**Comment by borm** [comment]
have similar problem
