### ISSUE TITLE
How to NOT use @next

### ISSUE THREAD

**Issue by bradennapier** [gaearon/react-hot-loader#644]
As far as I can tell all of the tagged updates are super old and I dont see a branch @next on github.  you can not use @next with flow-typed or it breaks the entire app.  

The latest version appears to be the beta .7 but that is a year old or so whereas the same version in master is a few days old.  

What does @next install?

**Comment by neoziro** [comment]
The next version is the beta 7, I started working on the project two weeks ago and I haven't release yet. I think we will release a v4 including React 16 support.
