### ISSUE TITLE
HotContainer is undefined

### ISSUE THREAD

**Issue by randomvasya** [gaearon/react-hot-loader#647]
In your migration guide says that i should import HotContainer  from react-hot-loader but last npm package (3.0.0-beta.7 v) still exports AppContainer.

**Comment by colinrcummings** [comment]
Found the same. I'm doing `import { AppContainer as HotContainer } from 'react-hot-loader'` for the time being.

**Comment by neoziro** [comment]
Sorry, the documentation reflected the code in master, not the code in the v3.0.0-beta7. I fixed it.

**Comment by colinrcummings** [comment]
Are folks married to the name `AppContainer` here? In Redux applications, I sometimes have a top-level `App` component that, after being connected to the store via `react-redux`, is named `AppContainer` by way of convention. While this connected `App` component isn't imported in the `app.js` entry point where HMR is configured (`Root` is), it is imported one level down in the `Root` component where it's wrapped inside the `Provider`.  `HotContainer` feels cleaner in this respect. Thoughts?

**Comment by randomvasya** [comment]
It does not matter what the container will be called. The main thing is that the description (in this case - the migration manual) should clearly describe this and contain only up-to-date information. If I do not like the name, I use `import { member as alias } from "module-name";`
