### ISSUE TITLE
Hot reloading not reliable - needs multiple file changes to trigger

### ISSUE THREAD

**Issue by BerndWessels** [gaearon/react-hot-loader#659]
### Description

What you are reporting:

Bug - `react-hot-loader` often doesn't hot reload right away - really annoying behavior.

### Expected behavior

What you think should happen:

Changing a file and saving it should trigger a hot-reload.

### Actual behavior

What actually happens:

Most of the time the first change actually works and hot reload happens. But after that it often requires to change and save a file multiple times before a hot-reload actually happens.

This makes hot-reloading feel very unreliable and painful.

### Environment

React Hot Loader version:

Run these commands in the project folder and fill in their results:

1. `node -v`: `6.11.1`
2. `npm -v`: `5.3.0`

`react-hot-loader` : `3.0.0-beta.7`

Then, specify:

1. Operating system: Windows 10
2. Browser and version: Chrome (any), Firefox (any)

### Reproducible Demo

Happens in all projects with `react-hot-loader 3`, even the 'official' ones:

https://github.com/gaearon/react-hot-boilerplate
https://github.com/gaearon/react-hot-boilerplate/issues/136

https://github.com/wkwiatek/react-hot-loader-minimal-boilerplate

**Comment by neoziro** [comment]
This is an issue related to Webpack and not to React Hot Loader, it can also be related to your filesystem watcher.
