### ISSUE TITLE
Does not output warnings on propTypes

### ISSUE THREAD

**Issue by fbm-static** [gaearon/react-hot-loader#66]
Reproduce:

1. Do not add a `propTypes` initially.
2. Add a` propTypes` which triggers a hot reload
3. No warnings outputted on the browser console

**Comment by gaearon** [comment]
I'm not *really* sure we can do that, but worth a try.

**Comment by gaearon** [comment]
Gonna be fixed when RHL switches to use [React Hotify](https://github.com/gaearon/react-hotify). Closing the issue for now, as it's fixed in Hotify. We might switch in a month or two.

**Comment by fbm-static** [comment]
Can't u close the issue, when it's already fixed? You  might forget this issue or something :see_no_evil:

**Comment by gaearon** [comment]
It *is* fixed, but in another project. RHL is going to switch to using this project as the engine later. I don't plan to fix it inside RHL itself, so it is non-actionable here.

**Comment by fbm-static** [comment]
k
