### ISSUE TITLE
Is it the right practice to import 'react-hot-loader' even in production code?

### ISSUE THREAD

**Issue by sahil290791** [gaearon/react-hot-loader#661]
### Description

I am new to webpack and have recently enabled hot reloading. I have one concern, for hot reload to work in dev we need to do the following changes:

```
// main.js
import React from 'react'
import ReactDOM from 'react-dom'
import { AppContainer } from 'react-hot-loader'
import App from './containers/App'

ReactDOM.render(
  <AppContainer>
    <App/>
  </AppContainer>,
  document.getElementById('root'),
)

// Webpack Hot Module Replacement API
if (module.hot) {
  module.hot.accept('./containers/App', () => { render(App) })
}
```
I have the following concerns:

- Now because we have done this change for dev purpose will it affect production code as we do not  need this additional `AppContainer` component? 
- Will this be included in the final bundle?

### Expected behavior

I think this is not needed in production code plus this should not increase the bundle size.

### Environment
React Hot Loader version: 3.0.0
1. node : v7.10.1
2. npm : 4.2.0
3. Operating system: MacOS

**Comment by neoziro** [comment]
We are taking care of not adding code in production, the goal is to simplify setup for end users.

If you do not want to include it in production, you can do it by your own :

```js
if (NODE_ENV === 'production') {
 ...
}
```

**Comment by sahil290791** [comment]
@neoziro will it break anything if included in production? Please correct me if I am wrong, I can see that this depends on `module.hot`. Does it read this from webpack config?

**Comment by neoziro** [comment]
@sahil290791 yes `module.hot` is Webpack stuff

It will not break anything if you include it in production. The only thing to do is to build your project with `NODE_ENV=production`, you can follow [Webpack environement guide](https://webpack.js.org/guides/production/#specify-the-environment).
