### ISSUE TITLE
Handle arrow function closure

### ISSUE THREAD

**Issue by neoziro** [gaearon/react-hot-loader#662]
```js
class MyComponent extends React.Component {
  constructor(props) {
    super(props)
    this.foo = () => { console.log(props.foo) }
}
```

This type of code breaks in v3.

https://github.com/gaearon/react-hot-loader/issues/660#issuecomment-335722039

**Comment by vorlov** [comment]
Same for me

**Comment by switz** [comment]
I fixed this for the time being by locking the package version to `3.0.0-beta.7`.

**Comment by neoziro** [comment]
@switz for now it is the best solution

**Comment by neoziro** [comment]
Thinking about reverting #464, since we do not have any solution to reload constructor without re-instantiating component.

**Comment by neoziro** [comment]
My

**Comment by theKashey** [comment]
```js
class MyComponent extends React.Component {
  onLoad = () => this.setState({loading: true});
  
  componentDidMount() { onLoad(); }
}
```
This code will not work, cos `this` in onLoad and the actual `this` are different.

**Comment by iEchoic** [comment]
This is happening to me as well. @switz' fix does work, but that version does not have React 16 compatibility, so we can't take that version either. Any suggestions to fix this on React 16?

**Comment by neoziro** [comment]
I think handling arrow functions is one of the biggest issue in React Hot Loader, this is mostly relative to Babel transform and React Proxy. I am thinking about transforming this project into a Lerna project (see #496) to be able to easily fix big issue like this one.

@theKashey I think we should plan a meeting to discuss about the project. Also you should be a collaborator. I will ping @gaearon about that. Do you know a good place to talk about a project between contributors? A Slack?

**Comment by theKashey** [comment]
Yep, @gaearon should be involved, cos one(current) solution for RHL is to implement a magic-proxy to hide the proxied component change from React. 
But the second, may be the better, solution is to add some magic into React, to enable hot-replace for component. Using a key prop, or some fiber/reconciliation magics..
Fighting with arrow functions (actually - fighting with language itself) is like fighting with wind mills. Just endless.
PS: Slack, Stride, Gitter, Telegramm – they are all good enought. The only problem is the time difference between UK/France and Australia.

**Comment by neoziro** [comment]
This is now fixed in [React Hot Loader v4](https://github.com/gaearon/react-hot-loader/tree/next/).
