### ISSUE TITLE
Hot swapping between a stateless component (arrow) and class causes a crash

### ISSUE THREAD

**Issue by adipascu** [gaearon/react-hot-loader#664]
### Description

Hot swapping between a stateless component (arrow function) and class causes a crash.
When switching from a class to a stateless component the error is:
```TypeError: Cannot convert undefined or null to object```
When switching from a stateless component to a class the error is:
```Uncaught Error: _default(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.```

### Environment

1. React Hot Loader version: 3.0.0
1. `node -v`: v8.5.0
2. `npm -v`: 5.4.2

1. Operating system: macOS 10.12.6 (Sierra)
2. Browser and version: Chrome 61.0.3163.100

### Reproducible Demo

URL: https://github.com/adipascu/React-Hot-Loader-crash-mvp

#### Steps to reproduce:

- Install dependencies with npm i
- Run the project with npm start
- Visit http://localhost:8080/ using a browser
- Follow instructions in [swap-me.jsx](https://github.com/adipascu/React-Hot-Loader-crash-mvp/blob/master/swap-me.jsx) to crash the HMR
- The error is visible in the browser dev tools

**Comment by theKashey** [comment]
This is issue for react-proxy. PrototypeProxy is bound to the first realisation.
```js
if (InitialComponent.prototype && InitialComponent.prototype.isReactComponent) {
```
And no one expects a change here.

**Comment by neoziro** [comment]
I tested it and it is now fixed in [React Hot Loader v4](https://github.com/gaearon/react-hot-loader/tree/next).

**Comment by theKashey** [comment]
(for ES6) you can switch from class to a function, but you cant switch from function to a class - `first` constructor is sealed during initialization.
Should not work. Easy to make it work without error but with a state loss (recreate ProxyComponent on type change).

**Comment by neoziro** [comment]
@theKashey I tested it but not in modern environment. You think there is still a bug in modern? It is easy to test it using examples.

**Comment by theKashey** [comment]
If you will evolve functional component it will copy over all methods, but __not a constructor__.
It will still inject methods, created in a constructor, but same for all instances.

This is commonly ok, but not always. For react components will work just only React injects some things (this.updater, for example) by itself.

**Comment by neoziro** [comment]
@theKashey if it is an edge cases it is OK for me. But having an error and breaking the application is not OK.

**Comment by neoziro** [comment]
This problem is solved, I tested it and we do not have any error. Of course constructor and methods could have some issues but it doesn't break all application.
