### ISSUE TITLE
Best practice: npm install react-hot-loader --save or --save-dev?

### ISSUE THREAD

**Issue by sachinrekhi** [gaearon/react-hot-loader#675]
Apologies for the basic question, but I just upgraded react-hot-loader to 3.1.1 from 1.3.1 and followed the directions on the Getting Started Guide. And as such, I now have import { AppContainer } from 'react-hot-loader' in my index.js.

Previously when I installed react-hot-loader, I did it with --save-dev and saved it as a devDependency.

But it seems now with the latest version since I'm importing AppContainer in my index.js, I have to install with --save and have it as part of my main dependencies.

Is this the recommended best practice? Or should I find a way for the import to exist behind a development flag? Maybe similar to an approach like is typically done with configure-store.dev.js VS configure-store.prod.js for configuring redux stores?

I'm concerned about any potential performance issues as well as any potential increase in bundle size caused in production by including react-hot-loader in my main dependencies.

**Comment by neoziro** [comment]
Yes this is the recommended best pratice. React Hot Loader handles development and production environment by itself. As you can see, [production AppContainer](https://github.com/gaearon/react-hot-loader/blob/master/src/AppContainer.prod.js) is very small and will not increase your build size.

**Comment by neoziro** [comment]
We should document it, because a lot of people are not serene with that.

**Comment by sachinrekhi** [comment]
Took a stab at adding details on this to the README.

**Comment by neoziro** [comment]
@sachinrekhi thanks
