### ISSUE TITLE
Calling accept() w/o parameters

### ISSUE THREAD

**Issue by cblaettl** [gaearon/react-hot-loader#680]
I just upgraded an app to React16 and react-hot-loader v3 w/ react-router v3.
HRM wasn't working until I replaced
```
if (module.hot) {
    module.hot.accept('./views/app/App', () => { render(routes) })
}
```
with
```
if (module.hot) {
    module.hot.accept()
}
```
in my root .jsx file.

Only the affected components are reloading, which is the desired behavior.
Are there any downsides to doing it this way?

**Comment by neoziro** [comment]
If you are not re-rendering the root, changes will not be visible until you manually triggers a new render. `AppContainer` propagates a forceUpdate in all application tree when re-rendered. If not, components are Hot Replaced but not re-rendered, this is the only downside.
