### ISSUE TITLE
Hot reload with styled-components

### ISSUE THREAD

**Issue by GiancarlosIO** [gaearon/react-hot-loader#684]
My question is simple, react-hot-loader works with Styled-components?
I'm trying to create a boilerplate for react + HMR, I finished with the setup and it works fine with components, but when i try to change the styles from any SC it no update the changes.

my webpack config is here:
https://github.com/GiancarlosIO/Django-HMRReact-boilerplate

Edit:
When a change occurred it adds a script-tag in the end of the header-tag, but the styles are not updated.
![screenshot from 2017-10-22 18 17 15](https://user-images.githubusercontent.com/17274950/31867427-49e02966-b755-11e7-8b59-5a23ef43f1d6.png)

That script has the changes that i made, so...
![screenshot from 2017-10-22 18 03 38](https://user-images.githubusercontent.com/17274950/31867513-b63c0020-b756-11e7-889c-f3878d63f6c7.png)

Thanks!

**Comment by neoziro** [comment]
Yes react-hot-loader works with styled-components. The problem could be in your Webpack entry setup, have you tried to remove entry_1 and entry_2? https://github.com/GiancarlosIO/Django-HMRReact-boilerplate/blob/master/webpack.config.js#L9

**Comment by GiancarlosIO** [comment]
@neoziro I try with that but it still can reload the styled components
![styled-bug](https://user-images.githubusercontent.com/17274950/31863030-6a5547b4-b70d-11e7-8dd9-296d04404325.gif)

**Comment by GiancarlosIO** [comment]
I will close this issue because its a bug in styled-components 2.2.1 package. I have to use the 2.2.0

**Comment by neoziro** [comment]
@GiancarlosIO 👍

**Comment by neoziro** [comment]
I experienced same issue, still a problem in styled-components > 2.2.0 very annoying. Follow https://github.com/styled-components/styled-components/issues/1225

**Comment by MrKou47** [comment]
Maybe your shouldn't use `extract-text-webpck-plugin` in the dev environment;

**Comment by GiancarlosIO** [comment]
@MrKou47 mmmm what? :thinking:

**Comment by MrKou47** [comment]
@geco  emmm.... Before I do not know I can not use `extract-text-webpck-plugin` in development environment. So my component's style can't hot reload. Then i remove this plugin and it works ok.
You can see this issue [RHL can't reload currently when i modify component'style used css-module](https://github.com/gaearon/react-hot-loader/issues/687)

**Comment by theKashey** [comment]
Components with static styles just sealed from any changes. As long they are not expected.
I hope they will fix it soon. (one line change)

**Comment by theKashey** [comment]
Resolved: https://github.com/styled-components/styled-components/issues/1225#event-1334523244
