### ISSUE TITLE
I've ripped you off

### ISSUE THREAD

**Issue by johnnyreilly** [gaearon/react-hot-loader#685]
Hey!  Thanks for all your work on react-hot-loader.  I was just trying to get a good example of hot reloading in the ts-loader repository.  After a false start or 2 I opted to take your react-hot-boilerplate and use it as the basis of our example.  My merry plagiarism can be found here:

https://github.com/TypeStrong/ts-loader/tree/master/examples/react-hot-boilerplate

I've left all attributions etc in place and just tweaked for TypeScript / ts-loader purposes. I hope that's okay? Thanks again!

**Comment by theKashey** [comment]
That's the nature of GitHub. Happy forking!

**Comment by johnnyreilly** [comment]
:smile:
