### ISSUE TITLE
Incorrect event handler

### ISSUE THREAD

**Issue by jbraithwaite** [gaearon/react-hot-loader#69]
Having an issue where events aren't firing. In the following test case:

```js
React.createClass({

  handleClick : function(){
    alert('clicked');
  },

  render: function() {
    return (
      <div onClick={this.handleClick}>
        Click Me
      </div>
    );
  }
});
```

If I'm using `react-hot-loader`:

![screen shot 2015-02-07 at 2 44 33 pm](https://cloud.githubusercontent.com/assets/1044105/6094315/ac24c906-aed9-11e4-8cd6-0251ec40223b.png)

If I'm not:

![screen shot 2015-02-07 at 2 44 46 pm](https://cloud.githubusercontent.com/assets/1044105/6094318/babd1d2e-aed9-11e4-958e-83f33e0053c4.png)

**Comment by jbraithwaite** [comment]
I changed the configuration for `WebpackDevServer` to exclude React.

```
    externals: {
      "react": "React",
      "react/addons": "React",
      ...
    }
```

**Comment by gaearon** [comment]
Not sure I'm following you.

The first screenshot looks fine: RHL will wrap your event handlers. They will proxy to the most recent versions of your methods.

Can you reproduce this problem in [React Hot Boilerplate](https://github.com/gaearon/react-hot-boilerplate)? I'm not sure how making React external would help here. In fact RHL needs a [special configuration for external React](https://github.com/gaearon/react-hot-loader/blob/master/docs/README.md#usage-with-external-react).
