### ISSUE TITLE
redux connect hoc causes component to not be accepted by hot reloader

### ISSUE THREAD

**Issue by joriskoris** [gaearon/react-hot-loader#690]
using "react-redux": "^5.0.6" and "react-hot-loader": "^3.1.1"

app.js
```
import React from 'react';
import ReactDOM from 'react-dom';
import { AppContainer } from 'react-hot-loader';

import configureStore from '@/store/configureStore';
import App from '@/containers/App';

const store = configureStore();

const render = (Component) => {
  ReactDOM.render(
    <AppContainer>
      <Component store={store} />
    </AppContainer>,
    document.getElementById('app'),
  );
};

render(App);

if (module.hot) {
  module.hot.accept('@/containers/App', () => { render(App); });
}
```

App.jsx
```
import React, { Component } from 'react';
import { Provider } from 'react-redux';
import PropTypes from 'prop-types';

import Dashboard from '@/components/Dashboard';

// eslint-disable-next-line
class App extends Component {
  render() {
    return (
      <Provider store={this.props.store}>
        <Dashboard />
      </Provider>
    );
  }
}

App.propTypes = {
  store: PropTypes.object.isRequired, // eslint-disable-line
};

export default App;
```

and finally

Component.jsx
```
import React, { Component } from 'react';
import { connect } from 'react-redux';

// eslint-disable-next-line
class Dashboard extends Component {
  render() {
    return (
      <div>dashboard</div>
    );
  }
}

const mapStateToProps = state => ({
  loaded: state.charts.loaded,
});

export default connect(mapStateToProps)(Dashboard);
```

For this setup, editing Dashboard.jsx  causes

```
React Hot Loader: this component is not accepted by Hot Loader. 
Please check is it extracted as a top level class, a function or a variable. 
Click below to reveal the source location: 
 ƒ Dashboard() {
    _classCallCheck(this, Dashboard);

    return _possibleConstructorReturn(this, (Dashboard.__proto__ || Object.getPrototypeOf(Dashboard)).apply(this, arguments));
  }
```

I am not using any HOC here, what causes this? Spent a good amount of time on this already and cannot figure it out.

Is this expected behavior? Page still hot reloads, but every component (even PureComponent ones) get re-rerendered which causes issues.

Just trying to understand it. Thanks

**Comment by joriskoris** [comment]
just noticed it is the same as https://github.com/gaearon/react-hot-loader/issues/666 so can probably be closed

**Comment by theKashey** [comment]
Did you use RHL's babel plugin? 
The source code looks ok, so it might be just not a quite correct configuration.

**Comment by Omniroot** [comment]
I'm having the same issue. I didn't find the babel plugin in time, so I wrote my own (`babel-plugin-decompose`) that's pretty rudimentary, but it works in my case, because all my exported `compose`s are default exports.

**Comment by theKashey** [comment]
I can name the way of babel-foo which leads to the victory: for each non-top-level function or a class find all non-top-level functions or a variables it is using. And store them in prototype. 
Next - it become possible to use just toString to compare the old and the new realisation (and next variables to match scope). 
Thus still will fail to hot replace component you actually changed, but it is far better that today.

**Comment by neoziro** [comment]
This should be fixed in [next](https://github.com/gaearon/react-hot-loader/tree/next). Multiple hocs (including Redux) are supported.

**Comment by Tsourdox** [comment]
Which version was this fixed in? The "next" link goes to a 404 page.

**Comment by theKashey** [comment]
@Tsourdox - "next" is not known as version 4 (current).
