### ISSUE TITLE
maximum call stack size exceeded due to arrow functions

### ISSUE THREAD

**Issue by CallMeXYZ** [gaearon/react-hot-loader#698]
When using `react-hot-loader`, a strange issue occurs to me. 

Only this case will throw `Uncaught RangeError: Maximum call stack size exceeded at Test.__test__REACT_HOT_LOADER__`

    class Test extends React.Component {
        test = () => {
            return 123
        }
        constructor(props) {
            super(props)
        }
        static propTypes = {
        }
        render() {
            return (
                <div>{this.test()}</div>)
        }
    }
But the followings three are all right

    // A
    class Test extends React.Component {
        test(){
            return 123
        }
        constructor(props) {
            super(props)
        }
        static propTypes = {}
        render() {
            return (
                <div>{this.test()}</div>)
        }
    }
    // B
    class Test extends React.Component {
        test(){
            return 123
        }
        constructor(props) {
            super(props)
        }
        static propTypes = {}

        render() {
            return (
                <div>{this.test()}</div>)
        }
    }
    // C
    class Test extends React.Component {
        test = () => {
            return 123
        }
        static propTypes = {}
        render() {
            return (
                <div>{this.test()}</div>)
        }
    }
Loader configuration  was followed as the doc says : `.babelrc` as below, add `babel-polyfill` and `react-hot-loader/patch` before file entry

        // .babelrc
        {
            "presets": [["env", {"modules": false}], "react", "stage-1"],
            "plugins": [
                "react-hot-loader/babel",
                "transform-decorators-legacy",
                "transform-flow-strip-types",
                "transform-object-assign",
                "transform-runtime",
                "typecheck",
                "react-css-modules"
            ]
        }

**Comment by theKashey** [comment]
Anyway - "the real arrow functions" (env preset) are not working with RHL enabled.

**Comment by neoziro** [comment]
This is fixed in [React Hot Loader v4](https://github.com/gaearon/react-hot-loader/tree/next).
