### ISSUE TITLE
I see “[HMR] Updated modules: ./modules/app/app.module.js” but nothing changes on the screen

### ISSUE THREAD

**Issue by ioanungurean** [gaearon/react-hot-loader#701]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

What you are reporting:

### Expected behavior

What you think should happen:

### Actual behavior

What actually happens:

### Environment

React Hot Loader version: 3.1.3

Run these commands in the project folder and fill in their results:

1. `node -v`: 8.6.0
2. `npm -v`: 5.4.2

Then, specify:

1. Operating system: Windows 10
2. Browser and version: Chrome 62

### Reproducible Demo
Here you can find the demo file on the `rhl` branch:
https://github.com/ioanungurean/react-app/tree/rhl

I dont know why it's not working. When I make changes it recompiles every time and shows the messages below but what's on the screen it didn't gets updated. I dont know what to do. I tried several times to follow the `Get Started` guide and also to watch the boilerplates that were given as an example and everything seems fine. I also tried to follow the [Troubleshooting](https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md) page and didn't find a solution so far.
![image](https://user-images.githubusercontent.com/11721719/33236232-a9c8a78e-d255-11e7-9135-9f79dbad9c30.png)

If you now what I'm doing wrong please let me know. Thank you in advance! Have a great day also!

**Comment by theKashey** [comment]
Easy. The issue #700 proposed to solve.
So - add `{modules:false}` into your babel.rc, and let webpack update code _magically_ or 
```js
if (module.hot) { module.hot.accept('./modules/app', () => { 
   App = require('./modules/app'); // do it by yourself.
   render(App); 
}); }
```

**Comment by ioanungurean** [comment]
@theKashey Thank you! You are right! 💯
