### ISSUE TITLE
patch.dev.js-resolveType-toString will be conflicted with the one user defined

### ISSUE THREAD

**Issue by txgj** [gaearon/react-hot-loader#702]
file:
node_modules/_react-hot-loader@3.1.3@react-hot-loader/lib/patch.dev.js

function: 
function resolveType(type) {
...
var signature = type.toString();
... 
}

description:
toString()  will be conflicted with the one user defined.

For example: 
if an React Component named "A" has a property:
toString = function( arg1 ) {
    console.log(arg1.name);
}

Rendering  Component "A" will lead to a crash with error:  "Cannot read property 'name' of undefined"

**Comment by theKashey** [comment]
Ok. My bad. 
Anyway - don’t overload magic methods, and don’t introduce new arguments.

**Comment by neoziro** [comment]
React Hot Loader wrap all components into proxies. You should be careful when manipulating types. For more information, please give a look to [react-stand-in documentation](https://github.com/gaearon/react-hot-loader/tree/next/packages/react-stand-in).
