### ISSUE TITLE
Bug in the docs causing hot reloading to not work

### ISSUE THREAD

**Issue by Sawtaytoes** [gaearon/react-hot-loader#706]
### Description

Unable to see hot-reloaded changes while developing when following the docs. This is the big piece. It's entirely related to the docs. Once that component's been imported, it is cached by Webpack and any changes no longer show up. So it needs to be re-required again in the `module.hot.accept` callback function.

### Expected behavior

The component I edited should reflect those changes in the DOM.

### Actual behavior

The component does not change, but the console does show in the log that it saw which files were modified. No browser refresh occurs either which I guess shows that it's somewhat working.

```log
[HMR] Updated modules:
log.js?4244:23 [HMR]  - ./app/components/root/AppRoot.js
log.js?4244:23 [HMR]  - ./app/components/root/ClientRoot.js
```

### Environment

React Hot Loader version:
3.1.3

Run these commands in the project folder and fill in their results:

1. `node -v`: v8.8.1
2. `npm -v`: 5.4.1
3. `yarn -v`:1.3.2

Then, specify:

1. Operating system: Windows 10 Pro 64-bit (Version 10.0.16299 Build 16299)
2. Browser and version: Google Chrome Version 63.0.3239.70 (Official Build) beta (64-bit)

### Reproducible Demo

This happens in two projects I've tested. This is one you can use to reproduce. Do a `yarn` install and then run `yarn start` to test at `localhost:3000`.

https://github.com/Sawtaytoes/Ghadyani-Framework/tree/react-hot-loader-docs-wrong/

**Comment by theKashey** [comment]
Yep. #700 is supposed to fix this.
But, if you will follow `best` webpack2 cases - you will enable `harmony` modules, ie {modules:false}, and webpack's magics will do the rest.

**Comment by neoziro** [comment]
Resolved in [next](https://github.com/gaearon/react-hot-loader/tree/next/).
