### ISSUE TITLE
App getting recompiled twice

### ISSUE THREAD

**Issue by James2516** [gaearon/react-hot-loader#713]
https://github.com/James2516/hot-reload
I followed the README to add hot loading to an existing webpack project.
I got it working except that `[WDS] App updated. Recompiling...` gets printed twice on every reload. 
Any idea what's causing it?

**Comment by theKashey** [comment]
The correct way is to:
1. remove __any__ hot thing from webpack config, except react-hot-loader of course 🥇 
2. run webpack dev server with --hot option.

Bingo!
PS: Anyway - this is related to webpack, not react-hot-loader.

**Comment by a7madgamal** [comment]
`remove any hot thing from webpack config`
more details please :)

**Comment by theKashey** [comment]
@a7madgamal - like HotModuleReplacementPlugin and so on.

**Comment by 007sair** [comment]
HMR does not work when I click a button, The button is like this: 
```html
<a href="javascript:;" @click="start">Click!</a>
```
Delete the href attribute, HMR is working now.
I hope this is useful to you.

**Comment by Leedehai** [comment]
No, after removing "hot" thing (the plugin item and the 'hot' option) and add '--hot' to commandline, as @theKashey suggested, it's still compiled twice.
