### ISSUE TITLE
Issue with recompose's withStateHandlers (or maybe every enhancer)

### ISSUE THREAD

**Issue by fenok** [gaearon/react-hot-loader#717]
### Description

I'm starting a project and trying to use react-hot-loader and recompose together.

### Expected behavior

When I alter contents of withStateHandlers enhancer, they should reflect in RecomposeCounter, or there should be error or warning in console.

### Actual behavior

Hot reloading silently fails (props.stateCounter and props.incrementStateCounter in RecomposeCounter refer to old values). Manual page reload fixes it.

### Environment

React Hot Loader version: 3.1.3

1. `node -v`: v6.9.1
2. `npm -v`: 3.10.8 (i don't use it)
3. `yarn -v`: 1.3.2

1. Operating system: win10, ubuntu
2. Browser and version: Chrome 63.0.3239.84

### Reproducible Demo

https://github.com/fenok/react-hot-boilerplate/tree/next
I.e. change sign in counter updater. It works fine in Counter, but silently fails in RecomposeCounter.

**Comment by theKashey** [comment]
We know > https://github.com/gaearon/react-hot-loader/issues/650

**Comment by fenok** [comment]
It's not about losing state. It's about RHL saying the app is up-to-date when it's not.

**Comment by theKashey** [comment]
Usually, RHL ignores actions made on componentDidMount, as long there will be no mount/unmount.
And it also ignores any changes made inside the constructor. Changing the stateUpdaters will affect only new instances. That's how react-proxy, the underlying internals of RHL works.

Will be solved by #707. The new version does regenerate changes from constructor in runtime.

**Comment by fenok** [comment]
Awesome, thank you!
