### ISSUE TITLE
HMR of React 16 PureComponent does not work! Add this to documentation!

### ISSUE THREAD

**Issue by MrChe** [gaearon/react-hot-loader#718]
HMR of React 16 PureComponent does not work! Use only Component.
`"react-hot-loader": "3.1.3",` - Not work with PureComponent
Please add this to documentation!

**Comment by theKashey** [comment]
Just tested, and it seems to be ok.
Are you wrap your application with AppContainers. It actually does the "update" work.

**Comment by neoziro** [comment]
HMR v3 and v4 works with `PureComponent`. I close it.
