### ISSUE TITLE
Why pass Component into the render function?

### ISSUE THREAD

**Issue by dnichols** [gaearon/react-hot-loader#719]
What is the purpose of passing `Component` into the render function, when all it does it render the same imported component?

```javascript
const render = Component => {
  ReactDOM.render(
    <AppContainer>
      <Component />
```
```javascript
module.hot.accept('./containers/Root', () => { render(Root) })
```
**vs**
```javascript
const render = () => {
  ReactDOM.render(
    <AppContainer>
      <Root />
```
```javascript
module.hot.accept('./containers/Root', () => { render() })
```

Genuinely curious. Thanks!

**Comment by theKashey** [comment]
When you are using webpack 3 with harmony modules enabled - there is __no difference__.

**Comment by neoziro** [comment]
Related to Webpack. [React Hot Loader v4](https://github.com/gaearon/react-hot-loader/tree/next#getting-started) has now a much more simpler set up.
