### ISSUE TITLE
React hot loader not compatible with electron

### ISSUE THREAD

**Issue by rllola** [gaearon/react-hot-loader#720]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

When using react hot loader in electron, the `instanceof` seems to be broken. At least when reloading the result is difference that when running it for the first time.

### Expected behavior

I would expect `instanceof` to have the same result after reloading.

### Actual behavior

After reloading the `instanceof` operator return a different answer than the first time.

### Environment

React Hot Loader version:
3.1.3
Run these commands in the project folder and fill in their results:

1. `node -v`: 7.10.1
2. `npm -v`: 5.4.2

Then, specify:

1. Operating system: Linux
2. Browser and version: Electron

### Reproducible Demo

https://github.com/rllola/hmr-example-issue

**Comment by neoziro** [comment]
The v4 will be based on a new proxy system. As soon as we will release a beta, we should test it on Electron.

**Comment by okonet** [comment]
@neoziro any ETA? Can the master branch be tested?

**Comment by theKashey** [comment]
@okonet - I hope this weekends.

**Comment by neoziro** [comment]
Yes I hope too.

**Comment by okonet** [comment]
Please let me know as I can help testing it.

**Comment by neoziro** [comment]
Ready 😊 https://github.com/gaearon/react-hot-loader/tree/next

**Comment by neoziro** [comment]
I tested it and it does not change the result. But I think it is related to your setup. It looks like code in `index.html` and in `scripts` are into two different universes.

I tried to pass `React` into props and then compare it to `import React from 'react'` in `app.js` and it does not work.

So this issue is probably not related to React Hot Loader, and maybe even not related to Hot Module Reloading.

**Comment by okonet** [comment]
Can confirm it's working with electron 1.8.2 beta! 👏

**Comment by rllola** [comment]
@okonet I still have the issue. Could you tell me what you used to test it ?

Could you tell me if it is working also for you with this setup : https://github.com/rllola/hmr-example-issue ?

**Comment by neoziro** [comment]
@rllola your application is not wrapped with `hot`. Please follow every steps of [Getting Started](https://github.com/gaearon/react-hot-loader/tree/next#getting-started).

**Comment by rllola** [comment]
@neoziro Thanks ! It is working now.
