### ISSUE TITLE
I don't want use AppContainer

### ISSUE THREAD

**Issue by somebac123** [gaearon/react-hot-loader#731]
I don't want use AppContainer

```js
import React from 'react'
import ReactDOM from 'react-dom'
import App from './containers/App'

ReactDOM.render(
    <Component />
  document.getElementById('root'),
)
```

Like this, is there any way to support HMR?

**Comment by neoziro** [comment]
[React Hot Loader v4](https://github.com/gaearon/react-hot-loader/tree/next#getting-started) has a simplified set up but all is required. You do need `AppContainer` or mark your app as *hot-exported*.
