### ISSUE TITLE
Replace warnings by debug and defaults it to false

### ISSUE THREAD

**Issue by neoziro** [gaearon/react-hot-loader#732]
We have a [prop `warnings`](https://github.com/gaearon/react-hot-loader/blob/next/packages/react-hot-loader/src/AppContainer.dev.js#L97) that activate some warnings. It is only relevant for advanced users and for debug purpose. The goal is to rename it everywhere with `debug`, defaults it to `false` and document it in README.

**Be careful by replacing every `warnings` present in code.**

**Comment by theKashey** [comment]
`debug` or `dev`?
How to pass options without AppContainer?
```js
import {enableDebug} from 'react-hot-loader';
enableDebug();

//or
import 'react-hot-loader/debug'
```

**Comment by neoziro** [comment]
Actually we can do it using `hot(module, { debug: true })`. What do you think?

**Comment by neoziro** [comment]
`dev` is confusing because we are in "development" environment when we use RHL.

**Comment by theKashey** [comment]
How many `hot` exports you may have in your project?
As I expected - at least one for every for every entry point (including chunks).
As I understand - you may have only one, at _loadables_ will still works
(PS: this mean than we could monkey patch `react-dom`)

But anyway - as long you may have more that one `hot` - this global setting should not be a part of it.

**Comment by neoziro** [comment]
@theKashey I agree, do you think we will need other options? I think about:

```js
import { configure } from 'react-hot-loader'
configure({ debug: true })
```

**Comment by theKashey** [comment]
To say the truth - it should not have options. But `configure` might be the simplest way.

**Comment by theKashey** [comment]
Not finished yet.

**Comment by neoziro** [comment]
@theKashey OK, waiting for PR.

**Comment by neoziro** [comment]
#743 will definitely fix this one
