### ISSUE TITLE
Automate release

### ISSUE THREAD

**Issue by neoziro** [gaearon/react-hot-loader#734]
Actually releasing the project is not automated. The goal is to create a `yarn release` command that will automate it:

* Run `yarn build`
* Generating a new CHANGELOG using [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog)
* Pushing release on GitHub using [conventional-github-releaser](https://github.com/conventional-changelog/conventional-github-releaser)
* Publishing a new version on npm using `lerna publish`

**Comment by oliviertassinari** [comment]
I'm using [np](https://github.com/sindresorhus/np) with my projects. Maybe that can help.

**Comment by neoziro** [comment]
@oliviertassinari not for Lerna projects 👎

**Comment by oliviertassinari** [comment]
@neoziro Is using Lerna with yarn workspace still relevant?

**Comment by neoziro** [comment]
Yes, `lerna publish` for example. But `yarn` does a lot!
