### ISSUE TITLE
Can't use "use strict";

### ISSUE THREAD

**Issue by hokkos** [gaearon/react-hot-loader#75]
Hi,
it seems the code injected after /* REACT HOT LOADER */ just before our code prevent the "use strict"; command from being the first instruction of the module and make it behave in strict mode. Any idea to make it works ?

Thanks.

**Comment by gaearon** [comment]
Oh, that's a good point. I never realized this happens. I'll take another look and if that's an issue, I'll wrap module code into IIFE.

**Comment by nelix** [comment]
This actually hit me pretty hard yesterday (not that it took long to fix or anyone noticed :P), production build failed to load due to something being undefined (not triggered in dev because strict was not enabled).

**Comment by gaearon** [comment]
Should be done. Thanks again for reporting.
