### ISSUE TITLE
[next] No substitution given for "RHL"

### ISSUE THREAD

**Issue by JounQin** [gaearon/react-hot-loader#753]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

What you are reporting: bug

### Expected behavior

What you think should happen: pass

### Actual behavior

What actually happens: throw error

### Environment

React Hot Loader version: 4.0.0-beta.9

Run these commands in the project folder and fill in their results:

1. `node -v`: v9.3.0
2. `npm -v`: 5.6.0

Then, specify:

1. Operating system: macOS
2. Browser and version: Chrome 63

### Reproducible Demo

https://github.com/JounQin/react-study

Upgrade `react-hot-loader` and run `yarn dev`

**Comment by theKashey** [comment]
https://github.com/babel/babel/issues/7035

**Comment by neoziro** [comment]
Fixed in [v4.0.0-beta.11](https://github.com/gaearon/react-hot-loader/releases/tag/v4.0.0-beta.11).

**Comment by JounQin** [comment]
It doesn't throw error anymore, however, it could not hot reload neither.

My usage code: https://github.com/JounQin/react-study/blob/master/src/entry-client.js

**Comment by theKashey** [comment]
@JounQin - cos you need to setup Hot-Module-Replacement first.
We do have examples for parcel and webpack, but not for koa, sorry.

**Comment by JounQin** [comment]
@theKashey I've set Hot-Module-Replacement correctly and it works on v4.0.0-beta.7 but not on >=v4.0.0-beta.8.

**Comment by theKashey** [comment]
@JounQin - this does not depend on RHL, it depends on `asyncComponent`. It prevents update of nested component. Literally, it updates the code __after__ RHL did it's work.
Solutions
 - dont use asyncComponent, there are a dozens more reliable versions. Try https://github.com/smooth-code/loadable-components, sound like it works out of the box.
 - wrap Hello with AppContainer
 - wrap default export of Hello with {hot} from React-hot-loader

(any of these variants will help)
