### ISSUE TITLE
code splitting with react-router4 cannot keep the component state 

### ISSUE THREAD

**Issue by likun7981** [gaearon/react-hot-loader#757]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

What you are reporting:
   code splitting with react-router4 cannot keep the component state 
### Expected behavior

What you think should happen:
  after hot reload , the component state should not change
### Actual behavior

What actually happens:
  the component state is reset
### Environment

React Hot Loader version: 3.1.3

Run these commands in the project folder and fill in their results:

1. `node -v`:  v8.9.0
2. `npm -v`: v4.6.1

Then, specify:

1. Operating system: MacOS 10.13.2
2. Browser and version: Chrome 63.0.3239.84

**Comment by theKashey** [comment]
Please try "next", or 4.0.0-beta.11

**Comment by likun7981** [comment]
Using the `next` version will refresh the page.
The `v3.1.3` is not refresh the page , only hot reload and reset the component state

**Comment by likun7981** [comment]
The `v3.1.3` and `v4.0.0-beta.11` are working good without `code splitting`.

**Comment by theKashey** [comment]
Could you spill some light? Any code example?
Page refresh means - something terrible happens (or you did not accept the change)
PS: I am about v4 only. It should work.

**Comment by likun7981** [comment]
please try https://github.com/likun7981/test-rhl

**Comment by neoziro** [comment]
@likun7981 Did you follow [Code Splitting guide](https://github.com/gaearon/react-hot-loader/tree/next#code-splitting)?

**Comment by apostolos** [comment]
@likun7981 Wrap your [default export](https://github.com/likun7981/test-rhl/blob/39c6e81f297f5c793b4ac6e8561f99254e7668be/src/Counter.js#L25) with hot(module) and it should work:

```js
import { hot } from 'react-hot-loader';
export default hot(module)(Counter);
```

**Comment by likun7981** [comment]
@neoziro     thank you for you answer,  my `Bundle` component is wrong,   I fork it from https://reacttraining.com/react-router/web/guides/code-splitting.  it is work use your `loadable-components`, Thanks again
