### ISSUE TITLE
[4.0.0-beta.11] Untranspiled RHL code in production bundle

### ISSUE THREAD

**Issue by apostolos** [gaearon/react-hot-loader#758]
### Description

Production bundle includes untraspiled *.prod.js code. Among other things, this breaks Uglify minifaction step.

### Expected behavior

Stub code should be transpiled.

### Actual behavior

The content of the following files is included "as is" on the **main** webpack chunk:

- https://github.com/gaearon/react-hot-loader/blob/next/packages/react-hot-loader/src/hot.prod.js
- https://github.com/gaearon/react-hot-loader/blob/next/packages/react-hot-loader/src/AppContainer.prod.js
- https://github.com/gaearon/react-hot-loader/blob/next/packages/react-hot-loader/src/utils.prod.js

### Environment

React Hot Loader version: 4.0.0-beta.11
Babel: 7.0.0-beta.36
Webpack: 4.0.0-alpha.2

### Reproducible Demo

https://github.com/LWJGL/lwjgl3-www

**Comment by theKashey** [comment]
Thank you. Will fix asap.

**Comment by SuhairZain** [comment]
@theKashey Hey,
Is there an update on this? We were looking to migrate from v3 to v4 because of an issue with setState. But doing so would break our production build with uglify.

**Comment by theKashey** [comment]
PR already opened. Waiting for completion.

**Comment by neoziro** [comment]
Fixed in [v4.0.0-beta.12](https://github.com/gaearon/react-hot-loader/releases/tag/v4.0.0-beta.12)

**Comment by apostolos** [comment]
Many thanks!

RHL v4 now in production here: https://www.lwjgl.org/
