### ISSUE TITLE
[next] Imports broken after adding `babel-loader`

### ISSUE THREAD

**Issue by DevanB** [gaearon/react-hot-loader#760]
### Description

After following setup instructions for TypeScript, imports (using react-loadable) are failing. It appears that the issue is adding `babel-loader`.

### Expected behavior

No errors with imports when using `babel-loader` with `ts-loader` and RHL.

### Actual behavior

Syntax errors caused by imports

### Environment

React Hot Loader version: next (`4.0.0-beta.11`)

Run these commands in the project folder and fill in their results:

1. `node -v`: `8.9.3`
2. `npm -v`: `5.5.1`

Then, specify:

1. Operating system: macOS 10.12.6
2. Browser and version: Safari 11.0.2 (12604.4.7.1.4)

### Reproducible Demo

https://github.com/DevanB/typescript-react-starters/tree/rhl/ts-react

(Notice the `rhl` branch)

**Comment by theKashey** [comment]
Look like there is no babelrc

**Comment by neoziro** [comment]
Yes it looks like it is a problem in Babel configuration but on our side we need to make a clear guide in README.

@DevanB to solve your problem:

Add a `.babelrc`:

```js
{
  "presets": ["env", "react"],
  "plugins": ["react-hot-loader/babel"]
}
```

Install "babel-preset-env" and "babel-preset-react".

You can take some inspiration from our [TypeScript example](https://github.com/gaearon/react-hot-loader/tree/next/examples/typescript).

**Comment by DevanB** [comment]
Ahh, okay that is working. Thanks!

I'll submit a PR to update the README, if you'd like @neoziro 

It stinks a TS user _must_ use Babel to take advantage of RHL (or use the older, harder to setup 3.x version).

**Comment by theKashey** [comment]
Is there any difference between webpack-babel-loader and webpack-not-babel-loader? We can hide babel under the hood, and reintroduce react-hot-loader/webpack.

TS is a language, Babel is just a tool. It can compile ES6 to ES5, can also be a "language", but in reality it just transforms the code. In this case it shall do nothing more, but code transform.
In real - babelrc @neoziro provided, is not correct - is does transpile JS, and JSX. As long it was already done by TS - there is no need to do it
The only thing you have to do - is to apply HRL patch.
```js
{
  "plugins": ["react-hot-loader/babel"]
}
```
__nothing more__. I hope in this form babel is not stinks :) as much as before.

Anyway - we need babel loader only to support non-transpiled arrow functions. If compilation target will be es5 - we could patch function.bind to do our work without any need of eval (and maybe we should do it). But as long the goal was _to_ support arrow functions - we did not do it.

**Comment by DevanB** [comment]
It appears adding a `.babelrc` with either of the configurations mentioned doesn't work. I was able to find the issue. I had to change my `tsconfig.json` from `module: "esnext"` to `module: "commonjs"`. I'm unsure why this change is necessary since before adding `babel-loader` the `esnext` configuration worked.

I believe that adding `babel-loader` _on top of_ `ts-loader` (or `awesome-typescript-loader`) is too much. There is no difference between Babel and TypeScript (besides being two different tools) except for that it has been chosen to support _only_ Babel. I have to run my code through two processes (`ts-loader` and `babel-loader`), which only adds complexity and time. Why not support a situation where you don't need to add `babel-loader` to a working TypeScript setup just to have RHL? It would be extra work, but would allow support for everyone writing JS and TS without added complexity and questions.

**Comment by theKashey** [comment]
When two worlds collide - one is going to die.
There is no way to extend TS, and create some ts-plugin to empower RHL. Just there is no "TS" way.

But your problem is not a problem. If you will ever google it, or provide the real error here - you will understand how to solve it
```js
{
            loader: 'babel-loader',
            options: {
              babelrc: true,
              plugins: [
                'react-hot-loader/babel',
                'syntax-dynamic-import',   // <<------
              ]
            }
          },
```
One line! And babel will undertand the syntanx it does not undertand before.
PS: Two lines, the second is `yarn add --dev babel-plugin-syntax-dynamic-import`

**Comment by DevanB** [comment]
>But your problem is not a problem. If you will ever google it, or provide the real error here - you will understand how to solve it
> ...
>One line! 

Now I understand that you aren't very friendly, understanding, or sympathetic (things I assume @gaearon would want to happen in his projects) and I personally won't be advocating for this project anymore.

**Comment by theKashey** [comment]
Dont get me wrong - I am willing to solve both your problem and our issue, which caused it.

The problem was not "Syntax errors caused by imports", the problem is "SyntaxError: Unexpected token import". And 2-3-4th results from Google contains enough information to solve it, as long this is a popular problem these days.
Spot a bug, google it, add one more babel-plugin. As long you are not a babel user - it might be not so clear for you, but I hope I explained the problem, and now you get the point.

That's what I said, and I could not see anything _unfriendly_ here. If you do - so, just sorry. If it was not supposed to be bad. Sometimes I am a bit straightforward.

**Comment by neoziro** [comment]
@DevanB do not take it like that, @theKashey is trying to help. He is not blaming you! I even prefer that you reported this issue rather than trying random stuff on Google. Also all should work out of the box so it is still an issue for this project.
