### ISSUE TITLE
react-hot-loader@next contains untranspiled ES6 code

### ISSUE THREAD

**Issue by meyer** [gaearon/react-hot-loader#763]
I accidentally started using RHL4 beta because I was using `react-hot-loader@next`in my package.json file (🙄). I encountered an Uglify error but I was uglifying all my own code. Turns out the untranspiled code was in RHL, specifically in `AppContainer.prod.js`. Do you all intend to leave that as is? If so, it would mean that I’d need to start transpiling `node_modules` as well, which would be less than ideal.

A potential workaround would be to use a functional component instead of a class component as the prod `AppContainer` (assuming `AppContainer` doesn’t need a backing instance).

**Comment by theKashey** [comment]
Should be fixed 2 days ago - #758 
Could you check exact version of RHL you use?

**Comment by meyer** [comment]
also holy moly you all have done a ton of work on v4. Exciting! I love the greatly simplified installation instructions.

**Comment by meyer** [comment]
@theKashey ahhhhhh yeah, I `npm install`ed on this project a few days ago. I was probably one version behind. It works now! Thanks!

**Comment by theKashey** [comment]
🎅

**Comment by meyer** [comment]
I should’ve checked those closed issues 🙄🙄🙄
