### ISSUE TITLE
webpack -p throws error when using react-hot-loader@next

### ISSUE THREAD

**Issue by joeldenning** [gaearon/react-hot-loader#764]
### Description

First off, thanks for your great work on this! I'm loving the beta version of react-hot-loader. When using react-hot-loader@4.0.0-beta.7 and webpack@3.10.0, running `webpack -p` on a project that uses react-hot-loader results in a build error. This is because react-hot-loader's code uses `let` which uglify does not support. This also presumably makes react-hot-loader not work with older browsers such as IE11 which do not support `let`.

The normal thing I've seen done to fix this is to change the project's main file to point to a es5 compiled version of the code that is part of the published package. Although admittedly I've recently been seeing more and more projects publish es6 code and have their main file point to es6 code. Additionally I've heard tell of webpack maybe moving off of uglifyjs, but Not sure where you guys stand on that debate, but I think that react-hot-loader not working with webpack -p 

Note that webpack@4 seems to fix this (maybe because it's no longer using uglify??), or as a workaround you can configure babel-loader to compile the node_modules/react-hot-loader during the webpack build process.

### Expected behavior

```
Version: webpack 3.10.0
Time: 3960ms
             Asset    Size  Chunks             Chunk Names
    calendar-ui.js  129 kB       0  [emitted]  main
calendar-ui.js.map  694 kB       0  [emitted]  main
```

### Actual behavior

```
ERROR in calendar-ui.js from UglifyJs
Unexpected token: name (exportedModule) [./node_modules/react-hot-loader/lib/patch.js:6,0][calendar-ui.js:5992,4]
error Command failed with exit code 2.
```

### Environment

React Hot Loader version: 4.0.0-beta.7

Run these commands in the project folder and fill in their results:

1. `node -v`: v9.3.0
2. `npm -v`: (actually i'm using yarn@1.3.2)

Then, specify:

1. Operating system: OSX
2. Browser and version: N/A

### Reproducible Demo

Let me know if you'd like a reproducible demo of this -- I thought I'd hold off on creating one until I heard if the solution was to just update webpack, don't use IE11, or maybe a change to react-hot-loader.

**Comment by theKashey** [comment]
Please update to the latest version - `4.0.0-beta.12`. This issue was already fixed.

**Comment by joeldenning** [comment]
👍 thanks! Upgrading worked.
