### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by neoziro** [gaearon/react-hot-loader#768]
Actually v4 is well tested but it is still not enough!

- [x] Run tests on React 15
- [ ] Add integration tests
- [ ] Reach 95% coverage

**Comment by theKashey** [comment]
- [ ] stand-in should be included into code coverage
- [ ] convert examples into integration tests.

**Comment by neoziro** [comment]
Not plan soon.

**Comment by theKashey** [comment]
But still an issue.
