### ISSUE TITLE
SCRIPT1002: Syntax error in IE 11

### ISSUE THREAD

**Issue by keeganstothert** [gaearon/react-hot-loader#772]
removed react-hot-loader from my project and tested in IE. works.
also works with react-hot-loader 3

console error SCRIPT1002: Syntax error
the error points to AppContainer in react-hot-loader

### Environment

React Hot Loader version: 4.0.0-beta.12

1. `node -v`: 7.7.3
2. `npm -v`: 4.1.2

1. Operating system: mac os high sierra 
2. Browser and version: IE 11

**Comment by neoziro** [comment]
@keeganstothert can you please try on [next](https://github.com/gaearon/react-hot-loader/tree/next)?

**Comment by theKashey** [comment]
RHL should NOT work in **IE11** and **dev** mode.
The reason - one of the goals for v4 was to support modern JS, thus require modern js to be used by React-hot-loader. 
As result, AppContainer contains untranspiled `class` keyword.

RHL is a development tool, and IE11 is not a _development_ browser.

We have 3 options to solve this issue:
 - provide another package (or another entry point) both for RHL and standin, with fully transpiled sources.
 - completely wrap RHL and standin with `eval`, and do not execute them in case of older browser.
 - do nothing. In case of IE11 you are not developing, but testing the Application. You just could use production build.

@neoziro ?

**Comment by neoziro** [comment]
@theKashey oh I had forgotten this, sorry you are right.

I vote for an explicit warning telling that the browser is not supported. I do not know how to detect if `class` is supported. May be using `try...catch` + `eval`?

**Comment by theKashey** [comment]
All ok... except the whole bundle file will not load, in case of syntax error inside it. And `class` threatens as a syntax error, as I understand.
Maybe I am wrong, and as long function will not be executed - it will not fall.
One need some experiments to accomplish first.

**Comment by escsun** [comment]
Yeah i too have this bug, i use IE11 for testing CSS styles, i dont need RHL in IE11, maybe u can check it by try...catch

**Comment by theKashey** [comment]
Even Linux penguins still use IE11. I'll pursue this issue.

**Comment by theKashey** [comment]
#772 will fix the errors. There also was arrow functions inside.

**Comment by theKashey** [comment]
Released in 4.0.0-beta.14

**Comment by Palid** [comment]
Issue still wasn't fixed - https://github.com/gaearon/react-hot-loader/pull/778/files#diff-647d447b1f1e195dc7d32858c321f74bR57 this line is still evaluated in IE11, which throws the whole block.

The quick&dirty fix:
```
var proxyClassCreator;

if (doesSupportClasses) {
  var ES6ProxyComponentFactory = eval('\n(function(InitialParent, postConstructionAction) {\n  return class ProxyComponent extends InitialParent {\n    constructor(props, context) {\n      super(props, context)\n      postConstructionAction.call(this)\n    }\n  }\n})\n');
  proxyClassCreator = exports.proxyClassCreator = ES6ProxyComponentFactory;
} else {
  var ES5ProxyComponentFactory = function ES5ProxyComponentFactory(InitialParent, postConstructionAction) {
    function ProxyComponent(props, context) {
      InitialParent.call(this, props, context);
      postConstructionAction.call(this);
    }
    ProxyComponent.prototype = Object.create(InitialParent.prototype);
    Object.setPrototypeOf(ProxyComponent, InitialParent);
    return ProxyComponent;
  };
  proxyClassCreator = exports.proxyClassCreator = ES5ProxyComponentFactory;
}
```

**Comment by theKashey** [comment]
I'll double check. Works on my machine.
