### ISSUE TITLE
[RHL-V4] component local state losing

### ISSUE THREAD

**Issue by swASO** [gaearon/react-hot-loader#780]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description
I dont`d know if this realy a bug but when i use RHl with react-router, the state didnt get inherited to the new "hot-updated" component, every time he losing his local state. 

### Expected behavior
local state is the same as before

### Actual behavior
local state is reseted

### Environment
React Hot Loader version: v4-beta-13
TypeScript: 2.6.2
mobx: 3.3.1
react: 16

Run these commands in the project folder and fill in their results:

1. `node -v`: v6.9.5
2. `npm -v`: 3.10.10

Then, specify:

1. Operating system: Win10 x64
2. Browser and version: Chrome 63

### Reproducible Demo

if you really need one, then i create one but its really simple: see attached file
[github_react-hot-loader.txt](https://github.com/gaearon/react-hot-loader/files/1619710/github_react-hot-loader.txt)

btw: [saw its better to use render prop on route because "component"
 will do everytime React.createElement](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js)

**Comment by aminland** [comment]
Did you try it by using actual react states? i.e. is this a MobX specific issue?

**Comment by swASO** [comment]
yes, can reproduce it with react states

**Comment by theKashey** [comment]
@neoziro - 😿  we should rename `hot` or introduce more clear readme, or strict checking. Maybe just throw an error, if react-dom is in scope.

@swASO - you are using `hot` in a wrong way. As long it affects the whole module, not a single `component` passed down to the function - use if to mark exports.

BAD:
```js
const IndexApp = hot(module)(() => (
    <Router basename={baseRoutePath}>
        <App />
    </Router>
));
```

GOOD:
```js
// App.js
.....
export default hot(module)(App)
```

**Comment by swASO** [comment]
ups! changed it but can still reproduced it

**Comment by theKashey** [comment]
Ok, will try to reproduce.

**Comment by theKashey** [comment]
Hey! @swASO - and could you share your webpack/typescript configuration?

**Comment by swASO** [comment]
sure 
[configs.zip](https://github.com/gaearon/react-hot-loader/files/1719032/configs.zip)

**Comment by neoziro** [comment]
React Hot Loader v4 is released, please try it and feel free to open a new issue if you still experienced some problems.

**Comment by seanlarge** [comment]
Hi, I'm using react hot loader v4.2.0 and I have this issue. basically, I'm on a given route, hot reloader refreshes the page and all the state is gone. component crashes...any workarounds? thanks!

**Comment by theKashey** [comment]
@seanlarge - 
1. Try to update RHL
2. Fill the issue with your case
