### ISSUE TITLE
Child "connect" component not updating on changes

### ISSUE THREAD

**Issue by kkomaz** [gaearon/react-hot-loader#784]
### Description
I am having difficulty fully getting react-hot-loader working on my current application.  Specifically when both parent and child components are "connect" components via `react-redux`.

### Expected behavior
When the "connect" child component is updated, HMR should update the browser with those specific changes.  However, this works when the child component is not connected.  This does not occur on every parent to child component.  Using the same component somewhere else HMR works fine.  Can't seem to find what differentiates one from the other.

### Works:
1. Changing Child component from "Hello World" to "Hello Worldsss" triggers hot-loader.
```
Parent:
  <div className="col-md-1">
    <h1>Test Component</h1>
    <DummyComponent />
  </div>

Child:
class DummyComponent extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div>Hello World</div>
    );
  }
}

export default DummyComponent;

```
### Doesn't Work:

```
Parent:
  <div className="col-md-1">
    <h1>Test Component</h1>
      <DummyComponent />
  </div>

Child:
import { connect } from 'react-redux';

class DummyComponent extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div>Hello World</div>
    );
  }
}

function mapStateToProps(state) {
  return {
    anything: state.anything
  };
}

export default connect(mapStateToProps)(DummyComponent);
```

### Actual behavior
- HMR not working for connected child components

### Environment

React Hot Loader version: 4.0.0-beta.13 (also tested on 3.0.0)

node version: v8.4.0
npm version: v5.3.0

### webpack.config.js
```
entry: ifProd(
  [
    'babel-polyfill',
    './src/main.js',
  ],
  [
    'babel-polyfill',
    'webpack-dev-server/client?http://localhost:8080',
    'webpack/hot/only-dev-server',
    './src/main.js',
  ]
),

```

**Comment by theKashey** [comment]
The only difference is `mapStateToProps`?
Did you wrap application with AppContainer or exported as _hot_?

**Comment by kkomaz** [comment]
Thank you I must've been following an old tutorial and didn't wrap with the AppContainer.  Works fine now.  Closing.
