### ISSUE TITLE
RHL4 -> Hot reloading arrow functions on classes do not bind `this`

### ISSUE THREAD

**Issue by benbayard** [gaearon/react-hot-loader#787]
### Description
If you have a class like this:

```jsx
class MyClass extends React.Component {
  renderSubTree = () => <div>{this.props.children}</div>
  render() { return this.renderSubTree() }
}

@hot(module)(MyClass)
```

and edit `renderSubTree`:

```jsx
class MyClass extends React.Component {
  renderSubTree = () => {console.log('did a thing'); return <div>{this.props.children}</div>}
  render() { return this.renderSubTree() }
}
```

`this` is no longer bound to `MyClass` instance

### Expected behavior

`this` is correctly bound to `MyClass` instance

### Actual behavior
an error is thrown
```
Uncaught ReferenceError: _this is not defined
    at ProxyComponent.eval [as renderBanner] (eval at __reactstandin__regenerateByEval (index.jsx:315), <anonymous>:5:31)
    at ProxyComponent.render (index.jsx:292)
    at ProxyComponent.render (createClassProxy.js:71)
    at finishClassComponent (react-dom.development.js:10249)
    at updateClassComponent (react-dom.development.js:10226)
    at beginWork (react-dom.development.js:10605)
    at performUnitOfWork (react-dom.development.js:12573)
    at workLoop (react-dom.development.js:12682)
    at performWorkCatchBlock (react-dom.development.js:12782)
    at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
```

### Environment

React Hot Loader version: `"react-hot-loader": "^4.0.0-beta.13"`

Run these commands in the project folder and fill in their results:

1. `node -v`: 8.2.1
2. `npm -v`: 5.3.0

Then, specify:

1. Operating system: OSX
2. Browser and version: Chrome, latest

### Reproducible Demo

Demo is above.

**Comment by theKashey** [comment]
Yep, RHL v4 was started to support arrow functions, and the goal was reached.
You have got an error, cos you are transpiling the arrow function into the es5 code, and babel produces `this` we did not expect.

We will handle this case, but for you, it will be easier to use more modern js during the development, ie set the target for `env` preset.

**Comment by benbayard** [comment]
Hey @theKashey what do you mean `ie set the target for env preset.`?
We are using `transform-class-properties`, which I believe is doing the additional transformation this isn't expecting.

**Comment by benbayard** [comment]
Also, that code looks to work, so yay!

**Comment by theKashey** [comment]
> what do you mean ie set the target for env preset.?
https://babeljs.io/docs/plugins/preset-env/ -> see "target" section.

**Comment by benbayard** [comment]
Thanks! After updating to the newest build, our problem has also been fixed so I am going to close. Thank you @theKashey 👍
