### ISSUE TITLE
How to quiet the console.log outputs? 

### ISSUE THREAD

**Issue by volkanunsal** [gaearon/react-hot-loader#79]
This kind of output in the browser console is really hard to work with. Can I disable these outputs?

```
[HMR] App is up to date.
[WDS] App updated. Recompiling...
[WDS] App hot update...
[HMR] Checking for updates on the server...

```

**Comment by gaearon** [comment]
You can copy paste `webpack/hot/only-dev-server` to your project, strip logs from it and use your version instead.

Closing, let me know if I missed something!

**Comment by steida** [comment]
Silent option in cofiguratiion would be nice.

**Comment by gaearon** [comment]
It's not really something we can control in RHL. You can file an issue with Webpack.

**Comment by pburtchaell** [comment]
It's a bit hacky, but I currently have this and it helps:

```
if (process.env.NODE_ENV === 'development') {
  console.clear();
}
```

The `NODE_ENV` variable is set by WebPack in the config.

**Comment by gaearon** [comment]
I'd use `if ('production' !== process.env.NODE_ENV)` in this case.
You'd need to set it to `true` using `DefinePlugin` for production anyway so React is properly compressed.

**Comment by irom-io** [comment]
How disable console.log for webpack/hot/only-dev-server ??

`    const server = new WebpackDevServer(compiler, {
        stats: {colors: true},
        hot: true,
        clientLogLevel: 'none',
        //quiet: true,
        watchOptions: {
            ignored: /node_modules/
        }
        /*
         historyApiFallback: {
         index: '/'
         }*/
    });`

quiet: true not working!

**Comment by tavurth** [comment]
Add this to your apps `index.js`:

```
// Clear after module reload
window.addEventListener('message', e => {
    if ('production' !== process.env.NODE_ENV) {
        console.clear();
    }
});
```

**Comment by leongaban** [comment]
This is really annoying, could anyone tell me where these logs are located in the `react-hot-reload` folder? Did not see them.

**Comment by tavurth** [comment]
@leongaban They're sprinkled liberally througout the code.
Go to your `/node_modules/webpack` folder and run a search and replace:

```
find . -type f -name "*.js" -exec sed -i '' 's/console.log.*$//g' {} \;
```

**Comment by leongaban** [comment]
@tavurth ah thanks! I was looking in the react-hot-reload folder.

**Comment by tavurth** [comment]
There's also this: 

https://github.com/webpack/webpack-dev-server/pull/579#issuecomment-244406936

**Comment by peterobrien** [comment]
A quick way to silencing could be filtering in devtools with regex. i.e. ~ `/^((?!(\[HMR|\[WDS)).)*$/`

**Comment by tofilagman** [comment]
Add this to your apps index.js or index.ts: 

var _log = console.log;
 
console.log = function () {
    if (arguments[0].indexOf('[HMR]') == -1) //remove hmr logging
        return _log.apply(console, arguments);
};

**Comment by lorenzomigliorero** [comment]
Import `log` module directly in your bundle, and change logLevel:

```
import { setLogLevel } from 'webpack/hot/log';
setLogLevel('none');
```

**Comment by maxmaxmaximus2** [comment]
@lorenzomigliorero set `var logLevel = "none";` by default OMG
ALL PEOPLE HATE IT ((((

**Comment by geiszla** [comment]
For those who can't make it work with `import { setLogLevel } from 'webpack/hot/log';`, see this comment: https://github.com/webpack/webpack/pull/6265#issuecomment-430932442

**Comment by NathanParsonKoroso** [comment]
None of these suggestions worked, except for the CLI option!!

``` 
webpack --client-log-level warning
// or 
webpack --client-log-level error
```

It defaults to `info` which is where all the [HMR] AND [WDS] spam comes from.

**Comment by IAMtheIAM** [comment]
Hey guys, none of these suggestions worked for me, except the CLI option does!!

``` 
webpack --client-log-level warning
// or 
webpack --client-log-level error
```

It defaults to `info` which is where all the [HMR] AND [WDS] spam comes from.

**Comment by jwld** [comment]
You can also just set `clientLogLevel: none` in your webpack `devServer` config:

```
devServer: {
  clientLogLevel: 'none'
}
```

https://webpack.js.org/configuration/dev-server/#devserverclientloglevel

**Comment by fenok** [comment]
If you're using `webpack-hot-middleware`, you can [configure it](https://github.com/webpack-contrib/webpack-hot-middleware#client) like this: `webpack-hot-middleware/client?reload=true&noInfo=true`

**Comment by agrublev** [comment]
Webpack config 
```
devServer: {
        clientLogLevel: "silent",
```
![image](https://user-images.githubusercontent.com/801433/62006052-7c909300-b0f0-11e9-8a73-ecd28e7efc17.png)

**Comment by elliotberry** [comment]
I love you guys. Finally found this thread after raging hard for like two years
