### ISSUE TITLE
Component doesn't render out in react using HMR

### ISSUE THREAD

**Issue by ionush** [gaearon/react-hot-loader#790]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

What you are reporting:
Component doesn't render out with webpack-dev-server --hot HMR enabled

### Expected behavior

What you think should happen:
Component should be rendered

### Actual behavior

What actually happens:
No component rendering, index.html still loads though

### Environment

React Hot Loader version:
4.0.0-beta.14

Run these commands in the project folder and fill in their results:

1. `node -v`: 8.9.1
2. `npm -v`: 5.6.0

Then, specify:

1. Operating system: ubuntu 16.04 lts
2. Browser and version: Version 63.0.3239.108 (Official Build) (64-bit)

### Reproducible Demo

Please take the time to create a new project that reproduces the issue.

You can copy your project that experiences the problem and start removing things until you’re left with the minimal reproducible demo. This helps contributors, and you might get to the root of your problem during that process.

Push to GitHub and paste the link here.

https://github.com/ionush/hotLoaderV4Bug

run npm i and then npm run dev

**Comment by theKashey** [comment]
You are transpiling your own node_modules - please exclude them from babel-loader.
```js
// webpack conf
     {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        exclude: /node_modules|packages/
      }
```

**Comment by theKashey** [comment]
This look like some webpack bug - when we inject our code to the file - it injects some additional code, and it actually breaks the stuff.

**Comment by theKashey** [comment]
To be more concrete
```js
 __webpack_require__("./node_modules/webpack/buildin/module.js")
```
Could not be execute if the current module IS module.js.

**Comment by theKashey** [comment]
This odd behavior has a roots in RHL, and we should mitigate the problem.

**Comment by theKashey** [comment]
Released in beta16.
