### ISSUE TITLE
Beta published as `@latest` on npm

### ISSUE THREAD

**Issue by timneutkens** [gaearon/react-hot-loader#795]
I'm not sure if this is expected, but people installing `react-hot-loader@latest` will get the beta channel.

`4.0.0-beta.14 is the latest of 99 releases`
https://www.npmjs.com/package/react-hot-loader

**Comment by theKashey** [comment]
Look like my bad. The question is how to fix it.

**Comment by theKashey** [comment]
Fixed!

**Comment by timneutkens** [comment]
💯 thanks!
