### ISSUE TITLE
[RHL-V4] Error while wrapping name  ->  TypeError: Object.defineProperty called on non-object

### ISSUE THREAD

**Issue by swASO** [gaearon/react-hot-loader#804]
since the last update ( from beta 13 to 15 ) we got a lot of these errors 
primary from components from react.semantic-ui.com, but also some of mine

![image](https://user-images.githubusercontent.com/4096843/35141897-de20a7c6-fcfc-11e7-98c0-7e8d40b3d002.png)

is this a bug or do we need to change something ? 

> App.tsx:101 -> export default hot(module)(AppMain) 

"AppMain" is a stateless functional component that wraps "App" - stateful (both in the same file)

**Comment by theKashey** [comment]
Could you provide some code? Or just debug - what was provided into the last function?
Sounds very badly.

**Comment by theKashey** [comment]
That is not an error, hopefully.
I'll raise a PR to suppress this sort of warnings.

**Comment by neoziro** [comment]
Fixed in 4.0.0-beta.16.
