### ISSUE TITLE
Get rid of AppContainer

### ISSUE THREAD

**Issue by theKashey** [gaearon/react-hot-loader#806]
Currently, we are asking to wrap some part of an Application with <AppContainer />.
Prior v4 it was used to "deep-force-update" the rendering tree. In v4 the goal of AppContainer is to perform `hot-render` to understand how application updated, and thus update some hidden behind HOC and decorators stuff.

Hot loader was a quite simple thing in the beginning, but day by day, case by case, it becomes more complex and implements more and more React details, it should not know about.

The problem is simply - hot-loader has to be more simply. And if it will be simply - it will fail to reconcile some Applications.

One could wrap any component at any level with `hot` to "scope" an update to a small branch, and help hot-render not-to-face complex cases.

However, nothing stops up from integration AppContainer into __all__ components. Just before the render (as long we control this method) one could double check that render was not called from existing `hot-render`, and then could run it's own hot-render.

As result - if something prevents AppContainer's hot-render to reconcile deeper nodes, they will run reconciliation by themselves.

Outcome - we could remove 50% code from hot-renderer and still be able to handle any case. Especially crazy stuff about children and fragments.
More of it - this should better handle portals (currently we don't handle them), and maybe future async render.

Performance hint: a single variable comparison on render, a single variable to be stored among instance.

**Comment by neoziro** [comment]
OK so you mean transforming `const Hello => 'hello'` into `const Hello => <Hot>hello</Hot>`, is it right?

I think it is not possible because we have no idea if it is a simple function or a component.

**Comment by theKashey** [comment]
No, I mean add one line to a ProxyComponent's `render` method.

Currently, it checks that elements "version" is the same as the last one. If not - injects the last version. Ie variables and bound functions. Prototype is already overriden.

Afterwards, will also check that elements was _rendered_ as a new version (or not rendered before). If not - call hotReplacementRender with itself as root.

Make any component behave as AppContainer.

**Comment by neoziro** [comment]
@theKashey OK I understand.

**Comment by theKashey** [comment]
The only feature we can achieve here - handle portals.
The only improvement we can get from the change - simplify the code.
The only concern - @gaearon said that he is going to work on hot-reloading in this year. Should we introduce a new level of complexity(even if it is simpler) hacking deeper into React, but just wait for a bright future, when all these features will be a part of react-dom reconciler.

**Comment by theKashey** [comment]
So - I'll try to handle this idea on weekends. And look like it's a "nothing more to add"(yet again).
