### ISSUE TITLE
Fix Babel plugin usage in an external toolkit by hard-coding react-stand-in constant

### ISSUE THREAD

**Issue by insin** [gaearon/react-hot-loader#807]
`REGENERATE_METHOD` is currently imported from `react-stand-in`

```js
const { REGENERATE_METHOD } = require('react-stand-in')
```

This makes it difficult to extract use of `react-hot-loader` in your development setup to an external toolkit module, as you can't alias the modules imported by a Babel plugin and `react-stand-in` imports `react`.

Hard-coding this constant instead makes it possible to use the Babel plugin for this use-case:

```js
const REGENERATE_METHOD = '__reactstandin__regenerateByEval';
```

Do you have any objections to hard-coding this constant instead?

**Comment by theKashey** [comment]
Not sure I understand the problem, but it is clear how to solve it.

**Comment by theKashey** [comment]
I've tried to solve this issue by using [preval](https://github.com/kentcdodds/babel-plugin-preval), but it could not import react-stand-in, as long it gonna to be build after the react-hot-loader.

So - just hardcoding constant and adding a test to secure the name.

**Comment by insin** [comment]
Nice, thank you!

**Comment by theKashey** [comment]
@insin - beta 16 just got released. Please check that it fulfils your requirements.

**Comment by insin** [comment]
It works beautifully, thanks: I can now externalise all the react-hot-loader config I need, so I don't  need to install development-only dependencies in my app, or runtime dependencies in my development config 👍

**Comment by theKashey** [comment]
But you have to entangle your application's code with our, like `AppContainer` or `hot`?

**Comment by insin** [comment]
No, I use [react-hot-loader-loader](https://github.com/NoamELB/react-hot-loader-loader) to add the `hot` call to the main app module only when serving the app in development mode. 

The react-hot-loader dependency is managed by [nwb](https://github.com/insin/nwb), so with this change in place I can now point to the absolute path to the `react-hot-loader/babel` plugin and alias `react-hot-loader` in my Webpack config so the generated code can resolve it: https://github.com/insin/nwb/blob/58ab23b8a30d0f3d5f870ba2d78436b4c0e8f226/src/react/index.js#L114-L139

**Comment by theKashey** [comment]
Wow, and then magic happens.
Oh, how I wish  react-hot-loader-loader to handle async chunks.
