### ISSUE TITLE
Is the redbox-react dependency still needed? [v4]

### ISSUE THREAD

**Issue by insin** [gaearon/react-hot-loader#808]
While playing around with the `errorReporter` prop in `react-hot-loader@next`, I noticed it has a dependency on `redbox-react` which isn't being used - should this be the default `errorReporter` or is the dependency no longer needed?

**Comment by theKashey** [comment]
No longer needed. Good catch.

**Comment by neoziro** [comment]
Yes good catch! I had seen it but I forgot, thanks!

**Comment by neoziro** [comment]
Let's remove this useless dependency!

**Comment by neoziro** [comment]
Fixed in [v4.0.0-beta.17](https://github.com/gaearon/react-hot-loader/releases/tag/v4.0.0-beta.17).
