### ISSUE TITLE
Non-JS root component? (Scala)

### ISSUE THREAD

**Issue by launchriot** [gaearon/react-hot-loader#809]
Been trying to figure out how to use react-hot-loader. I mount my component here:

```
ReactDOM.render(
    <MyApp/>,
    document.getElementById("app")
);
```
and that element that has `id="app"` is inside of a scala file, not a js file. The docs and my research all point to a root container that is like a parent component? I tried:

```
ReactDOM.render(
<AppContainer>
    <MyApp/>
</AppContainer>,
    document.getElementById("app")
);
```
and wasn't sure how to handle this part:

```
// Webpack Hot Module Replacement API
if (module.hot) {
  module.hot.accept('./containers/App', () => {
    render(App)
  })
}
```
because my ./containers/App equivalent is a scala file.

**Comment by neoziro** [comment]
You should be able to do it in Scala, it is a simple JS code using globals.

**Comment by theKashey** [comment]
As long you have webpack underneath - it should work. If not - then maybe not.

**Comment by launchriot** [comment]
I guess my issue is that 
`import App from "./containers/App"` results in an error because `./containers/App` is a scala file which is not the same syntax as JS. Is there a way to run `module.hot.accept` using (in my example) `<MyApp/>`? What is the App container needed for?

**Comment by launchriot** [comment]
I guess I could just run it as 

```
    if (module.hot) {
      module.hot.accept();
    }
```

**Comment by theKashey** [comment]
Usually you can’t just accept the change. And as long you are able to ‘import’ App - it is not a Scala file.

**Comment by launchriot** [comment]
What do you mean by "Usually you can't just accept the change"?

It is a foo.scala.html file, but within the file there is scala syntax, like

```
@()(implicit foo: Foo, bar: Bar)

@main(Foo("home.title")) {
    <div id="app"></div>
}
```
and it thrown a syntax error, but I can't make changes to this file.

(Thanks for your time/help.)

**Comment by theKashey** [comment]
I mean you can’t “just” “accept” - you have to do something to apply the changes. 

Any way - as it works for you - good luck.

**Comment by neoziro** [comment]
If it is fixed for you I close it, I think writing JS in Scala is not a good idea but good luck!
