### ISSUE TITLE
Problems when `module.exports.__proto__ === null`

### ISSUE THREAD

**Issue by moretti** [gaearon/react-hot-loader#81]
I'm having some problems updating my project to `react-hot-loader` 1.x because of this particular check in [`makeExportsHot.js`](https://github.com/gaearon/react-hot-loader/blob/master/makeExportsHot.js#L20):
```
if (freshExports.hasOwnProperty(key) &&
```
Essentially my project depends on `cheerio` and one of its dependendencies, [`css-select`](https://github.com/fb55/css-select), is [exporting objects with `__proto__ === null`](https://github.com/fb55/css-select/blob/master/lib/general.js#L12). 

I really think that redefining `__proto__` is a bad idea, but perhaps we could make the check more robust against such cases.

What do you think?

Thanks! :wink:

**Comment by gaearon** [comment]
Is the check failing or something? Can you submit a PR to fix it?

**Comment by gaearon** [comment]
Thanks! By the way, while it's good to have this fix in, you can just set `exclude: /node_modules/` in your loader config: https://github.com/gaearon/react-hot-boilerplate/blob/master/webpack.config.js#L24

This way we won't process any your dependencies.
