### ISSUE TITLE
Add an errorReporter option to the hot() HOC factory

### ISSUE THREAD

**Issue by insin** [gaearon/react-hot-loader#811]
If you add an `errorReporter` option to `hot()`, that can be passed on to the `<AppContainer>` rendered by the HOC it creates.

I've already done this locally to test it out (along with a local change to [react-hot-loader-loader](https://github.com/NoamELB/react-hot-loader-loader) to support configuring `errorReporter` via Webpack rule options): 0e384bbb478253fdb8f53f6b2cd1984c0f2d7b08

**Comment by insin** [comment]
One weird thing I've noticed is that if I create a runtime error in a component's `render()` method the error boundary doesn't handle it during HMR patching, but it does if I refresh the page to render from scratch.

Immediately after adding `{nonexistent.object}` to the `render()` method of a simple `App` component in `src/App.js`, which is exporting `hot(module)(App)`:
![firefox_2018-01-22_02-09-00](https://user-images.githubusercontent.com/226692/35196144-c74cf5bc-ff19-11e7-8090-899a11a31213.png)

After refreshing the page, the error boundary works and my configured `errorReporter` is rendered:
![firefox_2018-01-22_02-09-25](https://user-images.githubusercontent.com/226692/35196148-d3c127d2-ff19-11e7-8151-f986cb841eb4.png)

**Comment by neoziro** [comment]
We will deprecate `errorReporter` this is why it is not in `hot`. Instead the user would have to implement its own ErrorBoundary.

But we need to check deeply the behaviour you experienced. Maybe `componentDidCatch` is not called with HMR. @theKashey an idea?

**Comment by theKashey** [comment]
Should. But it is easy to reproduce the problem and found out the problem.

**Comment by theKashey** [comment]
You are right. If error boundary will be "above" the AppContainer - it will be notified about an error, but not about HRM event, as long this is just different things.
Implementing some notification mechanism is not a good idea.

There is two ways to solve
 - export a `top` function, wrap with it your application, and we will deep-force-update it on HRM event, bypassing all the boundaries.
 - support custom error reporters. Far easier way. Maybe not via `hot` function, but via `setConfig`.

**Comment by theKashey** [comment]
Ok, I've found a problem with error and open an PR to fix it. 
Why do I thounght that try...finally will swallow the error?

**Comment by theKashey** [comment]
About errorBoundaries - @neoziro just proposed in another issue, to place it just __after__ AppContainer. Should work for any case (after PR to swallow error got merged)

**Comment by neoziro** [comment]
Documented in [v4.0.0-beta.17](https://github.com/gaearon/react-hot-loader/releases/tag/v4.0.0-beta.17).
