### ISSUE TITLE
Component gets unmounted

### ISSUE THREAD

**Issue by xiaoouLi** [gaearon/react-hot-loader#816]
The following returns false:
nextType === 'object' && prevElement.type === nextElement.type && prevElement.key === nextElement.key;
since prevElement.type === nextElement.type is comparing two component objects instead of two string,
which leads to a component unmount...

Am I doing anything wrong?

Thanks!

**Comment by theKashey** [comment]
Look like this is an internals of react-dom.
It will return false unless you got react-hot-loader configured. That's our goal - bypass this comparison.

**Comment by xiaoouLi** [comment]
@theKashey thank you for your answer. 
I already configured react-hot-loader in webpack.config.js, like this:
`const webpack = require('webpack');
const path = require('path');

const config = {
  entry: [
    'webpack-dev-server/client?http://localhost:8080', // 是不是可以去掉server
    // 'webpack/hot/dev-server',
    'react-hot-loader/patch',
    './app/src/js/main.js'
  ],
  devServer: {
      hotOnly: true
  },
  devtool: 'source-map',
  module: {
    loaders: [{
      test: /\.jsx?$/,
      exclude: /(node_module|bower_components)/,
      loader: 'babel-loader',
      query: {
        presets: ['react', 'es2015', 'stage-0'],
        // presets: ['react', 'es2015', 'stage-0', 'react-hmre'],
        plugins: ['transform-decorators-legacy', 'react-hot-loader/babel'],
      },
    },
    {
      test: /\.css$/, // Only .css files
      loader: 'style-loader!css-loader?modules&localIdentName=[name]---[local]---[hash:base64:5]', // Run both loaders
    },
    {
      test: /\.(png|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: 'url-loader',
    }],
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production'),
      },
    }),
    new webpack.HotModuleReplacementPlugin(),
  ],
  output: {
    filename: './prod/reactapp.js',
    publicPath: '/', // why

  },
};

module.exports = config;

`
While it's still not working. 

I tried with react-transform-hmr before which worked without triggering component unmounted, but I saw react-transform-hmr is deprecated so that I'm replacing it with react-hot-loader now...

Is there anything wrong in the webpack.config.js?

Thanks!!!

**Comment by theKashey** [comment]
Yep, sure. The problem is... not inside webpack config :) In it inside your code - react-hot-loader just could not digest it. Happens usually with the current version.

How to solve -> **install react-hot-loader@next** and try again. If it will not help - then we will need and example with a problem to reproduce.

**Comment by xiaoouLi** [comment]
@theKashey Still doesn't work.

I guess it's probably wrong with this part:


`
const
  middleware = applyMiddleware(thunk),
  store = createStore(reducer, middleware),
  render = (DialogComponent, RouterComponent) => {
    ReactDOM.render(
      <Provider store={store}>
        <AppContainer>
        <div>
          <DialogComponent />

        </div>
        </AppContainer>
      </Provider>
    , document.getElementById('reactapp-content'));
  };

slc.react = function () {
  render(DialogComponent, RouterComponent);
};

if(module.hot) {
  module.hot.accept('./RouterComponent', function() {
    const newRouterComponent = require('./RouterComponent').default;
    const newDialogComponent = require('./DialogComponent').default;
    render(newDialogComponent, newRouterComponent);
  });
  module.hot.accept('./DialogComponent', function() {
    const newRouterComponent = require('./RouterComponent').default;
    const newDialogComponent = require('./DialogComponent').default;
    const Runinfo = require('./common/components/runInfo/RunInfo').default;
    render(newDialogComponent, newRouterComponent);
  });
}
`

Is it because I'm re-rendering a composite component so that the element.type is the object the component?

Big THANKS :dancing_men:

**Comment by xiaoouLi** [comment]
Ignore the part above if(module.hot)...Have no idea why the format got weird...

**Comment by theKashey** [comment]
And can you debug - which component is actually got unmounted. It element.type.name / element.type.displayName.
From the code perspective, it should be ok.

**Comment by xiaoouLi** [comment]
It's "DialogComponent" which is the updated one.

**Comment by xiaoouLi** [comment]
The thing is on the current page only DialogComponent is rendered. Then I updated a file which is a child component of DialogComponent. 
I add module.hot.accept handler in my main.js file to catch all updates and then re-render the two components that can have updates.

I guess there is something to do with re-rendering DialogComponent in the hot.accept handler

**Comment by theKashey** [comment]
Double check - the element.type should be an ProxyComponent - a wrapper around DialogComponent. If not - React-hot-loader does not instrument React properly.
How to debug - React.createClass should be patched_createClass from RHL. The "patch" file, you did include, replacing the original one, but maybe something went wrong.

Could you provide full sources, to let me play with them a bit?

**Comment by xiaoouLi** [comment]
Yeah, it's still the component class itself instead of a proxy. (I compared it with the result of react-transform-hmr, and then I know what you mean by "proxyComponent").
hmm... I think there is something wrong with my config file, cause react-proxy package is not loaded at all which is loaded for the case of react-transform-hmr.

**Comment by xiaoouLi** [comment]
BTW, there is no react-proxy dependency for version 4. I downgraded RHL back to 3 again.

**Comment by theKashey** [comment]
React-stand-in is standing in for react-proxy in v4. But this is still the same approach.

**Comment by xiaoouLi** [comment]
OK, problem solved. 
Very stupid issue: My webpack is under production env...That's why HMR is disabled!!! 

Thanks @theKashey for your great help!!!
