### ISSUE TITLE
react-hot-loader is causing `SectionList` to enter an infinite loop in react-native

### ISSUE THREAD

**Issue by omnikron** [gaearon/react-hot-loader#824]
This took me a long time to track down – react-hot-loader was added by a developer who left before I started working on this project and I may have gotten some details wrong, but removing it from our .babelrc fixed the issue completely.

### Description

Using react-hot-loader with react native and `SectionList` causes an infinite loop.

### Expected behavior
A `SectionList` component should be rendered OK (it works for `FlatList` for example).

### Actual behavior
When rendering a `SectionList` component, react-native goes into an infinite loop while trying to render the underlying `VirtualizedList` component. This only happens while `react-hot-loader` is installed.

### Environment

React Hot Loader version: "^3.0.0-beta.7"

Run these commands in the project folder and fill in their results:

1. `node -v`: v8.9.2
2. `npm -v`: 5.5.1

Then, specify:

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.2
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.1.1 => 16.1.1
  react-native: ^0.50.3 => 0.50.3

### Reproducible Demo

https://gist.github.com/omnikron/6ed50e102a800263afc59b8065dcdc1c

**Comment by theKashey** [comment]
Just dont used React-Hot-Loader and react native -> https://facebook.github.io/react-native/blog/2016/03/24/introducing-hot-reloading.html

**Comment by omnikron** [comment]
@theKashey yeah, I thought that was the case. I didn't actually know we were using it, it was added before I started on the project and not documented anywhere.  I thought I would make an issue partially just to make it googleable for any other lost souls, because this took up nearly a whole day!

**Comment by theKashey** [comment]
That’s a good idea.
