### ISSUE TITLE
Not hot reloading 'create-react-class' components

### ISSUE THREAD

**Issue by YouHusam** [gaearon/react-hot-loader#831]
### Description

Components created with 'create-react-class' are not being hot reloaded, webpack compiles, but the component is not updated in the browser, if I change the component to a es6 class, it works as expected. We have almost 200 components using create-react-class so I'm afraid updating them is not currently an option.

### Expected behavior

Component should rerender if it's made with 'create-react-class'

### Actual behavior

webpack compiles but browser doesn't rerender

### Environment

React Hot Loader version: 4.0.0.beta-18

`node -v`: v8.9.4
`npm -v`: v5.6.0

Operating system: MacOS 10.13.2
Browser and version: Google Chrome 63.0.3239.132

**Comment by theKashey** [comment]
I probably should ask you to run codemod against your sources (https://github.com/reactjs/react-codemod#create-element-to-jsx), but I thought that createClass should work. Let me double check.

**Comment by YouHusam** [comment]
@theKashey I ran codemod but it broke 90 unit tests.
Thank you very much

**Comment by theKashey** [comment]
:( Usually, it works fine. You can always stash or roll back changes.
V4 should normally work with any "classes" - es5, es6 or "createClass", as long they are es5. But we did test the elder ways to react.

**Comment by YouHusam** [comment]
Please note `createReactClass` was added in react 16 because they deprecated `React.createClass` maybe something changed there

**Comment by theKashey** [comment]
@YouHusam - just tested, and `createClass` works fine. The only concern - it will not update `bound` functions. We decided not to relay on the way createClass auto-binds methods, as v3 did. "Too internal-ish"

**Comment by YouHusam** [comment]
@theKashey Looks like that's the problem, it's working but I was testing in a bound function. Thank you very much for your time

**Comment by theKashey** [comment]
Anyway. I should point this problem and way to solve in readme

**Comment by wordofchristian** [comment]
Is there no may to make it do a full reload when a bound function changes? Right now it just reports a replacement but is not updated which is not ideal.

**Comment by wordofchristian** [comment]
> ... but still encouraging you to use codemod to level up your code.
I hear you. We currently have a lot of code using some legacy mixins that can't be codemoded away. We are in the process of migrating these components but it takes time. Thank you for re-opening this. If you can point me in the right direction perhaps I can help.

**Comment by theKashey** [comment]
I know how to detect the issue 
I don't know how to "stop RHL from replacing class", as long another part of RHL will throw an Exception, if something was not replaced.

Code is here - https://github.com/gaearon/react-hot-loader/blob/master/src/proxy/createClassProxy.js#L292
If RHL unable to "merge" old and new version - it should re-create a proxy, and return a brand new one (https://github.com/gaearon/react-hot-loader/blob/master/src/proxy/createClassProxy.js#L171)

**Comment by neoziro** [comment]
I am sorry but we will not solve this problem, `create-react-class` is deprecated and having React Hot Loader working with it is not a priority. For now just reload page at every changes. It is another motivation to migrate!
