### ISSUE TITLE
[v4] Arrow functions don't update with TypeScript ES5 target

### ISSUE THREAD

**Issue by Kimahriman** [gaearon/react-hot-loader#835]
### Description

Arrow functions don't hot update when using TypeScript to transpile to ES5. It's not a huge deal since we can just target ES2015 and use Babel from there. Just curious if this was expected behavior or not.

### Example

This example was modified from the `webpack` example. Babel is still included after the TypeScript compilation to include the hot reloader plugin.

Hello.tsx:
```typescript
import React from 'react'

class Hello extends React.Component {

  getText = () => {
    return "Hello world"
  }

  render() {
    return this.getText()
  }
}

export default Hello
```

tsconfig.json:

```json
{
    "compilerOptions": {
        "baseUrl": ".",
        "sourceMap": true,
        "allowSyntheticDefaultImports": true,
        "target": "es5",
        "allowJs": true,
        "jsx": "react",
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

### Expected behavior

Changing the text "Hello world" to something else will change the text in the browser

### Actual behavior

It doesn't change

### Environment

React Hot Loader version: 4.0.0-beta.18

Run these commands in the project folder and fill in their results:

1. `node -v`: v8.4.0
2. `npm -v`: 5.6.0

Then, specify:

1. Operating system: OSX Sierra
2. Browser and version: 63.0.3239.132

**Comment by theKashey** [comment]
ES5 "arrow" function may work, and may not. There is no normal way to make it stable :(

**Comment by theKashey** [comment]
React-hot-loader uses power of babel to hack into the classes and inject the magic method to regenerate the methods.
Into the "classes", not arbitrary prototype-based something.

We should clearly point on this in readme.

**Comment by neoziro** [comment]
RHL requires Babel, so it is expected.
