### ISSUE TITLE
[v4] Breaks if you define `require` somewhere

### ISSUE THREAD

**Issue by kentor** [gaearon/react-hot-loader#838]
### Description

If you define `require` anywhere in your code (to something not a function specifically), this breaks the page with a `_require` is not a function error.

This happens when compiling with webpack with the `react-hot-reload/babel` plugin in `.babelrc`.

### Expected behavior

To not break

### Actual behavior

Get `Uncaught TypeError: _require is not a function`

### Environment

React Hot Loader version: 4.0.0-beta.18

Run these commands in the project folder and fill in their results:

1. `node -v`: 8.9.0
2. `npm -v`: 5.5.1

### Reproducible Demo

Check out this branch:

https://github.com/kentor/react-boilerplate/tree/react-hot-loader-4.0

run `yarn` and `npm start`. Go to `localhost:10000` and open console to see error.

This causes the issue:

https://github.com/kentor/react-boilerplate/commit/92a3b2265411dcc61169f8616b50275575e1caf2

**Comment by theKashey** [comment]
Sorry. But there is no way to fix it.
`Require` is the only command one could use to `require` a module. You shall not shadow a few "system" variables, like `module`, `require`, `exports` as long there is no other way to repeat the same functionality they could provide.

It is possible to `fix` the issue, just by repeating v3 approach, and making React-hot-loader, you know, a global. But better - just don't shadow require.

**Comment by idan** [comment]
Hey there,

I'm seeing a suspiciously similar error; AFAIK I don't see `require()` getting redefined anywhere in the generated webpack bundle, and yet I get `Uncaught ReferenceError: require is not defined` from the line: `var React=_interopDefault(require("react"))`

Using webpack 4.1.x with RHL 4.0.0.

Any idea how to run this down? I haven't changed any of my code, and it works in development, but when I generate a bundle for production it seems to always contain this landmine.

**Comment by idan** [comment]
To be clear @theKashey — if you can just suggest a direction for me to dig further, I'd be grateful. I'm pretty stumped. Could one of my dependencies have created this shadow? Why is that not showing up in my webpack-compiled bundle, then?

Help me, Obi-Wan Kenobi. You're my only hope.

**Comment by theKashey** [comment]
Sorry, couldn't help you. Let me first create an example with webpack 4 to reproduce.
I know that webpack _sometimes_ does not provide `requre` to a module, but I dont know when and why.

PS: you can try to ask webpack team about this. They shall know more.

**Comment by idan** [comment]
@theKashey I did some more detective work and filed an issue with webpack: webpack/webpack#6752

It's clear that webpack doesn't notice the cjs require; when I run webpack in verbose mode, the react chunk does not list itself as being required by `react-hot-loader.production.min.js`.

I created a minimal example in an attempt to isolate the bug, but I'm unable to reproduce the broken behavior with the smaller project. In that smaller project, the RHL production shim chunk is properly transformed. 🤔 

If you have a moment to check out the webpack issue and say if you can think of a direction to look in, I'd be grateful!

**Comment by theKashey** [comment]
Great investigations!  I am in the same situation as you -> 🤷‍♂️
let's await for some help from webpack team.

**Comment by idan** [comment]
OK, solved! This was totally my fault.

My config specified `module.noParse: /\.min\.js/,` 🤦‍♂️  because of some other library we include that is already minified.

Hence the `react-hot-loader.production.min.js` wasn't processed.

Thanks for the positive vibes! <3

**Comment by theKashey** [comment]
Hm, maybe we should not include _min_ in the file name.

**Comment by neoziro** [comment]
@theKashey no `.min.js` is not the problem here.
@idan you should fix it from your side, `.min.js` is dangerous, you should be more explicit and specify something like `jquery|lodash`.
