### ISSUE TITLE
Unable to reload Reducers

### ISSUE THREAD

**Issue by Sangeli** [gaearon/react-hot-loader#839]
### Description

I am trying to get hot reloading working for my Reducers. However, when I change any files in the Epic tree I get this message in my Chrome debugger:

```
Ignored an update to unaccepted module ./src/client/root/reducer.js -> ./src/client/root/store.js -> ./src/client/client.js -> 0
```

Note that hot reloading of components works fine

### Expected behavior

Should hot reload changes to reducers without needing a page refresh

### Actual behavior

Warning on Chrome about not being able to hot reload thosechanges

### Environment

React Hot Loader version:

Run these commands in the project folder and fill in their results:

1. `node -v`: v8.9.0
2. `npm -v`:5.5.1

Then, specify:

1. Operating system: macOS High Sierra 10.13.3
2. Browser and version: Chrome 63.0.3239.132 

### Reproducible Demo

Here is my top level render file:

```
import React from 'react'
import ReactDOM from 'react-dom'
import { Provider } from 'react-redux'
import RedBox from 'redbox-react'
import { addLocaleData } from 'react-intl'
import ConnectedIntlProvider from './root/ConnectedIntlProvider'

//our modules
import App from './root/App'
import configureStore from './root/store'
import { concatAll } from 'rxjs/operators/concatAll'


// Save a reference to the root element for reuse
const rootEl = document.getElementById('main')
const store = configureStore()
ReactDOM.render(
  <Provider store={store}>
    <ConnectedIntlProvider>
      <App />
    </ConnectedIntlProvider>
  </Provider>,
  rootEl
)

/**
 * Setup up Hot Module Replacement in local dev mode.
 */
if (process.env.NODE_ENV === 'local' && module.hot) {
  module.hot.accept('./root/App', () => {
    // eslint-disable-next-line global-require,import/no-extraneous-dependencies
    const { AppContainer } = require('react-hot-loader')
    // eslint-disable-next-line global-require
    const NextApp = require('./root/App').default
    /**
     * Render the app along with the Hot Module Replacement app container.
     */
    ReactDOM.render(
      <Provider store={store}>
        <AppContainer>
          <ConnectedIntlProvider>
            <NextApp />
          </ConnectedIntlProvider>
        </AppContainer>
      </Provider>,
      rootEl
    )
  })
}
```

And store.js:

```
import { createStore, applyMiddleware } from 'redux'
import { composeWithDevTools } from 'redux-devtools-extension'
import { createEpicMiddleware } from 'redux-observable'

import reducer from './reducer'
import epic from './epic'

export default function configureStore(preloadedState) {
  const epicMiddleware = createEpicMiddleware(epic)
  const middlewares = [epicMiddleware]
  const middlewareEnhancer = applyMiddleware(...middlewares)

  const storeEnhancers = [middlewareEnhancer]

  const composedEnhancer = composeWithDevTools(...storeEnhancers)

  const store = createStore(reducer, preloadedState, composedEnhancer)

  if (process.env.NOVE_ENV === 'local' && module.hot) {
    /*
         * Hot reload Redux reducers in local dev mode.
         */
    module.hot.accept('./reducer', () => {
      // eslint-disable-next-line global-require
      const nextRootReducer = require('./reducer').default
      store.replaceReducer(nextRootReducer)
    })


  return store
}

```

Note I removed some code her to make it cleaner to read

**Comment by theKashey** [comment]
RHL does not cover this case, as long this is just a HRM setup issue. Look like `module.hot.accept('./reducer'`does not work.

PS: In the first file you have 2 different `ReactDOM.render` methods. They should be the same, or you will lose component state on the first render(but only on first)

**Comment by Sangeli** [comment]
>RHL does not cover this case, as long this is just a HRM setup issue. Look like module.hot.accept('./reducer'does not work.

OK so you're saying the problem is how I configured the HRM on the server rather than RHL on the client, yes?

**Comment by theKashey** [comment]
RHL is only about React and React Components. Everything else is generic Hot-module-replacement and you have to handle it by yourself. As I can see, you configured it correctly, and it should work.

It seems that ` module.hot.accept('./reducer', () => {` was not got executed. Are you sure, that ENV is local?

**Comment by Sangeli** [comment]
>RHL is only about React and React Components. Everything else is generic Hot-module-replacement and you have to handle it by yourself. As I can see, you configured it correctly, and it should work.

Right. I need to take this to the HMR issue page.

>It seems that module.hot.accept('./reducer', () => { was not got executed. Are you sure, that ENV is local?

Yes, I confirmed it.
