### ISSUE TITLE
Cannot set property displayName on class which has only a getter

### ISSUE THREAD

**Issue by humulus** [gaearon/react-hot-loader#845]
### Description
This part of code is unable to set displayName because class has only getter's
`react-hot-loader/packages/react-stand-in/src/createClassProxy.js`
```
// Try to infer displayName
const displayName = getDisplayName(CurrentComponent)
ProxyFacade.displayName = displayName
```

### Expected behavior
react-hot-loader should support classes with static getter's like 
```
static get displayName() {
    return "button";
}

static get defaultProps() {
    return {
        type: "primary",
    };
}

```

### Actual behavior
`react-hot-loader/packages/react-stand-in/src/createClassProxy.js`

```
Uncaught TypeError: Cannot set property displayName of function C3Chart() {
    _classCallCheck(this, C3Chart);

    return _possibleConstructorReturn(this, (C3Chart....<omitted>... } which has only a getter
    at update (createClassProxy.js?1dd3:210)
```

### Environment
React Hot Loader version: 4.0.0-beta.21
Node version: v8.9.4
NPM version: 5.1.0
Ubuntu 14.04
Google Chrome: 64

**Comment by humulus** [comment]
### temporary solution
```
if (process.env.NODE_ENV !== 'production') {
  Object.defineProperty(ClassObject, 'displayName', {
    set: function (val) {
      this.__displayName = val
    }
  });
}
```
I still think that createClassProxy should support static get displayName

**Comment by theKashey** [comment]
Ok, I'll just use safeDefineProperty as we use for the rest of props.

**Comment by neoziro** [comment]
Should be fixed in beta.23.
