### ISSUE TITLE
Fix CI in v4

### ISSUE THREAD

**Issue by neoziro** [gaearon/react-hot-loader#846]
Jest is not returning a zero code in v4. The CI seems green but it is red.

**Comment by brianlmacdonald** [comment]
Can I give this a shot?

**Comment by neoziro** [comment]
@brianlmacdonald of course! You are welcome!

**Comment by brianlmacdonald** [comment]
@neoziro got CI passing. Closed #847 because I accidentally committed React 16 as a dependency after running CI. PR #848 fixes that.

**Comment by neoziro** [comment]
Fixed.
