### ISSUE TITLE
Saga and reducer not correctly reloaded in some cases

### ISSUE THREAD

**Issue by thomasthiebaud** [gaearon/react-hot-loader#851]
### Description

In some cases, the sagas and reducer are not correctly reloaded (they are replaced, but the old one are still running). The problem seems to be related to where are the sagas and reducer are imported.

### Expected behavior

The saga and reducer should be hot reloaded in all cases

### Actual behavior

TL;DR Have a look at the Reproducible Demo

What actually happens:

In this example, the saga and reducer are not replaced correctly in the application (but the component itself is correctly hot reloaded)

```
// Home
export default Loadable({
  loader: () => import(/* webpackChunkName: "home" */ './Container'),
  loading() {
    return <div>Loading...</div>
  },
  render(Component, props) {
    state.injectReducer('home', Component.reducer)
    state.injectSagas(Component.sagas)

    return <Component.default {...props} />
  },
})
```

but in this example everything is working fine (component, reducer and saga)

```
// Home

import reducer from './reducer'
import sagas from './sagas'

export default Loadable({
  loader: () => import(/* webpackChunkName: "home" */ './Container'),
  loading() {
    return <div>Loading...</div>
  },
  render(Component, props) {
    state.injectReducer('home', reducer)
    state.injectSagas(sagas)

    return <Component.default {...props} />
  },
})
```

Both `injectReducer` and `injectSagas` are called in both case, but the old one keeps running in the application.

The `Home` component is used like this 

```
const routes = [{
  component: Home,
}]

const Router = () => (
  <BrowserRouter>
    {renderRoutes(routes)}
  </BrowserRouter>
)

export default hot(module)(Router)
```

### Environment

React Hot Loader version: 4.0.0-beta.21

Run these commands in the project folder and fill in their results:

1. `node -v`: v6.11.3
2. `npm -v`: 3.10.10

Then, specify:

1. Operating system: Osx
2. Browser and version: Google Chrome Version 64.0.3282.140 (Official Build) (64-bit)

### Reproducible Demo

In both repositories, try to edit the delay in `src/routes/Home/sagas.js` (500ms <-> 2000ms) and save without reloading. In one case the new delay is correctly applied, not in the other case.

Desire behaviour : https://github.com/thomasthiebaud/react-kit/tree/major-refactor
Issue example: https://github.com/thomasthiebaud/react-kit/tree/RHL-issue

**Comment by theKashey** [comment]
1. Don't ever do something not related to `render` inside the `render` function.
2. React-loadable if "HMR-unfriendly", it will totally ignore it, and keep the old component (not reload it).
3. Even if you setup HMR+RHL below and seeing the new component - Component.reducer will the same. As long loader was not remounted - it will not reload Component.

There is nothing you can do here, but change the way it works -> wrap Container with `hot`, and let him update reducers somehow.

**Comment by thomasthiebaud** [comment]
I will try that, thanks a lot for the ideas
