### ISSUE TITLE
SSR broken in beta.22

### ISSUE THREAD

**Issue by neoziro** [gaearon/react-hot-loader#854]
Render is now asynchronous so hydrate is broken.

<img width="534" alt="screen shot 2018-02-10 at 21 17 07" src="https://user-images.githubusercontent.com/266302/36066317-dbafa520-0ea7-11e8-93c9-84fe7d0afd09.png">

**Comment by theKashey** [comment]
🤷‍♂️ There is no RHL of server side, there is no RHL side effect before HMR event. How you do it?

**Comment by theKashey** [comment]
@neoziro - still need example to reproduce.

**Comment by neoziro** [comment]
Fixed in beta.23.
