### ISSUE TITLE
After update from beta21 to beta22 got errors and warnings on test execution

### ISSUE THREAD

**Issue by yuri-sakharov** [gaearon/react-hot-loader#856]
### Description

After update from beta21 to beta22 got 
warnings on test execution:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```
errors  on test execution like this:
```
 Error: expected undefined to sort of equal 'span'
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.eql (node_modules/expect.js/index.js:230:10)
      at Context.it (app/components/custom-alert/custom-alert-spec.js:22:42)
```

### Expected behavior

Works without errors and warnings

### Environment

React Hot Loader version: `4.0.0-beta.22`

Run these commands in the project folder and fill in their results:

1. `node -v`: v9.4.0
2. `npm -v`: 5.6.0

1. Operating system: MacOs Sierra 10.12.6 
2. Test running: on mocha v 5.0.0

**Comment by theKashey** [comment]
The first warning is not a warning. Something just killed a component of yours.
Could you please provide any code to reproduce the problem?

**Comment by yuri-sakharov** [comment]
I will try.

**Comment by AndyBarron** [comment]
I have repro for this, but it's causing my Jest snapshot tests to return `null` instead of the proper object. Confirmed that going from `4.0.0-beta.21` to `4.0.0-beta.22` causes it (and rolling back fixes it).

Node version: 8.9.4
NPM version:  5.6.0
OS: Ubuntu 16.04 (Windows Subsystem for Linux on Windows 10)
Test frameworks: Jest 22.2.2 / Enzyme 4.17.0 / jest-enzyme 4.2.0

**Comment by theKashey** [comment]
Just finished finished yet another fixing iteration, and I still have no idea how to reproduce this case. 
We need some code.

**Comment by AndyBarron** [comment]
Alright, I'll see if I can throw together a minimal example when I can

**Comment by theKashey** [comment]
@AndyBarron - I don't need a minimal example, I need any example.

**Comment by AndyBarron** [comment]
Unfortunately, it's in a private repo atm. I will pull out the relevant bits.

**Comment by theKashey** [comment]
Ok. Btw - how you got RHL running in jest environment? It should be transparent(and disabled) when HMR(module.hot) is not active.

**Comment by neoziro** [comment]
Should be fixed in beta.23.
