### ISSUE TITLE
[v4] StrictMode warns even when no unsafe methods are used

### ISSUE THREAD

**Issue by apostolos** [gaearon/react-hot-loader#860]
### Environment

React Hot Loader version: 4.0.0-beta.22
React: 16.3+

### Description

When enabling Strict/Async mode for any part of the tree that contains React components, React warns about unsafe lifecycle methods even when the components don't use them.

This only happens when *react-hot-loader/babel* plugin is loaded.

### Expected behavior

There should be no warnings.

### Actual behavior

```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Test

componentWillUpdate: Please update the following components to use componentDidUpdate instead: Test

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

### Reproducible Demo

```jsx
import * as React from 'react';
import { render } from 'react-dom';

class Test extends React.Component {
  render() {
    return <div>test strict</div>;
  }
}

render(
  <React.StrictMode>
    <Test />
  </React.StrictMode>,
  document.getElementById('app')
);
```

**Comment by theKashey** [comment]
- `componentWillUpdate` is already removed
- `componentWillMount` to be replaced by `componentDidMount`
- we could not replace `componentWillReceiveProps` yet, but as long it will coexist with React until version 17 - we might just prefix it by "UNSAFE" for a while.

**Comment by JustFly1984** [comment]
Sorry to bug you out, but I have issues with `<StictMode />`  in `gatsby v2`. it has `react-hot-loader@4.3.12` in dependencies, and I'm using it for example in my attempt to make new google maps api for React. I need to test it with SSR, and at the same time to test it in strict mode. It seems like I can't do both at the same time.

**Comment by JustFly1984** [comment]
Should I make new issue? I've made an issue in gatsby: https://github.com/gatsbyjs/gatsby/issues/10179
