### ISSUE TITLE
Bug? Hot reload doesn't work - no error provided

### ISSUE THREAD

**Issue by jakub2** [gaearon/react-hot-loader#865]
### Description

I have react hot reload setup, but it doesn't work - I can see that it happens in the background - I can see it in the console.

Here's an example after I make a change to my code:
```
[HMR] Waiting for update signal from WDS...
client?7071:77 [WDS] Hot Module Replacement enabled.
2client?7071:80 [WDS] App updated. Recompiling...
client?7071:222 [WDS] App hot update...
log.js:23 [HMR] Checking for updates on the server...
browser.js:49 Warning: [react-router] You cannot change <Router routes>; it will be ignored
warning @ browser.js:49
routerWarning @ routerWarning.js:21
Router_componentWillReceiveProps @ Router.js:113
callComponentWillReceiveProps @ react-dom.development.js:6389
updateClassInstance @ react-dom.development.js:6575
updateClassComponent @ react-dom.development.js:7848
beginWork @ react-dom.development.js:8225
performUnitOfWork @ react-dom.development.js:10224
workLoop @ react-dom.development.js:10288
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
renderRoot @ react-dom.development.js:10366
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
requestWork @ react-dom.development.js:10878
scheduleWorkImpl @ react-dom.development.js:10732
scheduleWork @ react-dom.development.js:10689
scheduleTopLevelUpdate @ react-dom.development.js:11193
updateContainer @ react-dom.development.js:11231
renderSubtreeIntoContainer @ react-dom.development.js:15229
render @ react-dom.development.js:15290
render @ main.tsx:14
(anonymous) @ main.tsx:30
hotApply @ bootstrap 72856f3d433c3d9cd967:581
(anonymous) @ bootstrap 72856f3d433c3d9cd967:289
Promise.then (async)
hotUpdateDownloaded @ bootstrap 72856f3d433c3d9cd967:288
hotAddUpdateChunk @ bootstrap 72856f3d433c3d9cd967:265
webpackHotUpdateCallback @ bootstrap 72856f3d433c3d9cd967:7
(anonymous) @ 0.72856f3d433c3d9cd967.hot-update.js:1
log.js:23 [HMR] Updated modules:
log.js:23 [HMR]  - 696
log.js:23 [HMR]  - 695
log.js:23 [HMR]  - 694
log.js:23 [HMR]  - 693
log.js:23 [HMR]  - 449
log.js:23 [HMR]  - 414
log.js:23 [HMR] Consider using the NamedModulesPlugin for module names.
log.js:23 [HMR] App is up to date.
```

### Expected behavior

It should show the changes on the webpage without refreshing the page manually.

### Actual behavior

I can see the logs in the console, but not the actual change on the webpage. I can see the change after I manually refresh the page.

### Environment

React Hot Loader version: 3.1.3

Run these commands in the project folder and fill in their results:

1. `node -v`: v8.9.4
2. `npm -v`:5.6.0

Then, specify:

1. Operating system: Windows 7 Enterprise
2. Browser and version: Chrome 64

### Reproducible Demo

I think the problem is here, but not sure:
```
if(module.hot) {
  module.hot.accept('./provider', () => {
    render(AppProvider);
  });
}
```

This is my AppProvider:
```
export const AppProvider = () => {
  return (
    <Provider store={store}>
      <AppRouter />
    </Provider>
  );
}
```

**Comment by theKashey** [comment]
Problem is in AppRouter
> Warning: [react-router] You cannot change <Router routes>; it will be ignored

Is not a warning. You have to extract "routes" not to be affected by hot-loader.
Consider bumping react-router, and react-hot-loader versions.

**Comment by theKashey** [comment]
Refer to React-Router documentation. I could not help here.

**Comment by bamboooooo** [comment]
Have you solved the problem, please? I have the same problem.

**Comment by jakub-astrahit** [comment]
No, I ended up not using hot reload.

**Comment by hermanomark** [comment]
I'm also encountering this problem, sometimes it fixes itself when I restart my machine. But it's really bugging me not to fix this.

this is related: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-start-doesnt-detect-changes

and this: https://github.com/webpack/webpack-dev-server/issues/875

**Comment by theKashey** [comment]
Try to wipe out node_modules and installing them back.
If, by the any reason, you started with one nodejs version, and ended with another (9 -> 10 transition) - something ("native modules") could go wrong.

Plus - I would not recoment using node 10 yet. Is has (at least for me) issues with fs-events, and they are those "file-change-observers" HMR is made with.
