### ISSUE TITLE
react-stand-in is missing

### ISSUE THREAD

**Issue by iamstarkov** [gaearon/react-hot-loader#866]
### Description

there are 2 links to `react-stand-in` in the ["Known limitations and side effects" of the README](https://github.com/gaearon/react-hot-loader/tree/v4.0.0-rc.0#known-limitations-and-side-effects). There is nothing there if you follow the links https://github.com/gaearon/react-hot-loader/tree/next/packages/react-stand-in

### Expected behavior

Something should be there

### Actual behavior

nothing is

### Environment

v4.0.0-rc.0 https://github.com/gaearon/react-hot-loader/tree/v4.0.0-rc.0

**Comment by theKashey** [comment]
Somewhere between beta.19 and beta.21 stand-in was merged into main project.
Here it is - https://github.com/gaearon/react-hot-loader/tree/next/src/proxy

TODO: fix links.
