### ISSUE TITLE
rc0 breaks jest/enzyme testing

### ISSUE THREAD

**Issue by frehner** [gaearon/react-hot-loader#872]
### Description
Recently upgraded from beta-21 to rc.0, and suddenly our jest/enzyme tests are failing in certain spots. I'm definitely not an expert in this area, but to my highly untrained eye it seems that it's related to how enzyme 3.x's `.find()` works when you give it a component.

Here's a link to a repo where you should be able to reproduce the error:
https://github.com/frehner/rhl-react-stand-in

Steps to reproduce:
1. `git clone`
1. `yarn`
1. `yarn test` (tests should pass on beta-21)
1. `git checkout rhl-rc0-fails`
1. `rm -r node_modules && yarn`
1. `yarn test` (tests fail on rc.0)

### Expected behavior
Tests should pass

### Actual behavior
Tests fail

### Environment

React Hot Loader version: beta-21 and rc.0

Run these commands in the project folder and fill in their results:

1. `node -v`: 8.9.4
2. `npm -v`: 5.6.0

Then, specify:

1. Operating system: MacOS 10.13.3 
2. Browser and version: N/A

### Reproducible Demo

Please take the time to create a new project that reproduces the issue.

You can copy your project that experiences the problem and start removing things until you’re left with the minimal reproducible demo. This helps contributors, and you might get to the root of your problem during that process.

Push to GitHub and paste the link here.
https://github.com/frehner/rhl-react-stand-in

Hopefully I got everything in. Let me know if I missed something. Thanks!

**Comment by blittle** [comment]
Confirmed on node `v9.3.0`

**Comment by theKashey** [comment]
Thank you for a bug. Just in time.

**Comment by theKashey** [comment]
Look like this is __not__ a bug. I totally disable RHL and problem still exists, resulting `Child` not to be found in `Root`.

How to solve - `jest --no-cache`

Please confirm that flushing cache is working for you.

**Comment by frehner** [comment]
Looks like that does resolve it. Thank you!
