### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by zerohh** [gaearon/react-hot-loader#877]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

What you are reporting:

### Expected behavior

What you think should happen:

### Actual behavior

What actually happens:

### Environment

React Hot Loader version:

Run these commands in the project folder and fill in their results:

1. `node -v`:
2. `npm -v`:

Then, specify:

1. Operating system:
2. Browser and version:

### Reproducible Demo

Please take the time to create a new project that reproduces the issue.

You can copy your project that experiences the problem and start removing things until you’re left with the minimal reproducible demo. This helps contributors, and you might get to the root of your problem during that process.

Push to GitHub and paste the link here.

**Comment by neoziro** [comment]
Please follow the reporting guideline, thanks.
