### ISSUE TITLE
Dist version of index.js has missing condition

### ISSUE THREAD

**Issue by pristas-peter** [gaearon/react-hot-loader#879]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

The source code of 'index.js' in dist version is missing  ```if (module.hot)``` in  condition.
Since we are also creating a nodejs webpack build and we do not have set NODE_ENV to 'production', the development version is also loaded in node and things like apollo's getDataFromTree for SSR break. 

What you are reporting:
Bug

### Expected behavior
The source code of 'index.js' in dist version should also have ```if (!module.hot || process.env.NODE_ENV === 'production')```

What you think should happen:

### Actual behavior

What actually happens:

### Environment

React Hot Loader version:

Run these commands in the project folder and fill in their results:

1. `node -v`:
2. `npm -v`:

Then, specify:

1. Operating system:
2. Browser and version:

### Reproducible Demo

Please take the time to create a new project that reproduces the issue.

You can copy your project that experiences the problem and start removing things until you’re left with the minimal reproducible demo. This helps contributors, and you might get to the root of your problem during that process.

Push to GitHub and paste the link here.

**Comment by neoziro** [comment]
You should not require the dist version, the entrypoints are in the root directory of the repository. This is the same approach as React.

**Comment by pristas-peter** [comment]
All i do is ```import {hot} from 'react-hot-loader';```. The bug is just a side effect of that.

**Comment by theKashey** [comment]
Condition exists - https://github.com/gaearon/react-hot-loader/blob/master/index.js
```js
'use strict'

if (!module.hot || process.env.NODE_ENV === 'production') {
  module.exports = require('./dist/react-hot-loader.production.min.js');
} else {
  module.exports = require('./dist/react-hot-loader.development.js');
}
```

Please check that you are using the latest version of RHL, as long the issue you are describing were fixed two weeks ago.
