### ISSUE TITLE
"Nothing hot updated"

### ISSUE THREAD

**Issue by th3fallen** [gaearon/react-hot-loader#881]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

What you are reporting: Hot Loader not seeing changed components?

### Expected behavior

What you think should happen: should reload changed components?

### Actual behavior

What actually happens: states "nothing hot updated"

### Environment

React Hot Loader version: 4.0.0

Run these commands in the project folder and fill in their results:

1. `node -v`:9.5.0
2. `npm -v`: 5.6.0

Then, specify:

1. Operating system: OSX 
2. Browser and version: Chrome Latest

### Reproducible Demo

Sadly i cannot distribute the code in a working form but i can share the affected files, here's the gist

https://gist.github.com/th3fallen/90d4e7472fce4d34449479659677fa43

**Comment by theKashey** [comment]
You `AsyncComponent` is not "HMR/RHL friendly". It have to re-import code splitting point.
To get RHL working you have to use:
- [react-universal-component](https://github.com/faceyspacey/react-universal-component)
- [react-imported-component](https://github.com/theKashey/react-imported-component)

Other loaders are not HMR friendly :(

**Comment by th3fallen** [comment]
Thanks for the input,  converted my async loader to use react-universal-component like so but i'm still getting the same result

```export default (componentImport, exportName = 'default', HOCWrapper = false, target = null) => {
  exportName = exportName || 'default';

  return universal(componentImport, {
    loading: Loading,
    key: exportName,
  });
};
```

**Comment by theKashey** [comment]
First double check that NOT async code is replaced correctly (may be you got problems with HMR itself)

Next you could try async loader from our [examples](https://github.com/gaearon/react-hot-loader/blob/master/examples/async-portals/src/async-component.js) - it should work, also `react-imported-component` was created specially for React-Hot-Loader, and also should work.

**Comment by th3fallen** [comment]
I'll try your example the imported comonent also fails with the same issue

**Comment by neoziro** [comment]
@th3fallen this is probably another problem, not relative to async component. [react-loadable](https://github.com/jamiebuilds/react-loadable) or [loadable-components](https://github.com/smooth-code/loadable-components) also work with React Hot Loader v4 following [the guide](https://github.com/gaearon/react-hot-loader#code-splitting).

Be careful of using `hot(module)` in each loaded components (in each module entry in fact).
