### ISSUE TITLE
mobx break in v4

### ISSUE THREAD

**Issue by Sunshine168** [gaearon/react-hot-loader#882]
### Description

What you are reporting:
hot load break with using mobx 

### Expected behavior

What you think should happen:
work well

### Actual behavior

What actually happens:
![image](https://user-images.githubusercontent.com/15126380/36890348-778b1994-1e38-11e8-95c9-b7ffbbd8112c.png)

### Environment

React Hot Loader version:4.0

Run these commands in the project folder and fill in their results:

1. `node -v`:v9.2.1
2. `npm -v`:5.5.1

Then, specify:

1. Operating system: macOS High Sierra
2. Browser and version:Chrome 64.0.3282.186

### Reproducible Demo
[link](https://github.com/Sunshine168/mobx-react-quick-starter/tree/react-hot-loader-v4)

```
http://localhost:3000/counter
```

**Comment by theKashey** [comment]
Your repo is not quite correct - it uses old react-hot-loader and not the last version of mobx,
but, anyway, problem exists.

**Comment by theKashey** [comment]
The problem - subRender could call `render` of a component inside the `render` of that component.
Nested call just blows MobX. Actually this is MobX's bug, but we could change our logic to mitigate it.

**Comment by theKashey** [comment]
Fixed repo - https://github.com/theKashey/mobx-react-quick-starter

**Comment by neoziro** [comment]
@theKashey thanks!

**Comment by theKashey** [comment]
May be we should fix it from our side.

**Comment by Sunshine168** [comment]
thx !
