### ISSUE TITLE
cannot hot loader when the same component is referenced by 2 files

### ISSUE THREAD

**Issue by bochen2014** [gaearon/react-hot-loader#886]
I have latest packages installed to my project
```js
├── react@16.2.0 
├── react-dom@16.2.0 
├── react-hot-loader@4.0.0 
└── react-router-dom@4.2.2 
```

one thing i've noticed today is that, say I have a component called `Component.js` and it is referenced by `./common/index.js` and `./wrapper.js`
```js
//common/index.js
import Component1  from './Component';
   .....

export {
 Component1 
 other_exports
}

//wrapper.js
import { Component1 } from './common'
const Wrapper=()=><div><Component1/></div>
```
then changing `./Component` will cause a page reload, **not** component reload;

However, if I remove the re-export from `index.js`, and refer the component from it's original path,  everything just works fine

is it a known issue? or a bug

**Comment by theKashey** [comment]
This is not related to the React-Hot-Loader only to the Webpack Hot-Module-Replacement setup you might have.
Component update somehow "leaking" thought React-hot-loader `hot`, and causing page refresh.

Just "preserve log" in console, and reproduce - webpack will inform you how the update went from one file to another, bypassing our traps by the way.

PS: if you have a "common pages entry" - you might need to accept changes there, to prevent them from leaking thought secondary entry point.

Better - just wrap with `hot` the Component itself.

**Comment by bochen2014** [comment]
thanks @theKashey  you are absolutely right in this case. 

My previous `hot` decorated module only  points to the root of router;
there is another path which is rooted from my redux store configure which is parallel to my router root;

I've add the `accept` statement in `index.js` and it works fine now. 
thanks again for your help!
