### ISSUE TITLE
Hot reloading break in sub-component and which also cause full page reloading

### ISSUE THREAD

**Issue by wellyshen** [gaearon/react-hot-loader#887]
Here's the [repo](https://github.com/wellyshen/react-cool-starter) and the structure as following:

AppComponent (root component which wrapped by hot helper)
|
|---- HomeContainerComponent
          |
          |---- SubStatelessComponent (It will break hot reloading and cause full page reloaded)

Any suggestion for it?

Environment:
react-hot-loader version: v4

**Comment by theKashey** [comment]
Could not found a react-hot-loader's babel plugin in your configuration.

**Comment by theKashey** [comment]
My bad, it exists. Actually, I could not spot any issues - everything should work. Let me try to run the code.

**Comment by wellyshen** [comment]
@theKashey I'm pretty sure that I have set up RHL according to the document. Let me help you how to reproduce this issue:
1. `git clone https://github.com/wellyshen/react-cool-starter.git`
2. `yarn install`
3. `yarn build`
4. `yarn start`
5. Edit `./src/components/UserList/index.js`

**Comment by theKashey** [comment]
Look like this is completely server side problem and absolutely unrelated to RHL. Webpack's connection socket dies just after the code update.
Fast googling shows 100500 issues around nodemod and webpack-dev-middleware, and most of them already resolved (in a different ways).

**Comment by wellyshen** [comment]
Excepting `nodemon` (use node directly). The sub-components still can't be hot reload (webpack will run re-bundle). Is this related with RHL?

**Comment by theKashey** [comment]
Rhl is front-end only library. Problem is bound to backend.

**Comment by wellyshen** [comment]
If I wrap sub-components with `hot` helper. This issue will be solved. How to explain it?

**Comment by wellyshen** [comment]
OK, I solved this issue by:
* Adjust `nodemon` watch files.
* Because I'm using `react-router-config` to handle my routes, so I use `AppContainer` to do hot reloading for my `routes.js` file.

@theKashey Thank you for your time.

**Comment by ianks** [comment]
@wellyshen can you post an example of hot module replacement with routes.js

**Comment by wellyshen** [comment]
@ianks [Here](https://github.com/wellyshen/react-cool-starter/blob/master/src/client.js#L39) you are.
