### ISSUE TITLE
Non-component modules are reloaded on component change

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#89]
This is an issue to track https://github.com/webpack/webpack/issues/826.

I've had this weird problem more than once: I edit a component, but for some reason a dependent Store gets reloaded (and thus my component's state resets).

It looks like the temporary fix for this is to only enable React Hot Loader for `jsx` files (assuming this is what you use for components). If you use `js` files for everything, you're going to have this bug until https://github.com/webpack/webpack/issues/826 is fixed (or we figure out that I misunderstand something).

**Comment by gaearon** [comment]
Webpack 1.7.0 is out with a fix for this behavior. I **strongly** suggest everyone to upgrade.

**Comment by natew** [comment]
:+1: updated in reapp
