### ISSUE TITLE
Ship "module" compliant version of the library

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [gaearon/react-hot-loader#893]
webpack and many other bundlers support the `"module"` package.json field for providing an ESM-compliant version of a package. As the compilers get more sophisticated, they can then perform better and better tree shaking to whittle down what little code is shipped by RHL in production.

The following things should be added:

1. An ESM build (the same as you have now, but with ES2015 module transpilation turned off and a different file name.)

2. A `"module"` package.json field, pointing to the above.

3. The `"sideEffects"` package.json field, set to `false`. This is the last bit that allows maximum dead code elimination in webpack 4+.

**Comment by evan-scott-zocdoc** [comment]
Actually now that I'm looking at this project's index file, I'm not sure if `#1` and `#2` can be done due to the dynamic require... unfortunately there isn't a package.json way to distinguish between prod vs dev builds at the moment.

`#3` should still happen though.

**Comment by theKashey** [comment]
As long RHL is shipped as a one-big-bundle, and actually has zero "dead" code to eliminate, and also has ~zero code in production - this issues does not make any sence.

**Comment by evan-scott-zocdoc** [comment]
There is some code left around though because the index exports AppContainer and such. The user might be only using the "hot" HOC and the AppContainer placeholder code could then be dead code eliminated.

**Comment by theKashey** [comment]
hot uses AppContainer underneath. It's literally nothing we could tree-shake off RHL.

**Comment by evan-scott-zocdoc** [comment]
@theKashey only for dev: https://github.com/gaearon/react-hot-loader/blob/master/src/hot.prod.js

Since the prod index file [pulls in code from all three files](https://github.com/gaearon/react-hot-loader/blob/master/src/index.prod.js), without the above changes, the [placeholder code](https://github.com/gaearon/react-hot-loader/blob/master/src/AppContainer.prod.js) in `AppContainer.prod.js` will not be dead code eliminated properly in the case of a consumer only using `hot`.

**Comment by evan-scott-zocdoc** [comment]
I'm happy to send a PR if you're in agreement

**Comment by theKashey** [comment]
You still could not do it, as long rollup, the bundler we use, does not allow this. If you will found workaround - fell free to draft a PR.

**Comment by neoziro** [comment]
I think this is not very useful, we are talking about 164 bytes gzipped. You can still avoid loading RHL in production if you want to optimize your build to the edge.

We ship the same type of bundles shipped by React, and yes it could be a problem for dead code elimination but it is simpler. We are not a real candidate for dead code elimination.
