### ISSUE TITLE
Hot reloading doesn't work for components passed into a function

### ISSUE THREAD

**Issue by Sawtaytoes** [gaearon/react-hot-loader#898]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

What you are reporting:
When creating entrypoints that render from a function, the component and its children passed into the function will not hot reload.

When using `hot` in v4, it works fine because I can specifically wrap this particular component in `hot`, but for some reason, it doesn't work at all in v3 (which is what I need to use right now).

### Expected behavior

What you think should happen:
The component should hot reload when it or its children have been updated.

### Actual behavior

What actually happens:
The entire page refreshes.

### Environment

React Hot Loader version: v3.1.3

Run these commands in the project folder and fill in their results:

1. `node -v`: v8.9.4
2. `yarn -v`: v1.3.2

Then, specify:

1. Operating system: Windows 10 64-bit
2. Browser and version: 66.0.3359.33 (Official Build) beta (64-bit)

#### entrypoint.js
```js
import React from 'react'

import TestComponent from '@shared/components/TestComponent'
import renderEntrypoint from './renderEntrypoint'

renderEntrypoint(<TestComponent />)
```

#### renderEntrypoint.js
```js
import React from 'react'
import { AppContainer } from 'react-hot-loader'
import { hydrate, render } from 'react-dom'

import ClientRoot from '@shared/components/root/ClientRoot'

export const renderEntrypoint = appEntrypoint => {
  const reactRootElement = document.getElementById('react-render-root')
  const clientDomRenderer = global.isDeployment ? hydrate : render

  const renderToDom = () => (
    clientDomRenderer(
      (
        <AppContainer>
          <ClientRoot appEntrypoint={appEntrypoint} />
        </AppContainer>
      ),
      reactRootElement
    )
  )

  renderToDom()

  module.hot
  && module.hot.accept('@shared/components/root/ClientRoot', renderToDom)
}

export default renderEntrypoint
```

**Comment by Sawtaytoes** [comment]
I came up with a workaround:
```js
import React from 'react'

import TestComponent from '@shared/components/TestComponent'
import renderEntrypoint from './renderEntrypoint'

renderEntrypoint(<TestComponent />)

module.hot
&& (
  module.hot.accept(
    '@shared/components/TestComponent',
    () => renderEntrypoint(<TestComponent />)
  )
)
```
Since this file is meant to be overridden in other projects, I don't like the fact that I have to duplicate the `module.hot.accept` code in other places depending on the name of the component being loaded. v4 seems to have a fix for this because I'd just need another `hot` wrapper, but it looks like v3 might be stuck since I don't know how it would understand that while this component is wrapped deep, it's `import` statement is somewhere else.

**Comment by theKashey** [comment]
This is how webpack's hot module replacement works. We could not change it.
