### ISSUE TITLE
Coffeescript/cjsx support?

### ISSUE THREAD

**Issue by KyleAMathews** [gaearon/react-hot-loader#9]
I'm trying to use this module with [cjsx-loader](https://github.com/KyleAMathews/cjsx-loader/blob/master/index.js)/[coffee-react-transform](https://github.com/jsdf/coffee-react-transform) and am hitting an error.

```
ERROR in ../react-hot-loader/replaceCreateClass.js!./react_components/hello_world.cjsx
Module parse failed: /Users/kylemathews/programs/react-hot-loader/replaceCreateClass.js!/Users/kylemathews/programs/coffee-react-quickstart/react_components/hello_world.cjsx Line 2: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| module.exports = function replaceCreateClass(createClassProxy) {
| # @cjsx React.DOM
|
| React = require 'react'
 @ ./react_components/hello_world.cjsx 4:17-182 8:6-171
```

I'm brand new to Webpack so am perhaps missing something obvious. In my webpack.config.js I tried switching the order of loaders for `.cjsx` so the `cjsx-loader` went first so `react-hot` would get javascript but that didn't work.

If code needs written, I'd be happy to write it if given a few pointers.

**Comment by ConradIrwin** [comment]
Thanks @KyleAMathews, you just saved me a bucket-load of time :).

**Comment by KyleAMathews** [comment]
@ConradIrwin haha thanks! You might want to check out as well my more up-to-date webpack config at https://github.com/KyleAMathews/coffee-react-quickstart

**Comment by cchanningallen** [comment]
@KyleAMathews me too! Thanks :)

**Comment by agilgur5** [comment]
@KyleAMathews been trying to find a solution for hours, didn't know about the back to front parsing! This explains why your cjsx-loader didn't check for literate flags. Thanks a ton!
