### ISSUE TITLE
Breaks components that rely on child's react type

### ISSUE THREAD

**Issue by jshthornton** [gaearon/react-hot-loader#901]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description
When using the babel plugin it wraps components in a `Proxy`, this changes the type of the React component, therefore any component that relies on the child's type no longer matches.

What you are reporting:

### Expected behavior
Type should be preserved.

What you think should happen:

### Actual behavior
Type is the Proxy components

What actually happens:

### Environment

React Hot Loader version:
version 4

Run these commands in the project folder and fill in their results:

1. `node -v`: 9.6.1
2. `npm -v`: yarn 1.5.1

Then, specify:

1. Operating system: Ubuntu 16.10
2. Browser and version: Chrome 63

**Comment by theKashey** [comment]
This is not a bug, this is a feature.
See https://github.com/gaearon/react-hot-loader#checking-element-types

**Comment by jshthornton** [comment]
I think this is a pretty bad way to support this functionality. Any existing library that uses types is now broken due to this, and asking libraries to use this tool just for type checking is going to create more issues than it solves.

**Comment by theKashey** [comment]
You can use non RHL specific logic - `child.type === <TheType/>.type`
Please refer to https://github.com/gaearon/react-hot-loader/issues/304

this is a root design issue, we could not solve for years.
