### ISSUE TITLE
Can changes in functions be hot loaded

### ISSUE THREAD

**Issue by xiaojingzhao091** [gaearon/react-hot-loader#903]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

Can changes in functions be hot loaded

### Expected behavior

Here is an example
```
export default class App extends Component {
  render() {
    return (
      <h1 >Hello, world.</h1>
    );
  }
}
```

if I bind an onClick functions for this "Hello word"
```
import React, { Component } from 'react';

export default class App extends Component {
  onClick = () => {
    console.log('2222222222')
  }
  render() {
    return (
      <h1 onClick={this.onClick} >Hello, world.</h1>
    );
  }
}
```

The rebuilding occurred. However, if I click "Hello world", nothing consoled  in console panel.

It seems hot-loader only hot replace UI relevant stuff. I wonder if I could hot load function?

### Actual behavior

The rebuilding occurred. However, if I click "Hello world", nothing consoled  in console panel.

### Environment

React Hot Loader version: ^4.0.0

Run these commands in the project folder and fill in their results:

1. `node -v`: 7.7.4
2. `npm -v`: 5.6.0

Then, specify:

1. Operating system: mac OS
2. Browser and version: chrome  65.0.3325.162

### Reproducible Demo

using https://github.com/gaearon/react-hot-boilerplate 
and add an onClick function for "hello world"
start this project
make some change in this onClick function 
click hello word
the function is not changed at all

I wonder what is the usual way to deal with this issue. As it is annoying if I change some function logic, I have to refresh the page every time

**Comment by theKashey** [comment]
You cannot use react-hot-boilerplate as example, as long it was created for React-Hot-Loader v1, and you are using v4.
Did you setup webpack HMR, or used `hot` help? Added a babel plugin?

Everything you are asking for is 100% working, 100% tested, and 100% double tested in real applications. 
Just follow the v4 instructions.
