### ISSUE TITLE
Feature Request: Tree shaking

### ISSUE THREAD

**Issue by 1pete** [gaearon/react-hot-loader#904]
### Description

Using v4 in production with `NODE_ENV=production` regardless what are used, all code in `react-hot-loader.production.min.js` is loaded into bundle

### Expected behavior

With tree shaking enable, when I do
```js
import { hot } from 'react-hot-loader'
```
only content in /src/hot.prod.js is loaded into bundle, which increase bundle size by no more than 200 bytes

### Actual behavior

all code in `react-hot-loader.production.min.js` is loaded into bundle, which increase size by ~18kb

**Comment by theKashey** [comment]
But the true size of that file is less that 1kb!

**Comment by neoziro** [comment]
We are aware of that, but the difference is very minimal probably less than 200 bytes gzipped. That's why for now we choose to not address it.

**Comment by 1pete** [comment]
Interesting, I try to reproduce with small project, only 1kb size increased. But my big project really got 18kb increased. Seem like it's not from this lib, I'll close this and investigate deeper.

Sorry for the inconvenience.
