### ISSUE TITLE
Handling errors and rerendering when there is an error in a render function of a component

### ISSUE THREAD

**Issue by carpben** [gaearon/react-hot-loader#908]
### Description

What you are reporting:
I installed the library in a react project. When there are no errors it works well. When there is an error the browser shows the react error page, and after fixing the error it reloads. It is not the behavior I expected after watching the video linked from the repository page: 
https://www.youtube.com/watch?v=xsSnOQynTHs

### Expected behavior
What you think should happen:
When there is an error in one of the render function of a component, I'd expect the error to present in the screen but be confined to the area of the component, without the entire screen being rerendered. 

### Actual behavior

What actually happens:
When there is a simple error in the render function, such as unmatching opening and closing tags, the react error message shows on the entire screen. After fixing it the browser rerenders. 

### Environment

React Hot Loader version: 4

Run these commands in the project folder and fill in their results:

1. `node -v`: 8.9
2. `npm -v`: 4.6.1

Then, specify:

1. Operating system: Windows 10
2. Browser and version: Chrome 65

### Reproducible Demo
1. Create a new create-react-app project. 
2. follow the instructions on migrating from create-react-app on the repository page. 
3. In the app root component, create 2 sub components. 
4. Run the project with npm start. 
5. add a title element with an h2 opening tag, and an h3 closing tag.  At this point, the react error page should show on the screen. 

Please take the time to create a new project that reproduces the issue.

You can copy your project that experiences the problem and start removing things until you’re left with the minimal reproducible demo. This helps contributors, and you might get to the root of your problem during that process.

Push to GitHub and paste the link here.

**Comment by theKashey** [comment]
@neoziro - yo dawg! I heard you had a cool error overlay?

**Comment by neoziro** [comment]
The video is a bit outdated, in https://github.com/smooth-code/error-overlay-webpack-plugin, I choose to reload the page when an error is displayed.

I don't know the behaviour of `create-react-app` but the reload is not done by `react-hot-loader`.

**Comment by neoziro** [comment]
Actually I will close it because this is expected, the only thing we have to do is updating the website.
