### ISSUE TITLE
Can't resolve 'react-hot-loader/webpack'

### ISSUE THREAD

**Issue by user905** [gaearon/react-hot-loader#910]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

What you are reporting:
Using the ASP.NET Core 2.0 React template and updating Bootstrap and various packages using  prevents the app from running. (Use "npm-check-updates -u" to update)

### Expected behavior

What you think should happen:
The web app loads.

### Actual behavior

What actually happens:
![image](https://user-images.githubusercontent.com/29554021/37998782-0bf46018-31ee-11e8-9d90-918a794d190a.png)

### Environment

React Hot Loader version:
^4.0.0
Run these commands in the project folder and fill in their results:

1. `node -v`: v8.9.0
2. `npm -v`: 5.8.0

Then, specify:

1. Operating system: Windows 7
2. Browser and version: Chrome Version 65.0.3325.181 (Official Build) (64-bit)

### Reproducible Demo

Please take the time to create a new project that reproduces the issue.

You can copy your project that experiences the problem and start removing things until you’re left with the minimal reproducible demo. This helps contributors, and you might get to the root of your problem during that process.

Push to GitHub and paste the link here.
https://github.com/user905/DEMO/tree/master

**Comment by theKashey** [comment]
React-Hot-Loader version 4 does not include Webpack loader anymore. Please use babel plugin. 
This is the only way for us to provide a better experience for you.

**Comment by user905** [comment]
What is the greatest version of the hotloader that works with webpack?

**Comment by theKashey** [comment]
It depends on the meaning of "working"
You can use RHL v4 without babel or webpack loader and might get even better experience than with version 3 and webpack/babel plugin.

We dropped webpack plugin, as long it count not help us to achieve some goals, like support ES6, while babel could. 

v3.1.1 was the last version with webpack loader included.

**Comment by user905** [comment]
Thank you. Can you point me to instructions on how to update?

**Comment by theKashey** [comment]
They are in readme. Just keep in mind - you cant 'update' - just remove webpack loader and add babel.

**Comment by Tsourdox** [comment]
@user905 I have the same issue, did you manage to fix the issue? Could you share what changes you made?

**Comment by theKashey** [comment]
@Tsourdox @user905  - just remove our webpack loader. Then it should work at 90%. Then, add babel plugin, to reach 100%.

**Comment by Tsourdox** [comment]
@theKashey thx for responding! I'm still kind of lost looking at my webpack.config file. I've read your readme file, but unsure if I should look at "migrating from v3" or "Typescript". I've tried some implementations but without any luck.

I haven't found where and how your webpack loader is used. The only reference to 'react-hot-loader' is this: 

```
import { AppContainer } from 'react-hot-loader';
```

(As I've understood the AppContainer syntax will work as before but can be replaced with the new hoc syntax, correct?)

Now, how do I "remove" your webpack loader?

This is what the webpack.config file looks like from the dotnet template we are using:
(any help would be greatly appreciated)

```
const path = require('path');
const webpack = require('webpack');
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const CheckerPlugin = require('awesome-typescript-loader').CheckerPlugin;
const merge = require('webpack-merge');

module.exports = (env) => {
    const isDevBuild = !(env && env.prod);

    // Configuration in common to both client-side and server-side bundles
    const sharedConfig = () => ({
        mode: isDevBuild ? 'development' : 'production',
        stats: { modules: false },
        resolve: { extensions: ['.js', '.jsx', '.ts', '.tsx'] },
        output: {
            filename: '[name].js',
            publicPath: '/dist/' // Webpack dev middleware, if enabled, handles requests for this URL prefix
        },
        module: {
            rules: [
                { test: /\.(tsx|ts)$/, include: /app|material-ui-component-package/, use: 'awesome-typescript-loader?silent=true' },
                { test: /\.(png|jpg|jpeg|gif|svg|eot|woff2|woff|ttf)$/, use: {
                    loader: 'url-loader',
                    options: {
                        limit: 25000
                    }
                } }
            ]
        },
        plugins: [new CheckerPlugin()]
    });

    // Configuration for client-side bundle suitable for running in browsers
    const clientBundleOutputDir = './wwwroot/dist';
    const clientBundleConfig = merge(sharedConfig(), {
        entry: { 'main-client': './app/boot-client.tsx' },
        module: {
            rules: [
                { test: /\.css$/, use: [
                    MiniCssExtractPlugin.loader,
                    isDevBuild ? 'css-loader' : 'css-loader?minimize'
                ] },
                { test: /\.scss$/, use: [
                    MiniCssExtractPlugin.loader,
                    isDevBuild ? 'css-loader' : 'css-loader?minimize',
                    'sass-loader'
                ] }
            ]
        },
        output: { path: path.join(__dirname, clientBundleOutputDir) },
        plugins: [
            new MiniCssExtractPlugin({
                // Options similar to the same options in webpackOptions.output
                // both options are optional
                filename: "site.css",
                chunkFilename: "[id].css"
            }),
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./wwwroot/dist/vendor-manifest.json')
            })
        ].concat(isDevBuild ? [
            // Plugins that apply in development builds only
            new webpack.SourceMapDevToolPlugin({
                filename: '[file].map', // Remove this line if you prefer inline source maps
                moduleFilenameTemplate: path.relative(clientBundleOutputDir, '[resourcePath]') // Point sourcemap entries to the original file locations on disk
            })
        ] : [
            // Plugins that apply in production builds only
        ])
    });

    // Configuration for server-side (prerendering) bundle suitable for running in Node
    const serverBundleConfig = merge(sharedConfig(), {
        resolve: { mainFields: ['main'] },
        entry: { 'main-server': './app/boot-server.tsx' },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./app/dist/vendor-manifest.json'),
                sourceType: 'commonjs2',
                name: './vendor'
            })
        ],
        output: {
            libraryTarget: 'commonjs',
            path: path.join(__dirname, './app/dist')
        },
        target: 'node',
        devtool: 'inline-source-map'
    });

    return [clientBundleConfig, serverBundleConfig];
};
```

**Comment by theKashey** [comment]
There is no webpack loader, and there is no way to `use` it. That's the point.

**Comment by Tsourdox** [comment]
But what did you mean by:

> just remove our webpack loader.

Was the webpack loader part of you library in v3 and removed in v4?

Just to clarify we are migrating from v3 to v4, in order to get multiple hoc support.

**Comment by theKashey** [comment]
You are right - he have removed it during migration, mostly cos it does not make a sense. It could not add anything.
RHL without babel will support any complex HOC composition, but will be unable to change arrow or ".bind" method body (which are usually also arrow today).

**Comment by Tsourdox** [comment]
Found this, seems to be related :) https://github.com/aspnet/JavaScriptServices/issues/1585

**Comment by Tsourdox** [comment]
@user905 check out the aspnet issue for more info about how to update!
