### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by YanYuanFE** [gaearon/react-hot-loader#911]
### Description

After update component，chrome update，and console err ‘Uncaught RangeError: Maximum call stack size exceeded’

### Expected behavior

not error

### Actual behavior

console error

### Environment

React Hot Loader version:4.0.0

Run these commands in the project folder and fill in their results:

1. `node -v`:9.9.0
2. `npm -v`:5.6.0
3. webpack： 4.2.0

Then, specify:

1. Operating system:ubuntu16.04
2. Browser and version:chrome 65.0.3325.181（正式版本） （64 位）

### Reproducible Demo

https://github.com/YanYuanFE/react-webpack

**Comment by theKashey** [comment]
Look like webpack is broken - the source code contains two blocks with `parentHotUpdateCallback`
 - one on line 5, added by webpack itself
 - the second on 6xx line, added by hot-module-replacement plugin

**Comment by theKashey** [comment]
Nope. This is your problem.
Just remove `HotModuleReplacementPlugin` from webpack.config. "--hot" option for webpack-dev-server is doing the same.
