### ISSUE TITLE
Fix/improve guide for Electron

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [gaearon/react-hot-loader#913]
HMR doesn't seem to work as expected in that example that is [linked to in the README](https://github.com/gaearon/react-hot-loader#electron). 

If I merely extend it to have the following component structure:
```
App
|-- Branch1
|-- Branch2
```
... and change something in Branch2 ...

### Expected behavior

... I expect only Branch2 and App to be updated.

### Actual behavior

... instead, this happens:
```
HMR sent to all windows!
  ←[3crimson;1melectron-compile:require-hook ←[0mGot HMR signal! ←[3crimsonm+41s←[0m
  ←[3crimson;1melectron-compile:require-hook ←[0mRemoving node module entry for D:\development\github\hmr-example-issue-2\src\app.jsx ←[3crimsonm+3ms←[0m
  ←[3crimson;1melectron-compile:require-hook ←[0mRemoving node module entry for D:\development\github\hmr-example-issue-2\src\branch1.jsx ←[3crimsonm+1ms←[0m
  ←[3crimson;1melectron-compile:require-hook ←[0mRemoving node module entry for D:\development\github\hmr-example-issue-2\src\branch2.jsx ←[3crimsonm+0ms←[0m
```

### Environment

React Hot Loader version: 4.0.0

### Reproducible Demo

https://github.com/s-h-a-d-o-w/hmr-example-issue-2

### Further notes

I think it should be mentioned in the README that the guide only applies to electron-forge/electron-compile. There is no `.compilerc` if you use e.g. electron-webpack or some custom electron setup.

On a sidenote - the behavior is as expected when using electron-webpack and the RHL v3 workflow.

But if you do stick with electron-compile, I think the code snippet in the README should be a bit bigger, e.g.:
```
import {enableLiveReload} from 'electron-compile';

const isDevMode = process.execPath.match(/[\\/]electron/);
if(isDevMode) {
    enableLiveReload({ strategy: 'react-hmr' });
}
```

**Comment by theKashey** [comment]
Sorry. I am not a real Electron user, but, as I remember it is how Electron's HMR works - it replaces just everything.
And, as not a real Electron user, could I ask you to draft a PR with the changes to README file?

**Comment by s-h-a-d-o-w** [comment]
Of course. I'll get on it as soon as I've figured out whether I can or can't improve electron-compile's HMR. (At least on my machine and in my scenario, it already works.)

**Comment by s-h-a-d-o-w** [comment]
> as I remember it is how Electron's HMR works

Electron doesn't do any HMR itself, electron-compile does. It could be optimized but the people in charge of the project feel that it doesn't need to be.

And so I switched to simply using webpack, setting up my own config. It's really no different from your regular web project.
