### ISSUE TITLE
The doesSupportClasses check fails on CSP without 'unsafe-eval'

### ISSUE THREAD

**Issue by birkir** [gaearon/react-hot-loader#917]
The doesSupportClasses check fails on CSP without 'unsafe-eval'

See: https://github.com/gaearon/react-hot-loader/blob/master/src/proxy/utils.js#L51

Is there no other way to test for class support without eval?

**Comment by theKashey** [comment]
Unfortunately no. Except the browser version matching. But RHL will use `eval` in some internal stuff, so it will not help.

Why do you need strict CSP rules in dev environment?

**Comment by birkir** [comment]
I don't, thing is, people go from no permissions to incrementally add what they need, but RHL swallows the error and just thinks it doesn't have class support when in fact the error was 'unsafe-eval' restriction.

It took me a long time to figure this out, so I guess the actionable here is to improve error reporting.

**Comment by theKashey** [comment]
The problem is - to remove eval we will have to remove IE11 support. `class` is just a __syntax error__ for IE11.

**Comment by chenders** [comment]
FWIW, we have strict CSP rules in dev environments to eliminate any CSP-related surprises when we move to QA/staging/prod environments. (I'm running into this problem as well.)

**Comment by theKashey** [comment]
PR has been drafted. Next version of RHL will include production, not development build if env does not met required conditions - for example due to browser version or CSP
