### ISSUE TITLE
Random generated component initial state

### ISSUE THREAD

**Issue by CalinaCristian** [gaearon/react-hot-loader#922]
When I have in the constructor code of a parent component something like:

this.state = { random: Math.random() } 

If I have logic in the child dependent on that field, I want on hot reload the value to remain the same. 

I know that when replacing ComponentA with ComponentB, the constructor is called once for ComponentA and once for ComponentB and this is the reason why the value is reset. 

When hot reloading due to this component or its child update, the constructor gets called and sets another value on state. 

The workaround that I used was to remove the constructor code and to set all the logic (binding and state) to "ComponentWillMount" because react lifecycles are not called on hot reloading. 

Is there another solution for this situation?

React Hot Loader version: 4.0.0

**Comment by CalinaCristian** [comment]
Since from the next major release, react will deprecate componentwillmount, this workaround will no longer be valid.

**Comment by theKashey** [comment]
The only way to solve this - dont update `state`. As long we are _preserving_ state  - we should not just override the old state, by the new one - so something has to be changed.
There is 2 options:
 - call setState on state change (will not solve this issue, but could solve others)
 - do nothing, but this might be not a great idea, as long _applying_ the changes - is usually expected operation.

How to actually __solve this issue__: change the state on componentDidMount to make state on instance differs from "initial" state, and prevent update as result.
PS: But only after #840. We dont have this logic yet.
