### ISSUE TITLE
Lose state while using TypeScript without Babel

### ISSUE THREAD

**Issue by nonoroazoro** [gaearon/react-hot-loader#923]
### Environment (**without Babel**):
1. node@8.11.1
1. npm@5.8.0 
1. typescript@2.8.1
1. webpack@4.4.1
1. ts-loader@4.1.0
1. react-hot-loader@4.0.0

### Expected behavior

HMR with **persistent state**.

### Actual behavior

HMR worked, while the **state is lost**.

### Upgraded Environment (**with Babel**):
1. babel@6.26.0
1. babel-loader@7.1.4
1. add `react-hot-loader/babel` in `.babelrc`

Now I get HMR with **state persisted**, but I really don't want to add Babel to my TypeScript project.

What I expected is to have HMR (with persistent state) without adding Babel. Are there ways around this? Thanks!

**Comment by neoziro** [comment]
For now we rely on Babel to make React Hot Loader work. I am sorry, but you have to add Babel if you want to use it.

**Comment by theKashey** [comment]
Babel is not required to __preserve__ the state, only to properly propagate updates.
Something else is wrong(may be setup?), but I could not help without actual code

**Comment by nonoroazoro** [comment]
@theKashey Yeah really? Maybe I made mistaks some where.  I'm really appreciate if you have time to help checking the code!

Here's the code: https://github.com/nonoroazoro/typescript-react-boilerplate

You can run `npm i && npm run dev` to start the app at `localhost:8080`.

I've put a button on the page, you can click it and then modify `App.tsx` to reproduce the result.

**Comment by nonoroazoro** [comment]
@neoziro Thanks anyway!

**Comment by nonoroazoro** [comment]
@theKashey Got it. I'll try this and wait for your good news. Thanks again for helping me understanding this issue~ 😸

**Comment by theKashey** [comment]
Even better - you can add this code to the index.tsx. Just right before ReactDOM.render

**Comment by nonoroazoro** [comment]
Yep, I'll do it :)

**Comment by pleerock** [comment]
@nonoroazoro did you get it working? Im interested in this issue as well.

**Comment by theKashey** [comment]
I've just played with your example, and fixed it with 3 lines, I've added to App.tsx (no changes in index.tsx)
```ts
import {hot} from 'react-hot-loader';
...... // all the file

declare const module: any;
export default hot(module)(App);
```

**Comment by nonoroazoro** [comment]
@pleerock  Yes it worked~

@theKashey Thanks again! :smile:  Actually I've already seen this api while I'm searching for the `register` function. The reason why I didn't use `hot` is because I got a `using private name 'App'` error from TypeScript compiler, and I didn't find a proper solution :sob:

**Comment by theKashey** [comment]
`export class App` -> I have to idea why, but TS expect you to reexport used class.

**Comment by pleerock** [comment]
Would be great to support this out of the box, there are lot of people using typescript that will face this problem

**Comment by theKashey** [comment]
We can’t. If we will try to hot reload code on each render - it will ruin everything. 
We need some signal to rely on, for example - ‘hot’ method.

**Comment by nonoroazoro** [comment]
`export class App` did solve the problem, but I don't quite like it... haha
