### ISSUE TITLE
HMR -237 The following modules couldn't be hot updated: (They would need a full reload!)

### ISSUE THREAD

**Issue by qyjandroid** [gaearon/react-hot-loader#925]
![image](https://user-images.githubusercontent.com/6645414/38285458-d26c5c46-37f2-11e8-864f-554f694c5e6a.png)
app.json
`{
  "isDebug":true,
  "version":"v1.0.0",
  "CDN_IP": "http://localhost:8080/debug/",
  "libs":[
    "jquery",
    "react-hot-loader",
    "react",
    "react-dom",
    "immutable",
    "redux",
    "react-redux",
    "./react/lib/core/index.js"
  ],
  "mainPage":"./react/src/page/**/*/index.js",
  
  "debug":"/debug",
  "release":"/release"
}`

webpackConfig.js
`const App = require('./app.json');
const hotMiddlewareScript = 'webpack-dev-server/client?http://localhost:8082/';
 const hotServer = 'webpack/hot/only-dev-server';
const extractSass = new ExtractTextPlugin({
    filename: "[name].css",
    disable: false //process.env.NODE_ENV === "development"
});
if(App.isDebug){
   // App.libs.unshift("react-hot-loader/patch");
    App.libs.unshift(hotMiddlewareScript);
    App.libs.unshift(hotServer);
}
var config = {
    devtool:  App.isDebug? 'eval-source-map':'source-map',

    //当存在多个入口时 ，可以使用 Array 的方式，比如依赖第三方库 bootstrap ，
    // 最终 bootstrap 会被追加到打包好的 index.js 中，数组中的最后一个会被 export。
    entry: {
        // 第三方包
        vendor: App.libs
    },
    output: {
        // 输出路径
        path: path.join(__dirname, App.isDebug? App.debug:App.release),
        //如果项目有多个页面，那么需要打包出多个文件，webpack 可以用对象的方式配置多个打包文件
        filename: '[name].js',// 输出名称或名称 pattern
        ////调试或者 CDN 之类的域名
    },
    module: {
        //忽略以下js
        //noParse: /node_modules\/(jquey|zepto|moment|chart\.js)/,
        
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: [
                    'babel-loader',
                 ],
            },
    ]
  },
   plugins: [
        new CleanPlugin(['debug'], {
          root: __dirname,
          verbose: true,  //打印日志
          dry: false,
          exclude: ["index.html","home.html"]//排除不删除的目录
      }),
        new CommonsChunkPlugin({
            names: ['vendor'],
            filename: "/js/jreact.js",
        }),
        new webpack.HotModuleReplacementPlugin(),
        new OpenBrowserPlugin({ url: 'http://localhost:8082' }),
        //把vendor第三方库里面的css单独打包生成vendor.css文件
        extractSass
    ]
 }`
dev-server.js
`const WebpackDevServer = require('webpack-dev-server'),
            webpack = require('webpack'),
            config = require('./webpack.config');

  const options = {
    publicPath: config.output.publicPath,
    hot: true,
    historyApiFallback: true,
    inline: true,//实时刷新
    noInfo:true,
    host: 'localhost',
    headers:{"Access-Control-Allow-Origin": "*"},
    stats:{colors: true},
  };   
  
  webpackDevServer.addDevServerEntrypoints(config, options);
const compiler = webpack(config);
const server = new webpackDevServer(compiler, options);

server.listen(8082, 'localhost', () => {
  console.log('dev server listening on port 5000');
});
`
.babelrc file
`{
  "presets": [
    "es2015",
    "react",
    "stage-2"
  ],
  "plugins": ["transform-decorators-legacy","react-hot-loader/babel"]
}`

react->lib->core->index.js
`import { AppContainer,setConfig } from 'react-hot-loader';
import React from "react";
import ReactDOM from "react-dom";
import App from "./app/App";

//ReactDOM.render(<AppContainer><App /></AppContainer> , document.getElementById("react_root"));
console.log("===aa==",AppContainer);
const render = Component => {
    ReactDOM.render(
      <AppContainer>
        <Component />
      </AppContainer>,
      document.getElementById('react_root'),
    )
  }
  
  render(App);
 
  if (module.hot) {
    module.hot.accept('./app/App', () => { render(App) })
  }
  setConfig({ logLevel: 'log' });`

**Comment by theKashey** [comment]
add `new webpack.NamedModulesPlugin()` to webpack plugins, to display and understand what you are doing wrong and hot update propagates.
PS: and dont forget to add react-hot-loader babel plugin (see README)

**Comment by qyjandroid** [comment]
@theKashey 
error:
![image](https://user-images.githubusercontent.com/6645414/38289631-c68f2f2c-3809-11e8-852e-46d6164c046a.png)

![image](https://user-images.githubusercontent.com/6645414/38289666-fc36e822-3809-11e8-9c47-f894a86f9424.png)

![image](https://user-images.githubusercontent.com/6645414/38289722-3376c53c-380a-11e8-87ba-b92db6bcf988.png)

**Comment by theKashey** [comment]
Yeah. So try to figure out why page/index should be accepted, or just accept it. 
Better - just use proper webpack-dev-server configuration (pick any from our examples folder). 

But there is nothing related to RHL.
