### ISSUE TITLE
Not following symlinks

### ISSUE THREAD

**Issue by jwahlin** [gaearon/react-hot-loader#926]
### Description
Hot reloading doesn't occur when using symlinks. I'm using react-hot-loader with parcel and starting up the dev server with this command:
```
parcel public/symlink-index.html
```
The public/symlink-index.html path is a symlink.

### Expected behavior
When I change the symlinked index.html file, hot reloading should occur. There should be an option to follow symlinks.

### Actual behavior
When I change the symlinked index.html file, not hot reloading occurs.

### Environment

1. React Hot Loader version: 4.0.1
2. `node -v`: 8.9.1
3. `npm -v`: 5.5.1

1. Operating system: High Sierra
2. Browser and version: Chrome 65.0.3325.181

### Reproducible Demo
1. Clone project from https://github.com/jwahlin/parcel-react-hot-loader.
2. Run ```npm install```.
3. Copy the  public/index.html file to a location *outside* of the project directory. Create a symlink to this file:
```ln -s path/to/outside/public/index.html path/to/test-project/public/symlink-index.html```
4. Run ```npm run start```. Modify the index.html file and hot reloading should occur as expected.
5. Run ```npm run start-symlink```. Modify the symlink-index.html file. Hot reloading does NOT occur.

**Comment by theKashey** [comment]
Unfortunately, this is not related to React-Hot-Loader at all.
Please raise the same issue for parcel bundler - detect module replacement and call correct endpoint HMR API - that is their job.
