### ISSUE TITLE
Render Method Called Twice!

### ISSUE THREAD

**Issue by dcflow** [gaearon/react-hot-loader#930]
Hello,

### Description

Whenever we do a change to a Main Component or Child Component, after `HMR` updates the changes every component in the tree calls the `render` method  twice.

### Environment

React Hot Loader version: `4.0.1`

### Reproducible Demo

This is a small example in the `create-react-app`
```
import React from "react";
import { hot } from "react-hot-loader";

class App extends React.Component {
  render() {
    console.log("App");
    return <h1>App</h1>;
  }
}

export default hot(module)(App);
```
If we change the header for example from `App` to `App2` the render method gets called twice.

Thank You!

**Comment by dcflow** [comment]
Using both `webpack HMR` and the `babel plugin` for the `react-hot-loader` causes the component to be updated again thus calling the render method twice.

**Comment by theKashey** [comment]
This is not a bug, this is a feature. This is how RHL trying to detect the changes.
Even more - sometime it could execute render 3! times.

**Comment by theKashey** [comment]
https://github.com/gaearon/react-hot-loader/wiki/How-React-Hot-Loader-works see for 1.2
