### ISSUE TITLE
Unable to keep component state in webpack 4

### ISSUE THREAD

**Issue by zlk89** [gaearon/react-hot-loader#934]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

What you are reporting:
Unable to keep component state after hot loading.

### Expected behavior

What you think should happen:
It should keep previous state.

### Actual behavior

What actually happens:
Everything is reset to initial state.

### Environment

React Hot Loader version: next

Run these commands in the project folder and fill in their results:

1. `node -v`: v6.9.5
2. `npm -v`: 5.8.0

Then, specify:

1. Operating system: Mac
2. Browser and version: Chrome 65.0.3325.181 (Official Build) (64-bit)

### Reproducible Demo

Please take the time to create a new project that reproduces the issue.

You can copy your project that experiences the problem and start removing things until you’re left with the minimal reproducible demo. This helps contributors, and you might get to the root of your problem during that process.

Push to GitHub and paste the link here.

https://github.com/zlk89/react-hot-loader-clear

- `npm i`
- `npm run start`
- Type some things in the field
- Change code, after hot loader finishes update, you will see everything is reset.

But this was working well, when it is webpack 3.

**Comment by theKashey** [comment]
Fear not! React-Hot-Loader is healthy. But HMR is broken in webpack.
https://github.com/webpack/webpack-dev-server/issues/1377
https://github.com/webpack/webpack-dev-server/issues/1369
https://github.com/webpack/webpack-dev-server/issues/1367

**Comment by zlk89** [comment]
Thanks, I am able to get it working by using express, instead of `webpack-dev-server`

**Comment by oliviertassinari** [comment]
@neoziro Thanks for the heads-up! My issue was with Next.js (using webpack v3). But don't worry about it. I think it's already tracked in #918.

**Comment by theKashey** [comment]
@oliviertassinari - but #918 is only about deprecation _warnings_, everything should still work.

**Comment by zlk89** [comment]
In case anyone might need, I have push a new branch which is using express and working: https://github.com/zlk89/react-hot-loader-clear/tree/express
