### ISSUE TITLE
Perform full-reload

### ISSUE THREAD

**Issue by sarink** [gaearon/react-hot-loader#936]
When changing some code that cannot be hot-reloaded (for example, a fat-arrow-bound event handler function), I was expecting react-hot-loader to perform a full-refresh of my page. I seem to recall a much older version of this lib behaving that way (but maybe I'm wrong).

Is this a configuration issue? A bug? A wont-fix? A feature request?

Thanks!

**Comment by theKashey** [comment]
A fat-arrow-bound event handler usually could be reloaded, unless it was "attached" via addEventListener in componentDidMount, and, as long component will not "remount" handler will not update.
Anyway - we could not detect such conditions.

RHL only not updating lifecycle events, everything else should be updated.

**Comment by theKashey** [comment]
In your case it will not, as long after ts-loader we have pure ES5, while our babel plugins looking for ES6 features, like classes.

Just swap them! Or change tsconfig to emit es6 (but not in prod). Check readme, I've updated this moment 3 weeks ago, or better dive into the original issue - https://github.com/gaearon/react-hot-loader/issues/884
