### ISSUE TITLE
[Question] Is there a similar way to use v4 like v3?

### ISSUE THREAD

**Issue by yangmingshan** [gaearon/react-hot-loader#953]
The `hot` helper provided by v4 is great. But our application have over 50 pages, each page is loaded on demand. So if I use `hot` helper, I have to rewrite every page's export. And if the page need connect to redux, the export will be like this:
```js
export default hot(module)(connect(mapStateToProps)(MyComponent));
```
It's maybe too long and complicated. 

So, is there a similar way to use v4 like v3?

**Comment by yangmingshan** [comment]
Our `async-loader` was written by myself, But I found the solution in `react-imported-component`. 

Use `hot` wrap the root component, `async-loader` reload async component after root component updated. No need to wrap async component's export.

I'm not sure it's the right way, but it works. Thank you.

**Comment by theKashey** [comment]
There is super simple RHL-frindly [solution in loadable-components](https://github.com/smooth-code/loadable-components/blob/master/src/loadable.js#L109) - it just always load a new component.

**Comment by sibelius** [comment]
does this work with https://github.com/jamiebuilds/react-loadable?

**Comment by theKashey** [comment]
Unfortunately no. Everyone has to pick it's own way to detect HRM and the way to reload stuff then. React-loadable still could not choose, but we have ideas how to enable every loader to work.
