### ISSUE TITLE
React Hot Loader stops components from rendering

### ISSUE THREAD

**Issue by OneCyrus** [gaearon/react-hot-loader#954]
### Description

When using reatc-hot-loader and office fabric ui react Pivot/PivotItems component it doesn't render. I created a bug reproduction here: https://github.com/OneCyrus/react-hot-loader-bugrepro

### Expected behavior

it should render the same way as without react-hot-loader (```yarn startNoBug``` in reproduction repo)

### Actual behavior

the components are not rendered (```yarn start``` in reproduction repo)

### Environment

React Hot Loader version: 4.1.2

Run these commands in the project folder and fill in their results:

1.  `node -v`: v8.9.4
2.  `npm -v`: 5.7.1
3. `yarn -v`: 1.5.1

Then, specify:

1.  Operating system: Windows 10, 1803
2.  Browser and version: Chrome 66

### Reproducible Demo

https://github.com/OneCyrus/react-hot-loader-bugrepro

**Comment by theKashey** [comment]
This is how our greatest sideeffect works :(
```js
    PivotBase.prototype._getPivotLinks = function (props) {
        var _this = this;
        var links = [];
        this._keyToIndexMapping = {};
        this._keyToTabIds = {};
        React.Children.map(props.children, function (child, index) {
            if (typeof child === 'object' && child.type === PivotItem_1.PivotItem) {
                                                                                 ^^^^^^^^ this comparison is "wrong"
```

see:
https://github.com/gaearon/react-hot-loader/issues/938
https://github.com/gaearon/react-hot-loader/issues/304

Unfortunately, there is no way to "fix" it from our side.
The only thing I could (each time) propose:
```js
node.type === <Component />.type
```
