### ISSUE TITLE
Fragment elements sometimes break RHL

### ISSUE THREAD

**Issue by CharlieIGG** [gaearon/react-hot-loader#956]
### Description

RHL was just not working for me on certain projects after working on them for a while. I actually had to manually reload every time I made a change. Using `setConfig({ logLevel: 'debug' })` showed the following error message on my console: `reconcilation failed due to error TypeError: a.filter is not a function`.

After a couple of hours of dissecting my application I realized the culprit where a couple of `<Fragment>` elements in my app. After removing or replacing the `Fragment`s RHL started working as expected again.

One such example was the following (This seems illogical, but I'll explain why this happened):

```
import React, { Fragment } from 'react';
import { Button, Typgrahpy } from 'some-ui-library';

const CtaButtonBase = props => {
  return (
    <Fragment>
      <Button className={props.somePropName}>
        <Typography variant="button">
          SOME TEXT
        </Typography >
      </Button>
    </Fragment>
  );
};

export default CtaButtonBase;
```

Now I know this seems weird – Why would you have a Fragment element wrapping a single component? The answer is it was wrapping more, and upon refactoring I forgot to remove the `<Fragment>` tags. 

I am suspecting this has to do with the `Fragment` component itself, seeming as other such elements that were wrapping two or more components seemed to cause no problem. **I realize if this is the case then trying to make the above quoted snippet seems rather pointless, but I wanted to spare other people two hours of their time.** Maybe this should be documented somewhere here.

### Expected behavior

RHL should auto-compile and replace modules upon code update.

### Actual behavior

Hot replacement breaks, have to manually reload page to see code changes.

### Environment

React Hot Loader version:"^4.1.2"

Run these commands in the project folder and fill in their results:

1.  `node -v`: v7.9.0
2.  `npm -v`: 5.8.0

Then, specify:

1.  Operating system: OS X High Sierra
2.  Browser and version: Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by theKashey** [comment]
Ok. Look like if Fragment is wrapped around a single element - it's children are actually a `child`.
Thanks for reporting. I'll fit it today.

**Comment by hedikasmanto** [comment]
Hi, I have found this issue too. Here is console.log while logLevel : debug


```
react-hot-loader.development.js:89 React-hot-loader: reconcilation failed due to error TypeError: a.filter is not a function
    at filterNullArray (react-hot-loader.development.js:990)
    at eval (react-hot-loader.development.js:1147)
    at Array.reduce (<anonymous>)
    at transformFlowNode (react-hot-loader.development.js:1145)
    at hotReplacementRender (react-hot-loader.development.js:1187)
    at next (react-hot-loader.development.js:1204)
    at eval (react-hot-loader.development.js:1236)
    at Array.forEach (<anonymous>)
    at hotReplacementRender (react-hot-loader.development.js:1192)
    at next (react-hot-loader.development.js:1204)

warn @ react-hot-loader.development.js:89
hotReplacementRender$1 @ react-hot-loader.development.js:1265
reconcileHotReplacement @ react-hot-loader.development.js:1272
renderReconciler @ react-hot-loader.development.js:1286
asyncReconciledRender @ react-hot-loader.development.js:1294
proxiedRender @ react-hot-loader.development.js:585
finishClassComponent @ react-dom.development.js:8389
updateClassComponent @ react-dom.development.js:8357
beginWork @ react-dom.development.js:8982
performUnitOfWork @ react-dom.development.js:11814
workLoop @ react-dom.development.js:11843
renderRoot @ react-dom.development.js:11874
performWorkOnRoot @ react-dom.development.js:12449
performWork @ react-dom.development.js:12370
performSyncWork @ react-dom.development.js:12347
requestWork @ react-dom.development.js:12247
scheduleWorkImpl @ react-dom.development.js:12122
scheduleWork @ react-dom.development.js:12082
enqueueForceUpdate @ react-dom.development.js:6682
Component.forceUpdate @ react.development.js:256
(anonymous) @ react-hot-loader.development.js:1454
(anonymous) @ react-hot-loader.development.js:1453
setTimeout (async)
updateInstances @ react-hot-loader.development.js:1447
(anonymous) @ react-hot-loader.development.js:1469
hotSetStatus @ index.1805021233.bundle.js:203
hotApply @ index.1805021233.bundle.js:552
(anonymous) @ index.1805021233.bundle.js:290
Promise.then (async)
hotUpdateDownloaded @ index.1805021233.bundle.js:289
hotAddUpdateChunk @ index.1805021233.bundle.js:266
webpackHotUpdateCallback @ index.1805021233.bundle.js:8
(anonymous) @ 0.c2c184befe30004ade89.hot-update.js:1

```

**Comment by theKashey** [comment]
It's fixed, but not released yet.
