### ISSUE TITLE
Please provide example with react-redux

### ISSUE THREAD

**Issue by borm** [gaearon/react-hot-loader#962]
https://github.com/gaearon/react-hot-loader/tree/master/examples

**Comment by theKashey** [comment]
Linked: https://github.com/gaearon/react-hot-loader/issues/959

**Comment by borm** [comment]
I had to return to [react-transform-hmr](https://github.com/gaearon/react-transform-hmr), and right now it worked fine with react `16.3.2`

**Comment by theKashey** [comment]
If yu have some issues with ReactHotLoader and redux - please raise the correct issue or provide an example. Then we will solve it.

**Comment by theKashey** [comment]
There is nothing special you have to do. It just should work.
