### ISSUE TITLE
Support React Context

### ISSUE THREAD

**Issue by theKashey** [gaearon/react-hot-loader#979]

**Comment by bbenezech** [comment]
In my app, components nested in context Providers lose their state when hot reloading happens.
Is this expected atm? (-> basic support)

Thank you very much for the awesome support.

**Comment by theKashey** [comment]
Yeah, that was a basic update. Unfortunately, RHL does not contain __any__ context related tests, as long enzyme still does not support them, as result some bugs exists.

So - the fix for your problem is almost ready - https://github.com/gaearon/react-hot-loader/pull/983

**Comment by Cottin** [comment]
![rhlerror](https://user-images.githubusercontent.com/4736419/40606451-abef2d4e-6265-11e8-835b-04ad4711f577.jpg)

I get the above error when using Context. You've seen this before? Me doing something wrong?

**Comment by theKashey** [comment]
@Cottin - click on `f` and try to figure out that is it. This is not Context, just something with context.
And that "something" got required before hot-loader.

**Comment by NervosaX** [comment]
When making changes, I get errors on this line:

https://github.com/gaearon/react-hot-loader/commit/56fdd05a948a81624d80c1afa3b420b1c952cda7#diff-56f32a77d9820e3b9dc60ca87529a61cR341

saying that props is undefined on the child variable. Changing this to `nextProps` seems to solve the issue.

```javascript
if (isContextProvider(child)) {
  extraContext = new Map(extraContext);
  extraContext.set(getContextProvider(child.type), child.nextProps.value);
  childName = 'ContextProvider';
}
```

**Comment by NervosaX** [comment]
@theKashey All good, I'll use my hack until then. Good luck!

**Comment by NervosaX** [comment]
Looks like 4.3.0 fixes this issue, can probably close this ticket now!

**Comment by theKashey** [comment]
👍
