### ISSUE TITLE
Broken with React 0.13 :(

### ISSUE THREAD

**Issue by syranide** [gaearon/react-hot-loader#98]
`isReactClassish.js:15 Uncaught TypeError: Object.getPrototypeOf called on non-object`

It seems to be called on a string `'textContent'`, I'm guessing something has changed.

cc @gaearon

**Comment by gaearon** [comment]
Is it failing on everything or a specific example?

**Comment by ZucchiniZe** [comment]
It is broken for me also

**Comment by gaearon** [comment]
OK, I'll take a look real soon. Stay tuned :-)
If anybody wants to take this, go ahead!

**Comment by gaearon** [comment]
Fixed in 1.2.2. Thanks for reporting!
