### ISSUE TITLE
Update CHANGELOG.md

### ISSUE THREAD

**Issue by neoziro** [gaearon/react-hot-loader#980]
https://github.com/gaearon/react-hot-loader/blob/master/CHANGELOG.md

v4.2.0 is missing.

**Comment by theKashey** [comment]
Yep, that's a bit _controversial_

**Comment by theKashey** [comment]
Could we land a `commitizen` or something similar here? I need something to _lint_ me.

**Comment by neoziro** [comment]
Just use `yarn release` and all will be fine 👌
