### ISSUE TITLE
how to reload if state has change ？

### ISSUE THREAD

**Issue by Hzy0913** [gaearon/react-hot-loader#985]
i reference to getting started set the webpack，when the state has change，hot-load is not to work，but change jsx and css is  normal work 。

**Comment by theKashey** [comment]
Could you provide an example?

**Comment by Hzy0913** [comment]
@theKashey 
**.babelrc**
`{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "react",
    "es2015",
    "stage-0"
  ],
  "plugins": ["transform-runtime", "transform-decorators-legacy", "react-hot-loader/babel"]
}
`


**router**

`
import React from 'react';
import {BrowserRouter, Route, Switch} from 'react-router-dom';
import {hot} from 'react-hot-loader';
import App from '../containers/app';
import Docs from '../containers/docs';

const Router = ({component: Component, children, ...rest}) => (
  <Route
    {...rest}
    render={props => (
      <Component {...props} ><Switch>{children}</Switch></Component>
    )}
  />
);

const Root = () => (
  <BrowserRouter>
    <div className="router-content">
      <Switch>
        <Router path="/" component={App} >
          <Router exact path="/docs" component={Docs} />
        </Router>
      </Switch>
    </div>
  </BrowserRouter>
);

export default hot(module)(Root);
`
**webpack-devServer**
`
  devServer: {
    hot: true,
    inline: true,
    contentBase: false,
    compress: true,
    host: HOST || config.dev.host,
    port: PORT || config.dev.port,
    open: config.dev.autoOpenBrowser,
  }
`

**Comment by theKashey** [comment]
Ok, so when it is working, and when - is not?
Everything seems to be ok-ish.

**Comment by theKashey** [comment]
What do you call "state"?

**Comment by Hzy0913** [comment]
@theKashey  
emmm...  the "state" of react

**Comment by theKashey** [comment]
Changing the state will never trigger hot-reload, only changes in source files.
More of it - if you change state the state(default state, for example) in sources files - it will not be reflected on the page, as long RHL __preservers__ the state.

**Comment by Hzy0913** [comment]
OK, thank you for your answer😊
