### ISSUE TITLE
DLL no longer works after upgrade from 4.1.3 to 4.2.0

### ISSUE THREAD

**Issue by joacim-boive** [gaearon/react-hot-loader#986]
### Description
It builds and runs without any errors using 4.1.3.

Upgrade to 4.2.0 and it still builds fine but the code stops working.

### Expected behavior
That the same code should continue to work.

### Actual behavior

What actually happens: 

Seems like the mapping in webpack.DllPlugin is broken by the upgrade.

![image](https://user-images.githubusercontent.com/270235/40301328-11ef0968-5cec-11e8-8ac6-f154ab4fd8b1.png)

### Environment
Webpack 3.12.0
React Hot Loader version: 4.1.3 and 4.2.0

1.  `node -v`: v9.4.0
2.  `npm -v`: 6.0.1

Then, specify:

1.  Operating system: Windows 7
2.  Browser and version: Any browser and version

### Reproducible Demo

Sorry, no demo.

**Comment by stnwk** [comment]
Doesn't work for me either :(

**Comment by theKashey** [comment]
I reckon - this is the root cause - https://github.com/gaearon/react-hot-loader/pull/975
Could anybody provide some text around the problem line?

**Comment by theKashey** [comment]
Look like there is nothing to fix here.
