### ISSUE TITLE
Adding arrow function to react class while live will break hot reloading

### ISSUE THREAD

**Issue by tgreen7** [gaearon/react-hot-loader#989]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

What you are reporting: Crashing when adding an arrow function to a class

### Expected behavior

What you think should happen: Hot reload to work in this case

### Actual behavior

What actually happens: It crashes saying this.functionName is not a function

### Environment

React Hot Loader version: next

Run these commands in the project folder and fill in their results:

1.  `node -v`: v10.1.0
2.  `npm -v`: 5.6.0

Then, specify:

1.  Operating system: MacOs 10.13.4
2.  Browser and version: Google Chrome 66.0.3359.181

### Reproducible Demo

Please take the time to create a new project that reproduces the issue.

You can copy your project that experiences the problem and start removing things until you’re left with the minimal reproducible demo. This helps contributors, and you might get to the root of your problem during that process.

Push to GitHub and paste the link here.

in the react-hot-loader/examples/react-bootstrap do yarn start -> open it in browser -> then while it is running change the code in App.js to 
```
import React from 'react'
import { hot } from 'react-hot-loader'
import FormControl from 'react-bootstrap/lib/FormControl'

class App extends React.Component {
  renderSomething = () => {
    return <div>
      weofji
    </div>
  }
  render() {
    return (
      <h1>
        Hello, world.<br />
        {this.renderSomething()}
        <FormControl inputRef={console.log} defaultValue="Write me" />
      </h1>
    )
  }
}

export default hot(module)(App)
```

It will crash with the error:
```Uncaught TypeError: this.renderSomething is not a function```

**Comment by theKashey** [comment]
version `next` or 4.2.+?

**Comment by theKashey** [comment]
React-Hot-Loader is not adding a new class properties on the fly.
