### ISSUE TITLE
New release broke old builds

### ISSUE THREAD

**Issue by jasonkuhrt** [gaearon/react-hot-loader#99]
We were using `^1.1.3` for weeks fine and then suddenly our build broke today:

![screen shot 2015-03-11 at 6 00 16 pm](https://cloud.githubusercontent.com/assets/284476/6607856/85cd0342-c818-11e4-8afc-c896f36acc15.png)

When we pinned our dependency to `1.1.3` then it worked again. We are trying to narrow down the exact version where things broke but we can safely say that it was AFTER `1.1.3`.

**Comment by jasonkuhrt** [comment]
Verified that `1.1.7` works.

**Comment by gaearon** [comment]
Can you verify that you have `exclude: /node_modules/` in your config in loader configuration [like on this line](https://github.com/gaearon/react-hot-boilerplate/blob/master/webpack.config.js#L24)? You need it, because without it different things may break.

**Comment by jasonkuhrt** [comment]
@gaearon We do not although that does not change the information above.

**Comment by gaearon** [comment]
1.1.x only worked by sheer luck. Too many things can break unexpectedly if you don't use `exclude`, and there's no good fix for that on RHL's part. In fact it looks like the error is related not to RHL, but some other loader (Babel?) that also has `exclude` unspecified.

[Tutorial](http://gaearon.github.io/react-hot-loader/getstarted/) explicitly states to use `exclude`, so please add it.

**Comment by jasonkuhrt** [comment]
@gaearon Will do thanks.
