### ISSUE TITLE
reconcilation failed due to error ReferenceError: areArgumentsShallowlyEqual is not defined

### ISSUE THREAD

**Issue by balciseri** [gaearon/react-hot-loader#995]
### Description

Hot reloading fails for files using reselect.

Removing all calls to reselect function fixes the issue for that file.

### Expected behavior

React hot loader normal behavior

### Actual behavior

```
react-hot-loader.development.js:159 React-hot-loader: reconcilation failed due to error ReferenceError: areArgumentsShallowlyEqual is not defined
    at ProxyComponent.eval [as totalScoreSelector] (eval at __reactstandin__regenerateByEval (IdolsApp.jsx:298), <anonymous>:9:5)
    at ProxyComponent.render (IdolsApp.jsx:233)
    at ProxyComponent.hotComponentRender (react-hot-loader.development.js:608)
    at render (react-hot-loader.development.js:1112)
    at hotReplacementRender (react-hot-loader.development.js:1241)
    at next (react-hot-loader.development.js:1259)
    at react-hot-loader.development.js:1323
    at Array.forEach (<anonymous>)
    at hotReplacementRender (react-hot-loader.development.js:1246)
    at next (react-hot-loader.development.js:1259)
```

### Environment

React Hot Loader version:

react-hot-loader@4.2.0

Run these commands in the project folder and fill in their results:

1.  `node -v`: v10.1.0
2.  `npm -v`: 6.0.1

Then, specify:

1.  Operating system: Windows 10
2.  Browser and version: Chrome Versione 66.0.3359.181

This might be related to:
https://github.com/gaearon/react-hot-loader/issues/984

**Comment by theKashey** [comment]
This is more about #978
Sorry - there is no cure yet, except moving "that" off constructor, away from RHL hands.

Could you please provide the your code, as long _reselect_ usually used in a component constructor.

**Comment by theKashey** [comment]
Yeah, "class properties" are created inside constructor. So this supposed to fail.
Meanwhile - it should not break all the things. 
Try/Catch around regeneration code will solve the problem.

**Comment by balciseri** [comment]
Thanks for the fast anwers. I tought the same after reading https://github.com/gaearon/react-hot-loader/issues/978.
I'm not quite sure where to put Try/Catch or Errorboundary dho ( i tried in different places but it still just errors out).
Are there any "ugly" tricks to make this work until a fix is found?

**Comment by theKashey** [comment]
@balciseri  - initialize in componentWillMount. Not 16.3 very compatible, but will temporary fix the problem.
Gonna fix this in the next release. Related - #978

**Comment by balciseri** [comment]
Great!
In the meanwhile I did as you said and it works, so the problems are really mostly just in the constructor 😮
From:
```
class App extends React.Component {
  state = {
    count: 0
  };

  testSelector = createSelector(state => state.count, count => `Count is: ${count}`);

  render() {
    const testSelector = this.testSelector(this.state);
    return (
      <div>
        <p>{testSelector}</p>
        <p>Modify me and saves!</p>
      </div>
    );
  }
}
```
to
```
class App extends React.Component {
  state = {
    count: 0
  };
  componentWillMount() {
    this.testSelector = createSelector(
      state => state.count,
      count => `Count is: ${count}`
    );
  }

  render() {
    const testSelector = this.testSelector(this.state);
    return (
      <div>
        <p>{testSelector}</p>
        <p>Modify me and saves!!</p>
      </div>
    );
  }
}
```

**Comment by balciseri** [comment]
I can confirm this fixed my reselect issues.
Thanks a lot
