### ISSUE TITLE
hot updated patch make the component re-render twice

### ISSUE THREAD

**Issue by Hubu** [gaearon/react-hot-loader#997]
### Description

1. when i setup the example code provide by official [here][webpack] named `webpack-modern`
1. with in `Counter ` component, i  **stop the counter timer** and add a log expression with only one param('**changed**') in `render method` before return
1. saved and check browser console, there are two 'changed' string printed.

### Expected behavior

there is only **one** 'changed' string should be printed.

### Actual behavior

there are **two**.

### Environment

React Hot Loader version: 4.0.0-beta.3

Run these commands in the project folder and fill in their results:

1.  `node -v`: v10.0.0
2.  `npm -v`: 5.6.0

Then, specify:

1.  Operating system: win10 1803 build 17134.81
2.  Browser and version: chrome 66.0.3359.181 official stable x64

### Reproducible Demo

the official example [webpack-modern][webpack]

update of Counter component:
```javascript
  render() {
    console.log('changed')
    return this.state.count
  }
```

[webpack]: https://github.com/gaearon/react-hot-loader/tree/master/examples/webpack-modern "jojo"

**Comment by theKashey** [comment]
Yes, this is expected behavior.
First RHL renders component to _understand_ it, next React can render it without state loss.
Sometimes it could be renderer even trice.
